### ISSUE TITLE
CSS position: fixed; elements hidden behind the UI

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1000]
Jira issue originally created by user phanebrink:

Original Author: Tanel Põld

.menu {
position: fixed;
top: 40px;
left: 0px;
}

This item will be hidden behind the user interface, Navigation tab and Context Bar in header. 
Shouldn't <body> be fully shown in content editing area?

 Jira-URL: https://jira.neos.io/browse/NEOS-533

**Comment by kitsunet** [comment]
I guess *won't fix*  as the rewritten UI takes care of that by using an iframe instead.
