### ISSUE TITLE
Consider replacing image alignment with layout

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1003]
Jira issue originally created by user @sebobo:

Instead of having an option for image alignment, we should provide a layout instead with some common scenarios instead of left, right, center because the rendering might be tied more to the importance of the image and not the positioning in different views

 Jira-URL: https://jira.neos.io/browse/NEOS-542

**Comment by kitsunet** [comment]
Still relevant @Sebobo ?

**Comment by Sebobo** [comment]
Not for now. Maybe in the future again
