### ISSUE TITLE
f:uri.node does not work in widget template

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1005]
Jira issue originally created by user pumatertion:

I think at this place we need a check for TypoScriptAwareViewInterface. It it is not present the propertyMapper should be invoked to convert an incoming string node="/foo/bar/baz" into a node.

 Jira-URL: https://jira.neos.io/browse/NEOS-549

**Comment by kitsunet** [comment]
This is a missing feature or rather needs some clarification in the docs. The behavior is normal as the widget is a subrequest not sharing the "context" of the main request and a nodepath alone is not sufficient to find a node.
