### ISSUE TITLE
Outline of shine through content elements not updated until reload

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1006]
Jira issue originally created by user @aertmann:

There's a orange outline shown on shine through elements and after editing the content so it becomes non shine through, the outline is still orange until that page is reloaded. It would make sense that the shine-through class is removed and the workspace of the content element is updated after the first saving of the element.

Additionally the orange outline should probably be a little transparent to match the non shine through outline.

 Jira-URL: https://jira.neos.io/browse/NEOS-561

**Comment by mhsdesign** [comment]
The behavior seems to have changed with the React UI
