### ISSUE TITLE
Removing users doesn't remove all data

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1007]
Jira issue originally created by user @aertmann:

When removing a user using the remove action of the user commands, lots of data related to the user is kept.

Needs to be handled for the UserCommandController's removeAction and the UsersController's deleteAction.

Preferably done with a service for removing users.

typo3_typo3cr_domain_model_nodedata
typo3_typo3cr_domain_model_workspace
typo3_neos_domain_model_user
typo3_neos_domain_model_userpreferences
typo3_party_domain_model_abstractparty
typo3_party_domain_model_person
typo3_party_domain_model_personname

 Jira-URL: https://jira.neos.io/browse/NEOS-565

**Comment by kdambekalns** [comment]
Probably fixed with #1376

**Comment by aertmann** [comment]
Not at all fixed with #1376

**Comment by Sebobo** [comment]
This is solved except for the remaining root node data, so I close this in favour of #2193
