### ISSUE TITLE
State object to keep track of state for the current page

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1016]
Jira issue originally created by user @aertmann:

Implement a state object that keeps track of the current page's information and is automatically updated when the page is updated. This will allow removing all the references to the neos-document-metadata dom node and have everything use bindings to keep updated instead of reading the dom every time.

Be aware that it might need to handle multiple states for split screen views in the future.

 Jira-URL: https://jira.neos.io/browse/NEOS-616

**Comment by kitsunet** [comment]
This will probably not happen anymore?

**Comment by aertmann** [comment]
right, was intended to fix some bugs in the Ember UI, the redux state in the new UI tackles the same problem to some degree
