### ISSUE TITLE
Transfer attributes for html/body on page change

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1017]
Jira issue originally created by user @aertmann:

When changing the page in the content module the attributes on the body and html tags aren't updated.

**Technical discussion 2014/06/15:**
=== Background: ===

When changing a page in the backend the html/body tag attributes are not updated making
it impossible to use html/body classes or styles e.g. I've created a patch for it https://review.typo3.org/#/c/30798/, but we need to decide on the appropriate approach.

===CONCLUSIONS ===
- Challenges
  ***\* Generated classes from Modernizr or other JavaScript frameworks
  ***\* Should the original attributes be removed or updated?
  **\* Transferring of .neos-*\* classes
- Possible solution would be to make the behavior configurable
  ***\* Merge with original attributes
  ***\* Remove original attributes
  **\* Use a configurable regular expression for which classes to keep (incl. .neos-*\* ones)
  → Make it configurable. Off by default (non-breaking). → Maybe lateron add a sane default which makes sense in 98% of the cases. -> exact configuration to be discussed in a dedicated meeting
- Further discusssion
  ***\* Updating of tags in <head> (script, link, etc.)
  
  Jira-URL: https://jira.neos.io/browse/NEOS-617

**Comment by kitsunet** [comment]
I would close this for now. We have some half backed solution for now and in rewritten UI the whole page is loaded anyway.
