### ISSUE TITLE
Show actual modifications of original content

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1022]
Jira issue originally created by user @robertlemke:

If the original content has changed since the last adoption (see NEOS-634) the content inspector tab "Content Dimensions" will display a button "Show changes" below the something-has-changed-message. Clicking on it will show a diff view between the original content at the time a change has been last acknowledged (again, see NEOS-634) and the its current state.

The diff view could be shown in a light box like dialogue or using the full-page inspector.

 Jira-URL: https://jira.neos.io/browse/NEOS-647

**Comment by kitsunet** [comment]
Is this still relevant with our workspace diff?
