### ISSUE TITLE
Simplify "Hide submenu" in Backend

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1024]
Jira issue originally created by user fedir:

The Backend interface of Neos begins to be complicated and charged.

To keep the philosophy of simplicity and lightness, we proposes to optimize the logic of backend in following maniere :

if a input field is not used and not obligatory, keep the label, hide the field by default. Only when we are clicking on the label, the field is shown.

Example : "Hide before" and "Hide after" inputs are used quite rarely, could be hidden by default and shown when we are clicking on their labels.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11148/S%C3%A9lection_162.png) 
![Jira Image](https://jira.neos.io/secure/attachment/11147/S%C3%A9lection_162.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-652

**Comment by mhsdesign** [comment]
Closing this, since i think a few things changed over the time, and i dont find the inspector bloated since the rarely used fields "Hide after" and so on are in the Metadata Tab
