### ISSUE TITLE
History timeline

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1025]
Jira issue originally created by user @robertlemke:

As a Neos user I would like to get an overview of what happened recently in my Neos installation.

A new backend module "History" should display a timeline which displays changes and other actions events. Ideally the list can be scrolled down endlessly (alternative: paginated by 30 events).

For starters, the following events should be displayed:
- created / modified / deleted document nodes
- created / modified / deleted content nodes
- created / modified / deleted users

The objects in question (for example a content element) are linked so that the user can quickly navigate to the module where the object can be displayed (not the case for delete objects).

An avatar of the user who triggered the event should be displayed next to the text. Since we don't have user profile picture support yet in Neos, we'll work with placeholders first.

See attached drawing for a rough layout idea.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11149/history-timeline.jpg) 

 Jira-URL: https://jira.neos.io/browse/NEOS-655

**Comment by kitsunet** [comment]
@robertlemke As you re-opened this, what is the deal? Should we keep it? Seems nothing happening.

**Comment by mhsdesign** [comment]
Seems to be added with https://github.com/neos/neos-development-collection/commit/a53deddcd951347a573a7d5f2f858b967867de16

as we have a history module now - there is also an alternative package: https://github.com/aertmann/history
