### ISSUE TITLE
Use Neos / Flow without a properly configured PHP CLI

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1026]
Jira issue originally created by user @robertlemke:

Currently one of the biggest problem is Flow's / Neos' dependency on a correctly configured PHP CLI. Flow relies on PHP CLI for the compilation step. Most systems though have a different php.ini for CLI than for web which often causes problems (blocker). Also, file access rights are going wild because most systems don't have proper configuration for group access rights - but since both, CLI and web, need write access, either one fails after the compilation process.

 Jira-URL: https://jira.neos.io/browse/NEOS-656

**Comment by kitsunet** [comment]
How did this end up over here 😆 Moving over to flow collection...
