### ISSUE TITLE
Make installation easier or possible on shared hosting

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1027]
Jira issue originally created by user dcumber:

I gave up trying to install NEOS on shared hosting. Too many blank pages or errors rendered both in the front and backend.
Basically, installation without use of a virtual host setup seems impossible at present.
HSphere control panels don't allow for setup of a domain name pointing to a folder, so pointing a domain name to the Web folder can't be done. Copying the files from Web to the document root leads to other problems with Neos being unable to find its resources. I'm sorry I can't provide much more detail, as I uninstalled and went back to TYPO3 CMS.

 Jira-URL: https://jira.neos.io/browse/NEOS-677

**Comment by kitsunet** [comment]
I don't think this is action-able in itself. Closing for now. We are well aware of the difficulties with shared hosting.
