### ISSUE TITLE
new nodeType dialog, nodeTypes sorting direction "wrong"

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1032]
Jira issue originally created by user inshadow:

The nodeType on the new noeType dialog, can be sorted by using the position property.
The only problem is that I don't think the nodeTypes are sorted the way you would normally expect (I know it's easy just to float left) when reading.
I would expect to look vertically and then the next column...
Here is a discussion on the topic:
http://stackoverflow.com/questions/3250174/which-direction-is-better-for-sorting-multi-column-lists

 Jira-URL: https://jira.neos.io/browse/NEOS-737

**Comment by kitsunet** [comment]
I think this won't change in the near future, closing.
