### ISSUE TITLE
Catch errors while publishing invalid resources

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1033]
Jira issue originally created by user @robertlemke:

Steps:
- one or more resources which are registered in the database don't have a matching file in Data/Persistent/Resources
- run ./flow resource:publish
- depending on the publishing target, the command will fail at least with an uncaught exception when the target tries to publish the broken resource

The targets should rather collect information about problems (maybe like the validation errors) and output a list of broken resources but continue.

 Jira-URL: https://jira.neos.io/browse/NEOS-743

**Comment by kitsunet** [comment]
Moved to https://github.com/neos/flow-development-collection/issues/958

Closing.
