### ISSUE TITLE
Publishing a single dimension breaks constraints for aggregate nodes

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1041]
Jira issue originally created by user @hlubek:

This is hypothetical for now, but we might have a problem that publishing is always based around a context and nodes, so multiple node variants won't necessarily be picked up, when publishing a specific dimension preset. This breaks our constraint for aggregate nodes where the path of each variant needs to match.

 Jira-URL: https://jira.neos.io/browse/NEOS-796

**Comment by mhsdesign** [comment]
@bwaidelich is this an issue? Otherwise i would suggest closing this.

**Comment by bwaidelich** [comment]
Uhm. I don't know?! Should I?

**Comment by mhsdesign** [comment]
Nope was just a guess because you know more about this stuff xD I thought you might be the right contact ^^

**Comment by bwaidelich** [comment]
> you know more about this stuff

I'm not so sure about this one :)
But this issue is more than 8 years old and a lot has changed with node publishing. So I agree that we should close it for now
