### ISSUE TITLE
Two image properties causes unexpected behavior

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1045]
Jira issue originally created by user @aertmann:

When having two image properties simultaneously the checkboxes behave unexpectedly. When checking the checkbox of the first image property, the checkbox of the second is checked too. This happens because a dom ID is used to change their state, and this ID is not unique for every image editor.

 Jira-URL: https://jira.neos.io/browse/NEOS-826

**Comment by kitsunet** [comment]
Was this ever fixed?

**Comment by aertmann** [comment]
not to my knowledge, probably never will but unlikely to be an issue in the new ui
