### ISSUE TITLE
Make loading indicator more visible

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1046]
Jira issue originally created by user @aertmann:

The loading indicator is not very visible currently. To make it more visible it should be centered and mirrored.

 Jira-URL: https://jira.neos.io/browse/NEOS-828

**Comment by rolandschuetz** [comment]
Won't implement in the old UI, in the new UI there's a [issue open](https://github.com/neos/neos-ui/issues/1771)
