### ISSUE TITLE
Two instances of same element breaks element selection

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1047]
Jira issue originally created by user @aertmann:

If a content element is rendered more than once on a page the content selection breaks for those elements. This happens e.g. when using the new "Insert records" element and inserting an element from the same page.

 Jira-URL: https://jira.neos.io/browse/NEOS-857

**Comment by mhsdesign** [comment]
Not an issue with the React ui, the selection works from the iframe perfectly, and the content tree will always select the first rendered one
