### ISSUE TITLE
As an editor I want to be able to easily create arbitrary links

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1048]
Jira issue originally created by user @bwaidelich:

The aloha linking wizard currently allows for quickly creating links to assets, document nodes and external URLs.
For more advanced features like linking to custom Content Elements or custom anchor tag attributes (e.g. "title", "target" or "class") a more sophisticated linking wizard is needed.

Should work in the aloha linking wizard and the link inspector editor. One idea is to have some sort of overlay with a tree and search that also allows selecting specific elements on a page as well as supporting options for target, title & class.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11510/TYPO3_CMS_RTE_link.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-860

**Comment by kitsunet** [comment]
This will probably only happen in the rewritten UI, adding to a collection of relevant issues there and closing this for now.
