### ISSUE TITLE
ContentElementWrappingService throws an exception while getting node properties of type 'date'

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1051]
Jira issue originally created by user @radmiraal:

the content element wrapping service uses the propertymapper (since the resource management change?) leading to a propertymapper error that can not find a typeconverter for type 'date'

this happens for non-internal node properties only as those are handled by the content element wrapping service.

Possible solutions would be to accept 'date' and 'datetime' as valid types temporarily, make 'datetime' preferred and deprecate 'date'. Other solutions would've to be done in CR (NodeType or Node object) or in the propertymapper which seems to be a wrong approach to fix it.

 Jira-URL: https://jira.neos.io/browse/NEOS-876

**Comment by kitsunet** [comment]
Closing for now, I think this works correctly by now.
