### ISSUE TITLE
As an editor i want to get access to texteditor panel if fullscreen is enabled

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1052]
Jira issue originally created by user pumatertion:

 Jira-URL: https://jira.neos.io/browse/NEOS-882

**Comment by kitsunet** [comment]
Not enough info, closing for now.

**Comment by aertmann** [comment]
think he meant that the text editor toolbar is hidden when viewing in fullscreen and he's suggesting to made it available.. heard others suggest the same
