### ISSUE TITLE
Nodes created in tree without giving a name are created as "unnamed" 

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1054]
Jira issue originally created by user @kitsunet:

if you give no name upon creating a node in the tree it will be created with "unnamed" as node name, which can result in problems if you have multiple of those nodes especially now that the node name is no longer exposed. On giving no name the name should be auto generated.

 Jira-URL: https://jira.neos.io/browse/NEOS-912

**Comment by knusperpixel** [comment]
Yes it is :-(

A possible solution would be, if the nodepath gets autoupdated when the title changes _and_ the nodepath is currently `unnamed`.

**Comment by dimaip** [comment]
We fixed it in the new UI btw.

**Comment by kitsunet** [comment]
Nice, in this case I would say `won't fix` -> new UI.
