### ISSUE TITLE
Contextmenu listener is destroing secondary view

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1060]
Jira issue originally created by user adgrafik:

To reproduce create a HTML content element and click on "Edit HTML source" to see the ember view. The codemirror plugin prevent this effect within the textfield element. But if you make a right mouse click on the left, where the line numbers are, the view will close unexpectly.

In my case, I have a plugin with a view and a dialog box which gets open. If the user click undeliberate the right mouse button, the view will destroyed but the dialog is still open and I get a error of missing view.

 Jira-URL: https://jira.neos.io/browse/NEOS-935

**Comment by mhsdesign** [comment]
Not an issue in the React Ui
