### ISSUE TITLE
Some paths are not automatically changed 

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1061]
Jira issue originally created by user jank:

If i add an image tag to the page template with srcset the 2nd path is not changed in output.

``` html
<img src="Public/Images/Logo.png" srcset="Public/Images/Logo.png 1x, Public/Images/Logo@2x.png 2x" alt="Company" height="100" width="228"/>
```

gets

``` html
<img src="http://neos.dev/*Resources/Static/Packages/My.Site/Images/Logo.png" srcset="http://neos.dev/*Resources/Static/Packages/My.Site/Images/Logo.png 1x, Public/Images/Logo@2x.png 2x" alt="Company" height="100" width="228">
```

 Jira-URL: https://jira.neos.io/browse/NEOS-941

**Comment by kitsunet** [comment]
Need to use the resource uri VH or image.uri VH. Closingg as we cannot just convert any path in the template...

**Comment by aertmann** [comment]
wait why? it seems like it's due to a regex processing the attribute, but only allowing one match.. there's no good reason for that restriction

**Comment by kitsunet** [comment]
I can re-investigate, but the constraint is IMHO a `attributeName="Public/Resource/Path"` which isn'T the case for the second path and there was a good-ish reason for that.

**Comment by kitsunet** [comment]
Ok, this is really a bug in the ResourceInterceptor, in 3.x all three resources are detected and changed BUT the ` 1x` is added as part of the uri which is wrong a well. Still moving to Flow dev collection because it needs to be fixed there.
