### ISSUE TITLE
Restrict moving of nodes

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1062]
Jira issue originally created by user andi:

It should be possible to restrict **moving** of nodes.
## Definition

A move-restricted node...
*\* _can not_ be drag/dropped in the _page-_ and _structure-tree_\*  ([UI legend](http://docs.typo3.org/neos/TYPO3NeosDocumentation/GettingStarted/UserInterfaceBasics.html))
*\* _can not_\* be deleted(?)
*\* _can not_\* be cut(?)
*\* _can_\* be copied/pasted

The corresponding buttons (cut, delete, ..) should be hidden/disabled in backend.
## Use cases

This can be used to fix the structure of a document (sub)tree. For example to disallow editors to move pages on the 1st level

 Jira-URL: https://jira.neos.io/browse/NEOS-946

**Comment by kitsunet** [comment]
adding the right @foerthner in this

**Comment by mhsdesign** [comment]
This seems to be now covered with NodePrivileges and normal node constrains
