### ISSUE TITLE
UI for Link "feels" wrong

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1065]
Jira issue originally created by user fft2911:

I made a headline and wanted to link it within the page tree. So I marked the headline text (it went blue) and klicked on the "link". I was expecting, that the marked text would be connected to the link. But instead the editor made a text "New Link", and inserted it within the marked text. See screenshot

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11708/Bildschirmfoto+2015-01-20+um+14.37.41.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-952

**Comment by kitsunet** [comment]
Nothing happened here, CK will behave differently anyway... Sounds like a glitch. Closing because not actionable.
