### ISSUE TITLE
Notify integrators on wrong metadata mapping

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1068]
Jira issue originally created by user @kitsunet:

As an integrator I want to be notified if I enabled inline editing for a property of a node that doesn't match the current metadata container. 

This can happen if I render a list of nodes and want some properties to be inline editable but in the template I do not wrap the correct metadata.

 Jira-URL: https://jira.neos.io/browse/NEOS-97

**Comment by jonnitto** [comment]
@kitsunet It is ok if I close this issue?
