### ISSUE TITLE
URL path segment change confuses the user

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1069]
Jira issue originally created by user fft2911:

Hi,
if you rename the URL path segment and hit return (1) it seems to get automatically published -which is fine - but you notice the are (2) turning orange than red, and the marked area in (3) is lost and the marked area pops to (4).
The turning red confuses a lot, as "red" is a signal, and the part where the marked area jumps from (3) to (4) is annoying in small sites, and _very_ annoying in large sites ;-)

all the best
Juergen

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11716/jira-capture-screenshot-20150127-163510-053.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-972

**Comment by kitsunet** [comment]
I think this is no longer an issue, closing for now.
