### ISSUE TITLE
Options of SelectBoxEditor moves at scrolling

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1072]
Jira issue originally created by user adgrafik:

To reproduce set the CSS-width of a frontend element by Firebug larger then the view, so you can scroll horizontally. Then open a select box in the inspector and scroll to right. The Options will move also to the right but the field stay at place. See screenshot.

This can be fixed if .neos-select2-drop is set to "proition: absolute" instead.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11717/Bildschirmfoto+2015-02-07+um+14.16.36.png) 
![Jira Image](https://jira.neos.io/secure/attachment/11719/Bildschirmfoto+2015-02-09+um+20.21.02.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-995

**Comment by kitsunet** [comment]
Closing this, problem won't happen in rewritten UI, due to iframe. Doubt we will fix this still in the current UI.
