### ISSUE TITLE
Soft deletion of nodes

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1081]
Jira issue originally created by user @aertmann:

Currently all nodes are deleted permanently if removed. This can easily lead to loss of data. To prevent this all nodes should be soft deleted with a flag instead. In the first iteration it's fine that it's just kept, but not possible to restore using the user interface.

Using the existing gedmo doctrine extensions package it should be possible to achieve without too much hassle. However it becomes a bit tricky because of workspaces and shadow nodes.

Conclusions from our technical discussion July 15th 2014:
- Should deleting a node in non-live workspace be soft deleted or only live nodes? Keep everything for the first iteration.
- Should there any automatic clean up deleted non-live nodes to avoid very large tables? Not in the first iteration.
- Would the constraint "pathhash", "workspace", "dimensionshash", "deletionDate" suffice? If using behaviors the “deletionDate” should be handled low-level, the unique index probably needs to be extended though
- Field name? e.g. '''deletionDate''', deletedAt, removedAt, removalDate → “deletionDate”
  → Extra: Hide behind a feature flag for the first iteration.
  
  Jira-URL: https://jira.neos.io/browse/NEOS-1151

**Comment by kitsunet** [comment]
duplicate of #1023

**Comment by aertmann** [comment]
will probably become obsolete with event sources / CQRS

**Comment by kitsunet** [comment]
Probably, as soon as we have a dedicated repository for CR for this I would add it there.

**Comment by mhsdesign** [comment]
I think we can close this with Neos 9.0 at the horizon ;)
