### ISSUE TITLE
Improve tree loading performance

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1085]
Jira issue originally created by user @kitsunet:

First step would be to actually introduce a count query instead of loading the full nodedata objects and counting the array finally in countChildNodes...

Second step would be an optimized query that accepts multiple paths/hashes and returns child counts for each of them:

`SELECT nd.parentpathhash, SUM(1) FROM (SELECT parentpathhash FROM typo3*typo3cr_domain_model_nodedata t0_ WHERE t0_.workspace IN ('user-admin', 'live') AND (t0_.persistence_object_identifier IN (SELECT t1_.nodedata AS sclr24 FROM typo3_typo3cr_domain_model_nodedimension t1_ WHERE t1_.name = 'language' AND t1_.value IN ('de', 'en_UK', 'en_US'))) AND t0_.parentpathhash IN ('33dd58646e6b7b07f2efe9ba41b3c8c0', 'e18f85383d549f7ad660893a02f43a92', 'b7e96cf2b80638b0e2f1f30eceb6e303', '79afab682334f90add91e91658e07a7c') AND t0*.nodetype IN ('TYPO3.Neos.NodeTypes:Page', 'TYPO3.Neos:Document') GROUP BY identifier) nd GROUP BY nd.parentpathhash`

 Jira-URL: https://jira.neos.io/browse/NEOS-1444

**Comment by kdambekalns** [comment]
This issue is very old by now and has not been updated for a while.

Chances are, it is solved or otherwise no longer relevant, so I close it.

Feel free to reopen, if this is still an issue and you can provide new information.
