### ISSUE TITLE
Empty node properties with object type do not return NULL in getProperty()

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1088]
Jira issue originally created by user @hlubek:

A node property with object type (e.g. ImageVariant) will not return NULL for an empty value, but the empty string. This is not intuitive and Eel expressions like `asset != null` do not return the expected value.

 Jira-URL: https://jira.neos.io/browse/NEOS-1461

**Comment by bwaidelich** [comment]
Looking at the implementation of `Node::getProperty()` this seems to be fixed in the meantime
