### ISSUE TITLE
Exception while trying to export deactivated node types

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1096]
Jira issue originally created by user just2b:

I started with the dummy package and deactivated that. everything fine.

If I want to export the site with {./flow Site:export} I end up with the exception 

```
Uncaught Exception
  The node type "TYPO3.NeosDemoTypo3Org:Chapter" is not available.

More Information
  Exception code      #1316598370
  File                /var/www/sites/TYPO3-Neos-1.1/Data/Temporary/Development/Cache/Code/Flow*Object_Classes/TYPO3_TYPO3CR_Domain_Service*NodeTypeManager.php line 104
  Exception reference #201407032127482012c5

```

which is of course true but either those nodes should be exported as disabled or just should be ignored.

 Jira-URL: https://jira.neos.io/browse/NEOS-212

**Comment by rolandschuetz** [comment]
The database is in a broken state. When changing the active pages a migration or at least a `node:repair` should have been executed. It's not really a bug when site:export can't handle wrong database content.
