### ISSUE TITLE
Skipping non used abstract Node type by default

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1098]
Jira issue originally created by user @dfeyer:

Currently we export all Node types by default. VIE schema can become big when the website use a lots of abstract Node type, per exemple with an agency package that can contains a lots of default Mixins.

 Jira-URL: https://jira.neos.io/browse/NEOS-530

**Comment by rolandschuetz** [comment]
@dfeyer Any updates?

**Comment by mhsdesign** [comment]
@Sebobo i think #3563 will fix this right?
