### ISSUE TITLE
RFC: Add a way to rename a TypoScript object

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1100]
Jira issue originally created by user @dfeyer:

Currently "prototype(TYPO3.Neos.NodeTypes:Text) >" unassign the given object. 

In some case it's can be useful to rename an object, before unassigning

See a use case here: https://gist.github.com/dfeyer/ae61a89f6658b9d0a3ba. 

In this case, the integrator need to replace the current Text implementation by a Case object. 

But the implementation of the Text object will be used later on. 

Without the renamed object, the integrator need to implement a new object that work like the original Text object. 

 Jira-URL: https://jira.neos.io/browse/NEOS-859

**Comment by rolandschuetz** [comment]
@dfeyer What's the current status on this?

**Comment by mhsdesign** [comment]
I think we can close this, since i wouldnt say that this is the best approach to the problem ... 
If someone really wants to replace the behaviour one can still use an `@process`

```
prototype(TYPO3.Neos.NodeTypes:Text) {

    @process.replace = TYPO3.TypoScript:Case {
     
	hasRelatedDocuments {
		@position = 'before targeted'
                condition = ${q(node).is('[instanceof Marvel.Website:RelatedDocumentsMixin]') && q(q(node).property('relatedDocuments')).get(0)}
                type = 'Marvel.Website:TextWithRelatedDocuments'
	}

	targeted {
		@position = 'before default'
		condition = ${q(node).property('target') ? TRUE : FALSE}
		type = 'Marvel.Website:TargetedText'
	}

	default {
		@position = 'end 9999'
		condition = TRUE
		renderer = ${value}
	} 
    }
}
```
