### ISSUE TITLE
Accessing variables in TypoScript re-evaluates them every time

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1107]
Jira issue originally created by user @aertmann:

When accessing a TypoScript variable, which happens in Fluid for instance, the value is evaluated every time. This is unexpected and confusion and also has a performance impact. Instead after accessing a variable it should be cached for the next call.

An example of this is assigning using a FlowQuery operation that returns the next instance in a collection and using that twice in a Fluid template for checking something on it and then displaying it e.g. Currently that would return a new one every time, unless the f:alias view helper is used.

 Jira-URL: https://jira.neos.io/browse/NEOS-1152

**Comment by mhsdesign** [comment]
Accessing `${this.bla}` or `${props.bla}` multiple times is now cached.
