### ISSUE TITLE
Clearing/Overriding a Fusion object does not clear e.g. @process rules

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1109]
Jira issue originally created by user reflexxion:

When I use an existing TypoScript object and want to override that, the @process rules are not deleted.

Found when overriding the TYPO3.Neos:Page.body object.

All of the below does not work:

``` javascript
page = Page {
  body > 
  body {
    # The @process.appendJavaScripts is still processed
  }
}
```

``` javascript
page = Page {
  body = TYPO3.TypoScript:Array {
    // The @process.appendJavaScripts is still processed
  }
}
```

I have to set the `@process.appendJavaScripts` to `value`:

``` javascript
page = Page {
  body = TYPO3.TypoScript:Array {
    @process.appendJavaScripts = ${value}
  }
}
```

 Jira-URL: https://jira.neos.io/browse/NEOS-1342

**Comment by Benjamin-K** [comment]
The issue still exists and is even there in some other case (when using arrays).
An example about it was posted in the Neos Slack-Channel here: https://neos-project.slack.com/archives/C050C8FEK/p1489748363567813

```
prototype(Vendor:ImgSizes1) < prototype(Neos.Fusion:RawArray) {
    1 = 1
    2 = 2
}

prototype(Vendor:ImgSizes2) < prototype(Neos.Fusion:RawArray) {
    2 = 2
    3 = 3
}

prototype(Vendor:Image) < prototype(Neos.Fusion:RawArray) {
    sizes = Neos.Fusion:RawArray {
        4 = 4
        5 = 5
    }
}

root = Neos.Fusion:Debug {
    value = Vendor:Image
    prototype(Vendor:Image) {
        sizes = Vendor:ImgSizes2
    }
}
```

This prints the following:
```
 'value' (5) => array(1)
   'sizes' (5) => array(4)
     integer 2 => integer 2
     integer 3 => integer 3
     integer 4 => integer 4
     integer 5 => integer 5
```

Expected behaviour would be:
```
 'value' (5) => array(1)
   'sizes' (5) => array(4)
     integer 2 => integer 2
     integer 3 => integer 3
```

The problem still occurs when clearing the array before (with `sizes >` here).

**Comment by kitsunet** [comment]
Related to https://github.com/neos/neos-development-collection/issues/1116
