### ISSUE TITLE
TypoScript2 Multiline comment in one line omits consideration of the following line

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1110]
Jira issue originally created by user @Weissheiten:

```
demo = 'foo'
/** next line will not be taken into account **/
demo = 'bar'
```

{demo} Outputs 'foo'

---

```
demo = 'foo'
# next line will be taken into account

demo = 'bar'

```
{demo} Outputs 'bar' as expected

 Jira-URL: https://jira.neos.io/browse/NEOS-1369

**Comment by mhsdesign** [comment]
this was fixed with https://github.com/neos/neos-development-collection/pull/3497 ;)
