### ISSUE TITLE
EEL Syntax error returns null property value instead of showing an error

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1111]
Jira issue originally created by user @bjen:

When creating a syntax error in EEL it doesn't show errors or any hints that something went wrong but simply ignores the affected properties.

Example:

attributes.class = ${q(node).property('color') <ins> ' ' </ins> (q(node).property('overflowHidden') ? 'overflow-hidden' : '') <ins> (q(node).property('noPaddingTop') ? ' no-padding-top' : '')} </ins> (q(node).property('overflowHidden') ? ' no-padding-bottom' : '')}

In this case there is a double curly bracket behind the padding-top property. This leads to all classes being not rendered anymore but no error or hint is shown.

 Jira-URL: https://jira.neos.io/browse/NEOS-137

**Comment by cvette** [comment]
This can be closed I guess:

![screenshot from 2018-11-04 15-40-04](https://user-images.githubusercontent.com/6884391/47965501-674a7480-e048-11e8-9d60-8f5917d1d6df.png)
