### ISSUE TITLE
Double underscore key not possible

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1119]
Jira issue originally created by user @aertmann:

It's not possible to use keys with double underscore since they are considered internal. This is necessary for the RawArray to allow creating desired keys.
1. Limit the filtering in Runtime's setPropertiesOnTypoScriptObject to specific internal keys
2. Namespace internal keys to avoid conflicts, e.g. __value & __meta
   
   Jira-URL: https://jira.neos.io/browse/NEOS-532

**Comment by kitsunet** [comment]
This has been solved some time ago and the keys are limited to `\Neos\Fusion\Core\Parser::$reservedParseTreeKeys`
