### ISSUE TITLE
TS2 Variables overwritten with > do not overwrite child objects

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1120]
Jira issue originally created by user @Weissheiten:

Custom NodeType inherits from TYPO3.Neos:Content where "attributes" and accordingly "attributes.class" are set.
Overwriting attributes with "attributes >" does not overwrite the "class" object and the case fails to render (see attached ts2 and Button.html)

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11151/Button.html) 
![Jira Image](https://jira.neos.io/secure/attachment/11150/Button.ts2) 

 Jira-URL: https://jira.neos.io/browse/NEOS-658

**Comment by kitsunet** [comment]
Closing as duplicate to https://github.com/neos/neos-development-collection/issues/1109
Should be the same issue and the other has much more description.
