### ISSUE TITLE
Batch handling of assets

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1121]
Jira issue originally created by user @aertmann:

It should be possible to batch handle assets like deleting or tagging multiple assets at once.

**Ideas**
Add a button in the top next to the filtering which enables multiple selection, when that is clicked the remove button is replaced with a checkbox (same hover effects as the drag icon in the bottom right corner), when clicking on a image it's selected and the checkbox and the hover outline is added around it (though only in the thumbnail view).

Show the amount of selected elements somewhere, preferably in the top with a delete option.

If you hold cmd (possibly something else on windows) or shift and click an image, the selection mode is automatically triggered and you start selection without having to enable it first
In the list view the checkbox is just added on the left of the image when selection mode is enabled.

When an asset has been selected it should be possible to drag all to a tag by dragging one of the selected assets.

When dragging more than one selected asset a counter is shown next to the drag helper.

Additionally it would be awesome if holding click and moving the cursor over would select elements.

 Jira-URL: https://jira.neos.io/browse/NEOS-1048

**Comment by mhsdesign** [comment]
@Sebobo i think this issue cannot be moved here https://github.com/Flowpack/media-ui but it does belong there now i guess?

**Comment by Sebobo** [comment]
Closed in favour of https://github.com/Flowpack/media-ui/issues/8
