### ISSUE TITLE
Check for soft-changes (TYPO3 strings in Comments, license header, documentation etc.)

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-development-collection#1139]
Should be done in master

**Comment by mgoldbeck** [comment]
- [ ]  Neos.Media
- [ ]  Neos.CMS
- [ ]  Neos.Kickstarter
- [ ]  Neos.NodeTypes
- [ ]  Neos.ContentRepository
- [ ]  Neos.Fusion

**Comment by mgoldbeck** [comment]
see https://github.com/neos/neos-development-collection/pull/1161 . Does this ticket still make sense or would it be better to rename all in one step?
