### ISSUE TITLE
Close icon in the media module doesn't work when opened by clicking an image directly

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#1155]
Happens with 2.3 LTS

Steps to reproduce:

1. Select element with an image
2. Click the image in the inspector
3. Try clicking X in the top right of media module

Result:
`RangeError: Maximum call stack size exceeded.` in `ContentModule-built.js`

**Comment by gerhard-boden** [comment]
Fixed in https://github.com/neos/neos-development-collection/pull/532
