### ISSUE TITLE
First cache entry with mode dynamic won't ouput the cached html

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-development-collection#1165]
A TypoScript prototype with cache mode dynamic will ouput return for the first created cached the cacheidentifier and not the cached html. So on a paginated list the first page is ok, switch to page 2 it's ok, switch back to page 1 only the identifiers will be returned, switch back to page 2 it's ok.
If you start with no caches and first open the second page the identifier will always be shown on page 2.

Cache configuration:

```
@cache {
        mode = 'dynamic'
        entryIdentifier {
            node = ${node}
        }
        entryDiscriminator = ${request.pluginArguments.typo3-typo3cr-search-viewhelpers-widget-paginateviewhelper.currentPage}
        context {
            1 = 'node'
            2 = 'documentNode'
        }
        entryTags {
            1 = ${'Node_' + node.identifier}
            2 = ${'NodeType_Some.Vendor:NodeType'}
        }
    }
```

Neos-Version: 2.3.6

**Comment by johannessteu** [comment]
So i debugged some more, guess the main problem is that the entryDiscriminator does not trigger outer caches. So the inner dynamic configured cache won't be evaluated correctly

**Comment by cvette** [comment]
The following snippet reproduces this bug, the inner object needs to be cached:

    prototype(Outer) < prototype(TYPO3.TypoScript:Template) {
        templatePath = 'resource://My.Package/Private/Templates/Outer.html'
        test = ${request.arguments.test}
        inner = Inner

        @cache {
            mode = 'dynamic'
            entryDiscriminator = ${request.arguments.test}
            context {
                1 = 'node'
                2 = 'site'
                3 = 'documentNode'
            }
        }
    }

    prototype(Inner) < prototype(TYPO3.TypoScript:Template) {
        templatePath = 'resource://My.Package/Private/Templates/Inner.html'
        @cache {
            mode = 'cached'
            context {
                1 = 'node'
                2 = 'site'
                3 = 'documentNode'
            }
        }
    }

**Comment by bwaidelich** [comment]
> switch back to page 1 only the identifiers will be returned

What do you mean by "only the identifiers will be returned"? Will it render the cache markers (like described in #1591 ?)
If so, this is most probably fixed by #1960

**Comment by johannessteu** [comment]
The ContentCache Marker aka `CONTENT_CACHE...`

**Comment by bwaidelich** [comment]
FYI: #1958 was closed. could someone test whether the fix solves this issue as well?
