### ISSUE TITLE
Allow non-UUID identifiers for nodedata

### ISSUE THREAD

**Issue by maltemuth** [neos/neos-development-collection#1193]
### Description

Right now, Neos does various checks that node identifiers (column "identifier" in the nodedata table) is actually a UUID by applying a regex; and does so inconsistenly. For instance, when using content references (NodeTypes with property of type 'reference' or 'references') publishing works fine one the first try; any update however will remove any node that does not have a UUID-like identifier.

This leads to surprises for developers, as well as the question "why". In some places, the code will throw Exceptions when encountering non-UUID-identifiers; in other places, these identifiers are silently ignored / discarded.

See discussion below.
### Steps to Reproduce
1. Create some Content-Node
2. manually edit its identifier to something non-UUID-ish, e.g. "test"
3. add a ContentReference Node and add the first node.
4. publish

You will now see the Content-Node from step 1 showing up fine.
1. Add another node to the same ContentReference
2. publish

Node #1 is gone.
#### Expected behavior

Node #1 stays.
#### Actual behavior

Node #1 is removed from the nodedata properties upon second publication.
### Affected Versions

Tested on neos 2.3.7  and flow 3.3.4.
### Discussion

Having non-uuid identifiers does have its merits (up to discussion) and it is not clear why the node-identifiers need to be UUIDs. Maybe this is a good time to change this enforcement; also, it seems that 'reference' and 'references' are special cases and about the only places where this is actually being checked.

I propose to investigate and hopefully drop the UUID requirement.

**Comment by kitsunet** [comment]
The change for that is #1477
