### ISSUE TITLE
Styling of ImageEditor is broken in translations

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#1199]
### Description

For image/asset properties with cropping enabled the buttons for the ImageEditor won't fit into one line:
![image](https://cloud.githubusercontent.com/assets/307571/19553072/ed40ebbe-96b2-11e6-801b-08713e81264d.png)

Apart from that the amount of text-buttons is not very user friendly

### Suggestion

As suggested by Jens, we should replace the text labels by corresponding icons instead:

![image](https://cloud.githubusercontent.com/assets/307571/19553199/75c76bd4-96b3-11e6-9a5d-0e5e16dfe6fb.png)

**Comment by gerhard-boden** [comment]
Like it a lot!
Much better than the text buttons. "Medien" und "Auswählen" didn't transport information about the actions pretty well. The image and upload icon are more intuitive.
