### ISSUE TITLE
Pager in Media module lacks CSS

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#1220]
### Description

The media module pager is not styled.

![image](https://cloud.githubusercontent.com/assets/642226/20336256/0f01b834-abc9-11e6-8157-283fd1eb7d6f.png)

### Steps to Reproduce

1. Go to the media module
2. Upload more than 25 Assets

#### Expected behavior

Horizontal aligned pager buttons.

#### Actual behavior

See picture above.

### Affected Versions

Neos: 

2.3 / master

Flow:

**Comment by Sebobo** [comment]
Was not related to the core but to a project where the pagination widget was overriden.
