### ISSUE TITLE
Unexpected exception is thrown if corrupt markup is used inside a fluid template

### ISSUE THREAD

**Issue by bjen** [neos/neos-development-collection#1226]
The Exception _'Exceeding segment end token after position 66049'_ is thrown if the template of a document node is corrupt.

**Steps to Reproduce**

1. Create a document node type with at least one content collection
2. Create the needed Fusion code
3. Create a Fluid template with the following corrupt code

```
<div {attributes -> f:format.raw()}
	{main -> f:format.raw()}
</div>
```

If you open such a document node inside Neos the above written exception will be thrown.

**Versions:**
Neos 2.3.7
Flow 3.3.4

**Comment by kitsunet** [comment]
The error suggests this is a problem of the TypoScript/Fusion cache, which is strange. Needs triage to figure out whne this exactly happens.

**Comment by hlubek** [comment]
@kitsunet Yes, I spoke with Berit about this one and it seems pretty odd to me. Maybe something with the content element wrapping / DOM parser is doing something strange here.

**Comment by kitsunet** [comment]
I don't think much will happen here.
