### ISSUE TITLE
FEATURE: Make sort direction of the media browser configurable

### ISSUE THREAD

**Issue by peterbucher** [neos/neos-development-collection#1230]
### Description

From Neos 2.1 to Neos 2.2, there is a change regarding the default sort direction of the media browser.
The sort direction in Neos 2.2+ is now set to sort so that the oldest media files are on the top.

Our editors complained that setting, because they are mainly interested in the new stuff, they added.

### Proposals

The new default ordering makes no sense for editors. We could change the default ordering so that the newest media files are on the top.

Or / also make the sort order configurable within the settings.

### Affected Versions

Neos: 2.2+

State
- https://github.com/neos/neos-development-collection/blob/2.3/TYPO3.Media/Classes/TYPO3/Media/Domain/Session/BrowserState.php#L30

Usage within neos/media
- https://github.com/neos/neos-development-collection/blob/2.3/TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php#L139

**Comment by aertmann** [comment]
can confirm it's a regression introduced with c7aed058d3a363db8e51e8e9b84a557e90bffd0e in 2.2

**Comment by aertmann** [comment]
it was intentionally newest files first when I initially improved the media browser

**Comment by peterbucher** [comment]
Thanks guys!
