### ISSUE TITLE
Applied inspector changes are not immediately visible

### ISSUE THREAD

**Issue by robertlemke** [neos/neos-development-collection#1238]
On current master (Neos Development Collection 101cb7919e2c45c75885aa7a62dbf29bee2a9350) changes applied in the inspector are only visible _in the user interface_ after a manual browser reload.

See this video for the actual problem:

![publishreloadbug](https://cloud.githubusercontent.com/assets/95582/20560494/f507645e-b179-11e6-93d8-451f820307ad.gif)

**Comment by robertlemke** [comment]
@skurfuerst can also reproduce it and will take a look at it.

**Comment by skurfuerst** [comment]
Fixed, see related PR!
