### ISSUE TITLE
Change vendor namespace to "Neos"

### ISSUE THREAD

**Issue by robertlemke** [neos/neos-development-collection#1240]
As per [our decision in July 2015](https://discuss.neos.io/t/rfc-vendor-namespace-of-the-neos-project/147), the new vendor namespace for products of the Neos Project is "Neos".

Related to this change is [the decision](https://discuss.neos.io/t/renaming-typoscript/252/46) to rename "TypoScript" to "Fusion".

This issue acts as an umbrella for all related tasks and code changes to put these decisions into practice.

## Package name and Namespace changes

The following packages are affected and will be renamed:

### Framework-Collection
- [x] Neos.Cache
- [x] Neos.Error.Messages
- [x] Neos.FluidAdaptor
- [x] Neos.Utility.Arrays
- [x] Neos.Utility.Files
- [x] Neos.Utility.Lock
- [x] Neos.Utility.MediaTypes
- [x] Neos.Utility.ObjectHandling
- [x] Neos.Utility.OpcodeCache
- [x] Neos.Utility.Pdo
- [x] Neos.Utility.Schema
- [x] Neos.Utility.Unicode
- [x] TYPO3.Eel → Neos.Eel
- [x] TYPO3.Flow → Neos.Flow
- [x] TYPO3.Kickstart → Neos.Kickstarter
- [x] TYPO3.Welcome → Neos.Welcome
---
### Neos-Collection
- [x] TYPO3.Media → Neos.Media
- [x] TYPO3.Neos → Neos.Neos
- [x] TYPO3.Neos.Kickstarter → Neos.SiteKickstarter
- [x] TYPO3.Neos.NodeTypes → Neos.NodeTypes
- [x] TYPO3.TYPO3CR → Neos.ContentRepository
- [x] TYPO3.TypoScript → Neos.Fusion

## Important packages, required by each installation
- [x] Flowpack.Behat -> Neos.Behat
- [x] TYPO3.Neos.Seo → Neos.Seo  https://github.com/neos/neos-development-collection/issues/1254
- [x] TYPO3.Form → Neos.Form
- [x] TYPO3.Party → Neos.Party
- [x] TYPO3.Setup → Neos.Setup
- [x] TYPO3.Twitter.Bootstrap → Neos.Twitter.Bootstrap
- [x] TYPO3.Imagine → Neos.Imagine

## Neos.io Infrastructure
- [ ] Neos.IdNeosIo
- [ ] Neos.Demo

## Neos.io
- [ ] Neos.NeosIo
- [ ] Neos.Marketplace

### Redirect Handler
- [x] Neos.RedirectHandler https://github.com/neos/redirecthandler/pull/10
- [x] Neos.RedirectHandler.NeosAdapter https://github.com/neos/redirecthandler-neosadapter/pull/12
- [x] Neos.RedirectHandler.DatabaseStorage https://github.com/neos/redirecthandler-databasestorage/pull/6
---
### Search
- [ ] TYPO3.TYPO3CR.Search → Neos.ContentRepository.Search https://github.com/neos/typo3cr-search/pull/19
- [x] Flowpack.Elasticsearch https://github.com/Flowpack/Flowpack.ElasticSearch/pull/52
- [x] Flowpack.Elasticsearch.ContentRepositoryAdaptor https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/162
- [ ] Flowpack.SimpleSearch https://github.com/Flowpack/Flowpack.SimpleSearch/pull/15
- [ ] Flowpack.SimpleSearch.ContentrepositoryAdaptor https://github.com/Flowpack/Flowpack.SimpleSearch.ContentRepositoryAdaptor/pull/24
- [x] Flowpack.SearchPlugin https://github.com/Flowpack/Flowpack.SearchPlugin/pull/19
---
### 
- [x] TYPO3.Swiftmailer → Neos.Swiftmailer [directly in master](https://github.com/neos/swiftmailer/commit/f07cc453bf59eabcfef4f8338df37f30360daef7)

### 3rd party
- [ ] Flowpack.Listable
- [ ] Flowpack.ViewHelperTest
- [ ] Flowpack.OAuth2.Client
- [ ] Flowpack.OAuth2.Server
- [ ] Flowpack.Hal.Client
- [ ] Neos.Contribute
- [x] TYPO3.Neos.GoogleAnalytics → Neos.GoogleAnalytics
- [ ] TYPO3.Ldap → Neos.Ldap
- [ ] TYPO3.Mailform → Neos.Mailform
- [ ] TYPO3.FormBuilder → Neos.FormBuilder
- [ ] TYPO3.DocTools → Neos.DocTools
---
### JobQueue
- [x] Flowpack.JobQueue*

## Documentation

- [ ] Revise installation / setup instructions
- [ ] Revise code examples

## Website

- [ ] Check all the content https://github.com/neos/Neos.NeosIo/issues/117
- [x] Flownative.Google.CloudStorage https://github.com/flownative/flow-google-cloudstorage/releases/tag/2.0.0

## Migration Guides

- [ ] Prepare guide how to adjust a package to the vendor namespace change. This should include instructions how to maintain (by branches) two versions in parallel.

**Comment by robertlemke** [comment]
Hey folks, I wonder why some of the packages in the check lists disappear again and again - does someone copy his / her checklist from a text editor to this issue description? I added a couple of packages three times on different days, but they get lost again after a while …

 ¯\_(ツ)_/¯

**Comment by fschwaiger** [comment]
See https://github.com/neos/ldap/pull/4 for neos/ldap
