### ISSUE TITLE
Pin used version of imagine to a branch for already released versions of Neos.

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-development-collection#1274]
typo3/media (older versions) need to declare a more restrictive version requirement for typo3/imagine, currently always the latest pinned version will be installed, which would be breaking for existing installations as soon as we tag a stable version for Neos 3.0

**Comment by mficzel** [comment]
As far as i see this already has happend and is released ... is this correct?

**Comment by robertlemke** [comment]
yes, this looks like it has been fixed: https://github.com/neos/media/blob/2.3.8/composer.json
