### ISSUE TITLE
Node can loose relation to children on publish

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-development-collection#1277]
Scenario:

* Node is created in path /foo (let's say that new node is then /foo/node-1)
* User A changes something in this node, does NOT publish
* User B takes the node and moves it to another path /baz (so there is now a node /baz/node-1)
* User B also adds content to this node and finally publishes
* Everything is fine, node & content are live
* Now user A comes back, sees that the node is still in /foo (in his workspace) and decides to move it to /baz, so that's what they do.
* On moving ``\TYPO3\Neos\Service\NodeOperations::move`` will find the new path (/baz/node-1) to be blocked already and creates a new node name for the moved node, so the node will end up in (/baz/node-2) in user A's workspace.
* Now user A publishes this node, neos tries to publish /baz/node-2 and finds a node with the same identifier in /baz/node-1. Now ``\TYPO3\TYPO3CR\Domain\Model\Workspace::replaceNodeData`` will similarize the existing node to be like the "to be published" node. Which means the path is changed to /baz/node-2 and the workspace node is removed. At this point the result is broken, as on publish this path change is not propagated to child nodes and so effectively the live node changed path and was disconnected from all child nodes.

Two things should be tackled to fix this:

* NodeOperations should check if the identifiers of found nodes with the same path match and then not change the path of a moved node
* we should evaluate if adapting the path of a live node should maybe be propagated to existing live children.

**Comment by robertlemke** [comment]
I could reproduce this behaviour on a current Neos master (future 3.0) with the Neos demo site.
