### ISSUE TITLE
URL path segment not updated after page title change

### ISSUE THREAD

**Issue by TheLalaMan** [neos/neos-development-collection#1290]
### Description

If the title of a page is changed in the inspector, the URL path segment is not automatically updated. This can be very confusing for editors (if they do not notice the discrepancy between page title and URL) and time-consuming (because they have to create the URL path segment themselves).

### Steps to Reproduce

1. Create a page with an arbitrary title
2. Note the automatically generated URL path segment for it
3. Change the page title to something else

#### Expected behavior

The URL path segment should automatically be updated if the page title is changed.

#### Actual behavior

The URL path segment stays the same, even after publishing the change.

### Affected Versions

Neos: 2.1

**Comment by johannessteu** [comment]
Hmm, guess this is intended. The title of a page shouldn't always be in sync with the uri paht segment for different reasons. For instance for SEO stuff and a lot of other things.

So i think the actual behavior is good correct?!

**Comment by gerhard-boden** [comment]
+1 to what @johannessteu just said. It's a little less problematic nowadays, because we automatically create redirects. But still: For me personally i prefer not to change the URI for every time the title is adapted.

**Comment by aertmann** [comment]
Can confirm this is not done on purpose.

If such behavior is desired, I've created a simple package you can use to achieve it https://packagist.org/packages/moc/synchronizeurl

**Comment by TheLalaMan** [comment]
@aertmann : Thanks for the tip, I tried your package with Neos 2.3.7. Seems to be working only one-way, though. If I change the URL instead of the title, I get a 404 even in the backend and incoming links as well. Any idea why?

**Comment by aertmann** [comment]
interesting, sounds like a bug the issue when changing URL segment

**Comment by TheLalaMan** [comment]
Okay guys, thanks for your feedback! I'll close this issue then. @aertmann : I opened an issue for your package regarding the page reload bug.
