### ISSUE TITLE
Deprecate TypoScriptService

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-development-collection#1297]
Since we are in the move to the new Name Fusion the TypoScriptService, wich is tagged with `@api`, should be marked as deprecated and a new FusionService should be introduced

**Comment by beheist** [comment]
I'd like to get this done today.

**Comment by johannessteu** [comment]
That would be awesome!

**Comment by beheist** [comment]
Had to reschedule a bit unfortunately. I will try to do that tomorrow instead, today's full :/
