### ISSUE TITLE
Drag&Drop in reference editor fails in Firefox

### ISSUE THREAD

**Issue by gerdemann** [neos/neos-development-collection#1309]
### Description

If I move an element in the reference editor, I will be directed to a different page.
For example, if i drop the item "Keramik" i will be directed to "http://keramik".
This error occurs only in Firefox.

![Beispiel](https://drops.azureedge.net/drops/files/acc_496443/2eE9?rscd=inline%3B%20filename%3DReference%2520Editor&rsct=image%2Fgif&se=2016-12-12T13%3A37%3A55Z&sig=U01thBuV3kJVyij8Y45wr%2FaOc0R9tGIHw1prJqtN19o%3D&sp=r&sr=b&st=2016-12-12T12%3A37%3A55Z&sv=2013-08-15)

### Steps to Reproduce

1. Open Firefox
2. Create a Node-Property of type "references"
3. Select multiple references
4. Drag&Drop an item in this list

#### Expected behavior

I expect the item to be moved

#### Actual behavior

In Firefox i will be directed to a different page.

### Affected Versions
Neos: 2.3.7
Flow: 3.3.5
Firefox: 46.0.1

**Comment by Nikdro** [comment]
I can confirm this issue

**Comment by aertmann** [comment]
seems to be a Firefox bug or at least a bug in the Sortable library, see https://github.com/RubaXa/Sortable/issues/1012 + https://github.com/RubaXa/Sortable/issues/985

**Comment by Nikdro** [comment]
This is gone with the new neos-UI.
Shouldn't this issue be closed?
