### ISSUE TITLE
Refactor `FusionView`

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-development-collection#1311]
According to the rename to `Fusion` the `FusionView` must be refactored to replace internal variables like `typoScriptPath`, `typoScriptPathPatterns` and so on. Those methods and options should be backported to the `TypoScriptView`. The view itself is not flagged as @api but could still break installations

**Comment by mficzel** [comment]
Working on this in https://github.com/neos/neos-development-collection/pull/1328
