### ISSUE TITLE
Create branches/tags for packages (for Neos 3.0)

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#1354]
- [x] Neos.Imagine 3.0
- [x] Neos.Party 4.0
- [x] Neos.Form 3.0
- [x] Neos.Setup 4.0
- [x] Neos.Twitter.Bootstrap 3.0
- [x] Neos.RedirectHandler 2.0
- [x] Neos.RedirectHandler.DatabaseStorage 2.0
- [x] Neos.RedirectHandler.NeosAdapter 2.0
- [x] Neos.SwiftMailer 6.0
- [x] Neos.GoogleAnalytics 2.0
- [x] Neos.Seo 2.0
- [x] Flowpack.Neos.FrontendLogin 3.0

**Comment by robertlemke** [comment]
is this (implicitly) also a list of missing branches for `set-dependencies.sh` or did you create an issue elsewhere already?

**Comment by robertlemke** [comment]
Might also be (partially) covered by the release script: #1358

**Comment by kdambekalns** [comment]
Implicit task for `set-dependencies.sh`, indeed.
