### ISSUE TITLE
Autocomplete link suggestions don't contain nodes of the current dimension after switching dimension

### ISSUE THREAD

**Issue by davematter** [neos/neos-development-collection#1362]
### Description
There is an issue with creating links in a multi-dimension setup. After changing from one dimension to the other in the Neos backend, it's not possible to search for nodes to link to from the current dimension. Only nodes of the previously visited dimension are taken into account while inserting a link.

### Steps to Reproduce

1. Log into the Neos backend
2. Change to another dimension (e.g. from /de_de/ to /us_en/)
3. Insert a link in a text field and start typing/searching for the document node that you want to link to

![bildschirmfoto 2016-12-22 um 10 14 29](https://cloud.githubusercontent.com/assets/941740/21422580/9c3a269c-c838-11e6-9bbe-0e532e1b1f5b.png)

#### Expected behavior
The link suggestions should only contain nodes of the current dimension.

#### Actual behavior
The link suggestions don't contain nodes of the current dimension. Instead, only nodes of the previously visited dimension are suggested.
E.g. if you're on the /us_en/ dimension, only german links of the /de_de/ dimension are shown if you've previously visited the /de_de/ dimension in the backend. 

### Affected Versions
Neos: 2.3.x, 3.0.x
Flow: 3.3.6

**Comment by peterbucher** [comment]
**Is this issue fixed within the new Neos Backend UI?**
For a Workaround: Force reload the Neos Backend does show links to the correct dimensions.
