### ISSUE TITLE
TypoScript  to Fusion migration not complete

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-development-collection#1363]
If you migrate a project with a custom TypoScript/Fusion object implementation you usually extend from
`TYPO3\TypoScript\TypoScriptObjects\AbstractTypoScriptObject`

unfortunately the migration changes this to:

`Neos\Fusion\TypoScriptObjects\AbstractTypoScriptObject`

which is a non existing class name. It should migrate to:

`Neos\Fusion\FusionObjects\AbstractTypoScriptObject`

to reference the now deprecated class.

Same probably applies to everything else in a namespace containing TypoScript.

**Comment by bwaidelich** [comment]
> It should migrate to:
> Neos\Fusion\FusionObjects\AbstractTypoScriptObject
> to reference the now deprecated class.

Couldn't we change it to `Neos\Fusion\FusionObjects\AbstractFusionObject` directly?

**Comment by kitsunet** [comment]
We could, but might be hard to figure out all possible permutations of use statements people might be using ;)
