### ISSUE TITLE
CSS img transition all leads to strange image cropping behavior

### ISSUE THREAD

**Issue by digitalpunkt** [neos/neos-development-collection#1373]
### Description

If you use something like img {  transition: all 0.5s ease; } on your page css file the image cropping tool looks a bit strange.

### Steps to Reproduce

1. Use img {  transition: all 0.5s ease; } in your CSS.
2. Enable cropping on your image property
'YourCompany:YourType':
  properties:
    image:
      ui:
        inspector:
          editorOptions:
            features:
              crop: TRUE
3. Crop an image

#### Expected behavior
![bildschirmfoto 2017-01-05 um 16 01 59](https://cloud.githubusercontent.com/assets/9802247/21685133/a6a3bb9c-d360-11e6-9009-38eb552f5a4c.png)

#### Actual behavior
![bildschirmfoto 2017-01-05 um 16 03 12](https://cloud.githubusercontent.com/assets/9802247/21685138/abdfaa6c-d360-11e6-97c7-3f5d7d6a10cd.png)

The original image is displayed way to small and does't fill the complete layer. Also the small thumbnail in the inspector can move behind the "mask" if you drag the selected area in the cropping tool around.

### Affected Versions
Neos: 2.3.x

**Comment by aertmann** [comment]
Hey thanks for reporting, it's pretty hard to prevent all conflicts with generic css like that. In the rewrite it will be encapsulated in an iframe, thus avoiding such issues.

However for now I'd suggest you simply unset that rule for the Neos backend, can even be loaded as a conditional backend stylesheet.

Something like:
    .neos img {
        transition: none;
    }

**Comment by kitsunet** [comment]
Won't fix, rewritten UI with iframe won't have that problem.
