### ISSUE TITLE
Missing translations for the media module

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#1380]
The current version of the media module lacks some translations.

![image](https://cloud.githubusercontent.com/assets/642226/21956244/b9cc487e-da7c-11e6-9e46-88ad32d08c89.png)
![image](https://cloud.githubusercontent.com/assets/642226/21956246/c83322ac-da7c-11e6-9cbb-dd25e6a33232.png)

### Affected Versions

Neos: master

**Comment by daniellienert** [comment]
@Sebobo: Are the covered with https://github.com/neos/neos-development-collection/pull/1305?

**Comment by kdambekalns** [comment]
Could you check this with the german version in latest 3.0/3.1? I shuffled some labels around in https://github.com/neos/neos-development-collection/pull/1624 - if that helps, it probably affects other languages as well and can be fixed by finally getting Crowdin running again…

**Comment by daniellienert** [comment]
Should be fixed in the meantime
