### ISSUE TITLE
Strange tooltip behaviour in node tree

### ISSUE THREAD

**Issue by jod4** [neos/neos-development-collection#1386]
### Description

- Tooltips over node tree elements don't always get removed from DOM once hovering over them has stopped.

### Steps to Reproduce
1. Make sure the node tree has a scroll bar
2. Hover over node tree element until the tooltip appears
3. Scroll around or click on another node tree element
4. Inspect the DOM at id="neos-application" -> watch for elements with class="neos-tooltip"

#### Expected behavior

The tooltip should disappear when hovering over the node tree element stops

#### Actual behavior

The tooltip is still there, either invisible in the DOM or actually visible in the node tree editor, see attached screenshot (yellow color highlighting the issue, done by our customer)

![tooltip_issue](https://cloud.githubusercontent.com/assets/1199165/22110839/806c1200-de5d-11e6-9535-170deb3250d2.png)

### Affected Versions

Neos: 2.3.7
and also confirmed for 2.2.5

Flow: 3.3.4

**Comment by mgoldbeck** [comment]
@jod4 First thank you for reporting, but isn't that the same bug as described in https://github.com/neos/neos-development-collection/issues/1387 ?

**Comment by knusperpixel** [comment]
@mgoldbeck no, I don't think so. #1387 describes that the tooltip is scrolling with the page content. This issue is about multiple tooltips shown at once.

**Comment by ComiR** [comment]
In `3.0.1` it only happens when the page scrolls (i.e. after #1387). So this could be fixed when the other one is.

**Comment by kdambekalns** [comment]
Tried to reproduce this today with latest Neos 2.2 and 2.3 using Chrome on OSX, without success. I _have_ seen those sticky tooltips in the past, though…

**Comment by kdambekalns** [comment]
Ok, I can reproduce it. Just, even when looking at the recording I don't understand what I did there. This is latest Neos 2.3 (con't let the URLs confuse you).

https://dl.dropboxusercontent.com/u/1536167/Neos-1386-ScreenFlow.gif

**Comment by kdambekalns** [comment]
Ok… Here we go: if you collapse or expand a subtree without moving the mouse afterwards, a tooltip appears. If you then move the mouse pointer away _without moving over the node title_, the tooltip stays. It even "survives" hovering over other nodes (but the next click makes it disappear).

I was not able to produce multiple stuck tooltips.

**Comment by ComiR** [comment]
Try:
1. selecting a node without navigating to it (click the row but not the title)
2. scroll the page
3. hover over the title of another node

I am only able to produce one additional tooltip. On selecting another node the first one will disappear (the second one only stays on hover).
