### ISSUE TITLE
Tooltip scrolling issue

### ISSUE THREAD

**Issue by jod4** [neos/neos-development-collection#1387]
### Description

- Tooltips over node tree elements won't disappear on scroll wheel events, hence, the tooltip will be shown on top of another element

### Steps to Reproduce

1. Make sure the node tree has a scroll bar
2. Hover over node tree element until the tooltip appears
3.Scroll around or click on another node tree element

#### Expected behavior

The tooltip should disappear when scrolling starts

#### Actual behavior

The tooltip stays visible, at least until the mouse gets moved

![pasted_image_at_2017_01_19_15_19](https://cloud.githubusercontent.com/assets/1199165/22111061/409f3034-de5e-11e6-81d5-658bf40f6b10.png)

### Affected Versions

Neos: 2.3.7
and also confirmed for 2.2.5

Flow: 3.3.4

**Comment by knusperpixel** [comment]
Actually, it happens when the *page* is scrollable! 
If the node tree is scrollable, the behaviour is correct as long as the scrolling happens inside the node tree, but as soon as the page scrolls, the wrong behaviour is shown.

**Comment by daniellienert** [comment]
@kdambekalns: This can finally considered fixed?

**Comment by kdambekalns** [comment]
@daniellienert no, the PR is still open…!?
