### ISSUE TITLE
Default converter for `array` Node properties

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-development-collection#1399]
Since the reworked property mapping of node properties a converter for properties can be assigned per property type.

The default converter for type `array` is currently `TYPO3\Flow\Property\TypeConverter\TypedArrayConverter` which doesn't make much sense, because there is no type defined for elements in this array. For the basic `array` type the `TYPO3\Flow\Property\TypeConverter\ArrayConverter` should be set as default.

**Comment by joachimmathes** [comment]
I will take care of this issue.
