### ISSUE TITLE
Edit and replace in the Media module does not work in list mode when opened via Neos inspector

### ISSUE THREAD

**Issue by hlubek** [neos/neos-development-collection#1408]
### Description

Edit and replace in the Media module does not work in list mode when opened via Neos inspector.

### Steps to Reproduce

1. Select a node that has an image/asset property
2. Click "Media"
3. Change to list layout
4. Select the dropdown with actions
5. "Edit" and "Replace" have no functionality but selects the asset

#### Expected behavior

"Edit" and "Replace" work the same as in the tile view

#### Actual behavior

"Edit" and "Replace" have no functionality but selects the asset

### Affected Versions

Neos: 2.3 (tested with 2.3.8, 2.3.x-dev) but not 3.0, did not test below 2.3

**Comment by hlubek** [comment]
See fix in #1401 that was applied to 3.0 recently

**Comment by Sebobo** [comment]
Hi, @hlubek can this be closed? Your PR is merged.
