### ISSUE TITLE
ImageMagick 7.0.4 and php70-imagick 3.4.2: undefined ALPHACHANNEL_RESET

### ISSUE THREAD

**Issue by fschwaiger** [neos/neos-development-collection#1412]
### Description

This reopens #580, because I managed to install (via homebrew) imagemagick 7.0.4 and php70-imagick 3.4.2 without getting an error notice that my version should be incompatible.

Yet I run into the error that ALPHACHANNEL_RESET and ALPHACHANNEL_OFF are both undefined, which gives me a cryptic error message that is hard to debug.

I suggest throwing a warning about incompatible versions when compiling the YAML configuration.

### Steps to Reproduce

1. `brew install imagemagick` (⇒ 7.0.4)
2. `brew install php70-imagick` (⇒ 3.4.2)
3. set `Imagick` driver in `Settings.yaml`
4. render PDF thumbnails

#### Expected behavior

first PDF page is turned into thumbnail image

#### Actual behavior

```
Undefined class constant 'ALPHACHANNEL_RESET'

Exception Code	0
Exception Type	Error
Thrown in File	Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Media_Domain_Model_ThumbnailGenerator_DocumentThumbnailGenerator.php
Line	76
Original File	Packages/Application/Neos.Media/Classes/Domain/Model/ThumbnailGenerator/DocumentThumbnailGenerator.php
```

The only constants available to me are:
```
["ALPHACHANNEL_ACTIVATE"]=> int(1)
["ALPHACHANNEL_SET"]=> int(13)
["ALPHACHANNEL_UNDEFINED"]=> int(0)
["ALPHACHANNEL_COPY"]=> int(4)
["ALPHACHANNEL_DEACTIVATE"]=> int(5)
["ALPHACHANNEL_EXTRACT"]=> int(8)
["ALPHACHANNEL_OPAQUE"]=> int(11)
["ALPHACHANNEL_SHAPE"]=> int(14)
["ALPHACHANNEL_TRANSPARENT"]=> int(15)
["ALPHACHANNEL_ASSOCIATE"]=> int(2)
["ALPHACHANNEL_DISSOCIATE"]=> int(7)
["ALPHACHANNEL_BACKGROUND"]=> int(3)
["ALPHACHANNEL_REMOVE"]=> int(12)
```

### Affected Versions

Neos: 3.0.x-dev
Flow: 4.0.x-dev

**Comment by dlubitz** [comment]
@fschwaiger Sorry, but IMHO this is not an Neos issue. 

Imagick starts to support ImageMagick 7 with version 3.4.3RC1. Earlier versions don't support the new constants of IM7. So just update your imagick should solve the problem.

**Comment by fschwaiger** [comment]
In that case this can be solved by adding a line to the installation doc page.
Or how about adding a comment to the exception message to check the installed version?

**Comment by kdambekalns** [comment]
Thanks!

But… there are countless combinations leading to broken results… if we warned about or documented all of them, we'd do nothing else.

Of course, feel free to open a PR!
