### ISSUE TITLE
Drop asset on tag failed

### ISSUE THREAD

**Issue by breadlesscode** [neos/neos-development-collection#1413]
### Description

If i drop an asset on a tag, the message "Tagging the asset failed." appears. 
It trys to recive data from /neos/management/media/tagasset.json but this is the response:

```
Required argument "asset" is not set.

Exception Code	1298012500
Exception Type	Neos\Flow\Mvc\Exception\RequiredArgumentMissingException
Log Reference	201702041221296ce9e5
Thrown in File	Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Controller_AbstractController.php
Line	370
Original File	Packages/Framework/Neos.Flow/Classes/Mvc/Controller/AbstractController.php
```

### Steps to Reproduce

1. Create new Tag  
2. Drop asset on it

#### Expected behavior

Asset added to tag

#### Actual behavior

Error message shown. 

### Affected Versions

Neos: 3.0.0
Flow: 4.0.0

**Comment by aertmann** [comment]
Thanks for reporting, submitted a fix for the bug.
