### ISSUE TITLE
Check VHs for standalone compatiblity

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-development-collection#1416]
There are reports of possibly broken VH behavior with Neos 3.0, so it might be that adjustments need to be made.

`<f:if condition="{neos:rendering.live()}">` seems to be broken eg.

**Comment by Flofas** [comment]
I mentioned the following issue:

I have a Default.html as Template for my standard `Neos.Neos:Page` -> `body` Object.
Inside that Template 
`<f:if condition="{neos:rendering.live()}">
			<f:then>
				Shown outside the backend.
			</f:then>
			<f:else>
				Backend
			</f:else>
		</f:if>` 
works fine.

But if i try to use this snippet inside my Stylesheet.html Template, which is type of `Neos.Fusion:Template`
The Condition doesn't work anymore and is always true.

Hope i can help with that.

**Comment by kitsunet** [comment]
Yes indeed you do, the issue is, that your Stylesheet.html template probably doesn't have `node` set as template variable, so we cannot actually find out what is right.
