### ISSUE TITLE
No way to flush caches when an image resource was replaced

### ISSUE THREAD

**Issue by dimaip** [neos/neos-development-collection#1434]
Currently if you replace an image resource in Media browser, there is no way to configure automatic Fusion cache flushing for nodes that use that image.

I have no idea how to fix it, but it could be an issue for editors. The only manual workaround for them is to manually "touch" all relevant nodes that use that image.

Any ideas?

**Comment by kitsunet** [comment]
I guess we could create a helper that extracts external references to objects from a node and creates tags for them. That way we could flush by those tags.

**Comment by daniellienert** [comment]
Couldn't we use the asset usage strategies for that? In the moment the asset replaces, all nodes that reference that asset need be market as changed, which then triggers the cache flushing as configured.

**Comment by aertmann** [comment]
This should already be the case with https://github.com/neos/neos-development-collection/blob/192d9ead6addeba75c532d747298321210eb592d/Neos.Neos/Classes/Package.php#L79 + https://github.com/neos/neos-development-collection/blob/cbbffec2d5fc187f3b91da6997af8f48326c4480/Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php#L94

**Comment by kdambekalns** [comment]
@dimaip Indeed that works fine with images used as "real image properties". But links to assets (`asset://…`) do not work, is that what you experienced? If so, I have a fix prepared that I'll push today.

**Comment by kdambekalns** [comment]
Is that solved with #1575?
