### ISSUE TITLE
Moving a node breaks if using shared workspace

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#1439]
### Description

If a page is moved while the personal workspace is based on an internal (shared) workspace, publishing that move leaves a broken node tree behind.

### Affected Versions

Neos: tested on Neos 2.3.9

##### original state

uuid|id|ws|removed|movedto
-|-|-|-|-
09b8c31d-97b8-49ec-b6ea-731d9940c1ec|33bebafa-c7ee-401a-935e-33cf820127dd|live|0|~

##### moved, not published yet

uuid|id|ws|removed|movedto
-|-|-|-|-
09b8c31d-97b8-49ec-b6ea-731d9940c1ec|33bebafa-c7ee-401a-935e-33cf820127dd|live|0|~
4b217064-a9ea-4149-abee-7e6ef801c2e2|33bebafa-c7ee-401a-935e-33cf820127dd|user|1|428657d7-9837-4b75-bd7a-e8455af789c6
428657d7-9837-4b75-bd7a-e8455af789c6|33bebafa-c7ee-401a-935e-33cf820127dd|user|0|~

##### published to "relaunch"

uuid|id|ws|removed|movedto
-|-|-|-|-
09b8c31d-97b8-49ec-b6ea-731d9940c1ec|33bebafa-c7ee-401a-935e-33cf820127dd|live|0|~
4b217064-a9ea-4149-abee-7e6ef801c2e2|33bebafa-c7ee-401a-935e-33cf820127dd|relaunch|1|428657d7-9837-4b75-bd7a-e8455af789c6
428657d7-9837-4b75-bd7a-e8455af789c6|33bebafa-c7ee-401a-935e-33cf820127dd|relaunch|0|~

##### published to "live"

uuid|id|ws|removed|movedto
-|-|-|-|-
09b8c31d-97b8-49ec-b6ea-731d9940c1ec|33bebafa-c7ee-401a-935e-33cf820127dd|live|0|~

**-> all works well**

---

##### original state

uuid|id|ws|removed|movedto
-|-|-|-|-
8d24ee46-4fd1-4787-bb95-683dc8841ee8|bd6b7a71-4fbe-4ad1-abee-2d13a3e7400a|relaunch|0|~

##### moved, not published yet

uuid|id|ws|removed|movedto
-|-|-|-|-
8d24ee46-4fd1-4787-bb95-683dc8841ee8|bd6b7a71-4fbe-4ad1-abee-2d13a3e7400a|relaunch|0|~
453f79c1-9a8d-4b8d-bc2a-9aec34ad5211|bd6b7a71-4fbe-4ad1-abee-2d13a3e7400a|user|1|597fd303-6b88-431b-80b1-1e89ef7f10e4
597fd303-6b88-431b-80b1-1e89ef7f10e4|bd6b7a71-4fbe-4ad1-abee-2d13a3e7400a|user|0|~

##### published to "relaunch"

uuid|id|ws|removed|movedto
-|-|-|-|-
8d24ee46-4fd1-4787-bb95-683dc8841ee8|bd6b7a71-4fbe-4ad1-abee-2d13a3e7400a|relaunch|0|~
130f8176-ec02-4453-a4ff-9a8f18676523|bd6b7a71-4fbe-4ad1-abee-2d13a3e7400a|relaunch|0|~    <--- new position

at this point the workspace module shows one added node, no other changes. publishing "works", but afterwards a change is shown. that is the "original new node" now being visible again in the "relaunch" workspace:

##### published to live

uuid|id|ws|removed|movedto
-|-|-|-|-
8d24ee46-4fd1-4787-bb95-683dc8841ee8|bd6b7a71-4fbe-4ad1-abee-2d13a3e7400a|relaunch|0|~
130f8176-ec02-4453-a4ff-9a8f18676523|bd6b7a71-4fbe-4ad1-abee-2d13a3e7400a|live|0|~

publishing that change "works", in that it simply discards the "original new node":

##### published to live again

uuid|id|ws|removed|movedto
-|-|-|-|-
130f8176-ec02-4453-a4ff-9a8f18676523|bd6b7a71-4fbe-4ad1-abee-2d13a3e7400a|live|0|~

**-> in some cases it doesn't end that well, maybe related to other pending changes (child nodes to the moved node, other changes on the node itself…**

**Comment by kitsunet** [comment]
Meh, I know we added code to fix the movedTo stuff on publish for layered workspaces, I will add a note when I found it. So apparently that doesn't catch all cases or is simply broken.

**Comment by kitsunet** [comment]
\TYPO3\TYPO3CR\Domain\Model\Workspace::handleShadowNodeData should be it

**Comment by kdambekalns** [comment]
Solved with #1609.
