### ISSUE TITLE
atal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 17988001 bytes) 

### ISSUE THREAD

**Issue by zopyx** [neos/neos-development-collection#1445]
I installed NEOS according to 

https://www.neos.io/download-and-extend.html

on my Mac.

After installation I tried to few the fresh created site. But this fails with...

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 17988001 bytes) in /Users/ajung/src/neos1/Packages/Libraries/imagine/imagine/lib/Imagine/Gd/Image.php on line 617

Why is NEOS trying to allocated 132 GB of memory?

<img width="1377" alt="screenshot 2017-03-04 10 56 11" src="https://cloud.githubusercontent.com/assets/594239/23577829/87654264-00c9-11e7-9ddb-10351de9286d.png">

**Comment by zopyx** [comment]
```
{
    "name": "neos/neos-base-distribution",
    "description": "Neos Base Distribution",
    "license": "GPL-3.0+",
    "support": {
        "email": "hello@neos.io",
        "slack": "http://slack.neos.io/",
        "forum": "https://discuss.neos.io/",
        "wiki": "https://discuss.neos.io/c/the-neos-project/project-documentation",
        "issues": "https://github.com/neos/neos-development-collection/issues",
        "docs": "http://neos.readthedocs.org/",
        "source": "https://github.com/neos/neos-base-distribution"
    },
    "config": {
        "vendor-dir": "Packages/Libraries",
        "bin-dir": "bin"
    },
    "require": {
        "neos/neos": "~3.0.0",
        "neos/nodetypes": "~3.0.0",
        "neos/demo": "~3.0.0",
        "neos/site-kickstarter": "~3.0.0",

        "neos/seo": "~2.0",
        "neos/setup": "~4.0",
        "flowpack/neos-frontendlogin": "~3.0",
        "neos/redirecthandler-neosadapter": "~2.0",
        "neos/redirecthandler-databasestorage": "~2.0"
    },
    "require-dev": {
        "neos/buildessentials": "~4.0.0",
        "mikey179/vfsstream": "~1.6",
        "phpunit/phpunit": "~5.4.0",
        "symfony/css-selector": "~2.0",
        "neos/behat": "dev-master"
    },
    "replace": {
        "typo3/neos-base-distribution": "3.0.1"
    },
    "suggest": {
        "ext-pdo_sqlite": "For running functional tests out-of-the-box this is required"
    },
    "scripts": {
        "post-update-cmd": "Neos\\Flow\\Composer\\InstallerScripts::postUpdateAndInstall",
        "post-install-cmd": "Neos\\Flow\\Composer\\InstallerScripts::postUpdateAndInstall",
        "post-package-update": "Neos\\Flow\\Composer\\InstallerScripts::postPackageUpdateAndInstall",
        "post-package-install": "Neos\\Flow\\Composer\\InstallerScripts::postPackageUpdateAndInstall"
    }
}
```

**Comment by aertmann** [comment]
Hey

Neos is trying to scale images which requires a good amount of memory depending on the size of the original image being scaled.

It's not trying to allocate 132 GB, but 134 MB which is higher than the default PHP limit which is 128 MB.

There are two ways of solving this issue, either raise the memory limit in PHP or use the Imagick PHP module which isn't limited by PHP's memory limit to process images.

http://php.net/manual/en/book.imagick.php

This is done by adjusting the configuration setting `Neos.Imagine.driver` from `Gd` to `Imagick`. And make sure the PHP module is installed and enabled.
