### ISSUE TITLE
Unable to log into the NEOS backend

### ISSUE THREAD

**Issue by zopyx** [neos/neos-development-collection#1447]
Installed NEOS from scratch on MacOS, I created a new site and now tried to login into the site which fails badly,
![screenshot-127 0 0 1-8081-2017-03-04-11-52-20](https://cloud.githubusercontent.com/assets/594239/23578180/2daf2dd6-00d1-11e7-9588-0d26663faa21.png)

**Comment by aertmann** [comment]
Hi thanks for opening an issue, this bug has already been reported and fixed in the development version but not yet released as a stable release. As soon `3.0.2` gets released the issue will be gone. Sorry for the inconvenience.

#1436
