### ISSUE TITLE
rel attribute on link renders empty content collection in backend

### ISSUE THREAD

**Issue by janinadanger** [neos/neos-development-collection#1449]
I have a problem with neos-empty-contentcollection-overlay rendering on links with `rel="value"` attribute. I have various links in my code like this `<a href="someLink" rel="nofollow">linktext</a>`. Neos renders and empty div.neos.neos-empty-contentcollection-overlay into this link, which breaks my layout

![example](https://cloud.githubusercontent.com/assets/8765633/23606234/1940e0d4-0260-11e7-9c8c-1900ad214ac1.png)

### Steps to Reproduce

1. Create a link with an rel tag
2. Open the site in the backend
3. you can see the empty collection overlay at that link position

#### Expected behavior

The empty content collection overlay should not be rendered

### Affected Versions

This bug appears at least on Neos 2.3 and 3.0

**Comment by aertmann** [comment]
Thanks for reporting, fixed the issue. Will be available in the next bugfix release.
