### ISSUE TITLE
BUG: prototype extending Neos.Neos:Page outputs unnecessary string

### ISSUE THREAD

**Issue by wexi79** [neos/neos-development-collection#1510]
### Description

When trying to follow the steps "Select Template based on NodeType" or "Using a DefaultPage Prototype" described here: http://neos.readthedocs.io/en/stable/HowTos/SelectingPageTemplate.html, the page renders an extra string containing the templatePath, title, URL segment and title override of the current page between the </head> and <body> tags.

### Steps to Reproduce

Create a page configuration following the documentation instructions mentioned above.

#### Expected behavior

Page renders without the extra string

#### Actual behavior

Page renders with an extra string that is not defined in the template

### Affected Versions

Neos: 3.0.2

Flow: 4.0.2

**Comment by sorenmalling** [comment]
Just adding a note from my experience after debugging the outout

@wexi I found out the the word `body` is “constantly” (lack of better word) having the site and node property filled (even if you reset it). So when I turn it into a array, they are printed
 
So for now, my main Page object (that the other inherits from) has this block
```
    body >
    content = Neos.Fusion:Array
```

**Comment by mgoldbeck** [comment]
@wexi79 did the note from @sorenmalling help you? Is this still a issue for you?

**Comment by wexi79** [comment]
Haven't checked with the latest Neos code but I'm assuming the problem persists.

**Comment by kitsunet** [comment]
Ok, I have some insight on this.

I suspect the automatically generated Fusion prototype for the NodeType interferes and is also not considered in the piece of documentation.

So given you have a document NodeType `Vendor.Package:SuperDocument` and you want to use that, you should try to clean it before inheriting from the default Page prototype:

```
prototype(Vendor.Package:SuperDocument) >
prototype(Vendor.Package:SuperDocument) < prototype(Neos.Neos:Page) {
...
}
```

And the rest from the docs obviously.

I think that should get rid of it.

**Comment by wexi79** [comment]
Thanks Christian, I will try this and report back if the solution works.

**Comment by lorenzulrich** [comment]
I had the same problem and @kitsunet's tip helped solve it. Thanks!

**Comment by kitsunet** [comment]
By now in new installations the Documents do not generate a NodeType by default anymore so that should have become unnecessary.

Either way closing.
