### ISSUE TITLE
404 for Fonts in Neos.Media.Browser

### ISSUE THREAD

**Issue by Nikdro** [neos/neos-development-collection#1517]
### Description

The media browser tries to load not existing Fonts from Neos.Media.Browser Package.
I think it's superfluous here, because they are already loaded by Neos itself... See here: 
<img width="444" alt="bildschirmfoto 2017-04-05 um 16 29 06" src="https://cloud.githubusercontent.com/assets/9807101/24710383/451e4d98-1a1d-11e7-9dbc-aed1e40ade5a.png">

### Steps to Reproduce

1. Login to Neos 3.0 Backend
2. Start Browser debugging tool (like firebug)
3. Open media browser
4. Look at network tab of debugger

#### Expected behavior

I think these Fonts should not be loaded again.

#### Actual behavior

Browser tries to load it form Neos.Media.Browser. But it's not there.

### Affected Versions
Neos:  3.X

**Comment by aertmann** [comment]
Thanks for reporting. Could be related to using minified resources or not. Loading them again should be fine as it doesn't do anything, but of course the resource path should be correct.

**Comment by kitsunet** [comment]
Has been fixed with https://github.com/neos/neos-development-collection/pull/1584
