### ISSUE TITLE
'defaultValue' of a NodeType Property is not getting translated

### ISSUE THREAD

**Issue by RadiRadiesel** [neos/neos-development-collection#1520]
### Description

After creating a NodeType I can set a 'defaultValue:' of a specific property. But this default Value is not getting translated using a translation .xlf file.

### Steps to Reproduce

1. Create NodeType
2. Add new property to NodeType 
3. set "defautValue: i18n" in .yaml fpr the NodeType under properties
4. create .xlf for your NodeType
5. add <trans-unit> entry into the .xlf file for the defaultValue. (e.g. 
  <trans-unit id="properties.myPropertx.defaultValue" xml:space="preserve">
    <source>myDefaultText</source>
  </trans-unit>

#### Expected behavior

default Value entered in .xlf file should show up

#### Actual behavior

instead default Value from .xlf, 'i18n' is showing up.

### Affected Versions

Neos: 3.0

Flow: 4.0

You can get this information by running `composer show` or using the package management module within Neos.

**Comment by aertmann** [comment]
This is an unsupported feature, thus not a bug. In short it's complicated.

Should it use the backend interfaces language to determine which language to use? Or should it use the arbitrary language content dimension to determine which language to use?

The former is easier to implement, but not yet supported and could easily cause confusion.

Feel free to provide your suggestions so we can talk about potential solutions.

**Comment by kitsunet** [comment]
IMHO this is impractical as it is the `defaultValue` of that property. So it's not a label but something stored to the database. It shouldn't depend on the editor, if anything it had to depend on the node dimensions but that is as Aske pointed out pretty difficult.

**Comment by jonnitto** [comment]
@kitsunet @mhsdesign I think something like 

```
defaultValue: "${I18n.translate('translationID', null, [], 'Main', 'Foo.Bar'}"
```

would be nice. Sometimes you want to set a default value, but an empty value should also be possible, this is why a placeholder isn't always the solution

**Comment by mhsdesign** [comment]
yes and no 🤔 it would be possible to do this in a node type preprocessor as a plugin right now, but i would say that shouldnt be part of the cores responsibility.

**Comment by jonnitto** [comment]
Hm. I'll try a workaround with node templates…

If it is successful, an entry on docs.neos.io would be good

**Comment by jonnitto** [comment]
It's quite easy with  [Flowpack.NodeTemplates](https://github.com/Flowpack/Flowpack.NodeTemplates)

```yaml
Foo.Bar:Content:Message:
  options:
    template:
      properties:
        message: "${I18n.translate('Foo.Bar:NodeTypes.Content.Message:properties.message.defaultValue')}"
```
