### ISSUE TITLE
PHP version dependency should be added in the composer.json file

### ISSUE THREAD

**Issue by ManthanBudheliya** [neos/neos-development-collection#1534]
Hello friends.

I don't know that it is a bug or not. I have just got a problem.
I have installed neos-base-distribution using the PHP 5.6 cli. and I got the PHP void return type issue with the ProxyManager package.
After some researching and communicating with the devs in slack, I found that PHP cli version when installing using composer creates problem.
So it would be better if the correct version of PHP is placed in the composer.json file so this problem will not arise for the new comers like me.

Thanks!

**Comment by dimaip** [comment]
To add to the discussion, I only see the php constraint here, and it's outdated too: https://github.com/neos/neos-development-collection/blob/master/composer.json#L18

Where do we want to put the php version constraint? In distributions only, or also on all read-only packages?

**Comment by kitsunet** [comment]
https://github.com/neos/flow-development-collection/blob/master/composer.json#L9 at least is right and should prevent the distribution from being installed?

But we should fix those for neos as well and probably also put them in the distribution.

**Comment by dimaip** [comment]
@kitsunet yep, but @ManthanBudheliya was using the normal distribution. So where exactly do we put them in the end? All distributions and collections, or also all packages?

**Comment by ManthanBudheliya** [comment]
@kitsunet 
I think we could add at the 23rd line of this file https://github.com/neos/neos-base-distribution/blob/master/composer.json
`"php" :"~7.0" `

It is also not available in the flow base distribution https://github.com/neos/flow-base-distribution/blob/master/composer.json

**Comment by kitsunet** [comment]
@dimaip every package should have one IMHO.

**Comment by mhsdesign** [comment]
The base distributions still dont have that version constraint, but that is fine - the packages neos/neos and neos/flow have it and with it an installation would fail if the wrong php version is present.
