### ISSUE TITLE
Fusion: getFusionPathForCurrentRequest returns invalid path

### ISSUE THREAD

**Issue by sorenmalling** [neos/neos-development-collection#1535]
The method `getFusionPathForCurrentRequest` from FusionView is used if no fusionPath is set.

When using Fusion without Neos, to render a application, the generated fusion path is not valid.

It returns paths like

/App/Application/UserController/settings

and that is not valid inside .fusion files. 

**Solution**
Use a different delimiter than "/"

**Another note** 
Could Fusion be released from the Neos development package as it does some nice things to application building, even when not used with neos

**Comment by kitsunet** [comment]
Fusion can be installed separately, it has no dependencies on Neos or CR. Just require `neos/fusion`.

**Comment by sorenmalling** [comment]
@kitsunet The reason for it to be used separately is the argument for letting it have it's own issue tracker. Thanks for marking this as a bug.

**Comment by kitsunet** [comment]
Hey @sorenmalling the deliminator and path are actually correct, for some reasons we couldn't use the `.` internally, so basically `/App/Application/UserController/settings` translates to the actual Fusion path `App.Application.UserController.settings`. Closing for now.

**Comment by sorenmalling** [comment]
@kitsunet When I enter 

`/App/Application/UserController/settings = <what-ever-object>`

The parser throws a syntax error - sorry for not mentioning that in the first post

**Comment by kitsunet** [comment]
As said, that is correct, you need to enter `App.Application.UserController.settings`.
