### ISSUE TITLE
Node loses focus when removing image in the inspector

### ISSUE THREAD

**Issue by PalatinCoder** [neos/neos-development-collection#1536]
### Description

When you remove an image in the image editor pressing the remove button, the node loses the focus and the inspector shows the properties of the document node. In the structure tree you can see that the document node got the focus now, however the blue border around the element stays. Also, the inspector has some unsaved changes (clicking somewhere on the page the dialog is shown). When you save them, some property of the document node is changed, although it isn't clear which one.

![neos_imageeditor_bug](https://cloud.githubusercontent.com/assets/11162390/25294505/cc65c15e-26df-11e7-9667-940127efaa1d.gif)

### Steps to Reproduce

1. Log in to Neos backend
2. Select any node (but not the document node) with a property of type "Image", so that the image editor is loaded in the inspector
3. Press "Remove"

#### Expected behavior

The image is removed and the dummy is shown in the editor. After clicking "Apply" the dummy is also shown on the page.

#### Actual behavior

The inspector shows the properties of the document node. There are unsaved changes in the inspector but you can't see which ones they are. The actual change can't be saved, which in fact makes it impossible to delete images overall.

### Affected Versions

neos/neos: 3.0.3
neos/demo: 3.0.3
neos/flow: 4.0.6
Only with Google Chrome 58

Not affected:
typo3/neos: 2.3.12
neos/demo: 2.3.12
typo3/flow 3.3.13
with Chrome 58

With Firefox also Neos 3.0.3 is not affected

**Comment by mhsdesign** [comment]
This is not an issue in the React Ui which replaced Ember some long time ago, so i will close this ;)
