### ISSUE TITLE
Auto generated references needs to be updated in docs

### ISSUE THREAD

**Issue by iseries** [neos/neos-development-collection#1558]
"_Command Reference_" and "_Media ViewHelper Reference_" is outdated.
I wanted to correct it but then i read that the reference was automatically generated from code. I don't know how this actually works, so this needs to be updated.

https://neos.readthedocs.io/en/stable/References/CommandReference.html
https://neos.readthedocs.io/en/stable/References/ViewHelpers/Media.html (see tags in examples)

**Comment by bwaidelich** [comment]
@iseries Hi and thanks for your report.

Can you clarify what you mean by "is outdated"?
That it's still referring to "TYPO3"?
The references are mostly generated from inline code docs, like https://github.com/neos/neos-development-collection/blob/master/Neos.Media/Classes/ViewHelpers/ImageViewHelper.php#L20-L68  They should be adjusted accordingly

**Comment by bwaidelich** [comment]
Nevermind. What I wrote above is true, but the references need to be re-generated, too.
I'll take care
