### ISSUE TITLE
Dimensions not working on vanilla 3.1 installation

### ISSUE THREAD

**Issue by jobe451** [neos/neos-development-collection#1564]
### Description

I use a vanilla 3.1 installation with MariaDB

Following the documented procedures, I can't get language-dimensions to work. ./flow node:repair proposes to remove the site. If confirmed, the site is ruined.

Question was also posted to:
https://discuss.neos.io/t/page-not-found-after-adding-dimensions/2224/1

### Steps to Reproduce

1. Install Neos according to https://neos.readthedocs.io/en/stable/GettingStarted/Installation.html
2. Create a new vanilla site
3. Adding to Settings.yaml the example configuration from https://neos.readthedocs.io/en/stable/HowTos/TranslatingContent.html#cookbook-translating-content2
4. Remove the settings added in step 3.
5. Do: ./flow node:repair and confirm removing the 3 pages the system proposes ("Node /sites/dim has invalid dimension values: {"language":["en_US"]}")

### Actual and Expeced behaviour
* After Step 2: I have an empty site that runs. Adding a header like "Hello World" works fine
* After Step 3: I get "Page Not Found" ... "The requested node does not exist or isn't accessible to the current user" for both / and /neos
* After Step 4: The system works again
* After Step 5: I get again "Page Not Found", it seems the page is now ruined for good

### Affected Versions
Neos 3.1

**Comment by mgoldbeck** [comment]
Hi @jobe451 thank you for your report and sorry for the long waiting for a response. Will try to reproduce it within the next day.

**Comment by kitsunet** [comment]
This is not a bug, you still had the demo site installed side by side which brings it's own dimensoin configuration. But dimension configuration is global across all sides so this interferes with your newly created site as well.

To fix this clean your DB, remove the demo site and start with just your own side. That should owrk just fine.

**Comment by jobe451** [comment]
I did follow your instructions. I removed the demos directory. I reiniated the mysql-db from scratch. I followed the tutorial. I stll get that page-not-found error.
