### ISSUE TITLE
Asset list broken since Neos 3.1

### ISSUE THREAD

**Issue by PalatinCoder** [neos/neos-development-collection#1568]
### Description

Editing nodes of type Neos.NodeTypes:AssetList or derived types is broken since Neos 3.1

### Steps to Reproduce

1. Log in to backend
2. Create a Asset List (creating works fine)
3. Select another node
4. Select the Asset List again

#### Expected behavior

In the Inspector I should see the list of assets and be able to add, remove or rearrange them.

#### Actual behavior

The server returns with HTTP 500 and the following exception is show: 
```
Exception while property mapping for target type "array", at property path "0": It is not allowed to map property "__initializer__".It is not allowed to map property "__initializer__".

You need to use $propertyMappingConfiguration->allowProperties('__initializer__') to enable mapping of this property.Exception Code1297759968Exception TypeNeos\Flow\Property\ExceptionLog Reference20170512171922c79014Thrown in FileData/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Property_PropertyMapper.phpLine129Original FilePackages/Framework/Neos.Flow/Classes/Property/PropertyMapper.php

Nested ExceptionYou need to use $propertyMappingConfiguration->allowProperties('__initializer__') to enable mapping of this property.Exception Code1335969887Exception TypeNeos\Flow\Property\Exception\InvalidPropertyMappingConfigurationExceptionLog Reference20170512171922856720Thrown in FileData/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Property_PropertyMapper.phpLine186Original FilePackages/Framework/Neos.Flow/Classes/Property/PropertyMapper.php
```

### Affected Versions

Neos: 3.1.0

Flow: 4.1.0

Not affected: Neos 3.0.3 with Flow 4.0.6

**Comment by PalatinCoder** [comment]
I could already track it down to the asset editor's `this.value` being initialized with some weird values, however I don't have a clue where they come from

**Comment by PalatinCoder** [comment]
Update: Investigating the changelog from 3.0 to 3.1 I suspected #1472 broke this functionality. And indeed, with the merge of #1472 reverted the bug is gone. 
Looking at the changes and inserting some logging I found out that with #1472 applied, when mapping the asset array the `$conversionTargetType`  ist set to `array<Neos\Media\Domain\Model\Image>`. Before this change, it was just `array<string>`. However, both Neos 3.1 and 3.0 use the `TypedArrayConverter` to perform the conversion. So from here I don't really know where to go, I'm not even sure if it is a problem of Neos or Flow, so maybe someone with a little more insight could have a look at this? :)

**Comment by kitsunet** [comment]
Will have a look

**Comment by kitsunet** [comment]
Yep, pretty complicated stuff, I think I have an idea, testing...

**Comment by DrillSergeant** [comment]
@kitsunet thank you for fixing this. I spent around 5 hours finding out about this bug.
