### ISSUE TITLE
Module workspace failed to show when define properties type as asset

### ISSUE THREAD

**Issue by Chhunlong** [neos/neos-development-collection#1577]
### Description

[BUG] Module workspace failed to show when define properties nodetype as `Neos\Media\Domain\Model\Asset`

### Steps to Reproduce

1. Define content nodeType with properties
` properties:
    pdfFile:
      type: Neos\Media\Domain\Model\Asset`
2. Add a document type.
ex: PDF file
3. Publish to demo workspace -> Go to workspace module -> Preview what has changed

#### Expected behavior

It should display as a simple text display which file changed. When I tried with properties asset as array
`type: array<Neos\Media\Domain\Model\Asset>`

#### Actual behavior
Display an error because try to display image changes it 

Application/Neos.Neos/Resources/Private/Partials/Module/Management/Workspaces/ContentChangeDiff.html

### Affected Versions

I think the version might all those version that support demo workspace.

Neos: 3.0.2

**Comment by kdambekalns** [comment]
Should be fixed by #1605
