### ISSUE TITLE
DateTime not saved in inspector in Safari

### ISSUE THREAD

**Issue by hphoeksma** [neos/neos-development-collection#1586]
### Description

After selecting a date in the inspector, the inspector does not save the value.

### Steps to Reproduce

1. open the inspector
2. select a datetime element
3. select a date / time
4. try to publish

#### Expected behavior

The selected date to be saved.

#### Actual behavior

Error: The given value was not a valid date.

### Affected Versions

Neos: 2.3.12 

Flow: 3.3.13

**Comment by KPeschke** [comment]
Same issue on Neos v3.1.5

**Comment by MCStreetguy** [comment]
Got the same issue, the editor keeps displaying "no date set" whenever I try to set one.

**Comment by elkamyko** [comment]
I tracked down a commit that introduces this error: https://github.com/neos/neos/commit/0c8d7d9381e9fb67e71c1e145eacfd67224f9756
New way of timezone offset generation fails due to unsupported date format in Safari and Explorer: m d, Y H:i:s

**Comment by mhsdesign** [comment]
This can be closed as it refers to the old React Ui only
