### ISSUE TITLE
As content editor I would like to select multiple assets and assign them to a tag / collection

### ISSUE THREAD

**Issue by hphoeksma** [neos/neos-development-collection#1587]
### Description

Currently you can create a tag, upload files and then those uploaded files are added to the tag. It is however not possible to select multiple assets and drag them to a tag - which would be nice if your assets are already uploaded.

### Steps to Reproduce

n/a

#### Expected behavior

Select assets (i.e. by ctrl + click) and drag them over to a tag or collection to add the selected files.

#### Actual behavior

n/a

### Affected Versions

Neos: 2.3.12

Flow: 3.3.14

**Comment by rzierhofer** [comment]
In general multi select in the media section would be great!

**Comment by klfman** [comment]
We also have this request in multiple projects.

Would be good to also have a function "select by tag" which selects all assets tagged by a tag. This would make tags very useful for buld editing assets with a similar purpose

**Comment by Sebobo** [comment]
This will be resolved in the new media ui and not be implemented anymore for the old module. See https://github.com/Flowpack/media-ui/issues/8
