### ISSUE TITLE
Workspace overview doesn't work if an asset of non-image type was changed

### ISSUE THREAD

**Issue by dimaip** [neos/neos-development-collection#1592]
### Description
This code tries to render an asset even if it's not in workspace overview here: https://github.com/neos/neos-development-collection/blob/2.3/TYPO3.Neos/Resources/Private/Partials/Module/Management/Workspaces/ContentChangeDiff.html#L52

### Steps to Reproduce

1. Change some asset property of type other than Image (e.g. AssetList)
2. Go to workspace overview
3. Contemplate the following error `The argument "image" was registered with type "Neos\Media\Domain\Model\ImageInterface", but is of type "Neos\Flow\Persistence\Doctrine\Proxies\__CG__\Neos\Media\Domain\Model\Document" in view helper "Neos\Media\ViewHelpers\ImageViewHelper".`

### Affected Versions
Neos 2.3 - 3.1

**Comment by kdambekalns** [comment]
@dimaip I like your style, "contemplate" is a very nice way to put it. :)

**Comment by kdambekalns** [comment]
@dimaip so, is this fixed with https://github.com/neos/neos-development-collection/commit/eb4676920a25fd30080b1ba747a1ec70d82a406f? Anything blocking you from making that a PR?

**Comment by dimaip** [comment]
@kdambekalns yes, sorry, I got distracted. I had to hotfix and beard it for production yesterday, but that's for 3.0. I'll backport it to 2.3 now and create a PR.
