### ISSUE TITLE
Multiple nodes with the same uri path segment in the document tree

### ISSUE THREAD

**Issue by robertlemke** [neos/neos-development-collection#1604]
It is possible to bring the content repository into a state which results in multiple document nodes at the same level appearing in the content module's node tree which have *the same uri path segment*. Since we use the URI path segments for routing in the backend, it is not possible, as an editor, to distinguish between the nodes - no matter which link in the node tree you click, you will always end up at the same node.

Steps to reproduce:

- create one workspace ("staging") which is based on "live"
- create a document node with uri path segment "foo" and publish it to live
- switch to workspace "staging"
- change the title of the page to "Staging", publish it to workspace "staging"
- switch to workspace "live"
- delete the document node "foo", publish it to workspace "live"
- create a new document node with the same name "foo", publish it to workspace "A"
- switch to workspace "B"

You will now see *two* nodes in the document tree which have the uri path segment "foo". No matter which one you click, you will always see the page with the changed title "Staging".

**Comment by robertlemke** [comment]
I'm wondering what the correct behaviour should be.

It's perfectly possible that one editor deletes a document and ultimately publishes it to "live" while other editors still have a modified version in their workspace. This may or may not be a problem, but at the very least can be confusing in a scenario like described above.

Since this is happening in the live workspace, there are no shadow nodes and no other traces of the deletion which could be used for resolving or warning about such conflicts. If we want to guard editors agains such problems, we should disallow publishing of node deletions to live which still have a corresponding version in any of the workspaces. *Or* we even introduce a dialog which allows (administrator) editors to actually delete all nodes in all other workspaces, too.

**Comment by bwaidelich** [comment]
I like your suggestion with the dialog

**Comment by bwaidelich** [comment]
Maybe not 100% related, but I think it would be a good idea to use proper query parameters while we’re at it: `http://yoursite.tld/neos?node=<uuid>&workspace=<workspace-name>&dimension[language]=de`. That would also solve routing cache issues because the cache entry is only generated for the path (`/neos` in this case)

**Comment by aertmann** [comment]
Re proper query parameters. Remember suggesting to do that for the new UI as well to allow for accessing nodes outside the site's node tree as well as allowing for multiple node identifiers for stuff like translation split view. A custom "location bar" in the UI could still show the pretty URL to the user.

**Comment by Rasmizzle** [comment]
I would argue this is not yet completely resolved. Neos Backend successfully distinguishes between the nodes but I can still create an environment in which two document nodes with the exact same path segment exist, in Neos 8.3.16. 

Let's assume there is a "pre-live" workspace based on "live"

1. create document "foo" in workspace live
2. switch to workspace "pre-live" and create a document "foo"
3. publish workspace "pre-live"
4. publish the node created in step 1 to workspace "live"
5. transfer changes from workspace "pre-live" to "live"

There are now two documents with the exact same uri path segment.

One could argue that this is fixable by the editor but it would be nice to get a warning in the UI.
