### ISSUE TITLE
Better Link Handling

### ISSUE THREAD

**Issue by iseries** [neos/neos-development-collection#1606]
This is just a "nice to have" ticket.
It would be cool when we improving the link handling in the editor. 

**The Problem:**
I can't edit the first and last letter from an existing link in neos -> I HAVE TO click in the middle (or delete the whole link and set it again).
![linkhandling](https://user-images.githubusercontent.com/6272363/26967297-fb8fa488-4cfd-11e7-85e8-7a220c88617e.gif)

I saw that wordpress released a nice link handling in their new version (http://t3n.de/news/wordpress-4-8-829343/) which is a nice solution for this problem. Maybe something similar is possible for the new UI (CKEditor)?

**Comment by beheist** [comment]
CKEditor seems to behave very much the same, however you get a context menu if you double-click a link where you can change the text. Should be sufficient, wdyt?

**Comment by iseries** [comment]
Oh thats great! I didn't know that this is possible. That context menu is great. I think we can close this then :) thanks for answer.
