### ISSUE TITLE
SQL duplicate entry error on publishing moved nodes in nested workspaces

### ISSUE THREAD

**Issue by robertlemke** [neos/neos-development-collection#1608]
### Description

When a node is being published which has been moved and otherwise changed, the content repository may fail with an error similar to the following:

> An exception occurred while executing 'UPDATE typo3_typo3cr_domain_model_nodedata SET workspace = ?, movedto = ?, lastmodificationdatetime = ?, version = version + 1 WHERE persistence_object_identifier = ? AND version = ?' with params ["campaign-a-ji4m8", "e8b06533-98c2-4426-bcda-7f772584f976", "2017-06-12 17:44:30", "619610d6-da0e-4539-b10b-3aae54b6fad7", 2]:
>
> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '09ba9aa6947480ff45b7e50dc00c370e-campaign-a-ji4m8-4f534b1eb0c1a7' for key 'UNIQ_60A956B92DBEC7578D94001992F8FB01'

### Steps to Reproduce

Steps are based on the Neos Demo website (2.3.x)

1. create a workspace "staging" based on workspace "live"
2. create a workspace "campaign" based on workspace "staging"
3. change the title of an existing page and publish it to "campaign"
4. move that page to some other place and publish it to "campaign"

#### Expected behavior

The node should be moved.

#### Actual behavior

An integrity constraint violation is logged.

### Affected Versions

At least Neos 2.3.x and 3.1.x - and probably everything in between

**Comment by robertlemke** [comment]
This bug maybe related to #1439

**Comment by robertlemke** [comment]
Here is another approach to trigger the bug, resulting in a different error message:

1. create a workspace "staging" based on workspace "live"
2. create a workspace "campaign" based on workspace "staging"
3. change the title of an existing page and publish it to "campaign" *by pressing the orange publish button in the Content module*
4. move that page to some other place and then: go to the workspace module, review changes of your user workspace, press "Publish all changes to campaign"

The result is "#1416484223: Cannot publish a list of nodes because of cycles"

![image](https://user-images.githubusercontent.com/95582/27490063-3473e2f6-583d-11e7-8073-52b5aef82b46.png)

**Comment by robertlemke** [comment]
Now, here's the crazy thing: it *does work* if you publish the workspace via the command line:

![image](https://user-images.githubusercontent.com/95582/27490498-c0e26b08-583e-11e7-8f47-7717ad2aa1b5.png)

**Comment by kdambekalns** [comment]
Solved with #1609.
