### ISSUE TITLE
Content Repository Behat tests fail with fresh checkout of 2.3-dev

### ISSUE THREAD

**Issue by robertlemke** [neos/neos-development-collection#1613]
### Description

Even though Travis doesn't complain about it at the moment, a couple of Behat tests currently fail on a completely fresh checkout of Neos 2.3 (and probably later versions as well).

The test will fail with a "Access denied for method" error, usually referring to `Workspace::publish()`. The reason seams to be that in some cases (as it seems, for Travis for example) other tests which authenticate a role are ran before tests doing `publish()` and in this concrete case the publish-tests are ran first. In general I figured out that statements like `Given I am authenticated with role "TYPO3.Neos:Administrator"` are leaking to all following tests.

### Steps to Reproduce

As it seems, it is important to start with a completely fresh checkout. @kdambekalns and @kitsunet were not able to reproduce the error on their existing branches, but could reproduce the error with a fresh checkout:

```
git clone git@github.com:neos/neos-development-distribution.git neos-2.3
cd neos-2.3
git checkout 2.3
composer install
composer install -d Build/Behat

# create database "neos-23-testing"

cat > Configuration/Testing/Settings.yaml <<- EOM
TYPO3:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        user: 'root'
        password: 'password'
        dbname: 'neos-23-testing'
EOM

# did you adjust the credentials above as needed?

bin/behat --ansi --stop-on-failure -f progress -c Packages/Neos/TYPO3.TYPO3CR/Tests/Behavior/behat.yml.dist
```

#### Expected behavior

Tests should succeed.

#### Actual behavior

```
..........F--

(::) failed steps (::)

01. Access denied for method
    Method: TYPO3\TYPO3CR\Domain\Model\Workspace::publish()

    Evaluated following 1 privilege target(s):
    "TYPO3.Neos:Backend.PublishToLiveWorkspace": ABSTAIN
    (0 granted, 0 denied, 1 abstained)

    Authenticated roles: TYPO3.Flow:Everybody, TYPO3.Flow:Anonymous
    In step `And I publish the workspace "user-demo"'.            # FeatureContext::iPublishTheWorkspace()
    From scenario `Publish a new ContentCollection with Content'. # Features/Basic/PublishUserWorkspace.feature:13
    Of feature `Publish user workspace'.                          # Features/Basic/PublishUserWorkspace.feature

3 scenarios (2 passed, 1 failed)
13 steps (10 passed, 2 skipped, 1 failed)
```

### Affected Versions

At least Neos 2.3-dev

**Comment by robertlemke** [comment]
Another observation: When I add `And I am authenticated with role "TYPO3.Neos:Administrator"` to the `Basic/PublishUserWorkspace.feature` test, the Content Repository tests succeed:

```
bin/behat --ansi --stop-on-failure -f progress -c Packages/Neos/TYPO3.TYPO3CR/Tests/Behavior/behat.yml.dist
```

![image](https://user-images.githubusercontent.com/95582/27172041-13b2fa8c-51b4-11e7-9905-e844d7d86871.png)

Then, when I remove the line and run the tests again, *the tests still succeed*. However, when I flush all caches, the tests will fail again.

**Comment by kdambekalns** [comment]
Some tests backing the "order of test runs" theory:

- https://travis-ci.org/kdambekalns/neos-development-collection/builds/243210583
- https://travis-ci.org/kdambekalns/neos-development-collection/builds/243210896

The first is the latest state of 2.3, the second has a changed order of Behat runs (https://github.com/kdambekalns/neos-development-collection/commit/f1f23ecc2513fb6b4822bfe58677d55ab7fa41e3). 🎉

**Comment by gerhard-boden** [comment]
Very interesting that this only happens on a fresh checkout... Couldn't reproduce it on my preexisting instance either. Maybe @hlubek has an idea what is going on

I only remember that I had this authentication issues some time ago when running a lot of behat tests, but could never fully figure out what was causing them :(

**Comment by kdambekalns** [comment]
We have seen it fail on a fresh checkout, if the Neos tests are not run first. So, existing setups may have the `$whatever` cached, that seems to be created when `And I am authenticated with role "TYPO3.Neos:Administrator"` has been "used" once. What would be interesting: what if on an existing setup all caches are pruned and then the CR tests are run first?

**Comment by gerhard-boden** [comment]
When running the tests with pruned caches the problem is the same:
![image](https://user-images.githubusercontent.com/10533739/27221692-c52d7398-5289-11e7-8be7-e39dbbcea652.png)
