### ISSUE TITLE
package was found more than once (neos/demo) when composer update

### ISSUE THREAD

**Issue by iseries** [neos/neos-development-collection#1615]
Hi,
i haven that much experience with composer but i think i found a problem which is related to this projekt.

### Description

> neos/demo was found more than once

exception when deactivate neos/demo and run composer update

### Steps to Reproduce

```
user@debi:/usr/www/users/c01$ php70 -d allow_url_fopen=1 composer.phar create-project neos/neos-base-distribution Neos
user@debi:/usr/www/users/c01$ cd Neos
user@debi:/usr/www/users/c01/Neos$ php70 flow package:deactivate --package-key Neos.Demo
-> Deactivated package "Neos.Demo".
user@debi:/usr/www/users/c01/Neos$ php70 -d allow_url_fopen=1 ../composer.phar update --no-dev
-> - Installing neos/demo (3.1.2): Loading from cache
->  [Neos\Flow\Package\Exception] The package with the name "neos/demo" was found more than once, please make sure it exists only once. Paths "Sites/Neos.Demo/" and "Inactive/Sites/Neos.Demo/".
```

#### Expected behavior

composer update sould be run without exception

#### Actual behavior

exception appers + the demo package is existing in /Packages/Sites AND  /Packages/Inactive/Sites/ after composer update

### Affected Versions

Neos:  3.1.2
Flow: 4.1.2

**Comment by kdambekalns** [comment]
Well, we should really get rid of `flow package:deactivate` – it does not play well with a composer-based project at all…

@iseries the package being in `/Packages/Inactive/Sites/ ` is actually the result of deactivating the package like that. One should rather `composer remove neos/demo`…

**Comment by kitsunet** [comment]
Agreed :/ I guess for now we need to fix the exception with a special check for disabled.

**Comment by iseries** [comment]
thanks for the quick answer. I removed the package as recommended.

**Comment by kdambekalns** [comment]
That concept (inactrive packages) no longer exists in Flow…
