### ISSUE TITLE
Resource replacing: redirect to new resource leads to 404

### ISSUE THREAD

**Issue by coders-market** [neos/neos-development-collection#1623]
### Description

Replacing a resource like a PDF with a new pdf with new name and active "Generate redirects from original file url to the new url" lead to 404 on old resource link.

### Steps to Reproduce

1. Upload a PDF
2. Link resource e.g. via aloha 
3. Copy resource link
4. Replace pdf with a new pdf version and new name
5. Try to open link from old resource

#### Expected behavior

New resource is shown with old resource link

#### Actual behavior

404 Not found is shown for old resource link (symlink is missing for old resource to new resource)

### Affected Versions

Tested with
Neos: 2.3.13, 3.1.2

**Comment by akappler** [comment]
Any update here?

**Comment by akappler** [comment]
This issue can be closed.
See: https://github.com/neos/redirecthandler-neosadapter#configuration
