### ISSUE TITLE
Setting up a vanilla 3.1 empty page, creates a site with inconsitant data 

### ISSUE THREAD

**Issue by jobe451** [neos/neos-development-collection#1651]
This is a follow-up to #1564.

The described remedy in #1564 is not working. A vanilla 3.1 installation seems to create an invalid site. 
After a fresh vanilla site is set-up, ./flow node:repair complains about "Nodes with invalid dimension values found"

### Steps to Reproduce

1. Reinitiate mysql data directory (fresh vanilla database, with neos data in)
2. Get fresh neos-instance: php /usr/local/bin/composer create-project --no-dev neos/neos-base-distribution eventtest
3. ./flow server:run
4. Go through setup wizard
5. Stop server
6. ./flow node:repair
Result, errors about invalid dimensions:
![image](https://user-images.githubusercontent.com/910027/28597119-8270f110-719c-11e7-8cd9-e9b4f70cfa3a.png)

#1564 describes that having neos-demo installed to be a problem. The demo application is mentioned as "inactive". I do not see how to avoid adding as "inactive". This is the default installation. Removing the directory makes the application fail.
![image](https://user-images.githubusercontent.com/910027/28597176-c2e114b4-719c-11e7-9f8a-bc1ddf57bec7.png)

**Comment by jobe451** [comment]
When I actively run
php /usr/local/bin/composer remove neos/demo
After step 2, then I can avoid the problem described above.

Also the configuration described in #1564 does not provoke the described errors anymore.

That is very frustrating. I spent about 8 hours with trial and error to arrive here....

I am very much convinced that a clean fresh install following the setup instructions ends in a not properly functioning state.

**Comment by kdambekalns** [comment]
First of all, sorry for causing frustration! Then, thanks for the issue.

Yes, removing the demo site package using composer is the only way to remove it's settings properly, so that is correct.
