### ISSUE TITLE
Image upload within media module is broken

### ISSUE THREAD

**Issue by gerhard-boden** [neos/neos-development-collection#1666]
### Description

Image upload within media module is broken

### Steps to Reproduce

1. Open media module
2. Try to upload an image
3. Upload fails with exception

#### Expected behavior

Upload should not fail

#### Actual behavior

Upload fails

### Affected Versions

Neos: master

Flow: master

### Exception
```
Argument 4 passed to Neos\Error\Messages\Message::__construct() must be of the type string, null given, called in /var/www/neos-master/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Controller_AbstractController.php on line 174
```

**Comment by kdambekalns** [comment]
Are you sure this is caused by Flow? That method never existed, AFAICT. We have a method to untangle file uploads, yes. But not that one.

**Comment by kitsunet** [comment]
@gerhard-boden this might be caused from the PSR-7 change? Probably some merge error then though. I can take a look tomorrow (hopefully). But this might give you a hint. Or maybe you have some broken caches after switching branches to review?

**Comment by gerhard-boden** [comment]
updated the exception, sorry for the confusion

**Comment by albe** [comment]
The null is coming from the translator inside `AssetController::addFlashMessage()`. Since that is probably a wide use-case, we need to accept nulls, at least for now.
