### ISSUE TITLE
Backend content dimensions search/filter functionality returns no results

### ISSUE THREAD

**Issue by DrNik** [neos/neos-development-collection#1667]
Hi guys,
as discussed on [this thread](https://discuss.neos.io/t/backend-content-dimensions-search-filter-functionality-seems-not-to-work/2507) I report here that the search/filter content dimensions box in Neos backend is not working; it simply returns no results whatever search string someone inputs.

I could reproduce the issue on version 3.x and 2.x and either with one or two content dimensions.

Thanks,
Nicola

**Comment by aertmann** [comment]
Styling looks weird too
![image](https://user-images.githubusercontent.com/903567/29226911-d8af5546-7ea1-11e7-9719-a6b610151ee6.png)

**Comment by aertmann** [comment]
Probably related to #1662

**Comment by DrNik** [comment]
Is there any update on this? I believe is some how obsolete with the new UI even if on that there is still and ordering issue (but that's a different story).
