### ISSUE TITLE
Asset Usage shows broken link for assets linked to disabled nodes

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#1672]
### Description

Having an asset referenced by a disabled node creates broken urls in the asset usage interface.
This makes it especially hard to find the reference with multiple sites.

### Steps to Reproduce

1. Reference image from a document node
2. Disable document node
3. Check the asset usage interface of the image

#### Expected behavior

The url should still be generated but with the users workspace so the link actually works.

#### Actual behavior

Just ".html" is rendered as url.

### Affected Versions

Neos: 

2.3 + 3.1

**Comment by Sebobo** [comment]
@kitsunet this issue is related to your rewrite of the asset usage view and strategy.

**Comment by Sebobo** [comment]
This seems to be fixed when #1762 is merged.

**Comment by rolandschuetz** [comment]
@Sebobo This got merged, can we close the task?
