### ISSUE TITLE
Unable to create links ending with ".pdf" using Aloha or inspector

### ISSUE THREAD

**Issue by dennisirmscher** [neos/neos-development-collection#1673]
### Description

Whenever you type in a link - no matter if within Aloha or the link editor in the inspector - that ends with ".pdf" you will get kicked out of Neos und have to relogin.

### Steps to Reproduce

1. Mark some text within a inline editable element
2. Add a link via the Aloha controls
3. Type in anything ending with ".pdf"

Alternatitive way:

1. Select an element having a property using the link editor in the inspector (e.g. Neos.Neos.Nodetypes:Image)
2. Type in anything ending with ".pdf" within the link editor

#### Expected behavior

Get it linked to the PDF-file.

#### Actual behavior

You get logged out of Neos CMS. If you were lucky your link is in place anyway. `/neos/service/assets?searchTerm=***.pdf` is returning `303 See Other` redirecting to `/neos/login` which is responding with `401 Unauthorized`.

### Affected Versions

Neos: 2.1, 2.2, 2.3, 3.0, 3.1

**Comment by aertmann** [comment]
Hey there. Thanks for the fix. However be careful with symptom fixes where you don't know the cause, would actually suggest to block this until it's understood why it happens.

**Comment by dennisirmscher** [comment]
Hi @aertmann I'm sorry, but what fix did you mean?

**Comment by dennisirmscher** [comment]
PS: If you call /neos/service/assets?searchTerm=***.pdf directly, it correctly returns a list of PDF-files in the system without logging you out.

**Comment by aertmann** [comment]
Sorry had some issues commenting and got two issues mixed up.. meant to say:

Hey thanks for reporting, however I'm not able to reproduce this issue. It also sounds very odd to me that a specific file ending would cause anything like this.

Can you reproduce this behavior on a fresh install with the demo site? It's more likely to be related to your specific site/installation or setup than a core issue.

You mentioned a lot of affected versions, did you confirm the issue exists in all of those versions?

**Comment by dennisirmscher** [comment]
> Can you reproduce this behavior on a fresh install with the demo site? It's more likely to be related to your specific site/installation or setup than a core issue.

Actually not, you are right. Which is weird, because I testet it in a bunch of Neos installations to check all the different versions I've listed and it occurred everywhere. I will dig into it a little bit deeper, to find out what is causing the issue.

**Comment by dennisirmscher** [comment]
Ok. Meanwhile I figured out the issue is only present on one specific machine we are hosting all the Neos-sites on. I've tested it in some other environments and it is working fine there.

So far I have no idea what could cause the issue and would appreciate if you would have any clue for me.

**Comment by rolandschuetz** [comment]
@dennisirmscher We would like to close open tasks. Any further information?

**Comment by dennisirmscher** [comment]
No, couldn't figured out what was causing the issue and have to admin I finally just forgot about it. As it seem's no one else is complaining about it, I think we can just ignore it for once.
