### ISSUE TITLE
Disable a NodeType via ~leads to an error in configuration module

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-development-collection#1674]
### Description

```
# works without error
'Neos.NodeTypes:Html': []
# error shown in configuration module
'Neos.NodeTypes:Html': ~
```

### Steps to Reproduce

1. Disable a nodetype in your nodetypes.yaml via assigning ~
2. Visit the nodetypes-tab in the configuration module 

#### Expected behavior

NodeType is removed (or shown with value NULL)
No errors are shown

#### Actual behavior

An error is shown:
NodeTypes.Neos.NodeTypes:Html -> expected: type=dictionary found: type=NULL

### Affected Versions

Happend in all Neos-Version I touched so far (2.1 untill 3.1)

**Comment by iseries** [comment]
I still fail to understand this. It seems that there are many ways to do this.

I know that this works if I want to disable:
`'Vendor.Site:YourNodeType':
  abstract: TRUE`

Heard from Florian Weiss in Slack that the following works too - but not for me:
`'Vendor.Site:YourNodeType':
  ui: ~`

I think the right way should be noticed in the docs. There is no hint or something else right now (to my knowledge).

**Comment by DrillSergeant** [comment]
Same here, would be nice to know what is the best way to do this. I assume that disable just the ui-part will i.e. not result in an action when running node:repair.
I expect that "disabled" NodeTypes are not allowed at all (and not only hidden in the ui) and that's why they should be removed when running a node:repair.

**Comment by bwaidelich** [comment]
Disabling a NodeType by just overriding it with an empty configuration is probably not a good idea because it might break sub types.
I think
```yaml
Neos.NodeTypes:Html:
  ui: ~
```
is a safe solution for this (or marking it abstract ofc).

**Comment by bwaidelich** [comment]
as a follow-up after collecting more input from slack:
When you only want to hide all nodes implementing a specific type from the creation wizards, using the `ui: ~` approach is the best IMO as marking them `abstract` would permanently delete the affected nodes on `./flow node:repair` (after a confirmation dialog). If _that's_ what you want, than of course that's a viable solution as well.

Anyone up for adding a short section to the documentation?

**Comment by iseries** [comment]
Would do it but I think my english is to bad to write good text for documentation. maybe @DrillSergeant ?

**Comment by DrillSergeant** [comment]
I am slacking with @bwaidelich right now to make I sure I got everything right. Will contribute someting for the docs afterwards.

**Comment by DrillSergeant** [comment]
Documentation pull request: https://github.com/neos/neos-development-collection/pull/1680
