### ISSUE TITLE
Using context variables in a condition of another context variable doesn't work in current master

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#1677]
### Description
AFAIK using context variables in an other context variable is not possible.
But untill Version 3.1, it was possible to use a context variable in a condition for another variable. 
Should that never have been possible?

Given the following example code:

```
prototype(Neos.Neos:Page) {
    @context.condition = ${true}
    testValue1 = ${'ContextInTernary: ' + (condition == true ? 'TRUE' : 'FALSE')}

    testValue2 = '<br/>VariableAndIf: Works'
    testValue2.@if.conditionIsTrue = ${condition}

    @context.testValue3 = '<br/>ContextAndIf: Works'
    @context.testValue3.@if.conditionIsTrue = ${condition}
    testValue3 = ${testValue3}
}
```

Output Neos <= 3.1:
```
ContextInTernary: TRUE
VariableAndIf: Works
ContextAndIf: Works
```

Output Neos master / 3.2
```
ContextInTernary: TRUE
VariableAndIf: Works
```

**Comment by kitsunet** [comment]
Ye, the case number 3 should've never worked.

**Comment by gerhard-boden** [comment]
Should we mention this in the release notes for 3.2?

**Comment by gerhard-boden** [comment]
I mean it's fixed now as it is, but might Break something

**Comment by daniellienert** [comment]
It is fixed, but also braking and took me some time to figure out what it actually was as there is no error message that points you in the right direction.

I guess we should mention it. Better would be to throw an exception if someone tries to use a context variable in an other context variable or condition. But I am not so into that part of the code and node sure if that is possible at all or if so - if there are good reasons not to do that.

**Comment by kitsunet** [comment]
I doubt we can do that. Technically any context variable could come from the context above and currently it's not forbidden to call an undefined context variable.
