### ISSUE TITLE
Cut & paste across pages with dimensions loses ContentCollection child nodes

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#1696]
### Description

When cutting and pasting nodes with content collection children in a site with dimensions, content collections get lost during publishing.

### Steps to Reproduce

1. Set up the demo site (`composer create-project neos/neos-base-distribution=2.3.16 testsetup`, migrate DB, import site, create user)
2. Create two pages in _en_US_, named _Test 1_ and _Test 2_
3. On _Test 1_ create a two-column element
4. In the first column of that element, create another two-column-element
5. Switch language to _de_, choose "Create & Copy" when asked
6. Publish all changes
7. Switch back to _en_US_
8. Cut the nested two-column element
9. Paste it into the _Test 2_ page
10. Publish all changes

#### Expected behavior

One of:

- the children of the moved two-column element move along (only!) in _en_US_
- the paste is not allowed

since the target does not exist in _de_.

#### Actual behavior

The ContentCollection children of the moved element are left at their original location. This leads to missing children in the new location and orphaned (old) nodes.

This can be seen (partly) by looking at the _Test 1_ page in _de_ using the structure tree - the nested two-column element lost it's children (_column0_ and _column1_), even though the _de_ variant of the content wasn't touched at all.

<img width="296" alt="test_1_-_neos_demo_site" src="https://user-images.githubusercontent.com/95873/30316185-b377826c-97a6-11e7-81a5-5d37ae201f91.png">

The multi-column rendering of TYPO3.Neos.NodeTypes does not produce any immediate errors now, since the children to be rendered are collected using

	columns = TYPO3.TypoScript:Collection {
		collection = ${q(node).children('[instanceof TYPO3.Neos:ContentCollection]')}
		itemRenderer = TYPO3.Neos.NodeTypes:MultiColumnItem
	}

so that simply nothing is rendered.

If one uses Fusion code like this, rendering breaks with an exception:

 	column0 = TYPO3.Neos:ContentCollection {
		nodePath = 'column0'
	}

This is because the explicitly requested node is not found.

### Affected Versions

Neos: seen in 2.3.13, 2.3.14 and 2.3.16

**Comment by DrillSergeant** [comment]
Could we flag this issue as "bug". I would even vote to handle this as a critical issue.
