### ISSUE TITLE
SQLSTATE[HY000] [1698] Access denied for user ''@'localhost'

### ISSUE THREAD

**Issue by igodorogea** [neos/neos-development-collection#1714]
I tried to install neos with composer as described [here](https://www.neos.io/download-and-extend.html)
but when I run `./flow server:run` I get this:
```
An exception occured in driver: SQLSTATE[HY000] [1698] Access denied for user ''@'localhost'

Type: Doctrine\DBAL\Exception\DriverException
File: Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriv
er.php
Line: 115

Nested exception:
SQLSTATE[HY000] [1698] Access denied for user ''@'localhost'

Type: Doctrine\DBAL\Driver\PDOException
Code: 1698
File: Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php
Line: 47

Nested exception:
SQLSTATE[HY000] [1698] Access denied for user ''@'localhost'

Type: PDOException
Code: 1698
File: Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php
Line: 43

Exception Code	1355480641
Exception Type	Neos\Flow\Core\Booting\Exception\SubProcessException
Log Reference	20170930133648098329
Thrown in File	Packages/Framework/Neos.Flow/Classes/Core/Booting/Scripts.php
Line	612
```
Does that means that it requires a present mysql anonymous user? I don't have it.

## System config
1. __OS__ - Windows 10 (WSL Ubuntu 16.04)
2. PHP 7.1
3. MariaDB
4. Neos v3.2

P.S.: It may be because of WSL and it's faulty sockets, but idk... I successfully installed TYPO3 CMS 8.7 :|

**Comment by grebaldi** [comment]
Hi,

it might be, that during `server:run`, some part of the framework is trying to access the database without having credentials configured yet.

Have a look at the following file: `Configuration/Development/Settings.yaml.example`
and add your database credentials there. Then rename the file to `Configuration/Development/Settings.yaml` and try `./flow server:run`.

Best regards,
Wilhelm

**Comment by igodorogea** [comment]
The problem was the missing mysql anonymous user. I've recreated it and the Neos installation went ok.
