### ISSUE TITLE
exceptions occurred during export

### ISSUE THREAD

**Issue by MCStreetguy** [neos/neos-development-collection#1732]
### Description

Whenever I try to export my current Site package I get the following error message:
```
2 exceptions occurred during export.
Please see the log for the full exceptions (including stack traces). The
exception messages follow below: 
0: Neos\Flow\Property\Exception
Exception while property mapping for target type "string", at property
path "": No converter found which can be used to convert from "boolean"
to "string".

1: Neos\Flow\Property\Exception
Exception while property mapping for target type "string", at property
path "": No converter found which can be used to convert from "boolean"
to "string".

  Type: Neos\ContentRepository\Exception\ExportException
  Code: 1409057360
  File: Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_ContentRepos
        itory_Domain_Service_ImportExport_NodeExportService.php
  Line: 422

Open Data/Logs/Exceptions/2017102608551049838d.txt for a full stack trace.
Segmentation fault
```
The Exception log tells me that this is thrown while exporting the path `/sites/mainwebsite` which is my Homepage NodeType. I don't got any boolean properties on this NodeType, therefore I'm quite a bit confused about that error.
(*I can add the Configuration and other files if needed.*)

### Steps to Reproduce

1. Fill your page with some content
2. Export it to your Site package

#### Expected behavior

All sites should have been exported to the named package.

#### Actual behavior

The mentioned error message shows up.

### Affected Versions

Neos: 3.2.0

Flow: 4.2.4

**Comment by MCStreetguy** [comment]
I was able to track the issue down to the problematic properties.

**Comment by MCStreetguy** [comment]
This can be closed, as the issue is already [reported correctly here](https://github.com/neos/flow-development-collection/issues/1103)

**Comment by bwaidelich** [comment]
Should be fixed with latest releases (https://discuss.neos.io/t/neos-bugfix-releases-3-2-1-3-1-6-3-0-8-2-3-17/2808)
