### ISSUE TITLE
Error 414 when selecting too many assets in inspector AssetEditor

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#1747]
### Description

When using too many assets in the inspector (AssetEditor), an error is shown.

### Steps to Reproduce

1. Define some node type with an assets array property
2. Add a lot of assets using the inspector
3. Try to edit the node making sure the inspector tries to refresh it's data

#### Expected behavior

The inspector shows the selected assets.

#### Actual behavior

An error message is shown, no assets show up in the inspector.

![request-uri-too-large](https://user-images.githubusercontent.com/95873/32539233-0e1a922e-c469-11e7-80ce-88fe7148153b.png)

### Affected Versions

Neos: 2.3 (and later, most probably)

**Comment by kdambekalns** [comment]
The reason is how the image data is fetched. In the background an XHR GET request is done, looking like the following. With a certain number of assets that URI will simply become too long.

`http://www.acme.com/neos/content/asset-with-metadata?assets%5B0%5D%5B__identity%5D=0a9df4da-65bb-49d6-8ddb-bdd0cc3a4c5e&assets%5B0%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B1%5D%5B__identity%5D=6d7025dd-e107-46b5-88c2-6ef6996df722&assets%5B1%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B2%5D%5B__identity%5D=55d9cdb7-cfdf-41e9-9023-d97ac6967549&assets%5B2%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B3%5D%5B__identity%5D=21acef50-bc81-4c42-a478-7104e99ab9f9&assets%5B3%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B4%5D%5B__identity%5D=aa164be3-e16a-4856-9138-88b6a2343538&assets%5B4%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B5%5D%5B__identity%5D=4495d9c1-a2e3-44e0-8679-77284e716df4&assets%5B5%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B6%5D%5B__identity%5D=27a32db6-295b-4021-b364-f74823476ccd&assets%5B6%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B7%5D%5B__identity%5D=3b16f194-bcf0-4a01-9c66-41e78a4e3b4e&assets%5B7%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B8%5D%5B__identity%5D=fae2c1f1-2849-468a-9638-6604faa70983&assets%5B8%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B9%5D%5B__identity%5D=df1758b2-9145-46dc-8bb8-ca0310669e53&assets%5B9%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B10%5D%5B__identity%5D=ad99427c-4f46-4cdb-9976-2fa4a28ea17d&assets%5B10%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B11%5D%5B__identity%5D=c525fe91-31de-461c-8600-d3d0a8eae173&assets%5B11%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B12%5D%5B__identity%5D=647e006c-d81d-4d3e-b7c1-0424b539fb0f&assets%5B12%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B13%5D%5B__identity%5D=269416db-6c67-4b93-a87b-48deb570c3d7&assets%5B13%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B14%5D%5B__identity%5D=546a26c5-9d72-4587-8ac9-45feb2250f65&assets%5B14%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B15%5D%5B__identity%5D=38637172-e7e0-4f4e-b8d7-0789c8b5079e&assets%5B15%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B16%5D%5B__identity%5D=f3693e70-a05f-4abb-9216-8b9382cca295&assets%5B16%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B17%5D%5B__identity%5D=d9b0729c-4c21-4811-b89c-6cc1de3fa2b5&assets%5B17%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B18%5D%5B__identity%5D=250e049e-b998-4e7e-ac7e-48a339cff794&assets%5B18%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B19%5D%5B__identity%5D=14e76a95-a7ad-49fb-aa23-d540dfcc538d&assets%5B19%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B20%5D%5B__identity%5D=8088728f-fe0d-4bcb-817f-c542d6af01f8&assets%5B20%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B21%5D%5B__identity%5D=241be7e2-2e75-4eb3-bcfc-5e735cc69b06&assets%5B21%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B22%5D%5B__identity%5D=ab90f439-07e3-4911-97a5-30d14e64cdf4&assets%5B22%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B23%5D%5B__identity%5D=5fc4f041-0a65-47fc-ab44-76e031e35338&assets%5B23%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B24%5D%5B__identity%5D=3529d161-485a-45e7-be43-61b13c394865&assets%5B24%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B25%5D%5B__identity%5D=7ec2a493-82a5-45e5-9df4-39694c982633&assets%5B25%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B26%5D%5B__identity%5D=3c28b0c3-50b4-4cb3-a733-45bffbe46b67&assets%5B26%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B27%5D%5B__identity%5D=fc3a8d0d-efac-4222-a217-b08cfecf402e&assets%5B27%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B28%5D%5B__identity%5D=41779e4a-21b3-47e2-a72b-e283d3674ec2&assets%5B28%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B29%5D%5B__identity%5D=84472693-fa6d-49d1-9fff-ecb74e09f232&assets%5B29%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B30%5D%5B__identity%5D=1b72f32f-1e33-4895-9e76-95dd817f04f6&assets%5B30%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage&assets%5B31%5D%5B__identity%5D=c07a44e4-0e67-4017-a2d8-35b5fab96fc8&assets%5B31%5D%5B__type%5D=TYPO3%5CMedia%5CDomain%5CModel%5CImage`

**Comment by bwaidelich** [comment]
> In the background an XHR GET request is done

woot?

**Comment by bwaidelich** [comment]
<d

**Comment by bwaidelich** [comment]
Not into this one, but the only quick fix I can think of is to turn that into a POST request even if it doesn't change the server state..
Or use a different approach for that large amount of assets ofc (i.e. asset collections)

**Comment by bwaidelich** [comment]
> I can think of is to turn that into a POST request [...]

I missed your PR where you do exactly that.
As written, a more "elaborate" fix could be to split up the request in multiple ones – but I'm not sure if it's worth the extra work if it works with POST requests
