### ISSUE TITLE
Match RouteParts with ObjectType

### ISSUE THREAD

**Issue by nixahnung** [neos/neos-development-collection#1750]
### Description

Match RouteParts with ObjectType

### Steps to Reproduce

1. Create a Route like shown in Manual

       -
         name: 'Single product route'
         uriPattern: 'products/{product}'
         defaults:
           '@package':     'My.Demo'
           '@controller':  'Product'
           '@action':      'show'
         routeParts:
           product:
             objectType: 'My\Demo\Domain\Model\Product'
       
2. Call an Uri
3. Watch 404 not Found

#### Expected behavior

Resolve an correct Uri

#### Actual behavior

Get 404, when URI wasn't created throw an Viewhelper or something else first.
(no entry on ObjectPathMappingRepository)
If no Entry is found on Mappingtable, an Mapping should be created!

### Affected Versions

Neos: current stable

Flow: 4.2.4

**Comment by kdambekalns** [comment]
Hi @nixahnung - the routing is part of Flow, so would you mind creating that issue in the neos/flow-development-collection issue tracker instead? Thanks!

**Comment by rolandschuetz** [comment]
Posted it at https://github.com/neos/flow-development-collection/issues/1274
