### ISSUE TITLE
Refactor the part how site node names are generated

### ISSUE THREAD

**Issue by 2case** [neos/neos-development-collection#1756]
### Description

Currently the `GeneratorService` from the `SiteKickstarter` package generate the site node name with the last part of the package key. That leads with an package name like `Vendor.Customer.Site` to a site node name of `site` which looks on the node path like `/sites/site/...`. It would be better if the full package name is used for that. Also the `Utility::renderValidNodeName($name)` should use for generating a valid node name. Maybe a fallback to `site-` instead of `node-` as prefix would also nice. 

### Steps to Reproduce

1.  Simple use the command line interface `./flow kickstart:site` and use any package name

### Affected Versions

Affects all Neos versions.

**Comment by jonnitto** [comment]
I close this, as there is already a commit for this. Thank you for your issue!
