### ISSUE TITLE
ReactUI: Image cropping allows custom ratio when disabled

### ISSUE THREAD

**Issue by p-weisk** [neos/neos-development-collection#1766]
### Description
The image cropping dialogue in the Inspector in the new UI still allows for a custom aspect ratio even though it has been disabled in the configuration file. Furthermore, it also ignores the "defaultOption".

### Steps to Reproduce

1. Create a NodeType with a property of type Neos\Media\Domain\Model\ImageInterface
2. set "allowCustom" to false in the configuration file
3. Create a node of that type, try and set the image
4. Select one of the aspect ratios and then manipulate the numbers manually

#### Expected behavior

Setting allowCustom to false would only allow the editor to pick one of the predefined aspect ratios by removing "custom" from the aspect ratio dropdown and it would also make the predefined aspect ratios uneditable

#### Actual behavior

Setting allowCustom to false removes the "custom" option from the aspect ratio dropdown, but the editor can still set a custom aspect ratio by choosing one of the predefined aspect ratios and changing the numbers of that aspect ratio:
![bildschirmfoto 2017-11-21 um 12 15 22](https://user-images.githubusercontent.com/28752561/33069871-3b041e5c-ceb6-11e7-8681-ed9e22572c05.png)

### Affected Versions

Neos: 3.2

Flow: 4.2

**Comment by rolandschuetz** [comment]
Thank you for the bug report. Please post the issue in the React UI issues at https://github.com/neos/neos-ui/issues and close this issue.

Thanks a lot!
