### ISSUE TITLE
How to organize documentation efforts?

### ISSUE THREAD

**Issue by maxstoyanov** [neos/neos-development-collection#1771]
Today, I contacted the guys at #guild-documentation at slack. There is no central place where documentation efforts are coordinated.

**I would like to work on the following aspects. How do we approach this?**

1. **Coverage.** A lot of questions from the forum could be answered with in the official manual. Either the information is missing or can not be found. (In a Information Architecture sense, not in a technical search engine way.)

2. **Assumptions.** Neos features some unique concepts. New users are faced to grasp them efficiently. (Mapping content to nodes, properties, using fusion, eel, flow...) The current manual expects users to be familiar with certain concepts. (Example: If you're used to WordPress and now are learning or even looking at Neos you will not understand how to build your website. If you're coming from TYPO3 Fusion will be a natural progression.)

3. **General organisation.** Documentation is divided per package. This is a legitimate structure but as a user that installs the "whole CMS" there is only one package: Neos. Either we find a way to guide a user through the individual package docs or we unify them. Possibly just rendering all those single repositories under one domain as separate chapters...

Cross posting on our forum: https://discuss.neos.io/t/rfc-how-to-organize-documentation-efforts/2879

**Comment by jonnitto** [comment]
Hi @maxstoyanov

**Comment by jonnitto** [comment]
Hi @maxstoyanov 
Thank you for your effort. **I think you touch here very important points.** Did you also post your conclusions on discuss.neos.io? I think there you would get more views and comments…

**Comment by kitsunet** [comment]
I had also chatted with you in Slack, so again 👍  from me!

**Comment by maxstoyanov** [comment]
Actually, I just had not enough time to do the crossposting.

The biggest question is: **What tools an processes are we going to use?**

**Comment by maxstoyanov** [comment]
I just did the crosspost. I also published a link to my personal trello board with my current thoughts. https://trello.com/b/pYNV6iKc/neos-documentation-effort

**Comment by rolandschuetz** [comment]
@maxstoyanov Documentation is definitely a weak point of Neos CMS. We need to improve this.

**Editor documentation**
We are currently working on a editor documentation based on https://academy.codeq.at/de/neos-anleitung/einleitung
https://github.com/neos/Neos.NeosIo/pull/206#event-1570811501

**Developer documentation**
Your proposals should all become part of [neos.readthedocs.io](https://neos.readthedocs.io/en/stable/), would be amazing if you extend it with a pull request, the [content can be found here](https://github.com/neos/neos-development-collection/tree/master/Neos.Neos/Documentation)

**Comment by rolandschuetz** [comment]
See https://github.com/neos/neos-development-collection/pull/2616
