### ISSUE TITLE
Bulk actions for media browser

### ISSUE THREAD

**Issue by Nikdro** [neos/neos-development-collection#1773]
We should add some bulk actions to the media browser.
It's already possible to delete elements in overview using the "3 dots button".

It would be very helpful, if we add a checkbox to each element to perform a bulk action (delete for example) on the selected elements. 

Maybe we can find a solution which solves #1587, too.

**Comment by klfman** [comment]
We also have this request in multiple projects.

Would be good to also have a function "select by tag" which selects all assets tagged by a tag. This would make tags very useful for buld editing assets with a similar purpose

**Comment by Sebobo** [comment]
This will not be implemented anymore in the current Media Browser but will be covered by the new implementation.
