### ISSUE TITLE
Different behavior in asset list when image is missing

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-development-collection#1791]
### Description

In the neos demo package is one image file missing and therefore the asset list has problems to render the missing image. The browsers handle this problem very different. Chrome renders the alt tag content, Firefox renders a loading spinner and Safari renders a loading spinner and a empty box as overlay.

So when you have no asset or if the asset file type is no image you get this problem.

### Steps to Reproduce

1. Setup neos with the demo package for instance
2. Go page Features -> Other elements
3. Edit the file list and look at the asset editor

#### Expected behavior

Same behavior in all browsers. Maybe an icon instead of the loader.

#### Actual behavior

Chrome: Alt text
Firefox: Load indicator
Safari: Load indicator with empty box overlay

### Affected Versions

Neos: dev-master

Flow: dev-master

### Screens

**Firefox:**
<img width="314" alt="bildschirmfoto 2017-12-07 um 20 22 09" src="https://user-images.githubusercontent.com/1014126/33735289-2e4f626c-db8f-11e7-9531-5d414796f060.png">

**Safari:**
<img width="311" alt="bildschirmfoto 2017-12-07 um 20 21 00" src="https://user-images.githubusercontent.com/1014126/33735290-2e796cd8-db8f-11e7-853f-8b4c85619cd0.png">

**Chrome**
<img width="310" alt="bildschirmfoto 2017-12-07 um 20 20 09" src="https://user-images.githubusercontent.com/1014126/33735292-2ec4604e-db8f-11e7-90d9-b26204832130.png">

**Comment by mgoldbeck** [comment]
Hi @markusguenther 
As the referenced issue was closed, I also close this one.
If I am wrong, feel free to reopen it.
