### ISSUE TITLE
Neos doesnt install under multiple PHP Versions

### ISSUE THREAD

**Issue by martinwolfdresden** [neos/neos-development-collection#1806]
### Description

Neos doesnt install under multiple PHP Versions. The alias for php is php => Version 5.6, php70 => Version 7.0, php71 => Version 7.1. The Provider doesnt allow to change the php Alias global. When Apache runs a php Script from console with php SCRIPTNAME, The console thinks it is php 5.6. 

In my opinion U need a chance to set a variable for the correct php Alias. Default is php.

Or have you another idea?

Martin

**Comment by kdambekalns** [comment]
The default `Settings.yaml` example files show how to do that:

```Neos:
  Flow:
  # You might need to uncomment the following lines and specify
  # the location of the PHP binary manually.
    core:
      phpBinaryPathAndFilename: 'php71'```

You might need to adjust `flow` and `Web/index.php` as well.

**Comment by mgoldbeck** [comment]
Hi @martinwolfdresden did this help you?
