### ISSUE TITLE
There is no error response for invalid electronic addresses

### ISSUE THREAD

**Issue by dimitriadisg** [neos/neos-development-collection#1807]
### Description

When adding an electronic address (and specifically an e-mail address) for a user through the backend user management module, there is no response message from the input validator.

The validator works as expected, doesn't approve invalid input, but fails too silently.

### Steps to Reproduce

1. Log-in to the backend (/neos route)
2. Toggle-open the modules menu (top left corner) 
3. Select "User Management"
4. Click the pencil (edit user) on any of the users on the list
5. Click the "Add electronic address" button
6. Enter the following fields:
    Type: Email
    Identifier: Test
    Usage: Home
7. Click the "Save" button

#### Expected behavior

Normally, one would expect for the saving to fail and see an error message describing the problem.

#### Actual behavior

The saving fails silently, There is no error message.

### Affected Versions

Neos: 3.2.1

Flow: 4.2.5

**Comment by kdambekalns** [comment]
Reproducible, should be easy to fix by showing validation errors / flash messages in the template.

**Comment by bwaidelich** [comment]
This has _finally_ been fixed via #https://github.com/neos/party/pull/34 – Thanks a lot for reporting this!
