### ISSUE TITLE
DatePicker didn't work in Safari 11.0.2

### ISSUE THREAD

**Issue by iseries** [neos/neos-development-collection#1821]
### Description

When selecting a date in the inspector (NodeType with a datepicker), the **selected date doesn't appear** in the input field after picking a date. This only happens in **Safari 11.0.2**. In chrome it works fine.

### Steps to Reproduce

1. Install neos
2. Try to pick a date in the inspector

#### Expected behavior

The chosen date should be displayed in the datepicker field.

#### Actual behavior

The selected date doesn't appear in the inspector datepicker field.

### Affected Versions
Neos: 3.2.1
Flow: 4.2.5

**Comment by mhsdesign** [comment]
hi, and sorry for no response ;)
is this still an issue?

**Comment by iseries** [comment]
Idk. In newer versions (Neos, Safari) the problem never appeared again. 3.2 is outdated anyway. So I think this can be closed.

**Comment by mhsdesign** [comment]
Thank you ;)
