### ISSUE TITLE
Neos does not render Help message from Yaml file.

### ISSUE THREAD

**Issue by Nguonchhay** [neos/neos-development-collection#1830]
The Help message is not rendered by following the guide at http://neos.readthedocs.io/en/3.3/References/PropertyEditorReference.html#property-type-string-textfieldeditor-single-line-text-editor-default.

**Comment by Nikdro** [comment]
I can confirm that

**Comment by mgoldbeck** [comment]
Hi @Nguonchhay and @Nikdro Do you use the old or the new Ui? If it is the new please add the bug here https://github.com/neos/neos-ui/issues

**Comment by Nikdro** [comment]
Hi @mgoldbeck,  
thanks for the hint, this is really a bug in the new UI. 
I created a copy of this Issue at https://github.com/neos/neos-ui/issues/1694

Since I can't reproduce it in the old UI, I think this Issue can be closed.

**Comment by dimaip** [comment]
Closing in favor of related issue from neos-ui.
