### ISSUE TITLE
Neos 3.3 new UI: Backend switching between multi dimensions with constraints

### ISSUE THREAD

**Issue by calcalid** [neos/neos-development-collection#1833]
### Description

In the new UI, I miss the dimension apply button or a correct refresh of the selectors. 
We have dimension constraints, so the new language/country selectors don't update themselves with the correct values. Sometimes the user has to refresh the backend several times to get the right values.

### Steps to Reproduce

1. Go to the backend
2. Change to another language dimension in the language selector (e.g. from de-> country:global to en)
3. The needed country USA (en-> language, country->usa) is not visible in the country selector,  even you manually reload the page
4. If you than get the country USA, you can see and choose other languages, which are not allowed.

#### Expected behavior

The dimension selectors update themselves with the correct dimension constraints.

#### Actual behavior

The dimension selectors don't update themselves, so the user have to manually reload the page. Also the user can select languages which are according to the configuration (constraints) not allowed. 

### Affected Versions
Neos: 
Neos 3.3 new UI

**Comment by kdambekalns** [comment]
More or less a duplicate of https://github.com/neos/neos-ui/issues/1565 and fixed with https://github.com/neos/neos-ui/pull/1607 👍
