### ISSUE TITLE
Adjust documentation of xsd generate command controller

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-development-collection#1859]
### Description

The command controller for the creation of the XSD files still uses the typo3.org domain.
This will replace the domain with neos.io

This should also adjust the documentation for the change.
https://github.com/neos/flow-development-collection/issues/1186

**Comment by jonnitto** [comment]
As there is a PR for this (https://github.com/neos/neos-development-collection/pull/1860 and https://github.com/neos/flow-development-collection/pull/1187) I'll close this issue.

Thank you @markusguenther, we'll discuss and decide on the PR thread.
