### ISSUE TITLE
Allow attributes to be added to ContentElementWrapping

### ISSUE THREAD

**Issue by lorenzulrich** [neos/neos-development-collection#1879]
### Description

Currently there's no way to target elements via CSS based on their node type in the backend user interface.

**Comment by bwaidelich** [comment]
Closing in favor of https://github.com/neos/neos-ui/issues/1647  (in the old UI this issue does not exist)

**Comment by bwaidelich** [comment]
According to @skurfuerst's comment on https://github.com/neos/neos-ui/pull/1648 I'll re-open this ticket as reference for a more extensible `ContentElementWrapping`
