### ISSUE TITLE
Neos 3.3.4 breaks if package without Translations folder is installed

### ISSUE THREAD

**Issue by lorenzulrich** [neos/neos-development-collection#1886]
### Description

#1708 introduced a regression. If a package without a Translations folder is loaded, the installation breaks with the following error:

![image](https://user-images.githubusercontent.com/1816023/35980547-3dcf4fb2-0ceb-11e8-87ed-3a9b60870dac.png)

### Steps to Reproduce

1. Update to Neos 3.3.4
2. Install a package without a `Resources/Private/Translations` folder, e.g. `Flowpack.Listable`.
3. Try to access Neos

#### Expected behavior

Neos should load normally. The package doesn't need any translations.

#### Actual behavior

Neos breaks because it tries to scan a non-existing folder.

### Affected Versions

Neos: 3.3.4

**Comment by lorenzulrich** [comment]
Pull Request: #1887

**Comment by kdambekalns** [comment]
Freshly gained knowledge: only affects packages that have `userInterface.translation.autoInclude` enabled but do not provide translations. Well. Doh. 😉

**Comment by lorenzulrich** [comment]
Ah, good to know. I created a PR for Listable: Flowpack/Flowpack.Listable#28
