### ISSUE TITLE
Flickering upload dropzone in Backend

### ISSUE THREAD

**Issue by mad99** [neos/neos-development-collection#1889]
### Drag and Drop in Backend-upload-field triggers a flickering and open the file in browser instead of start the upload process

See video for description: https://vimeo.com/255018357

### Steps to Reproduce

1. select file/fiels in Finder
2. Drag and Move to upload Area/Form
3. Move exactly to text «Dateien hier ablegen» / (maybe in english: Files move here)
4. If it is a matter of chance and the files are placed exactly on the text, they are displayed in the browser instead of being uploaded.

#### Expected behavior

Upload the files to Neos

#### Actual behavior

open the file in Browser

### Affected Versions

ALL -> I also saw this in previous Version, also classic UI. So this is the reason why I cerated here the Issue and not in ReactUI. 

## Solution that works locally:

I have changed the css for the form and the flickering is gone. It also upload every time the files instead to open it in browser.
*With the css-selector I'm not sure. Please check code an use the right selector for precisely address the right form-field.*
**Maybe this could match:**
```css
#dropzone.neos-upload-area form {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0; 
}
```
With position absolute and width and height, the form will cover the text. The hover of text-field does not have longer influence to form-field-behaviour. Effect: No flickering and the upload always starts!

Hope will help
CU
Martin

**Comment by aertmann** [comment]
Thanks for reporting, fixed it with #1890
