### ISSUE TITLE
Node.getOtherNodeVariants() may lead to call on a non-object

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#1896]
### Description

When `getOtherNodeVariants()` is called on a `Node` instance, a fatal error may be the result, because `getNodeData()` is called on a non-object (i.e. a `null` value.)

### Steps to Reproduce

Reproducing this may not be easy, but the general flow is:

1. Have a node on which you call `getOtherNodeVariants()`
2. Have some variant of that node be "internal" or invisible, inaccessible or hidden (if the content context used does not allow access to such nodes)

#### Expected behavior

Well, the node is ignored, nothing (bad) happens.

#### Actual behavior

A fatal error happens, because `$node->getNodeData()` is called in [Node.php](https://github.com/neos/neos-development-collection/blob/1f7d2c237a8452cf7a4b013786e05e4a6ba35d8d/TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Node.php#L345).

This is because `$this->context->getNodeVariantsByIdentifier($this->getIdentifier())` may indeed include `null` values in the returned array.

### Affected Versions

Neos: 2.3.14 (and later)

**Comment by dlubitz** [comment]
@kdambekalns AFAIS this is fixed and can be closed.

**Comment by kdambekalns** [comment]
Could be… let's see. ;)
