### ISSUE TITLE
Missing Date.formatCldr() Eel Helper in Docu

### ISSUE THREAD

**Issue by samuelhauser** [neos/neos-development-collection#1898]
In the documentation the Date.formatCldr() Eel Helper is missing

**Comment by aertmann** [comment]
Missing on the auto-generated Eel helper reference http://neos.readthedocs.io/en/stable/References/EelHelpersReference.html

**Comment by dlubitz** [comment]
Rendering with neos/doctool works fine. Seem to be a missing job or commit while build/release. The last change of [EelHelpersReference.rst](https://github.com/neos/neos/blob/master/Documentation/References/EelHelpersReference.rst) was in May 2017. Also open changes for other view helpers references

**Comment by mgoldbeck** [comment]
@kdambekalns can you help here??

**Comment by dlubitz** [comment]
Could you already have a look into it @kdambekalns ?

**Comment by kdambekalns** [comment]
No, sorry… not yet.

**Comment by jonnitto** [comment]
https://neos.readthedocs.io/en/stable/References/EelHelpersReference.html#date-formatcldr-date-cldrformat-locale
