### ISSUE TITLE
How do I create a new project in Neos CMS?

### ISSUE THREAD

**Issue by justinbrunkow** [neos/neos-development-collection#1901]
I recently turned a computer into a Ubuntu server. I have installed all dependencies following http://neos.readthedocs.io/en/stable/GettingStarted/Installation.html My version of Ubuntu (or Apache) did not have a "htdocs" folder like the article suggested, so I created a folder called newsletter in var/www/html per this article https://askubuntu.com/questions/683953/where-is-apache-web-root-directory-on-ubuntu Then I try to complete step 2 of "Fundamental Instruction" by using the following code cd /your/htdocs/ php /path/to/composer.phar create-project neos/neos-base-distribution Neos but it does not work. Instead of inputting "cd /your/htdocs" I navigate to /var/www/html I am getting "Could not open input file: /path/to/composer.phar" I believe I already have composer installed, so I don't really want to have to go through https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-ubuntu-16-04 Should I change "/path/to/composer.phar"? Has the location changed?

**Comment by kdambekalns** [comment]
Well, you either have composer or not. If you don't you need to install it. The easiest way is following https://getcomposer.org/download/ IMHO.

And then you need to call composer in the place you installed it to. Wherever that is. ;)
