### ISSUE TITLE
missing multi-site informations in documentation

### ISSUE THREAD

**Issue by iseries** [neos/neos-development-collection#1927]
**This ticket is a nice-to-have for the future.**
There is no detailed documentation for the neos multi site support. The user knows that neos is supporting this feature, but there is no documentation about a setup or a "what to do to create a multisite". I don't know how this could be documented in detail, but I think we definitely need more information in this section.

Current documentation for Multi Site:
http://neos.readthedocs.io/en/stable/CreatingASite/MultiSite.html

**Comment by jonnitto** [comment]
https://docs.neos.io/cms/manual/content-repository/multisite-support
