### ISSUE TITLE
Context structure tree breaks in Neos 2.3.21

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#1933]
This pull request breaks the correct behavior in Neos 2.3.21 of the structure tree:
https://github.com/neos/neos-development-collection/pull/1785

In the structure tree, it is not possible to create new content elements.

**Comment by jonnitto** [comment]
![screenflow](https://user-images.githubusercontent.com/4510166/36847821-c49c9246-1d5f-11e8-826d-2c03e762ea29.gif)

**Comment by aertmann** [comment]
Thanks for reporting, fixed with #1934
