### ISSUE TITLE
Changes to a document node are recognized as changes to all auto-created child nodes

### ISSUE THREAD

**Issue by beheist** [neos/neos-development-collection#1961]
### Description

If I change a document-level node property, the change seems to be cascaded to all auto-created child nodes. In the Neos-Demo site, a change to the title of the homepage results in 4 changes instead of one:
![image](https://user-images.githubusercontent.com/10347669/37337156-ba21d968-26b3-11e8-8824-264a504d33d5.png)

The issue seems to exist in both the old and new UI, but the new UI displays a (4) while the old one displays a (1) on the button. "(4)" is only visible for "Publish all" here, even though there are no changes on other pages. Also, the child nodes are not marked as changed in the content structure tree.
![image](https://user-images.githubusercontent.com/10347669/37336696-77e5c40c-26b2-11e8-8b91-66ad78df8fef.png)

The issue also exists in 2.3 LTS:
![image](https://user-images.githubusercontent.com/10347669/37337040-75517532-26b3-11e8-9b4c-39d9797f4c4f.png)

### Steps to Reproduce

1. Get a fresh instance of the Neos-Demo site.
2. Change the title of the Homepage to something else, click "Apply".
3. You get a weird number of changes and all auto-created child nodes are marked as changed.

#### Expected behavior

(1) change instead of (4).

#### Actual behavior

See above.

### Affected Versions

All Versions of Neos (tested 3.3 LTS, 2.3 LTS).

**Comment by kdambekalns** [comment]
@beheist This should be fixed with https://github.com/neos/neos-development-collection/pull/2085 - feel free to reopen if this is still an issue.
