### ISSUE TITLE
Remove Neos.NodeTypes from required packages

### ISSUE THREAD

**Issue by Benjamin-K** [neos/neos-development-collection#1980]
### Description

Today i tried to install a new version of Neos without having neos/nodetypes in the composer requirements. If you do so, you can complete the Neos Setup and also login to the backend. 
BUT: If you are logged in and try to add any node, you will get an error message (with lots of html).
The problem here is: Neos always creates new site nodes / pages with a nodetype of Neos.NodeTypes:Page, even if that nodetype isn't in the nodetype declarations. To fix this, one will have to add (or keep) neos/nodetypes in the requirements, which will also add all the subpackages of neos/nodetypes – i thought they were separated to only require the packages you need.

### Steps to Reproduce

1. Create a new installation of Neos (`composer create-project --no-dev neos/neos-base-distribution .`).
2. Remove neos/nodetypes from required packages.
3. Run the setup.
4. Add at least one nodetype you can add in a ContentCollection (i had neos/form-builder installed, so you can use that, too).
5. Log into backend.
6. Try to add that nodetype to the ContentCollection of the page created from setup.

#### Expected behavior

Adding nodes without having neos/nodetypes and all its subpackages installed should still work. Neos should have its own nodetype definition for a page, which will be used for pages in default or (even better) the user should be able to choose which document-nodetype he wants to choose for his home page. Or, if there is no document-nodetype available during setup, Neos should give a warning so that the user adds a nodetype definition first before setting up an invalid nodetype tree.

#### Actual behavior

The Neos Setup finishes without errors, even if neos/nodetypes is not installed. After logging in to the backend you are not able to add any nodes without getting an error.

<img width="609" alt="bildschirmfoto 2018-03-29 um 07 51 22" src="https://user-images.githubusercontent.com/3098031/38072601-649f7984-3327-11e8-8537-7edffe6fb4d2.png">

The error occurs in Neos\Neos\Ui\Domain\Model\AbstractChange::updateWorkspaceInfo() on line 83. The problem is, that (in line 81) Neos\Neos\Ui\ContentRepository\Service\NodeService::getClosestDocument($node) does return NULL, because `Neos.NodeTypes:Page` is not in the nodetype definitions and therefore does not extend `Neos.Neos:Document` and can't be found as document.

### Affected Versions

This error occurred on the new UI. But i think it is also present in earlier versions of Neos.

Neos: 3.3.0+, maybe also earlier.

**Comment by rolandschuetz** [comment]
Thank you for the bug report. 

This problem already exists for a long time. Neos should NOT have it's one root node type since most developers implement there own Homepage node type. Instead, the setup needs a possibility to define the root node.

**Comment by jonnitto** [comment]
@Benjamin-K Is this problem still here or can we close this one?

**Comment by Benjamin-K** [comment]
@jonnitto I need to check this first. I have worked around this error since then, but i think it is still here. 

One thing i can say is, when creating a new site package with `flow kickstart:site` you will always add requirement for `neos/nodetypes`, which should not be necessary, i think. See `Neos\SiteKickstarter\Service\GeneratorService::generateSitePackage()`. I don't know, if `neos/nodetypes` is only added to the site requirements or if it is used anywhere else (like in the nodetype definitions or sth.). If it is not in the nodetype definitions or in fusion, this requirement should be removed.

**Comment by jonnitto** [comment]
Please test it against master, bc we have some updates there

**Comment by kdambekalns** [comment]
AFAIK this is soved. If the site kickstarter still adds that dependency without a reason, please open a new issue about that.
