### ISSUE TITLE
Flush cache throws exception when cache tables

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-development-collection#1985]
### Description

I changed my caching backend to the PdoBackend and wanted to use the migrations to create the
caching tables. Just in favor of manually written SQL. While doing this I found out that the flush cache command does not check if the caching tables are there.

It just try to flush that cache and then you get exceptions.

### Steps to Reproduce

1. Change caching backend to PdoBackend
2. DONT create caching tables manually
3. ```./flow flow:cache:flush```
4. See some nice Exceptions

#### Expected behavior

It would be nice if we don't return the exceptions. A nice hint in the cli that the caches could not be cleared because the caching table are missing would be nice.

#### Actual behavior

Get exception that the SQL could not be executed. Obvious because the cache and tag table is missing ;)

### Affected Versions

Neos: 3.3

Flow: 4.x

You can get this information by running `composer show` or using the package management module within Neos.

**Comment by markusguenther** [comment]
Maybe it ist just my point of view but from the user perspective I would like to get a hint and not an exception. If you also like the idea I will tackle that :)

**Comment by rolandschuetz** [comment]
You can manually add the cache tables by executing:
`Packages/Framework/Neos.Flow/Resources/Private/Cache/SQL/DDL.sql`

**Comment by kdambekalns** [comment]
See https://github.com/neos/flow-development-collection/pull/1384 for a fix…

**Comment by davidspiola** [comment]
Hi @markusguenther, I guess we can close this issue! right?

**Comment by markusguenther** [comment]
When it is already fixed we can :)
