### ISSUE TITLE
Override router implmentation

### ISSUE THREAD

**Issue by breadlesscode** [neos/neos-development-collection#1997]
### Description

Im trying to override the `Neos\Flow\Mvc\Routing\Router`. I configured the following lines in my `Object.yaml`:

```yaml
Neos\Flow\Mvc\Routing\RouterInterface:
  className: 'Vendor\Xy\Mvc\Routing\Router'

```

So far, so good. The problem is that the `Router->route()` method never gets called. Only the `Router->resolve()` method gets called.

### Steps to Reproduce

Try to override the router

#### Expected behavior

The  `Router->route()` method gets called. 

#### Actual behavior

The  `Router->route()` method never gets called. 

### Affected Versions
Neos: 3.3.9
Flow: 4.3.4

**Comment by mgoldbeck** [comment]
Hi, is this still valid?

**Comment by kitsunet** [comment]
This should go to flow-development-collection instead
