### ISSUE TITLE
Include also the brand icons from FontAwesome 5

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#2045]
With the introduction of FontAwesome 5, many new icons were added. But the [brand icons](https://fontawesome.com/icons?d=gallery&s=brands&m=free) are missing, so for example with `icon-youtube` I didn't get any icon

To reproduce, install the demo package and try to add a new content element. The element "YouTube" has no icon at all

**Comment by sbruggmann** [comment]
@jonnitto The Youtube Icon works for me, at least since Neos 3.3
But I have made PRs for FontAwesome 5.5.0 now: https://github.com/neos/neos-development-collection/pull/2261 and https://github.com/neos/neos-ui/pull/2230
