### ISSUE TITLE
Introduce copyright notice as a persisted field for Neos assets

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#2064]
With the introduction of Neos asset sources, the author is able to search and select images from third party asset sources. 
These asset sources normally provide the author / photographer with their image meta data. 
They also specify in detail how the attribution has to look like. 
This data can be stored together with the asset and later used when inserting the image, like we have it with label and description already.

**Comment by dfeyer** [comment]
Go go ;) it's an important one.

**Comment by robertlemke** [comment]
> This data can be stored together with the asset and later used when inserting the image, like we have it with label and description already.

You mean like we have it with _title_ and _caption_, correct?

Sure, let's do that!

**Comment by kitsunet** [comment]
I guess we need that? I would hope we can tackle the whole metadata topic soon but I guess it will be too long to wait for it and then it makes sense to have this for the time being.

**Comment by pduersteler** [comment]
Is that something that should go directly into it or is there a plan to have some sort of "configurable fields" which needs more work? We have a few requests for this, if it's the former (simpler) case I think I could submit something.

**Comment by bwaidelich** [comment]
To make it clear: This suggests to extend the `Asset` entity by two new fields for `author` and `copyright`, correct?

I'd be fine with two additional fields of course, but I fear that this gets another "god model" with additional field requests.

Not to overcomplicate things, but to make this extensible from the start we could introduce a `AssetMetadata` ValueObject that implements `JsonSerializable`.
Searching those isn't as nice, but `WHERE metadata LIKE '%"name": "author","value": "<term>%'` usually works. Or we use the [JSON](https://github.com/SyslogicNL/DoctrineJsonFunctions) support.


But I wonder: Should we really extend the `AssetInterface`? That would mean that `ImageVariants` have these fields, too.
