### ISSUE TITLE
Media Browser: Uploading an existing file should display a notice

### ISSUE THREAD

**Issue by lorenzulrich** [neos/neos-development-collection#2074]
### Description

When an already existing file is uploaded again, Neos (intentionally) doesn't upload a duplicate. Instead, it just displays a flash message stating that the file has been successfully uploaded.

This is not a real problem, but it becomes one when a user uploads an existing file again, but coming from an Asset Collection. The user opens the "Upload" window, selects the file. The Asset Collection is already pre-selected. The user then clicks the "Upload" button. The file is (as stated before) not really uploaded, but a success message is displayed. But it is also not added to the selected Asset Collection - therefore the user assumes the upload failed somehow.

### Steps to Reproduce

1. Go to the Media Browser
2. If you already have Asset Collections, click "All" so no Asset Collection is selected.
3. Upload a file
4. Open (create) an Asset Collection
5. Upload the same file again from the same asset collection.

#### Expected behavior

Either: A message stating that the file was not uploaded because it already exists.
Or (better?): The file should be added to the previously selected Asset Collection

#### Actual behavior

A message "File uploaded successfully" is displayed.
Inside the Asset Collection selected in step 4, no change is visible because the document was not uploaded again and therefore also not added to the Asset Collection

### Affected Versions

Neos: 3.3 LTS+

**Comment by rolandschuetz** [comment]
Thank you for the great. Issue, I agree that would be a valuable fix for editors!

**Comment by sbruggmann** [comment]
@lorenzulrich I can't reproduce this in Neos 3.3 with Neos-UI 1.3 and the Code looks ok: https://github.com/neos/neos-development-collection/blob/3.3.13/Neos.Media.Browser/Classes/Controller/AssetController.php#L478

Is it maybe only a problem of the old UI?

**Comment by lorenzulrich** [comment]
Interesting - cannot reproduce it in 3.3 latest anymore. So this can be closed.
