### ISSUE TITLE
Node names are not always unique

### ISSUE THREAD

**Issue by davidspiola** [neos/neos-development-collection#2089]
### Description

Node names are sometimes not unique within the same path. If you copy a node within the same path, the newly created node has a new unique node-name. But if you copy and past it into a new path the node-name remains the same. Sometimes the editor might want to move the new node into the old path, but this results in an error message "Node with path "node-xyz" already exists." As an editor you can't change the node-name and you are forced to perform this action with an unnecessary workaround. 

I propose, that newly generated node should always get a new node-name regardless of performed action. 

### Steps to Reproduce

1. Copy a existing node
2. Paste it into a new folder (node-path)
3. Drag and drop a newly created node in the node-path of step 1

#### Expected behavior

Dragging the new node into the old path should be possible.

#### Actual behavior

Error message "Node with path "node-xyz" already exists."

**Comment by rolandschuetz** [comment]
I can confirm that issue! Needs fixing.

**Comment by Weissheiten** [comment]
Can also confirm this.

**Comment by sbruggmann** [comment]
Bug is fixed in neos/neos-ui 1.3.3 but there are similar problems on moving nodes:
https://github.com/neos/neos-development-collection/pull/2161
https://github.com/neos/neos-ui/pull/2098

**Comment by davidspiola** [comment]
Issue is resolved
