### ISSUE TITLE
database set utf8mb4 - unique index is too long

### ISSUE THREAD

**Issue by davidspiola** [neos/neos-development-collection#2090]
### Description

The unique key for the database table neos_media_domain_model_importedasset is reaching the limit of the utf8mb4 charset. 

```
CREATE TABLE `neos_media_domain_model_importedasset` (
  `persistence_object_identifier` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `assetsourceidentifier` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remoteassetidentifier` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `localassetidentifier` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `localoriginalassetidentifier` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `importedat` datetime NOT NULL,
  PRIMARY KEY (`persistence_object_identifier`),
  UNIQUE KEY `flow_identity_neos_media_domain_model_importedasset` (`assetsourceidentifier`,`remoteassetidentifier`,`localassetidentifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
All three values for the key have a length of 255 characters. This results into an error:

`MySQL error: The maximum column size is 767 bytes`

### Steps to Reproduce

1. Import existing Neos 4.0 project dump into MySQL Instance 5.6.19-67.0 

### Affected Versions
Neos 4.0

**Comment by kitsunet** [comment]
https://www.neos.io/blog/neos-40-and-flow-50-released.html

If you are using a MySQL based database you must use at least MySQL 5.7.x or MariaDB 10.2.x.
Other database systems are not affected.
