### ISSUE TITLE
inline editorOptions placeholder: 'i18n' not working

### ISSUE THREAD

**Issue by h1Modeling** [neos/neos-development-collection#2118]
Description

With the new inline editorOptions the placeholder translation doesn't work anymore

Steps to Reproduce

Create a property with i18n placeholder and new inline editorOptions format
properties:
text:
type: string
ui:
inline:
editorOptions:
placeholder: 'i18n'
Expected behavior

Neos should display the translated value or the property string if it doesn't find the value

Actual behavior

Neos just displays i18n

<img width="184" alt="bildschirmfoto" src="https://user-images.githubusercontent.com/17990673/43301413-3591d078-9165-11e8-8282-95597420da53.png">

Affected Versions

Neos: 4.0

UI: >= 1.2.3 (and maybe older)

**Comment by dimaip** [comment]
Yep, all correct. Could you provide a PR?

**Comment by h1Modeling** [comment]
Have created one.

**Comment by Sebobo** [comment]
Hi @h1Modeling, is this already resolved? 

I can't see the related PR. And the ones related to the commits are something else I think.

**Comment by h1Modeling** [comment]
Yes it was #2125
