### ISSUE TITLE
Argument 1 passed to Neos\Flow\Security\Account_Original::setExpirationDate() must be an instance of DateTime or null, instance of Neos\Flow\Utility\Now given

### ISSUE THREAD

**Issue by PascalNegwer** [neos/neos-development-collection#2131]
### Description

When using the function deactivateUser from UserService 
(See: https://github.com/neos/neos/blob/master/Classes/Domain/Service/UserService.php#L567 )
I get the following Exception:

Argument 1 passed to Neos\Flow\Security\Account_Original::setExpirationDate() must be an instance of DateTime or null, instance of Neos\Flow\Utility\Now given

### Affected Versions

neos/neos                        4.0.7
neos/neos                        4.0.6
maybe more

**Comment by kitsunet** [comment]
Correct, that was changed to be \DateTimeImmutable at some point which is not compatible with \DateTime. That indeed needs to change.

**Comment by jrenggli** [comment]
Just had the same issue today with Neos 4.3.3 and Flow 5.3.3.

As far as I see the change to `\DateTimeImmutable` has been introduced in Flow 3.1.

The easiest way would be to change `setExpirationDate()` (and all the other methods handling dates) in `Account` class to use `\DateTimeImmutable`. But all these methods are part of the API. I assume we can only change these in the next major version. This would currently be Flow 6.

Neos 3 and 4 would need a patch to cast the date to `\DateTime` explicitly.

@kitsunet: Or is there another way? Should I create some PRs accordingly?
