### ISSUE TITLE
Media Browser: The layout files could not be loaded error

### ISSUE THREAD

**Issue by DrNik** [neos/neos-development-collection#2170]
### Description

When trying to open the media browser from a content node Image property ([Image Selection](https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-image-neos-media-domain-model-imageinterface-imageeditor-image-selection-upload-editor)) returns the error:

`The layout files "resource://Neos.Media.Browser/Private/Layouts/Default.html", "resource://Neos.Media.Browser/Private/Layouts/Default" could not be loaded.
Exception Code	1225709595
Exception Type	Neos\FluidAdaptor\View\Exception\InvalidTemplateResourceException
Thrown in File	Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_FluidAdaptor_View_TemplatePaths.php
Line	279
Original File	Packages/Framework/Neos.FluidAdaptor/Classes/View/TemplatePaths.php`

### Steps to Reproduce

1. Update Neos.MediaBrowser to version >= 4.1.0
2. click on the _camera icon_ in any ImageEditor

#### Expected behavior

Media Browser opens up to let me choose pre-uploaded images

#### Actual behavior

Reported error returned

### Affected Versions

Neos.Media.Browser 4.1.* (and probably other releated packages)

Neos: 4.1.*

THanks,
Nicola

**Comment by aertmann** [comment]
Can confirm.

Additionally they layout of the backend module is messed up, possibly related.
![image](https://user-images.githubusercontent.com/903567/44925022-65fd8280-ad4d-11e8-83e0-28562f156e30.png)

**Comment by dfeyer** [comment]
Can confirm too

> Additionally they layout of the backend module is messed up, possibly related.

Can't reproduce the messy layout, maybe only when you have more than X tags ?

**Comment by dfeyer** [comment]
I think its my fault https://github.com/neos/neos-development-collection/pull/1745 I don't why but this PR remove all the layout on the Layout directory

**Comment by dfeyer** [comment]
Working on a fix, will push a PR asap

**Comment by dfeyer** [comment]
Should solve the issue https://github.com/neos/neos-development-collection/pull/2171

**Comment by DrNik** [comment]
Thank you very much guys, 
just to know how to move from here, when is the fix supposed to publicly available?

Thanks again,
Nicola

**Comment by soee** [comment]
I think we should release the fix ASAP. Atm. working with content with assets so hard - we can't select existing image, we have to upload them each time via properties manager :)
