### ISSUE TITLE
New Neos.Fusion:Debug / DebugDump implementation truncates dump for very short output

### ISSUE THREAD

**Issue by beheist** [neos/neos-development-collection#2176]
### Description

The Content-Length header sent by Neos does not take into account the output generated by DebugDump, as it is echoed directly.

### Steps to Reproduce

The following Fusion code:

```
root >
root = 'foobarbazz'
root.@process.debug = Neos.Fusion:Debug
root.@process.dump = Neos.Fusion:DebugDump
```
#### Expected behavior

The output "foobarbazz" and a var_dump output in the Neos style.

#### Actual behavior

The following is the entire server response:
```
<style typ
```
which is the first 10 characters of the debugger output. The Content-Length header confirms this:
```
Content-Length: 10
```

### Affected Versions
Neos: 4.1
Flow: n/a

**Comment by sbruggmann** [comment]
@beheist and @bwaidelich Please have a Look at the PR #2253
