### ISSUE TITLE
FEATURE: Add a delete button in backend user details view

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#2178]
While a backend user can be deleted using a button in the user listing, there is no delete button in the user details view.

![image](https://user-images.githubusercontent.com/642226/45144037-3fac6c80-b1bd-11e8-9a29-a9bd6707d255.png)

**Comment by tantegerda1** [comment]
The relevant pull request is merged, so this bug can be closed, I assume?

**Comment by bwaidelich** [comment]
yep, solved with #2228 apparently
