### ISSUE TITLE
BUG: Not possible to open the original/full scale URL of an asset in media browser detail view

### ISSUE THREAD

**Issue by DavidSporer** [neos/neos-development-collection#2184]
### Description

In one of the previous versions of Neos it was possible to click on the image in the Media module and the image (or PDF or whatever) was opened in a new window which allowed users to copy the URL and link the image elsewhere. There are cases where that comes pretty handy, e.g. if somebody else has uploaded the image and you want to upload it to Facebook or if there's an editor that allows you to use images that are stored elsewhere and you can link them.
I think it would be great if that could be re-added or if there would be a button to open the asset.
Currently if you click on the preview it opens the same page of the media module in a new window (the detail view of the asset).

### Steps to Reproduce

1. Open an image in the Media module
2. Click on the preview image

This "mockup" has a button included to open the original asset.
![asset-original-url](https://user-images.githubusercontent.com/1636571/45375988-ebf3b600-b5f6-11e8-9dd6-0fabb20d17ea.png)

**Comment by aertmann** [comment]
This is a unintentional change and thus a bug. Possibly related to #1745
