### ISSUE TITLE
Fusion dynamic @position (with eel expression)

### ISSUE THREAD

**Issue by PRGfx** [neos/neos-development-collection#2185]
### Description
I understand that it may be intended to not evaluate the `@position` meta-property as it might rely on the current object's elements already being sorted, but I see use-cases for when it would be helpful,e.g.:
```
content = Neos.Fusion:Array {
  left = '<p>left</p>'
  left.@position = ${props.changeOrder ? 'end' : 'start'}
  right = '<p>right</p>'
}
```
With an example as simple as this it would be possible to use a RawArray, `@process.reverse` and  `@process.join` it. A different workaround might be a bit like this:
```
content = Neos.Fusion:Value {
  el1 = '<p>one</p>'
  el2 = '<p>two</p>'
  el3 = '<p>three</p>'
  normalOrder = ${[this.el1, this.el2, this.el3]}
  changedOrder = ${[this.el3, this.el2, this.el1]}
  value = ${Array.join(props.changeOrder ? this.changedOrder : this.normalOrder, '')}
}
```
Is there further reasoning behind the current implementation or are there any proper solutions in dealing with the described situation?

#### Expected behavior

Sorting should be applied according to the evaluated eel expression. Maybe the PositionalArraySorter should throw an InvalidPositionException for unexpected input types as well.

#### Actual behavior

The expression gets passed to the sorter as something like this:
```
array (size=3)
  '__eelExpression' => string 'props.changeOrder ? 'end' : 'start'' (length=35)
  '__value' => null
  '__objectType' => null
```
which breaks the `preg_match` calls on the given "position" in the PositionalArraySorter. (Naturally values like `${'end'}` will cause an exeption in the same way.)

**Comment by Sebobo** [comment]
Have never thought about that, but I would be interested in more use cases. 

For your given example usually I advise to use css to position stuff in the frontend. 

For flexible layouts you could also make separate layout objects that load the individual parts as needed and the needed layout is f.e. selected via a case object.
