### ISSUE TITLE
Make Asset Property Editors work with custom Asset sources

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#2198]
The property editors for [images](https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-image-neos-media-domain-model-imageinterface-imageeditor-image-selection-upload-editor) and [assets](https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-asset-neos-media-domain-model-asset-array-neos-media-domain-model-asset-asseteditor-file-selection-editor) in general are currently "hard-coded" to find assets using the `AssetRepository`.
As a result, assets with custom asset sources (see #1979) are only found if they have been imported before.

**Comment by bwaidelich** [comment]
Some more technical background info and what I tried so far:

The endpoint for the asset editor search is `Neos\Neos\Controller\Service\AssetsController::indexAction()` which currently searches for assets in the AssetRepository:
```php
$assets = $this->assetRepository->findBySearchTermOrTags(
    $searchTerm,
    $this->tagRepository->findBySearchTerm($searchTerm)->toArray()
);
```

As a first approach I copied some code from `Neos\Media\Browser\Controller\AssetController` in order to search the asset *proxies* instead:

```php
$activeAssetSource = $this->getAssetSourceFromBrowserState();
$assetProxyRepository = $activeAssetSource->getAssetProxyRepository();
$assetProxies = $assetProxyRepository->findBySearchTerm($searchTerm);
```

As a result the `Assets/Index.html` template fails because the Thumbnail VH expects an Asset. Adjusting the template to sth like:
```
<a rel="thumbnail" href="{assetProxy.thumbnailUri}">{neos:backend.translate(id: 'thumbnail', value: 'thumbnail')}</a>
```
works (the "asset-show" link won't work, but it's currently not used AFAIS).


## What needs to be done / decided

* I copied the `getAssetSourceFromBrowserState` logic from the Media Browser, but probably the asset source should be configurable - or it should search in all configured sources
* When an asset is selected it needs to be imported, so probably we need to invoke the `neos/media/browser/asset-proxies/import` endpoint from the editor(s)

**Comment by robertlemke** [comment]
I got it working, with currently only one little issue. And it took another full day ;-)
