### ISSUE TITLE
Cleaning a Fusion Path does not work

### ISSUE THREAD

**Issue by beardcoder** [neos/neos-development-collection#2213]
### Description

Cleaning a Fusion Path does not work with the> symbol. The properties are still inherited

### Steps to Reproduce

1. Include a prototype with an Array or RawArray
2. Clean this property with >
3. Write an Neos.Fusion:Value to this property

Code Example
```
prototype(My.Package:Page) < prototype(Neos.Neos:Page) {
    body = Neos.Fusion:Array {
        1 = ${q(node).property('title')}
        2 = ${q(node).property('description')}
    }
}

prototype(My.Package:FrontPage) < prototype(My.Package:Page) {
    body >
    body = Neos.Fusion:Array {
        1 = ${q(site).property('title')}
    }
}
```

The Frontpage will output the title and the description

#### Expected behavior

The path output only the new value

#### Actual behavior

The path output the new and the old value

### Affected Versions

Neos: 4.0.9
Flow: 5.0.8

**Comment by Sebobo** [comment]
Thanks for the bug report, I can confirm that.
