### ISSUE TITLE
Image view in Media.Browser also list non image assets

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-development-collection#2255]
### Description

A issue in the react-UI  pops up that the media browser returns also non image assets when the editor is configured for just images. After some investigation it turns out that this is not an issue of the react-UI. The Image Controller in the Media.Browser has no applied filter.

https://github.com/neos/neos-ui/issues/2176 

### Steps to Reproduce

1. Press the Media Button near the Image
2. Choose a non-image-file (PDF)
3. You get an Error 💥

#### Expected behavior

You can only select images.

#### Actual behavior

See also PDF assets

### Affected Versions

Neos: master

Flow: master

**Comment by markusguenther** [comment]
The error exists since neos 4.0.

**Comment by aertmann** [comment]
Regression of #1979
