### ISSUE TITLE
Custom label for auto created child nodes

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#2276]
Allow the label of auto created child nodes to be predefined (i.e. overridden) via the NodeType definition

**Comment by kitsunet** [comment]
I thought we explicitly said we do not want that somewhere at the sprint? If you need that you create a separate nodetype? or secret trick - a property that is never editable with a default value?

**Comment by bwaidelich** [comment]
@kitsunet I just created tickets for open "4.2 PRs" without one. This one is for #530
