### ISSUE TITLE
Moving document nodes breaks nested variants

### ISSUE THREAD

**Issue by sbruggmann** [neos/neos-development-collection#2282]
#### Given

- you have a content dimension "language" with values "all", "de", "en". The latter two have a fallback to "all".
- you have a translated page
- the page has a content element with child nodes in a content collection
- the child nodes have variants in "all" and "de"

#### Problem

If you move the "de" document node variant to a new parent and publish all open changes, results in the translated content disappearing from the frontend output.
This is because the "de" document node variant is getting a new node-name, the original "all" variant not.

The Problem sound familiar to #943 but is not exactly the same.

#### Expected behavior

As if you move the original "all" document node variant to a new parent. This results in consistant node-names and no lost translations.

### Affected Versions

Neos: 3.3+

**Comment by markuspfeifenberger** [comment]
Hi Stefan,

we are facing the same problem right now. Can you please do the following and let me know the result:

Given: You have nothing to publish and in the Database there are no workspace entries on your "user-YOURNAME" workspace - check it with this SQL (replace YOURNAME with your login username):
```
SELECT * FROM neos_contentrepository_domain_model_nodedata
WHERE workspace like 'user-YOURNAME' AND  path not like "/"
```
Then make the move action that causes the problems in Neos and publish the changes.

After this, when you have nothing to publish in Neos, do the SQL query again.

Please let me know if there are still entries in the DB, an if some of them have values in the `moveto` column.

**Comment by markuspfeifenberger** [comment]
... that's the same we have for some of the nodes. If they don't fit perfectly, I mean, they have all the same identifier and nodepath, I think that's the problem. The nodes lose there binding, when they are moved in a way, I cannot reproduce so far ... When I make a test scenario, everything is fine and there are no "workspace moveto" entries left in the DB, I can't see in the Backend.

To be continued.
