### ISSUE TITLE
Moving document nodes back and forth breaks child nodes

### ISSUE THREAD

**Issue by nlx-lars** [neos/neos-development-collection#2284]
### Description

When moving a document node into another page and then back out, the moved page will disappear from the page tree. After publishing, it will be visible again but all child nodes are left at the old node path.

### Steps to Reproduce

1. Clone demo package
2. Move any document node into another page
3. Move the document node to it's original position in the tree

#### Expected behavior

The moved node should be at it's original position and all child nodes should still be there.

#### Actual behavior

The moved node is missing from the page tree until the change is published. After publishing, all child nodes of the moved node are not at the correct path.

See https://youtu.be/8MZIuN84Mew

### Affected Versions

Neos: 4.1.8

Flow: 5.1.4

**Comment by mficzel** [comment]
This is probably a duplicate of https://github.com/neos/neos-ui/issues/2258 which affects Neos-UI 1.3.+

**Comment by nlx-lars** [comment]
Closing since this is related to the UI.
