### ISSUE TITLE
Policy evaluation re-fetching nodes

### ISSUE THREAD

**Issue by j6s** [neos/neos-development-collection#2301]
### Description

Policies are evaluated in the `/neos/ui-services/get-policy-info` for every node and policy.

When declaring a policy that includes another node (such as `matcher: 'isDescendantNodeOf("93c96eac-4f66-41ce-a8e1-77482f5a5475")'`) the fixed node (in this case `93c96eac-4f66-41ce-a8e1-77482f5a5475`) will be fetched from the database for every subject node that is being compared.

This results in heavy performance hits for all websites that are medium sized or larger. Depending on the webserver setup (e.g. nginx timing out  after some time) the request may not even go through correctly resulting in editors not being able to edit content.

I have narrowed this down to `NodePrivilegeContext::getNodeByIdentifier` where the node is fetched from the database - explicitly resetting the upstream cache since this request is being done without authorization checks.

Adding a small cache (e.g. as static property of `NodePrivilegeContext`) resolves this issue.

In my development environment response times for the AJAX Endpoint dropped from around 200s to about 8s.

### Steps to Reproduce

1. Define a policy including `isDescendantNodeOf(...)`
2. Add a logging statement to `NodePrivilegeContext::getNodeByIdentifier`
3. Open Backend and wait for AJAX request to `/neos/ui-services/get-policy-info`
4. Watch logging output fetch the same node over and over.

#### Expected behavior

Nodes used in policies should be fetched from the database once.

#### Actual behavior

Nodes used in policies are fetched from the database for every subject (basically every node of the page).

### Affected Versions

Neos: At least 3.3.16 and higher. Have not tested lower.

**Comment by kitsunet** [comment]
Actually see https://github.com/neos/neos-development-collection/pull/2302#issuecomment-444091719 and after for why it was changed ;) So I oppose this on the same grounds 😆
