### ISSUE TITLE
Neos.Media Migration Version20181104152203 Error

### ISSUE THREAD

**Issue by yanbreu** [neos/neos-development-collection#2310]
### Description

Wrong use of `use` in [Neos.Media/Migrations/Mysql/Version20181104152203.php](https://github.com/neos/neos-development-collection/blob/master/Neos.Media/Migrations/Mysql/Version20181104152203.php)

I think [line 17](https://github.com/neos/neos-development-collection/blob/master/Neos.Media/Migrations/Mysql/Version20181104152203.php#L17) should be:
```
use Doctrine\DBAL\Migrations\AbstractMigration;
```
instead of:
```
use Doctrine\Migrations\AbstractMigration;
```

### Steps to Reproduce

1. run `./flow doctrine:migrate`

#### Expected behavior

Migrate without error

#### Actual behavior

```
Fatal error: Class 'Doctrine\Migrations\AbstractMigration' not found in /data/www/Packages/Application/Neos.Media/Migrations/Mysql/Version20181104152203.php on line 19
```

### Affected Versions

Since 04.11.2018?

**Comment by kdambekalns** [comment]
Fixed with Flow 5.2.1
