### ISSUE TITLE
Neos.Fusion:Map not existing

### ISSUE THREAD

**Issue by danielkestler** [neos/neos-development-collection#2313]
It should be "Neos.Fusion:Map", not "Neos.Fusion:Maping", right?

https://github.com/neos/neos-development-collection/blob/5db08afb57e327f32d67fe7a89f5511c4a90d61f/Neos.Fusion/Resources/Private/Fusion/Root.fusion#L39

**Comment by jonnitto** [comment]
@danielkestler After #2315 is merged, I'll release a new version, thanks for the report!

**Comment by jonnitto** [comment]
@danielkestler I've released Neos 4.2.3, thanks for the issue
