### ISSUE TITLE
Support for next gen image formats like webp 

### ISSUE THREAD

**Issue by beardcoder** [neos/neos-development-collection#2317]
### Description

Support for next gen image formats like webp and jp2 (jpeg2000)
At the moment only IE not support the webp format.
https://caniuse.com/#feat=webp

### Steps to Reproduce

1. Go to media manager
2. Upload a image with the format webp or jp2000

#### Expected behavior

I can use all image features eg. resize

#### Actual behavior

You get an error like this

```
Could not convert target type "Neos\Media\Domain\Model\Asset": Tried to refresh the dimensions and meta data of Image asset "" but the file of resource "9719132959c42c0ca0b7f03a40281e05e82d9b28" does not exist or is not a valid image.
```

**Comment by kdambekalns** [comment]
Ok, it boils down to the needed support in the underlying image processing. Flow and Neos do support webp, and with PR neos/flow-development-collection#1482 they will know that JPEG2000 is an image format.

Still, that only works, if your GD, Gmagick, Imagick or VIPS can handle those formats. In that sense it's like PDF…

One way to support webp is to use VIPS, see https://www.flownative.com/en/documentation/guides/beach/neos-cms-vips-for-faster-image-rendering.html for instructions.
