### ISSUE TITLE
When rendering thumbnails, configure target format

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#2320]
### Description

When rendering thumbnails, currently the input format is used as output format. I.e. when a WebP image is uploaded, any variant will also be a WebP image.

Sometimes it might be desired to render variants as JPG or PNG, e.g. when a larger WebP or TIFF is uploaded for later download, but previews should be viewable in any client (regardless of their ability display WebP or TIFF).

This could either be achieved by an option to pass when fetching a thumbnail for display (Fluid, Fusion, …) or by a setting that affects all created variants (of a certain type).

**Comment by daniellienert** [comment]
What? I didn't knew that we use the input as output format. But https://github.com/neos/neos-development-collection/blob/994b864f24a4cd705180889d2ceb66774576ec3e/Neos.Media/Classes/Domain/Service/ImageService.php#L115 and further down the Imagine code does just that.

Aside from the WebP case, I doubt someone really wants to have TIFF thumbnails.
I would go for the settings option, with a default to render thumbnails as jpeg and a possibility to set individual output formats, something like

```
outputFormat:
  default: 'image/jpeg'
  'image/png': 'image/png'
```

Should be easily doable in the ImageService.

**Comment by mficzel** [comment]
For WEBP a newer version of imagine (>1.0.0) is needed that includes this https://github.com/avalanche123/Imagine/pull/504

**Comment by mficzel** [comment]
I would consider it equally important to be able to control the format for each image that is created by Neos.Fusion:ImageUri , Neos.Media:ImageViewHelper or even the ThumbnailGenerator to support cases like this
```
<picture>
  <source type="image/webp" srcset="pyramid.webp"> 
  <img src="pyramid.png" alt="regular pyramid built from four equilateral triangles">
</picture>
```

**Comment by kdambekalns** [comment]
Feel free to take this, everyone…

**Comment by mficzel** [comment]
A pr for the imagine update already exists https://github.com/neos/imagine/pull/15
