### ISSUE TITLE
PostgreSQL migrations with records in asset table is broken

### ISSUE THREAD

**Issue by radmiraal** [neos/neos-development-collection#2333]
### Description

The PostgreSQL migration added in https://github.com/neos/neos-development-collection/pull/2240/files is not setting a default value, but does set the column copyrightnotice to NOT NULL. PostgreSQL requires a default value in this case.
The query should be changed to for example:

    ALTER TABLE neos_media_domain_model_asset ADD copyrightnotice TEXT NOT NULL DEFAULT ''

### Steps to Reproduce

1. Have a Neos install on 4.1 using PostgreSQL and data in the table neos_media_domain_model_asset
2. Update Neos to >=4.2.0
3. Run a doctrine:migrate

#### Expected behavior

Working migrations

#### Actual behavior

Failing migration:

    An exception occurred while executing 'ALTER TABLE neos_media_domain_model_asset ADD copyrightnotice TEXT NOT NULL':
    SQLSTATE[23502]: Not null violation: 7 ERROR:  column \"copyrightnotice\" contains null values

### Affected Versions

Neos: 4.2.0+

**Comment by daniellienert** [comment]
Hey @radmiraal, thanks for reporting, would you please have a look at the fix?
