### ISSUE TITLE
Tags not Visible

### ISSUE THREAD

**Issue by signalwerk** [neos/neos-development-collection#2350]
When I have my Media-Assets and I add a Tag I see the new tag in the List. But as soon as go to a different view, I don't see the Tag in the list anymore. 

NEOS 4.2 and NEOS 4.0

**Comment by signalwerk** [comment]
![taghandling](https://user-images.githubusercontent.com/992878/51579613-ea4dcf00-1ec1-11e9-82d6-86a4836b7ec8.gif)

**Comment by lorenzulrich** [comment]
Can't reproduce in 3.3, so must be a newer bug.

**Comment by kdambekalns** [comment]
Assigned tags are never shown… Reproducable in 5.1 at least. Probably 4.3 and up affected.

**Comment by kdambekalns** [comment]
In fact this has been broken by asset proxies… they don't have `getTags()` anymore. /cc @kitsunet & @robertlemke

**Comment by kitsunet** [comment]
`assetProxy.asset.tags` should do the trick (for native Neos assets only ofc)

**Comment by kdambekalns** [comment]
Implemented the "trick". Seems fine, since tags are only supported in the "Neos" asst source (for now.)
