### ISSUE TITLE
Make default module configurable

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#2351]
In case you've got a Neos backend user which only should see a custom module, but should not edit content. The default module is the content module and logging in without access to that module fails. 

A configuration option is needed to set another default user for this user.

**Comment by kitsunet** [comment]
Role seems difficult as you could have multiple, but I would say we should have two things, first a sensible check in the redirecter that detects if the global default is denied and maybe instead uses the first available one and secondly a user setting for default module (without UI for now) that you can maybe set via command line?

**Comment by daniellienert** [comment]
@kitsunet: Currently I have a better feeling, to configure that default module for roles and not for users. It could get tedious to configure every user separately here. 
I agree, users have many roles, so configurations could conflict, and default module could not be distinctly determined. I would rate that as a rare edge case though. And in that case I could use abstract marker roles to define the default module unambiguously.

**Comment by bwaidelich** [comment]
To recap: There's a setting `Neos.Neos.userInterface.routeAfterLogin` that could be used/extended, but I would rather deprecate that in favor of a higher level configuration.

@cvette suggested the following new configuration in https://neos-project.slack.com/archives/C04PYL8H3/p1548234597041800
```yaml
defaultModules:
  Neos.Neos:Editor:
    module: /content
    position: 2
  Some.Custom:Role:
    module: /custom
    position: 1
```
I'm not sure about the `position` part and what exactly it refers to – the precedence order of the rules (if multiple roles match)!?

But maybe it's enough just to do something like:
```yaml
defaultModules: ['content', 'management/workspaces']
```
and redirect to the first accessible upon login?
