### ISSUE TITLE
As a content editor I want to identify unused assets and remove them

### ISSUE THREAD

**Issue by klfman** [neos/neos-development-collection#2354]
Currently I can remove unused resources through the flow CLI command `media:removeunused`. It would be great to have this possibility as editor through the UI of the media browser backend module.

Related to: #819

**Comment by Sebobo** [comment]
Moved the issue into the new project

**Comment by Sebobo** [comment]
Note: The new media ui package can now do this since 0.4.0. See https://github.com/Flowpack/media-ui#fast-asset-usage-calculation--unused-assets-view
