### ISSUE TITLE
As editor I would like to upload multiple assets at once in the media browser

### ISSUE THREAD

**Issue by klfman** [neos/neos-development-collection#2355]
Currently uploading assets through the media browser backend module is only possible one by one in the media browser backend module via the "upload" button in the top left:
![screenshot 2019-01-25 at 12 11 35](https://user-images.githubusercontent.com/9661367/51742576-6dc21880-209a-11e9-9161-ecd4db98f8dd.png)

It would be great to have a UI to upload multiple (e.g. multiselect or by selecting entire folders) at once.

**Comment by klfman** [comment]
I just found out that you can already upload multiple via drag & drop. But: The tagging-feature of the single uploads through the button is not available then.

Would actually resolved with the current capabilities by resolving #1587

**Comment by Sebobo** [comment]
Yes this will be covered by https://github.com/Flowpack/media-ui/issues/8
