### ISSUE TITLE
If a Collection is selected in the media browser, the asset count of  other collections are zero

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#2358]
![image](https://user-images.githubusercontent.com/642226/51913441-c9600f00-23d6-11e9-8880-61e88f057085.png)

![image](https://user-images.githubusercontent.com/642226/51913458-d11fb380-23d6-11e9-9da0-82e8037f4628.png)

**Comment by lorenzulrich** [comment]
Can't reproduce in Neos 3.3. Which version did you use?

**Comment by kdambekalns** [comment]
From the PR it seems as if Neos 4.0 is affected…

**Comment by kdambekalns** [comment]
Fixed…
