### ISSUE TITLE
Serious performance issue resolving assets from resources, if having a table with many resources

### ISSUE THREAD

**Issue by fcool** [neos/neos-development-collection#2380]
### Description

Serious performance issue resolving assets from resources, if having a table with many resources

### Steps to Reproduce

1. Load your resources with more than 100.000 of resources
2. Call `Neos\Media\Domain\Repository\AssetRepository::findOneByResourceSha1`
3. You'll see that the following query is executed:
```sql
SELECT n0_.persistence_object_identifier AS persistence_object_identifier_0, n0_.lastmodified AS lastmodified_1, n0_.title AS title_2, n0_.caption AS caption_3, n1_.width AS width_4, n1_.height AS height_5, n0_.dtype AS dtype_6, n0_.resource AS resource_7 FROM neos_media_domain_model_image n1_ INNER JOIN neos_media_domain_model_asset n0_ ON n1_.persistence_object_identifier = n0_.persistence_object_identifier LEFT JOIN neos_flow_resourcemanagement_persistentresource n2_ ON n0_.resource = n2_.persistence_object_identifier WHERE LOWER(n2_.sha1) = '7de4b602dcf41ba9babf5e6b9e37e344bcbdd236' ORDER BY n0_.lastmodified DESC LIMIT 1;
```

#### Expected behavior

I expect the performance to be more or less independent of the number of reosources already known.

#### Actual behavior

Usage of LOWER prohibits index usage on this field, which in turn means that the execution time gets bigger and bigger with every added resource (
A possible solution would be to adopt Flow's behavior here and just don't try force case insensitivity but rely on sha1 keys to be generated and inserted lowercase. Anotherone could be to rely on a case insensitive collation for this field and index.

### Affected Versions

Neos: From the beginning ;)

**Comment by kitsunet** [comment]
Interesting, I wonder why that lower comes in there anyway. Good catch!

**Comment by kitsunet** [comment]
ohh, because query builder and case insensitive I guess...

**Comment by fcool** [comment]
Yeah. Exactly.

The problem is the `false" in here:
```php
$query->matching($query->equals('resource.sha1', $sha1, false))->setLimit(1);
```

Flow does not set this in its repositories, so until now only Neos.Media is affected

**Comment by daniellienert** [comment]
@fcool: Good catch indeed! 
@kitsunet: Found the commit that introduced it ;) https://github.com/neos/neos-development-collection/commit/350f5f1dce4fc5e0906119d981b5b4e51eb30be5 

The method makes no sense to me at all. I would suggest to remove it (and maybe annotate its existence in the header comment) and use the default magic method.

**Comment by fcool** [comment]
If I understand this correctly the magic method won't work. It searches for a property of a related object. `resource.sha1` not its own `sha1`

**Comment by daniellienert** [comment]
@fcool: Correct

**Comment by daniellienert** [comment]
@fcool: Would you take care of a PR against 3.3 that changes it?

**Comment by fcool** [comment]
I'll love to!

**Comment by fcool** [comment]
Pull-Request arrived:
#2383

**Comment by Sebobo** [comment]
I assume this can be closed as the PR was merged.
