### ISSUE TITLE
BUG: FlowQuery doesn't respect hidden parents

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#2392]
**I've created a repo with this issue to reproduce this bug: https://github.com/jonnitto/Neos.Issues**

If a FlowQuey is written with `find()`, hidden parents will not be respected. This can lead to links to not available pages.

![in backend](https://user-images.githubusercontent.com/4510166/54028083-0d97b980-41a4-11e9-999c-a2dd14f202d7.png)
![live](https://user-images.githubusercontent.com/4510166/54027900-6f0b5880-41a3-11e9-939f-1f4321cefc1f.png)

**Comment by johannessteu** [comment]
Hm, what about your context nodes context? These are possible values and there defaults:
```
 $defaultContextProperties = [
            'workspaceName' => 'live',
            'currentDateTime' => $this->now,
            'dimensions' => [],
            'targetDimensions' => [],
            'invisibleContentShown' => false,
            'removedContentShown' => false,
            'inaccessibleContentShown' => false
        ];
```

guess invisibleContentShown may be the one you're interested in?

**Comment by jonnitto** [comment]
The default is to set  `false`, and so it shouldn't be accessible in the frontend. I know this might be breaky in some installations, but I expect that I only get the nodes who are accessible for me in my context.

**Comment by jobee** [comment]
@jonnitto as a workaround I use an extra FlowQuery operation to filter by parents visibility. I try to use it only if necessary, cause it might adds a ton of loops (depending on your node tree).

https://gist.github.com/jobee/60f2c8de7b5e2de8e5a462fba83075c6

**Comment by mhsdesign** [comment]
I can confirm this when using `$context->getNodeByIdentifier($identifier)` or flowquerys find operation: `FlowQuery::q([$context->getCurrentSiteNode()])->find('[instanceof Neos.Neos:Document]')->get()`.

In my case i used a slight derivation but basically the same helper:
```php
private function findIsNodeVisible(Node $node): bool
{
    do {
        $previousNode = $node;
        $node = $node->getParent();
        if ($node === null) {
            if ($previousNode->isRoot()) {
                return true;
            }
            return false;
        }
    } while (true);
}
```

i was told that this wont be happening with the new ESCR in neos 9
