### ISSUE TITLE
Neos.Neos:ConvertUris destroys `<article>`-Tags

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-development-collection#2395]
More specifically:
https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php#L119

This regex clearly mistakes `<article>`-Tags for `<a>`-Tags, even if there's no `href`-Attribute present. So any markup that is processed by this method will be left with destroyed `<article>`-Tags.

**Comment by kitsunet** [comment]
Ouch!

**Comment by KommunikativCh** [comment]
I try to solve this issue and can't se how this regex mistake can happen because it needs a </a> at the end.
can somebody give me a test case thanks

**Comment by KommunikativCh** [comment]
I have now a test case
Input: <article href="asset://xxxxx"><a href="node://xxxx"></a></article>
output: <a href="node://xxxx"></article>

**Comment by KommunikativCh** [comment]
sorry 
Input:
`<article href="asset://xxxxx"><a href="node://xxxx">xxxx</a></article>`
output:
`<a href="node://xxxx">xxxx</article>`

**Comment by KommunikativCh** [comment]
there is another issue with the regex in the replaceLinkTargets function 
input: `<article> <a href="xx"></a></article>`
output: `<a target="_target_"rticle> <a target="_target_" href="xx"> </article>`
I think this is the main problem with this issue

**Comment by KommunikativCh** [comment]
the issue in replaceLinkTargets function was already fixed in 4.2 release on 5 Nov 2018
i do now a pull request for 3.3 release
