### ISSUE TITLE
Call to undefined method Neos\Flow\Http\Response::setRedirectUri()

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#2437]
### Description

If you try to create a tag or a collection in the media module, it fails with the exception `Call to undefined method Neos\Flow\Http\Response::setRedirectUri()`

### Steps to Reproduce

1. Go to the media module
2. Create a tag or a collection

### Affected Versions

Neos: 4.3-dev

Flow: 5.3-dev

**Comment by mficzel** [comment]
@kitsunet is it possible that this is caused by the PSR changes.

**Comment by kitsunet** [comment]
Also relevant: https://github.com/neos/flow-development-collection/pull/1540

**Comment by kitsunet** [comment]
Both PRs should alone fix the bug. Both are good ot have though.

**Comment by mficzel** [comment]
This is now solved twice with both prs

**Comment by jonnitto** [comment]
Yep. Tested it and now it works! ❤️
