### ISSUE TITLE
Package kickstarter breaks when listing repos as array in composer manifest

### ISSUE THREAD

**Issue by gerhard-boden** [neos/neos-development-collection#2448]
### Description

The package (and site package) kickstarter breaks if the repositories are listed in the following form:
```
    "repositories": [
        {
            "type": "path",
            "url": "DistributionPackages/*"
        },
        {
            "type": "composer",
            "url": "https://repo.packagist.com/gesagtgetan/"
        },
        {
            "packagist.org": false
        }
    ]
```

this however still works:

```
    "repositories": {
        "DistributionPackages": {
            "type": "path",
            "url": "DistributionPackages/*"
        },
        "composer": {
            "type": "composer",
            "url": "https://repo.packagist.com/gesagtgetan/"
        },
        "packagist.org": false
    }
```

The latter form for listing composer repos is discouraged as stated in the composer documentation:
https://getcomposer.org/doc/04-schema.md#repositories

> Using JSON object notation is also possible. However, JSON key/value pairs are to be considered unordered so consistent behaviour cannot be guaranteed.

### Steps to Reproduce

1. list repositories in array format like in the example above
2. type `./flow kickstart:package` in the console and try to create a package

#### Expected behavior

New package is created

#### Actual behavior

`Notice: Undefined index: type in /var/www/lombagine.vm/Packages/Framework/Neos.Flow/Classes/Package/PackageManager.php line 348`

### Affected Versions

Neos: 4.2

Flow:  5.2

**Comment by mficzel** [comment]
This actually breaking in the package:create command inside flow. So this issue should go there.

**Comment by gerhard-boden** [comment]
right, site package is just utilizing the same functionality

**Comment by mficzel** [comment]
@gerhard-boden can you try this one https://github.com/neos/flow-development-collection/pull/1549
