### ISSUE TITLE
Breaking FlowQuery behaviour since 4.3 

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#2459]
### Description

Since Neos 4.3 FlowQuery walks up till the root of all nodes. Before (till 4.2) it stops at the site node.

### Steps to Reproduce

* Output somewhere the FlowQuery `q(site).parents().count()` on your page
* On Neos 4.2.x you will get the integer `0`
* On Neos 4.3 you will get the integer `2`

#### Expected behavior

Flow Query stops at the root site level

#### Actual behavior

Flow Query walks up till the root of all nodes

### Affected Versions

Neos: 4.3  
Flow: 5.3

**Comment by gerhard-boden** [comment]
I'm surprised that this never failed: 
https://github.com/neos/neos-development-collection/blob/4.3/Neos.Neos/Tests/Unit/FlowQueryOperations/ParentsOperationTest.php

**Comment by mficzel** [comment]
The test expects the site node to throw an exception if it tries to access the root-node. Which makes the code work but is not what the current cr actually does and also not what the flowQuery really expects. https://github.com/neos/neos-development-collection/blob/4.3/Neos.Neos/Tests/Unit/FlowQueryOperations/ParentsOperationTest.php#L38
