### ISSUE TITLE
Assigned asset collections cannot be unassigned

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#2473]
### Description

If an asset is assigned to one or more collections, the collections cannot be unassigned anymore.

### Steps to Reproduce

1. Create a collection
2. Assign an asset
3. Open the asset in the single view
4. Uncheck the checkbox
5. Save

#### Expected behavior

The asset is unassigned

#### Actual behavior

When opening the asset again, it is still assigned.

### Affected Versions

Neos: master
Flow: master

**Comment by mficzel** [comment]
I can confirm this problem for all Neos versions back to 4.0 in 3.3 it still works as expected.
