### ISSUE TITLE
Fix phpunit deprecation warnings

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#2498]
With the change to phpunit 8, some deprecation warnings are thrown - they should be easily fixable. See: https://travis-ci.org/neos/neos-development-collection/jobs/531834349

**Comment by theDex** [comment]
I think there are no alternatives for these functions, because phpunit want's us to not test non-public attributes. https://github.com/sebastianbergmann/phpunit/issues/3339

**Comment by daniellienert** [comment]
@theDex, ah thanks for digging into it. Se we could replace 
```
$this->assertAttributeNotContains($object, 'changedObjects', $persistenceManager);
```
with
```
Assert::assertNotContains($object, ObjectAccess::getProperty($persistenceManager, 'changedObjects'));
```

**Comment by theDex** [comment]
PR created in flow-development-collection
https://github.com/neos/flow-development-collection/pull/1581
