### ISSUE TITLE
neos/nodetypes 4.3.1 was not published to packagist

### ISSUE THREAD

**Issue by baschny** [neos/neos-development-collection#2508]
### Description

Any project (i.e. the official neos-base-distribution) having in `composer.json`:
```
        "neos/nodetypes": "~4.3.0",
```

will not be upgrading to Neos 4.3.1 because the "4.3.1" version of neos/nodetypes was not published to packagist.org.

https://github.com/neos/neos-nodetypes/releases/tag/4.3.1 => tag is there
https://packagist.org/packages/neos/nodetypes => tag is missing

### Steps to Reproduce

* Setup a project with https://github.com/neos/neos-base-distribution
* Wonder why you are not getting 4.3.1, but `composer update` keeps 4.3.0.

#### Expected behavior

* `composer update` should update my Neos to 4.3.1.

#### Solution

Best: Make sure github publishes the release to packagist. 

Workaround, add this to main `composer.json` to circumvent packagist for this particular package:
```
    "repositories": {
        "neos-nodetypes": {
            "type": "git",
            "url": "https://github.com/neos/neos-nodetypes.git"
        }
    },
``` 

#### Long term

If the neos/nodetypes is "deprecated" or not recommended anymore (and will maybe even be removed in 5.0?) it should be documented somewhere, as it currently seems to be the "way to go" still. And maybe add some hints about it in the Best Practice?

**Comment by baschny** [comment]
@kdambekalns @johannessteu - see also thread in Slack about it. Who is responsible for the "packagist.org" pushing and is able to re-push the missing tag there?

**Comment by kitsunet** [comment]
Seems the update trigger did no run, I did it manually now.

**Comment by daniellienert** [comment]
Fixed in the meantime -> https://packagist.org/packages/neos/nodetypes
