### ISSUE TITLE
Moving nodes between content collections makes them disappear in the UI

### ISSUE THREAD

**Issue by klfman** [neos/neos-development-collection#2520]
### Description

When moving content nodes between content collections they suddenly disappear after a few moves. 
When it happens, the following stacktrace is printed on the console: [stacktrace.txt](https://github.com/neos/neos-development-collection/files/3201743/stacktrace.txt).
The backend did not log any exceptions in Data/Logs/Exceptions.

Refreshing the page does not bring the node back. Publishing or discarding, however, does, so the node is just visually gone, content repository seems fine.

When asking in slack about this I was asked about redirecthandler package versions as there seems to be a known bug with moved pages, which seems unrelated. I pasted them to the affected versions, just in case.

I'll happily reproduce this bug together with someone if it helps.

**Update**: When experimenting around some more, I realised that after a few moves when content disappears I also get an exception which is rendered in a red popup box in the backend. This is the log from Data/Logs/Exceptions: [Exception.txt](https://github.com/neos/neos-development-collection/files/3276285/Exception.txt)

### Steps to Reproduce

~I cannot tell under which circumstances it happens, it feels random to me. Generally after a few moves of content between content collections.~

**Update**: It can be reproduced by moving a node from one of the content collections to another and then back to the original one.

#### Expected behavior

Nodes should not disappear.

#### Actual behavior

![disappearing nodes](https://user-images.githubusercontent.com/9661367/58084167-af7f4d80-7bba-11e9-8166-e0f3ed4f624f.gif)

### Affected Versions

The two versions I can confirm this problem with
Neos: 4.2.9; 4.3.0
Flow: 5.2.4; 5.3.0
Neos-UI: 3.3.0

neos/redirecthandler 2.0.1
neos/redirecthandler-databasestorage 3.0.0
neos/redirecthandler-neosadapter 3.0.0

**Comment by kitsunet** [comment]
The stacktrace seems to indicate this belongs to the https://github.com/neos/neos-ui repository but that reloading doesn't bring it back could indicate a problem here. Are you sure this isn't a (trivial) cache configuration problem?

**Comment by skurfuerst** [comment]
Just checked the issue; it is definitely not a caching problem.

I think we have to check the instance itself; as moving nodes generally seems to work well (in other instances).

All the best, Sebastian

**Comment by skurfuerst** [comment]
I've tracked this down.

## ORIGINAL SITUATION:

/column1/a
/column2/a

## Then, move /column1/a into /column2

-> Result:
/column2/a
/column2/a-renamed (THIS IS RENAMED from /column1/a)

Additionally, there still exists a /column1/a line with "deleted=1".

Now, when moving back, somehow both the deleted line stays, and the other one as well - both with a different node name... (TODO EXPLAIN THIS FURTHER).

## FIX for us

we could simply rename all auto-generated node names.

## Related Issues

- https://github.com/neos/neos-ui/pull/2078
- https://github.com/neos/neos-development-collection/issues/2089
- https://github.com/neos/neos-ui/pull/2098
- https://github.com/neos/neos-development-collection/pull/2161

**Comment by davidspiola** [comment]
Hi Folks, is this issue still open or is it fix with #2161 ?

**Comment by klfman** [comment]
It's fixed for me

**Comment by skurfuerst** [comment]
@davidspiola FYI https://gist.github.com/skurfuerst/beb644cc81af76eca7a321bb00dc07ee this is the command controller which we used for rewriting our (broken) content :)
