### ISSUE TITLE
BUG: Umlauts disappearing from menu

### ISSUE THREAD

**Issue by PascalFolleher** [neos/neos-development-collection#2591]
### Description
We recently discovered that umlauts are disappearing from menu items. Umlauts still appear in other places on the page. Also the backend ui properly shows page titles containing umlauts. The used Neos version is 4.3.3. The projects are hosted on AWS with an Apache webserver. We suspect that the issue (or at least a part of the issue) might lie with `Neos.Neos:MenuItems`.

Screenshot how a menu item with umlauts is rendered.
![Menu](https://user-images.githubusercontent.com/44175317/60655049-64a95480-9e4d-11e9-831d-76f41ffaa9c5.png)
Screenshot of a breadcrumb for the same page
![Breadcrumb](https://user-images.githubusercontent.com/44175317/60655091-725eda00-9e4d-11e9-8c44-2526e7e4ae49.png)
Screenshot of the backend ui, showing the expected umlauts are part of the title
![Backend-UI](https://user-images.githubusercontent.com/44175317/60655113-7f7bc900-9e4d-11e9-86a8-251d779dfe85.png)

Details on the server:
Contains information on php version and modules, operating system, cpu, the used neos packages, the apache version and modules.

[serverinfo.txt](https://github.com/neos/neos-development-collection/files/3358724/serverinfo.txt)

### Steps to Reproduce

1. Create a page or change a page's title so that the title contains umlauts

#### Expected behavior

Proper rendering of strings containing umlauts.

#### Actual behavior

Umlauts get replaced with spaces.

### Affected Versions

Neos: 4.3.2, 4.3.3

Flow: 5.3.2

If you can provide us with some pointers where to start with debugging we'd like to take a shot at fixing this issue ourselfs.

**Comment by MarcoPNS** [comment]
I can't reproduce this issue. Everything works fine on my site with the same php version, same neos and Flow version. What is the format of your database?

**Comment by dlubitz** [comment]
Same here. Works fine for me in the given versions. As @kitsunet already stated out on Slack, it looks more like an issue with a external library. Could you share the used composer packages?

**Comment by akappler** [comment]
We found the issue. The problem is that the current Amazon Elastic Beanstalk Image (PHP 7.2 on 64bit Amazon Linux/2.8.12) has PCRE 8.21-7.8.amzn1 included. This version is not working for umlaute together with this bug fix for node labels: https://github.com/neos/neos-development-collection/pull/2524

To solve this issue, you have to use a newer PCRE version. We tried for CentOS 8.32 - where we don't have to recompile our self - and the issue was gone. 

Probably something to write in the minimum requirements doc?

**Comment by albe** [comment]
For the record, PCRE 8.21 is from 2011:
https://www.pcre.org/original/changelog.txt

We could add `lib-pcre`: `>=8.32` to our composer dependencies though?
https://stackoverflow.com/questions/20999187/composer-not-working-when-going-from-windows-to-centos
