### ISSUE TITLE
Neos requires Neos.Setup package

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#2618]
### Description

Currently the `neos/setup` package can't be uninstalled because `neos/neos` depends on it.

Reson for this hard dependency are the [Step-implementations](https://github.com/neos/neos-development-collection/tree/master/Neos.Neos/Classes/Setup/Step) that break the proxy building if the corresponding base classes can't be found.

**Comment by bwaidelich** [comment]
Maybe this can be solved by adding a `@Flow\Proxy(false)` annotation to the Step-classes. If that doesn't work they have to be moved to a separate package probably

**Comment by bwaidelich** [comment]
> Maybe this can be solved by adding a @Flow\Proxy(false) annotation to the Step-classes

I just gave it a shot and it won't work and results in a

    Required class "Neos\Neos\Setup\Step\AdministratorStep" could not be loaded properly for reflection.

exception during compilation.

A separate package (maybe `Neos.Neos.Setup`?) with the step implementations and configuration should work though

**Comment by kitsunet** [comment]
I am somewhat sure we should have a ticket about this somewhere. And yes, a separate package would be the only way to solve this, unless we somehow change the way steps interact with the package (probably difficult as you want at least some interface to contract to).

**Comment by bwaidelich** [comment]
> I am somewhat sure we should have a ticket about this somewhere
I thought so too, but couldn't find it?

**Comment by KovalVV** [comment]
When I was discussing fixing the issue just for myself at https://discuss.neos.io/t/is-it-possible-to-disable-or-hide-neos-setup-in-a-friendly-reversible-manner/4442 , I was thinking about forced rerouting of \<website\>/setup to \<website\>/neos or just to \<website\>/ .

As long as is \<website\>/setup cannot be accessed, I don't really care about the package itself.

Is my way simpler and/or possible at all? :-)

**Comment by bwaidelich** [comment]
@KovalVV you can of course change your server setup to redirect `/setup` but it won't work with the Flow Routing configuration because the `/setup` route is triggered via a custom RequestHandler (see https://github.com/neos/setup/blob/master/Classes/Core/RequestHandler.php#L42).

As work around for this, we could introduce some flag `Neos.Setup.enable` to the `Settings.yaml` but I'd prefer to make this package uninstallable
