### ISSUE TITLE
Uploading an asset in the Neos Backend module leads to an exception

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#2668]
### Description
1. Upload an image in the backend

#### Expected behavior

Image gets uploaded :)

#### Actual behavior

Exception: 

![image](https://user-images.githubusercontent.com/642226/64060014-20290380-cbc7-11e9-8b78-fe940caa7b29.png)

### Affected Versions

Neos: master / 5.0

**Comment by kitsunet** [comment]
This is... interesting, because that part shouldn't have changed. I geuss before that happened in property mapping only...

**Comment by albe** [comment]
Should be handled by the ResourceTypeConverter... is this missing a mapping to type `resource` somewhere?

**Comment by kitsunet** [comment]
solved with fix in neos
