### ISSUE TITLE
Renaming tag in media browser leads to 404-page

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-development-collection#2678]
Renaming a tag in the media browser results in a 404 error

1. Open media browser
2. create a tag
3. edit the tag
4. save
5. 404 page

I'd expect a tag to be edited if I edit it.

Testing Neos 5.0

**Comment by maya-shines** [comment]
Update: editing collections in the media browser results in 404 errors aswell

**Comment by kdambekalns** [comment]
Old news: https://github.com/neos/neos-development-collection/pull/2674 🙃
