### ISSUE TITLE
Main menu looses state when a module is clicked

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#2682]
## How to reproduce

![MenuLoosesState](https://user-images.githubusercontent.com/642226/64249209-7376bb00-cf13-11e9-8b26-07ed93cfdaa8.gif)
 
## Affects 

dev/maser / 6.0

**Comment by markusguenther** [comment]
Tried this now with some Browsers on Mac but could not reproduce that.
* Brave
* Chrome
* Firefox
* Safari
* Vivaldi

Hope that we can find it :/

**Comment by Sebobo** [comment]
Can confirm. Seems the content module and all others store their own state.

**Comment by markusguenther** [comment]
Hi there now I understand you guys :)

The problem ist that the React UI saves the states in the LocalStorage under persistedState.
I created my own little state management for the menu and put that into the session.

So to solve that I need to use the same persistence.

**Comment by markusguenther** [comment]
I am on it and adjust the session handling to the existing storage handling.

**Comment by markusguenther** [comment]
Sorry guys did not get that you switched between the content module and the other modules.
Fixed it now and it works on my machine :P
