### ISSUE TITLE
Dropdowns in Firefox look different

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-development-collection#2689]
### Description

In the firefox (68) the dropdown will be rendered in a "ugly" way. That happens in the non react-ui modules. For instance in the user module when you edit a user.

The UI is also broken in the 4.3 Neos.

### Steps to Reproduce

1. Open user module
2. Edit a user
3. Language drop down looks ugly

#### Expected behavior

Looks like in Chrome or other browsers

#### Actual behavior

![broken-dropdown-firefox](https://user-images.githubusercontent.com/1014126/64283187-3af8d080-cf57-11e9-8185-c6b8104b67f6.gif)

### Affected Versions

Neos:  minimal version 4.3

**Comment by mhsdesign** [comment]
cant reproduce on fx 110.0 macos neos 8.3


![image](https://user-images.githubusercontent.com/85400359/230043872-151fedf1-15f5-4986-a400-8ee16b08681c.png)
