### ISSUE TITLE
Update of doctrine/orm 2.6.4 breaks neos

### ISSUE THREAD

**Issue by obi12341** [neos/neos-development-collection#2710]
### Description

After upgrading the package doctrine/orm from 2.6.3 to 2.6.4 neos breaks with the following error:
Catchable Fatal Error: Object of class Neos\ContentRepository\Domain\Model\Workspace could not be converted to string in /home/vagrant/mobi/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php line 77

### Steps to Reproduce

1. update doctrine/orm from 2.6.3 to 2.6.4

#### Expected behavior

Not to break :P

#### Actual behavior

it broke :(

### Affected Versions

Neos: 4.3.4

Flow: 5.3.4

**Comment by jonnitto** [comment]
This is related to https://github.com/doctrine/orm/issues/7827 and solved with #2709

**Comment by jonnitto** [comment]
Soon, there will a new release with this fix. Thank you for your report.

Closing this now, as it is fixed in master
