### ISSUE TITLE
Old namespace for aloha editor in Neos 5.0 text mixin

### ISSUE THREAD

**Issue by akappler** [neos/neos-development-collection#2718]
### Description

In Neos 5.0 the inline aloha editor is not available anymore and is replaced by CK5 editor. The namespace/id for the placeholder text of the text element however has the old aloha namespace/id.

### Steps to Reproduce

1. Add a new text element

#### Expected behavior

Show (translated) placeholder text from translation file

#### Actual behavior

Shows the namespace/id 

Neos: 5.0

**Comment by davidspiola** [comment]
Hi Alexander, are you planning to do a merge request for that? Or is there already one and I can't find it :-)

**Comment by davidspiola** [comment]
found it #2719
