### ISSUE TITLE
countAll() on repository extending AssetRepository returns wrong count

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#2724]
### Description

When using a repository that extends from `AssetRepository` the use of `countAll()` leads to unexpected results.

### Steps to Reproduce

1. Have two images and two PDF documents uploaded
2. use `countAll()` on the `ImageRepository`

#### Expected behavior

The count should be 2.

#### Actual behavior

The count is 4.

### Affected Versions

Neos: 2.0.5 and later (as of PR #230)

**Comment by kdambekalns** [comment]
So far the "solution" would be to overwrite the method in the extending repository.

I have a different solution, but… is this a bugfix that should go into Neos 3.3, or do we put it into 4.3 (as the "almost current" LTS), or 5.0 or just master?

Could it be breaking for someone, because suddenly the count is correct?

**Comment by mficzel** [comment]
I think this is a clear bug and should be fixed in 3.3. It is easy to determine that for anyone that this is buggy so i would expect anyone running into this reporting the bug and not building on it. 

Even harder is to imagine how anyone may have built something useful out of this behavior.

**Comment by albe** [comment]
What ☝️ said

**Comment by kdambekalns** [comment]
Thanks–I marked the PR agains 3.3 as "ready for review" now.
