### ISSUE TITLE
ContentCacheFlusher: wrong usage of systemLogger(Too few arguments)

### ISSUE THREAD

**Issue by mwitte** [neos/neos-development-collection#2744]
### Description
Exception: Too few arguments to function Neos\Flow\Log\Psr\Logger::log(), 1 passed and at least 2 expected

https://github.com/neos/neos/blob/6579bd3c34a9fbb3031642db8d3681b7fa671391/Classes/Fusion/Cache/ContentCacheFlusher.php#L290

### Steps to Reproduce
Not sure how to exactly reproduce, because this a case should not happen, but if it does, this throws an exception

#### Expected behavior

Logging should work

#### Actual behavior

Exception
Exception: Too few arguments to function Neos\Flow\Log\Psr\Logger::log(), 1 passed and at least 2 expected

### Affected Versions

Neos: 
4.3.x - current

**Comment by daniellienert** [comment]
Hey @mwitte, thanks for reporting that issue.
