### ISSUE TITLE
$this->redirectToUri with delay = 0 fails

### ISSUE THREAD

**Issue by mkuiphuis** [neos/neos-development-collection#2752]
### Description

Whilst using a plugin on a Neos page and wanting to call $this->redirectToUri with a delay of 0 (which IIRC uses the new HTTP PSR-7 functionality instead of a <html meta-refresh>) the redirect does not happen. Most likely it looks like the plugin cannot change the outer response.
https://neos-project.slack.com/archives/C04V4C6B0/p1570635110017800

### Steps to Reproduce

1. Have a plugin with 2 actions
2. The first action should display a link which calls the 2nd action
2. Inside the 2nd action place a redirect to the first action

#### Expected behavior

I expected the page to redirect to the URI :-)

#### Actual behavior

No redirect was happening. I.e. on some of my sites we have a frontend login form. Upon successful login, I would have expected to see the page I wanted to redirect to, instead the same page is being shown, but now without the login form.

### Affected Versions

This has started with the latest versions of Neos and Flow as it looks like a PSR-7 issue that was introduced with Flow 6.0
Neos: 5.0.X
Flow: 6.0.X

**Comment by Nikdro** [comment]
**Hacky workaround:** Adding a minimal delay (second parameter of redirectToUri). Then another redirect-method is used and it works.  
`$this->redirectToUri($uri, 1);`

**Comment by Nikdro** [comment]
Any news on this? It's a very annoying bug and we rely on it very often.

**Comment by jonnitto** [comment]
The bugfixes https://github.com/neos/neos-development-collection/pull/2777 and https://github.com/neos/flow-development-collection/pull/1850 are already merged. So this will be in the next release

**Comment by Nikdro** [comment]
Ah cool, thanks for the hint!
