### ISSUE TITLE
BUG: Cant render Fluid Templates with PHP 7.3.11

### ISSUE THREAD

**Issue by breadlesscode** [neos/neos-development-collection#2776]
### Description

If I open one of the Fluid-based Backend Modules with PHP 7.3.11 it fails with an exception.

> The argument "arguments" was registered with type "array", but is of type "string" in view helper "Neos\FluidAdaptor\ViewHelpers\Uri\ActionViewHelper".

### Steps to Reproduce

1. Use PHP 7.3.11
2. Visit a backend module

#### Expected behavior

I can use a backend module

#### Actual behavior

Fails with the following exception: 

```
The argument "arguments" was registered with type "array", but is of type "string" in view helper "Neos\FluidAdaptor\ViewHelpers\Uri\ActionViewHelper".

Exception Code | 1256475113
InvalidArgumentException
Packages/Libraries/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php
356
```

### Affected Versions

Neos: 5.0.4

Flow: 6.0.5

**Comment by jonnitto** [comment]
Has this something to do with https://github.com/TYPO3/Fluid/issues/449#issuecomment-551049248?

**Comment by dlubitz** [comment]
Looks like that.

**Comment by kdambekalns** [comment]
Also see https://discuss.neos.io/t/frisches-neos-4-3-mit-demo-package-exception-im-hauptmenu/4334

**Comment by radmiraal** [comment]
just running into this after having the same issue with TYPO3 v9 for a while, in TYPO3 it's fixed by adding quotes to the arguments (see https://review.typo3.org/c/Packages/TYPO3.CMS/+/62450)

**Comment by dlubitz** [comment]
A fix of fluid has been released. Please check if this solves your issue and close the ticket.
https://github.com/TYPO3/Fluid/pull/493#issuecomment-581378186

**Comment by radmiraal** [comment]
close is valid, bug is indeed solved in upstream fluid
