### ISSUE TITLE
bug: re-login glitch

### ISSUE THREAD

**Issue by creative-resort** [neos/neos-development-collection#2780]
### Description

The re-login form is re-loaded in an endless loop

### Steps to Reproduce

1. Log in to a demo site and click on a page, e.g. "Features" in In-Place Edit Mode
2. Let the session's login duration expire.
3. In the navigation tree, click on a different page (e.g. "Shortcuts"), so a re-login is initiated.

#### Expected behavior

Normal re-login screen.

#### Actual behavior

Here is a video of how the re-login form keeps being reloaded in a loop:

![neos login error](https://user-images.githubusercontent.com/12367437/69498750-aa91b280-0eeb-11ea-989b-5281452b35d1.gif)

As the form is constantly re-loaded, logging in is impossible.
Only after canceling the page loading via browser button "cancel", the reloading stops.

### Affected Versions

Neos: 5.0.4
Flow: 6.0.5

PHP 7.3

Browser: latest Google Chrome Browser

**Comment by davidspiola** [comment]
Hi, can you provide js console output or php error logs?

**Comment by creative-resort** [comment]
JS Console:
![2019-11-24_204941](https://user-images.githubusercontent.com/12367437/69500501-03694700-0efc-11ea-94e4-857254660224.png)

**Comment by markusguenther** [comment]
@creative-resort 
Hmm can remember an issue in the neos-ui that lead to an infinite loop. But that was solved at some point. Which UI version you are using?

**Comment by markusguenther** [comment]
Ok can reproduce it.
Thanks for reporting @creative-resort ❤️ 

Created an issue in the neos-ui for that https://github.com/neos/neos-ui/issues/2590
