### ISSUE TITLE
proposal: higher neos-label contrast

### ISSUE THREAD

**Issue by creative-resort** [neos/neos-development-collection#2782]
### Description

Let's improve the legibility of label text in the backend.

### Steps to Reproduce

1. Open the Neos Packages administration page

#### improved existing style without too drastic changes:

![2019-11-26_222436](https://user-images.githubusercontent.com/12367437/69674814-94c3ef00-109d-11ea-8877-774e47621a25.png)

#### current, hard to read text:
![2019-11-26_222405](https://user-images.githubusercontent.com/12367437/69674843-a3aaa180-109d-11ea-8d2a-65cc7b30bf6e.png)

### Affected Versions

Neos: 5.0.4

used CSS:
`.neos.neos-module table.neos-table .neos-label {
    background-color: #444;
    box-shadow: #2d2d2d 0px 0px 10px 5px;
    font-weight: normal;
    letter-spacing: .05em;
    padding: 2px .5em;
}`

**Comment by markusguenther** [comment]
@creative-resort Thanks for your suggestion. I created a little PR so that everybody can test it.

**Comment by creative-resort** [comment]
Be sure to check if the selector `.neos .neos-label` is maybe more appropriate, as seen in the following cascade - or if the specificity of the table is context is ok:

![2019-11-27_222711](https://user-images.githubusercontent.com/12367437/69760635-542fa880-1165-11ea-8bf3-998850ec9fa1.png)

Also, this style seems to be used in various other places. Let's also check if it looks good everywhere.
