### ISSUE TITLE
BUG: Browser back function in Backendmodules

### ISSUE THREAD

**Issue by breadlesscode** [neos/neos-development-collection#2791]
### Description

I’m not sure if this is the right place for it, but me and @sebobo discovered a bug in the Neos Backend modules. If you visit a backend module one XHR is sent out, if you then click on a subpage of the module and afterwards use the browser’s back button, you get the unparsed markup. This only happens with the Redirect Handler UI (as far as we can tell).

See here:  https://github.com/neos/redirecthandler-ui/issues/41

### Steps to Reproduce

1. Visit redirect handler ui backend module
2. Click export redirects
3. Click browsers back button
4. Unparsed markup shown

#### Expected behavior

Unparsed markup shown

#### Actual behavior

See the backend module

### Affected Versions

Neos: 5.0.4
Neos Ui: 5.0.1
Flow: 6.0.5

**Comment by Sebobo** [comment]
Important note: The XHR is sent in every backend module with Neos 5, but only the redirect module with it's actions seems to trigger the issue.

**Comment by Sebobo** [comment]
Found out where the second request comes from. During the partial ember removal the endpoint url for the `neos-nodetypeschema` was removed and the backend still tries to load it. If no url is defined it will use the current url.
Adding the missing line again will solve the issue.

But we actually don't need the schema for backendmodules. So it would be better if our backend wouldn't try to load the schema if it's not defined.

@markusguenther maybe you can look into this?
