### ISSUE TITLE
Strict typing in ImageAdjustments causes issues with some Neos installations

### ISSUE THREAD

**Issue by nezaniel** [neos/neos-development-collection#2811]
In certain Neos installations, especially those who have been migrated from earlier versions, nodes may still use images with adjustments having a rather sparsely populated property set. Especially ResizeImageAdjustment's ratioMode property can be null, which conflicts with the newly introduced strict string return type.

This affects Neos.Media 4.3.7 and most probably 5.0.4 as well.

The relevant part of the stack trace would be
Exception in line 141 of /path-to-project/Packages/Libraries/neos/utility-objecthandling/Classes/ObjectAccess.php: Return value of Neos\Media\Domain\Model\Adjustment\ResizeImageAdjustment_Original::getRatioMode() must be of the type string, null returned

131 Neos\Media\Domain\Model\Adjustment\ResizeImageAdjustment_Original::getRatioMode()
130 Neos\Utility\ObjectAccess::getPropertyInternal(Neos\Media\Domain\Model\Adjustment\ResizeImageAdjustment, "ratioMode", false, true)
129 Neos\Utility\ObjectAccess::getGettableProperties(Neos\Media\Domain\Model\Adjustment\ResizeImageAdjustment)
128 Neos\Media\TypeConverter\ImageInterfaceArrayPresenter_Original::convertFrom(Neos\Flow\Persistence\Doctrine\Proxies\__CG__\Neos\Media\Domain\Model\ImageVariant
, "array", array|0|, Neos\Flow\Property\PropertyMappingConfiguration)
127 Neos\Neos\Ui\TypeConverter\UiDependentImageSerializer_Original::convertFrom(Neos\Flow\Persistence\Doctrine\Proxies\__CG__\Neos\Media\Domain\Model\ImageVariant
, "array", array|0|, Neos\Flow\Property\PropertyMappingConfiguration)
126 Neos\Flow\Property\PropertyMapper_Original::doMapping(Neos\Flow\Persistence\Doctrine\Proxies\__CG__\Neos\Media\Domain\Model\ImageVariant, "array", Neos\Flow\P
roperty\PropertyMappingConfiguration, array|0|)
125 Neos\Flow\Property\PropertyMapper_Original::convert(Neos\Flow\Persistence\Doctrine\Proxies\__CG__\Neos\Media\Domain\Model\ImageVariant, "array", Neos\Flow\Pro
perty\PropertyMappingConfiguration)
124 Neos\Neos\Service\Mapping\NodePropertyConverterService_Original::convertValue(Neos\Flow\Persistence\Doctrine\Proxies\__CG__\Neos\Media\Domain\Model\ImageVaria
nt, "Neos\Media\Domain\Model\ImageInterface")
123 Neos\Neos\Service\Mapping\NodePropertyConverterService_Original::getProperty(Neos\ContentRepository\Domain\Model\Node, "image")
122 Neos\Neos\Service\Mapping\NodePropertyConverterService_Original::getPropertiesArray(Neos\ContentRepository\Domain\Model\Node)
121 Neos\Neos\Ui\Fusion\Helper\NodeInfoHelper_Original::renderNodeWithPropertiesAndChildrenInformation(Neos\ContentRepository\Domain\Model\Node, Neos\Flow\Mvc\Con
troller\ControllerContext)
120 Neos\Neos\Ui\Aspects\AugmentationAspect_Original::contentElementAugmentation(Neos\Flow\Aop\JoinPoint)
119 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
118 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
117 Neos\Neos\Service\ContentElementWrappingService::wrapContentObject(Neos\ContentRepository\Domain\Model\Node, ...)

I suggest to at least make all properties nullable to prevent this problem and similar ones.

**Comment by kdambekalns** [comment]
https://github.com/neos/neos-development-collection/pull/2781
