### ISSUE TITLE
Error when replacing asset: argument to recreateVariant() must be of the type string

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#2837]
### Description

`Argument 2 passed to Neos\Media\Domain\Service\AssetVariantGenerator_Original::recreateVariant() must be of the type string, null given`

### Steps to Reproduce

1. Create a variant generated without the use of a preset, e.g. by manually cropping an image
2. Replace the asset for that variant, triggering `recreateVariant()` 

#### Expected behavior

No error. Ideally the variant's adjustments are `refit()` like before 5.1.

#### Actual behavior

```
Argument 2 passed to Neos\Media\Domain\Service\AssetVariantGenerator_Original::recreateVariant() must be of the type string, null given
Exception Code	0
Exception Type	TypeError
Thrown in File	Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Media_Domain_Service_AssetVariantGenerator.php
Line	150
Original File	Packages/Application/Neos.Media/Classes/Domain/Service/AssetVariantGenerator.php
```

### Affected Versions

Neos: 5.1.0

**Comment by albe** [comment]
Fixed as of ☝️
