### ISSUE TITLE
Rename Neos.Neos.TYPO3CR

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#2842]
### Description

In #1240 we changed the vendor namespace, but deep inside some parts are still quite retro…

**We should get rid of `Neos\Neos\TYPO3CR` and rename it accordingly.**

### Affected Versions

Neos: 5.1.0 (should be fixed with 6.0)

**Comment by bwaidelich** [comment]
> deep inside some parts are still quite retro

What _kind_ of parts?

**Comment by jonnitto** [comment]
> > deep inside some parts are still quite retro
> 
> What _kind_ of parts?

For example `Neos.Neos/Classes/TYPO3CR/`
