### ISSUE TITLE
No login possible with Neos behind Basic Auth and Chrome 79

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#2845]
### Description

No login possible with Neos behind Basic Auth and Chrome 79

### Steps to Reproduce

1. Have your site secured with basic auth on a server-level
2. Use Chrome 79 (79.0.3945.88 was what I used)
3. Go to www.your.site/neos

#### Expected behavior

Get redirected to /neos/login and see a login screen

#### Actual behavior

A white page. Chrome receives the 401 (which we send since https://github.com/neos/neos-development-collection/commit/2ca96fad076a8c5ebb8921a883c7b5a93e333ee4) and this cancels the basic auth (in that latest Chrome version), it seems.

### Affected Versions

Neos: 1.2.0-beta1 and up (that's when the change was merged)

**Comment by kitsunet** [comment]
It actually cancelled the basic auth since ever, just before it would simply ask again for auth instead of failing completely.

**Comment by kdambekalns** [comment]
Workaround for the time being:

1. Open an Incognito window
2. Directly go to  www.your.site/neos/login 
3. Enter basic auth credentials
4. Enter Neos credentials

This avoids the intercepted request that triggers the 401.

**Comment by dlubitz** [comment]
Can confirm bug and workaround ... unfortunately. Any ideas how to tackle that?

**Comment by gerhard-boden** [comment]
Noticed this as well yesterday. Has anybody worked his head around the issue what it could possibly be? Since this is happening to very old Neos versions as well it's unlikely we recently introduced an issue, but there is some sort of incompatibility that now came up.

**Comment by kdambekalns** [comment]
Like @kitsunet already said:

> It actually cancelled the basic auth since ever, just before it would simply ask again for auth instead of failing completely.

In fact the 401 is plain wrong at that point. The login screen is not unauthorized, ever.

**Comment by gerhard-boden** [comment]
> Like @kitsunet already said:
> 
> > It actually cancelled the basic auth since ever, just before it would simply ask again for auth instead of failing completely.
> 
> In fact the 401 is plain wrong at that point. The login screen is not unauthorized, ever.

So the fix could be as easy as adjusting this code?
https://github.com/neos/neos-development-collection/commit/2ca96fad076a8c5ebb8921a883c7b5a93e333ee4#diff-6f633c634dbe91476e5f1d3295bb3232R66

(and all other occurences ofc.)

**Comment by kdambekalns** [comment]
As easy as that, yes. But without breaing the UI code that relies on that behavior. 🤷‍♂️

**Comment by kitsunet** [comment]
Probably switching from 401 to a custom header to indicate authentication failure would be the way to go.

**Comment by gerhard-boden** [comment]
I could take care! Hopefully can even free up some time this afternoon!

**Comment by gerhard-boden** [comment]
Is this considered a security related bugfix? (asking if I should look at this in 3.3 or 4.3)

**Comment by kitsunet** [comment]
Strictly speaking I guess not. Security fixes are really to avoid having vulnerable installations in the wild as much as possible. In this case, it's really a bug and warrants an update to a newer version. I guess 🤷‍♂ as always hard to say. Obivously people stuck on the older version for some reason will surely appreciate the fix, but mmm, I think no?

**Comment by gerhard-boden** [comment]
Alright, let's make this a good reason to update then 👍 
Customer will also understand that an update is inevitable if the website does not work with the latest browser anymore.
