### ISSUE TITLE
Return value of Neos\Media\Domain\Model\Adjustment\ResizeImageAdjustment::getRatioMode() must be of the type string, null returned

### ISSUE THREAD

**Issue by radmiraal** [neos/neos-development-collection#2846]
### Description

Neos throws exceptions on media with a null image ratio.

### Steps to Reproduce

Probably having the `null` value in the database is an invalid state that doesn't appear in all installs. But to force it:

1. Create a page with an image
2. Set column 'ratiomode' to `null` in neos_media_domain_model_adjustment_abstractimageadjustment
3. Try editing content in Neos

#### Expected behavior

Should work

#### Actual behavior

Throws internal server errors

### Affected Versions

Neos: 4.3.7 and 5+

#### Probable error

https://github.com/neos/neos-development-collection/commit/2869edc8df0e2b1bed8b1dc20aa1a23cbbdd7f3e introduced strict return types. ResizeImageAdjustment::getRatioMode() has a return type `string` while the column annotation has `nullable=true`. This means the database **can** have `null` values, and in such case PHP will throw a fatal error.

I could fix it by simply updating the `ratiomode` to be an empty string if `null`.

**Comment by kitsunet** [comment]
I think there is a migration as well that fixes it in existing content...

**Comment by kdambekalns** [comment]
Hi @radmiraal, great to see you around!

Solved with https://github.com/neos/neos-development-collection/pull/2834 and https://github.com/neos/neos-development-collection/pull/2781 - both merged and released in: 5.1.0 – 5.0.5 – 4.3.8

**Comment by radmiraal** [comment]
ah, lol, I found the first and overlooked the latter ;) Thanks!
