### ISSUE TITLE
Make multiple AuthenticationProviders possible

### ISSUE THREAD

**Issue by gerdemann** [neos/neos-development-collection#2847]
### Description

It should be possible to use multiple AuthenticationProviders for the Neos backend.

A long time ago I created a pull request. But there were still many questions and remarks.
PR: https://github.com/neos/neos-development-collection/pull/693

I'd like to try to keep working on this subject. But I need help for that. 😃

### Steps to Reproduce

No steps...

#### Expected behavior

Multiple AuthenticationProviders for the Neos backend should work

#### Actual behavior

No actual behavior

### Affected Versions

All 😉

**Comment by albe** [comment]
@gerdemann can you check in how far #2577 already covers this?

**Comment by albe** [comment]
I'll close this issue as resolved as of #2577 - feel free to reopen if you see something still missing :)
