### ISSUE TITLE
Personal workspace names are not always unique

### ISSUE THREAD

**Issue by theilm** [neos/neos-development-collection#2850]
### Description

The personal workspace name of a user is created based on the user's account identifier. Special characters are removed from the account identifier. This can lead to duplicate workspace names.

### Steps to Reproduce

1. Create users with the account identifier "test-user" and "testuser"
2. Log in as "test-user" - everything works as expected.
3. Log in as "testuser" - an exception is thrown.

#### Expected behavior

Both users should be able to login and have a personal workspace.

#### Actual behavior

Only the first user is able to login, as the personal workspace name of both users is the same (the hyphen gets removed).

### Affected Versions

Neos: all

**Comment by DrillSergeant** [comment]
I just ran into the same issue. Our customer created 2 users:
"john doe" and "john.doe". Result was that they both tried to use the same workspace "user-johndoe" which did not work: The second created user "john.doe" ended in an 404 after loggin in.

**Comment by kitsunet** [comment]
We should check if this problem still exists in Neos 9 and possibly fix it, as at least in previous versions fixing it would be a breaking change.

Notes:
We currently have only the implicit relation of transform-function(username) => workspace name, no DB entries. So changing the transform-function (eg. adding a hash over username) would break existing workspaces (unless we rename them but then you might have another can of worms after that), or we create a relation table for it and the transform function appends if a given workspace name is already used up, but then we would need a DB migration in a bugfix versoin.

**Comment by mhsdesign** [comment]
Related: https://github.com/neos/neos-development-collection/issues/4566

**Comment by mhsdesign** [comment]
By reimplementing the user workspace creation and spending a lot of thought into the mapping from user name to workspace we accidentally just fixed that :D see https://github.com/neos/neos-development-collection/blob/a14bbe701335c013df85579d1703f9dd4b018cc5/Neos.Neos/Classes/Domain/Service/WorkspaceService.php#L222 

... at least for Neos 9
