### ISSUE TITLE
Reflection error after installation

### ISSUE THREAD

**Issue by beheist** [neos/neos-development-collection#2862]
Hey folks 👋hope you are doing well! I just wanted to try out the new Neos, but I can't due to a bug:

### Description

Setup ends in an error:
Required class "TYPO3\Neos\Service\DataSource\AbstractDataSource" could not be loaded properly for reflection..

### Steps to Reproduce
1. composer create-project neos/neos-base-distribution
2. ./flow server:run
3. Go through setup as usual
4. After step 4, instead of showing the setup finish page, the above error occurs. 

### Affected Versions
I tried with 5.1.4 and 5.0.7, both throw the same error.

**Comment by albe** [comment]
**TYPO3**\Neos 🤔 That class surely doesn't exist under that namespace. Could it be that you still had some old code base somewhere lying around?

**Comment by beheist** [comment]
Not really, I removed the entire directory every time I tried it.. it also confused the hell out of me, but there we are. Did you try to reproduce?

**Comment by beheist** [comment]
I just tried from scratch, same issue.. here is the stacktrace:
```
Exception: Required class "TYPO3\Neos\Service\DataSource\AbstractDataSource" could not be loaded properly for reflection.

Possible reasons are:

 * Requiring non-existent classes
 * Using non-supported annotations
 * Class-/filename missmatch.

The "Neos.Flow.object.excludeClasses" setting can be used to skip classes from being reflected.

29 Neos\Flow\Reflection\ClassReflection::Neos\Flow\Reflection\{closure}("TYPO3\Neos\Service\DataSource\AbstractDataSource")
28 spl_autoload_call("TYPO3\Neos\Service\DataSource\AbstractDataSource")
27 include("/Users/bastian/src/pers/oase/Packages/Applica…es/Service/DataSource/FormDefinitionDataSource.php")
26 Composer\Autoload\includeFile("/Users/bastian/src/pers/oase/Packages/Librari…es/Service/DataSource/FormDefinitionDataSource.php")
25 Composer\Autoload\ClassLoader::loadClass("TYPO3\Neos\NodeTypes\Service\DataSource\FormDefinitionDataSource")
24 spl_autoload_call("TYPO3\Neos\NodeTypes\Service\DataSource\FormDefinitionDataSource")
23 ReflectionClass::__construct("TYPO3\Neos\NodeTypes\Service\DataSource\FormDefinitionDataSource")
22 Neos\Flow\Reflection\ClassReflection::__construct("TYPO3\Neos\NodeTypes\Service\DataSource\FormDefinitionDataSource")
21 Neos\Flow\Reflection\ReflectionService::reflectClass("TYPO3\Neos\NodeTypes\Service\DataSource\FormDefinitionDataSource")
20 Neos\Flow\Reflection\ReflectionService::Neos\Flow\Reflection\{closure}("TYPO3\Neos\NodeTypes\Service\DataSource\FormDefinitionDataSource")
19 array_filter(array|1|, Closure)
18 Neos\Flow\Reflection\ReflectionService::reflectEmergedClasses()
17 Neos\Flow\Reflection\ReflectionService::buildReflectionData(array|33|)
16 Neos\Flow\ObjectManagement\CompileTimeObjectManager::initialize(array|129|)
15 Neos\Flow\Core\Booting\Scripts::initializeObjectManagerCompileTimeFinalize(Neos\Flow\Core\Bootstrap)
14 call_user_func(array|2|, Neos\Flow\Core\Bootstrap)
13 Neos\Flow\Core\Booting\Step::__invoke(Neos\Flow\Core\Bootstrap)
12 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
11 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
10 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
9 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
8 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
7 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
6 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
5 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
4 Neos\Flow\Core\Booting\Sequence::invoke(Neos\Flow\Core\Bootstrap)
3 Neos\Flow\Cli\CommandRequestHandler::boot("Compiletime")
2 Neos\Flow\Cli\CommandRequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()
```

**Comment by albe** [comment]
Currently installing neos locally. Can you check what the System log tells about the reflection? For some reason it somewhere finds a `TYPO3\Neos\NodeTypes\Service\DataSource\FormDefinitionDataSource` class, which is... wrong. Can you find this namespace somewhere in the installed codebase?

**Comment by albe** [comment]
Okay... now I have that too. 🐼 What the hell is going on?

**Comment by markusguenther** [comment]
Hi @beheist ,

great that you still take a look at neos development :)
I just tried it and it just worked.

Test it on a mac and used the homebrew local php stuff.

![Screenshot 2020-01-17 at 11 17 16](https://user-images.githubusercontent.com/1014126/72604433-2cfe8780-391b-11ea-83c8-525135c01248.png)

**Comment by albe** [comment]
Okay, @beheist - I think I know what that error is about: the creation of a site package leads to requiring neos/nodetypes (which is deprecated by now and only referenced in the sitekickstarter still, but that of itself is not the issue). Now for some reason for me (and probably you too) this lead to installing a rather old version of that package (2.3.7 in my case), leading to the TYPO3.Neos namespace package and the reflection error.
So, this is probably a sitekickstarter bug - it should require more strict versions of neos/nodetypes instead of `*` - which can end up installing such an archaic version if it sits in the cache.

I got it resolved after simply running a `composer update` and then trying again.

**Comment by beheist** [comment]
Holy cow, what a weird issue. I'm kinda happy you also had an outdated composer cache @albe, otherwise I'd probably gone crazy.. ;)
Workaround: run `composer clear-cache` before running `composer create-project`, then everything works from the beginning.
Thanks to both of you! Back to trying out Neos 5 ;)

**Comment by albe** [comment]
Closing with above new "Solved" label. Hope this makes sense to everyone!
