### ISSUE TITLE
Translation errors cause 500s in backend

### ISSUE THREAD

**Issue by beheist** [neos/neos-development-collection#2863]
### Description

And another one, after reporting #2862 I went down to 4.3.9. The installation runs through and the backend works, but if I access a menu item other than the actual content editor (eg Media Module), I get:

```
Argument 2 passed to Neos\Flow\I18n\Translator_Original::translateById() must be of the type array, int given, called in /Users/bastian/src/pers/oase/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_FluidAdaptor_ViewHelpers_TranslateViewHelper.php on line 139
```

### Steps to Reproduce

1. `composer create-project neos/neos-base-distribution oase ~4.0`
2. Start dev server and do the setup normally
3. Access the backend and click on the media module --> error.

### Affected Versions
Neos 4.3.9
Neos 4.2.17

**Comment by beheist** [comment]
Update: Just tried out 4.2.17, it has the same issue. :/

**Comment by albe** [comment]
Could (big "could") be related to https://github.com/neos/neos-development-collection/pull/2856 respectively https://github.com/TYPO3/Fluid/issues/449

At least the translate viewhelper gets invoked with an `argument` argument that is evaluated as int, which hints at wrong fluid template parsing.

**Comment by beheist** [comment]
Hey, I just change the title since this also occurs in the newest version. Since this makes everything but content editing unusable, I think its rather critical.. is there a workaround of any sort maybe?

**Comment by albe** [comment]
Can you try merging in #2856 on your local setup and check if that solves it for you? Still curious if that Fluid bug is indeed the root issue.

**Comment by albe** [comment]
The PR above is now merged into dev-master of TYPO3 Fluid, so you can check it out by pulling that into your installation.

**Comment by dlubitz** [comment]
A fix of fluid has been released. Please check if this solves your issue and close the ticket.
https://github.com/TYPO3/Fluid/pull/493#issuecomment-581378186
