### ISSUE TITLE
SiteKickstarter still adds a require neos/nodetypes which is deprecated

### ISSUE THREAD

**Issue by albe** [neos/neos-development-collection#2864]
This should be replaced by the specific `neos/nodetypes-{something}` packages.

https://github.com/neos/neos-development-collection/blob/master/Neos.SiteKickstarter/Classes/Service/GeneratorService.php#L50

For 4.x this should be changed to require `^4.0` to prevent the new package from installing very old (and incompatible) versions, since `neos/nodetypes` itself does not have a strict constraint on the neos version.

This in turn lead to https://github.com/neos/neos-development-collection/issues/2862

**Comment by jonnitto** [comment]
@albe Can we close this one?
