### ISSUE TITLE
Move neos/fusion-afx into the neos-development-collection

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#2878]
This will make it much easier to implement changes that need synchronous alterations in afx and fusion and will reduce the number different of version constraints we have to deal with.

**Comment by albe** [comment]
Someone still going to do that for 5.2? Guess that's something we could still do after feature-freeze today, but we could also postpone for 5.3

**Comment by mficzel** [comment]
I cannot do this as this requires setting up subsplits etc. i hoped to do this on a sprint but i agree that this is not urgent.

**Comment by bwaidelich** [comment]
+1 @kitsunet you are assigned to this issue, are you taking care of this?

**Comment by bwaidelich** [comment]
@kitsunet *ping*

**Comment by kdambekalns** [comment]
- [ ] fetch `master` of dev collection
- [ ] push `master` as `master-backup-20201204-pre-afx-repair`
- [ ] remove traces of `Neos.Fusion.Afx` from dev collection
- [ ] merge `neos/fusion-afx` again
- [ ] force-push `master`  of dev collection

Then
- the splits should work again!?
- probably the first push of the AFX split to master needs to be force-pushed once…

**Comment by kdambekalns** [comment]
See https://github.com/neos/slicer/issues/11

**Comment by kdambekalns** [comment]
✅
