### ISSUE TITLE
No Cache Flush after changing an ImageVariant

### ISSUE THREAD

**Issue by larslehners** [neos/neos-development-collection#2897]
### Description
If you access an image property in a node and render an Image Variant from it via fusion using an image variant preset, the cache is not flushed if the image variant is changed afterwards, e.g. changing the crop in the media management module.

In the case of the local asset source, a new file is generated after the Image variant has been adjusted and the old one is deleted.

### Steps to Reproduce

Go to media management module and change the image variant of an already rendered image based on a image variant preset

#### Expected behavior

The cache of the start page has been deleted. Renderd output  refers to the new Image Variant. The old Image Variant has been deleted.

#### Actual behavior

The cache of the start page was not deleted. The new image variant is not displayed in the rendered output. The old Image variant is not displayed there either, because it has already been deleted. A reference is made to an image that no longer exists. File status: 404

### Affected Versions

Neos: 4.3.10
Flow: 5.3.7

**Comment by larslehners** [comment]
#https://github.com/neos/neos-development-collection/issues/1434

**Comment by kdambekalns** [comment]
Can reproduce with Neos 5.1, will work on a solution…
