### ISSUE TITLE
Calling a missing eelhelper should give an error

### ISSUE THREAD

**Issue by kabarakh** [neos/neos-development-collection#2900]
### Description

Calling a missing eelHelper should give an error describing what is missing. Instead, a missing eelHelper just returns null at the moment.

### Steps to Reproduce

```
joinedArray = ${Array.join(PunktDe.Array.arrayFilter([]), ' ')}
```

#### Expected behavior

Error: EelHelper PunktDe.Array.arrayFilter does not exist

#### Actual behavior

Error: Array.join expects first parameter to be array, null given

### Affected Versions

Neos: 5.1.4

**Comment by mhsdesign** [comment]
Sorry but eel is conceptualized to be forgiving
