### ISSUE TITLE
Media browser: Upload url/viewhelper not resolved for drag'n'drop upload

### ISSUE THREAD

**Issue by sorenmalling** [neos/neos-development-collection#2906]
### Description

The uploadUrl variable for the upload field of the media browser is not being resolved (see image)

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/531918/74748415-c0074600-5268-11ea-8273-1ebac3d9eeb4.png">

### Steps to Reproduce

1. Open "Media" module
2. Dragn'n'drop a image
3. Get HTTP error in Neos (red alert from top) 
4. Look at your network tab 

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/531918/74748549-fc3aa680-5268-11ea-8096-cf40b456ce70.png">

#### Expected behavior

Uploading

#### Actual behavior

No resoved uri for upload

### Affected Versions
Neos: 5.1.4

**Comment by sorenmalling** [comment]
PHP 7.3.11

**Comment by akappler** [comment]
I have the same issue and I did a workaround localy: 

In `Packages/Application/Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html`

I changed the code to: 
```
    <div id="neos-media-upload-url" data-url="{f:uri.action(action: 'upload', additionalParams: {__csrfToken: '{f:security.csrfToken()}'}, absolute: true) -> f:format.raw()}" /></div>
    <f:if condition="!{activeAssetSource.readOnly}">
        <script type="text/javascript">
            var neosMediaUploadElement = document.getElementById('neos-media-upload-url');
            var uploadUrl =  neosMediaUploadElement.getAttribute('data-url');
```
The interesting part here is, that it seems related to the `<f:if>` condition. If I move the div into the if-condition the viewhelper won't get rendered, as soon as it is outside of the if statement, its working.

This workaround is probably not for live but I had to upload quickly an image on my local machine. 

Maybe this hint helps to find a solution. Well... next to not using fluid anymore ;-)

**Comment by akappler** [comment]
I could find the cause of this issue. 

Fluid has a problem if you add e.g. javascript that has e.g. an if condition like:

`if(this.istrue) {
     doSomething
}`

This will break the fluid rendering in the current tag, in this case the <script> Tag. 

Therefore I only changed the if condition into a single line if without the need of {} and it worked again. 

If I should change anything on my PR, give me a note.

**Comment by akappler** [comment]
This issue is related to PHP 7.3, my change will work with PHP 7.2, anything else I should do?

**Comment by breadlesscode** [comment]
Same  Problem here, PHP 7.3 with Neos 5.2.2
