### ISSUE TITLE
Translation not picked up as expected from XLIFF

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#2963]
### Description

- a site uses a content dimension `language` with values `de_DE` and `en_GB`
- XLIFF files in the site package are in folders `en` and `de`
- labels from those XLIFF files are output using `<f:translate id="foo" package="Acme.AcmeCom"/>`

#### Expected behavior

When the visitor switches to english on the website, along with translated content any output based on those labels switches to english, too.

#### Actual behavior

Labels stay in german.

### Background

It starts to work, when moving the XLIFF folders to `en_GB`, the same as the used dimension value. Which seems obvious, given https://github.com/neos/flow-development-collection/blob/79ceba8a335cbbcbd22ac98ffab027c1b24c555c/Neos.Flow/Classes/I18n/Xliff/Service/XliffFileProvider.php#L110

But… it used to work and broke at some (sadly unknown) point in the not too distant past.

Is it a bug? Misconfiguration? Broken fallback chain handling Any feedback appreciated!

### Affected Versions

Neos: 5.1.6

Flow: 6.1.5

**Comment by kitsunet** [comment]
Sounds like a bug to me, I am pretty sure the fallbacks (especially for this) should be in place and there is no configuration to make it happen.

**Comment by franzkugelmann** [comment]
The demo package would have the same problem, but there the LocaleChain contains an additional item "en" (based on the setting for default Language?).
If one would use ie. "de_DE" instead of only "de" in the language dimensions, the german labels would never show up, because as fallback still "en" applies.

**Comment by kdambekalns** [comment]
The `XliffFIleProvider` is unchanged and would work as epxected. The locale fallback chain is wrong in the case at hand.

**Comment by kdambekalns** [comment]
THis is what broke it (changes the fallback rule handling to `strict`): https://github.com/neos/neos-development-collection/pull/2570
