### ISSUE TITLE
FusionObjects: LazyProps doesn't accept ComponentImplementation

### ISSUE THREAD

**Issue by erkenes** [neos/neos-development-collection#2985]
The LazyProps-Helper doesn't Accept ComponentImplementation.
LazyProps excepts `Neos\Fusion\FusionObjects\Helpers\object` due to the Class Configuration.

### Steps to Reproduce

1. Just use Neos.Fusion latest version (5.2.1).

#### Actual behavior

The Site isn't loading and throws an error (see attachment)

### Affected Versions

Neos: 5.2.1

Flow: 6.2.0

PHP-Version:  7.1.30

![image](https://user-images.githubusercontent.com/8766722/82793358-0cb67a80-9e71-11ea-9910-2f6f3cd16140.png)

**Comment by EnesE** [comment]
#2986

**Comment by EnesE** [comment]
With `composer update` the error is still present. But if i change the PHP-Version to 7.3 everythin is working fine.

**Comment by mhsdesign** [comment]
Closing see https://github.com/neos/neos-development-collection/pull/2986
