### ISSUE TITLE
Augmenting wrapped content elements not working as expected

### ISSUE THREAD

**Issue by patricekaufmann** [neos/neos-development-collection#2988]
I already attempted a fix 1.5 years ago: https://github.com/neos/neos-development-collection/pull/2281 but it got rejected. I keep running into this issue while developing modular Neos components.

The issue:

When passing wrapped content elements to a fusion renderer via @props, a script tag gets added when evaluating:

```
$wrappedContent = $this->htmlAugmenter->addAttributes($content, $attributes, 'div');
$wrappedContent .= "<script data-neos-nodedata>(function(){(this['@Neos.Neos.Ui:Nodes'] = this['@Neos.Neos.Ui:Nodes'] || {})['{$node->getContextPath()}'] = {$serializedNode}})()</script>";
```

This leads to the xPath query in _HtmlAugmenter.php_ not detecting a root element since the html is of structure `<div></div><script></script>`. It will break functionality for the Neos.Fusion:Augmenter since it will wrap the actual root element one more time.

More specific: It is not possible to use the _Neos.Fusion:Augmenter_ to augment _Neos.Neos:ContentCollection_ passed via props Context to a _Neos.Fusion:Renderer_ because instead of augmenting the attributes on the ContentCollection div, the HtmlAugmenter can't detect a single root element and now wraps the ContentCollection div into another div.

Neos 5.2
Neos UI 5.2

**Comment by patricekaufmann** [comment]
In case anyone else finds this issue: The original PR got denied some years ago and we have been using an augmenter modification like this ever since:

`$rootElement = $xPath->query('//html/body/*[not(self::script and @data-neos-nodedata)]|//html/head/*[not(self::script and @data-neos-nodedata)]');`

**Comment by mhsdesign** [comment]
Hi ;) Thanks for this issue, i never though of this usecase ^^

The fact that there are `script` tags in the markup is already quite hacky and we though already of a "Minimally Invasive Content Element Wrapping" via html comments: https://github.com/neos/neos-ui/issues/3231#issuecomment-1531328511

Once we have reworked the content element wrapping, you should not face this problem any longer. But i also have to admit that this will still likely take some time until it is ready (if it ever will be).

**Comment by Sebobo** [comment]
The script tag is gone now with [#3770 ](https://github.com/neos/neos-ui/pull/3770)
