### ISSUE TITLE
Re-login after session timeout in backend not possible

### ISSUE THREAD

**Issue by bxburak** [neos/neos-development-collection#2990]
### Description

After updating to Neos 5.1 (and recently 5.2 too) I think I found a bug in the backend UI. When a user session times out and the UI prompts the backend user to login again, it is not possible to login. The UI says that the username or password is incorrect (even though it is definitely correct).

The AJAX request to “/neos/login.json” returns a 500 error with Neos-PHP-Error “Call to undefined method Neos\Flow\Mvc\View\JsonView::setFusionPathPattern()”.

Is this maybe a bug related to the new AuthenticationProvider changes in the recent Neos versions?

### Steps to Reproduce

1. Create a new instance
2. Login into the backend
3. Run "flow flow:session:destroyAll"
4. Try to re-login in the dialog that the backend pops up when a session times out

#### Expected behavior

The backend takes the user back to where he left off before the session timed out.

#### Actual behavior

The AJAX request for authentication returns a 500 error. The backend says that the username/password is incorrect and you need to go back to /neos to login.

### Affected Versions

No problems at 4.3, Bug is present at 5.1 and 5.2 AFAIK.

Neos: 5.2.1
Neos-UI: 5.2.1
Flow: 6.2.0

**Comment by Sebobo** [comment]
Thx for the issue, it's related to my rewrite of the login controller to Fusion. I'll look into it :)

**Comment by Sebobo** [comment]
Done
