### ISSUE TITLE
Error during setup:  Undefined index: CHARACTER_SET_NAME

### ISSUE THREAD

**Issue by cluetjen** [neos/neos-development-collection#2991]
### Description

Trying to install neos it stops while applying database migrations with error:

      Notice: Undefined index: CHARACTER_SET_NAME in /var/www/html/Packages/Application/Neos.GoogleAnalytics/Migrations/Mysql/Version20141111161429.php line 42

### Steps to Reproduce

1. use https://github.com/code-q-web-factory/Neos-Skeleton
2. Start setup in browser
3. Enter db data
4. => It take some time to load and then ends with error page

#### Expected behavior

Setup should apply migration

#### Actual behavior

Packages\Application\Neos.GoogleAnalytics\Migrations\Mysql\Version20141111161429.php fails with

      Exception #1 in line 42 of /var/www/html/Packages/Application/Neos.GoogleAnalytics/Migrations/Mysql/Version20141111161429.php: Notice: Undefined index: CHARACTER_SET_NAME in /var/www/html/Packages/Application/Neos.GoogleAnalytics/Migrations/Mysql/Version20141111161429.php line 42

Reason:

        $columnCharSets = $this->connection->executeQuery("SELECT character_set_name FROM information_schema.`COLUMNS` WHERE table_schema IN (SELECT DATABASE()) AND table_name = '${tableName}' AND column_name = 'persistence_object_identifier'")->fetch();
        $charSet = $columnCharSets['CHARACTER_SET_NAME'];

Index in $columnCharSets was returned lower case ($columnCharSets['character_set_name') exists).

I'm using MariaDB 10.5 docker image and neos inside of php74-apache docker images.

**Comment by Sebobo** [comment]
Should be solved with https://github.com/neos/neos-googleanalytics/releases/tag/3.2.1
