### ISSUE TITLE
Allow NodeTypes to be defined in hierarchical folders

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#3000]
With bigger projects the number of NodeType definitions can grow such that it's really hard to keep an overview.
Therefore it would be nice if NodeTypes could be defined in a hierarchical folder structure.

### Problem

Since sub folders underneath `/Configuration` are reserved for application context specific settings, it's not possible to define NodeTypes in subfolders.

### Suggestion

I would suggest to allow a new place for the NodeType definitions, so instead of:

```
/Configuration
  NodeTypes.Document.SomeDocument.yaml
  NodeTypes.Document.SomeOtherDocument.yaml
  NodeTypes.Content.SomeContent.yaml
  NodeTypes.Content.SomeOtherContent.yaml
  NodeTypes.Mixin.SomeMixin.yaml
  NodeTypes.Mixin.SomeOtherMixin.yaml
```

we could have

```
/NodeTypes
  /Document
    SomeDocument.yaml
    SomeOtherDocument.yaml
  /Content
    SomeContent.yaml
    SomeOtherContent.yaml
  /Mixin
    SomeMixin.yaml
    SomeOtherMixin.yaml
```

**Comment by kitsunet** [comment]
How do we deal with ApplicationContext then? I guess it's doable, but we ened to think carefully about that.

**Comment by breadlesscode** [comment]
> How do we deal with ApplicationContext then? I guess it's doable, but we ened to think carefully about that.

Maybe allow both ways? Configuration/... and NodeTypes/... ?

**Comment by bwaidelich** [comment]
BTW: Obviously the "old" location should still be supported and IMO the resolution order should be:
# /Configuration/<Context>/NodeType.yaml
# /Configuration/NodeType.yaml
# /Some/Package/Configuration/<Context>/NodeType.yaml
# /Some/Package/Configuration/NodeType.yaml
# /Some/Package/NodeTypes/NodeType.yaml

**Comment by markuspfeifenberger** [comment]
We don't, but do please really use Nodetype only in a specific context, eg Production only?

**Comment by markuspfeifenberger** [comment]
We don't, but do please really use Nodetype only in a specific context, eg Production only?

**Comment by breadlesscode** [comment]
That commenting speed :D

**Comment by kitsunet** [comment]
yeah, it makes not much sense to only define NodeTypes in specific context but it is possible, therefore I assume someone did it for some reason.

**Comment by bwaidelich** [comment]
@kitsunet what do you think about the suggested resolution?
That way you could define node types in a new consistent way (only in a package, independent from the app context) and still be able to override things globally and/or per context as before

**Comment by markuspfeifenberger** [comment]
What will be the load order, just in case ther is a override case  
\- Configuration (context as now) first  
\- NodeTypes folder (context less) first  
needs to be documented well, IMHO

**Comment by bwaidelich** [comment]
@markuspfeifenberger That's what I suggested with https://github.com/neos/neos-development-collection/issues/3000#issuecomment-646599120

**Comment by kitsunet** [comment]
Seems fine to me <3

**Comment by markuspfeifenberger** [comment]
makes absolutely sense \<3

**Comment by daniellienert** [comment]
> yeah, it makes not much sense to only define NodeTypes in specific context but it is possible, therefore I assume someone did it for some reason.

We have NodeTypes, which are defined for functional Tests in the Testing context only.

**Comment by Sebobo** [comment]
I like @bwaidelich's proposal ❤️

**Comment by jonnitto** [comment]
I like @bwaidelich proposal also. As we are heading to Neos v6, this would be a good moment to push this. What do you think?

**Comment by grizooo** [comment]
I would prefer storing NodeTypes.yaml directly into the fusion component. The old way should be still working, but in future i could imagine something like this:

SomePackage/Resources/Private/Fusion/Components/Article/NodeTypes.Article.yaml

So everthing what depends on the component is nearby together. 

It is hard to find everything for new neos developers, so everything should be stored in the same directory which belongs together. IMO.

**Comment by DrillSergeant** [comment]
@grizooo I understand your idea and maybe my approach could be interesting for you:
I bundle all the stuff for a NodeType together in an own Distribution Package: NodeType-Definition, Fusion-Rendering, Translations, ....
This way I have the files in their folders organized in the folders as Neos expects it but they are not far away from each other inside a single package. If I dont need that NodeType anymore, I remove that package and everything is clean.
It is not always one NodeType per package, sometimes multiple NodeTypes are closely related, so I bundle them in one package.

In the end you have a ton of packages, which I dont mind. Better than jumping through a huge folder-structure when working on a single NodeType.

Here an example of how this looks like:
![image](https://user-images.githubusercontent.com/883552/110973061-05f3e800-835d-11eb-8059-6dd7e36fd4b9.png)


Besides that, I like the idea of @bwaidelich to move the NodeType definitions.

**Comment by grizooo** [comment]
@DrillSergeant This ist ok for small extensions like accordion, tabs modul, slider or whatever. but i am talking about more complex extension lilke ProductOrderFormular, buildable in backend like FormBuilder ... you can not separate this package into a bunch of small packages ...

**Comment by grizooo** [comment]
![orderform configuration](https://user-images.githubusercontent.com/52205810/111111761-34411580-855f-11eb-9d4e-01368580ad94.jpg)
Here You can see just the configuration folder. guess what comlex structure is inside ...

**Comment by DrillSergeant** [comment]
@grizooo thanks for that insights. At a first glance I would say this can be split up into smaller packages. 

- Product
- Product.OrderFormular

Depending on what is behind that maybe even some additional sub-packages:
- Product.Options
- Product.Folder
- ...

**Comment by grizooo** [comment]
Ok, different Questions, how would you separate neos/form-builder in different packages ...

**Comment by bwaidelich** [comment]
> I would prefer storing NodeTypes.yaml directly into the fusion component

I see a couple of issues with that approach:
The Content Repository can be used completely without Fusion or other Neos components. In general I think it's one of its main features that _content_ and _rendering_ are two completely separate concerns.¹

So I'm with @DrillSergeant on this one: If your application grows too big, split it in useful chunks. Unfortunately I don't think that we can come up with a universal rule on _what_ those chunks are, so regarding:

> how would you separate neos/form-builder in different packages

I'd say it depends on your usecase..
For one project we purposely separate Form element types (and their corresponding node types) from the rendering components. In another one I put them all together into a separate `Some:Project.Form` package because forms have a special meaning there.


---
¹ Frankly, I think the common 1:1 mapping of node type to component pattern is not the best heuristic for many scenarios. It _sometimes_ leads to quirky node or component names and models. For example: You might have a "File" node type that you can render via some "Download" or some "Preview" component with a tiny bit of Fusion mapping in between. That's some great power that might get lost if we promote the 1:1 mapping via folder structure

**Comment by Sebobo** [comment]
I had already a discussion before with @grizooo and can understand the idea and some of its benefits.

But currently I think splitting CR configuration and rendering is still a good idea for long term maintainability and separations of concerns.
I see that there is an issue with nodetypes or rendering staying around while its counterpart might already have been removed. 
But that's something that can probably be solved either by my CR.Analyser package or Linter or something we build into Neos in the future. Introducing folders to group nodetypes that belong to each other already will help a lot IMO.

I'm not a super big fan of splitting too much into separate packages as this causes a lot of maintenance work (multiple PRs, versions, dependencies) if you want to share them between projects.
If they stay inside a distribution then it's of course perfectly fine to split them.

**Comment by bwaidelich** [comment]
> If they stay inside a distribution then it's of course perfectly fine to split them.

Of course.
I think what I meant to say is: I don't think that we can define a single best practice that works for all use cases.

Also, we should probably clarify:

I (and I think most of us) usually have:
1. A NodeType
2. A corresponding Fusion prototype
3. A rendering component

I was just talking about a separation between 1/2 and 3.
It probably _does_ make sense to be able to co-locate 1 and 2 though but I'd probably move the _Fusion_ file to the node type definition not the other way around, like:

```
/NodeTypes
  /Document
    # ...
  /Content
    /Article
      ArticleNodeType.yaml
      Article.fusion
/Resources
  /Private
    /Fusion
      /Component
        /Molecule
          Article.fusion
          Article.scss
```

**Comment by bwaidelich** [comment]
^ and that should already be possible

**Comment by Sebobo** [comment]
That could actually be a good idea. But first we need the NodeTypes folder ;)

**Comment by markuspfeifenberger** [comment]
@gjwnc had a look at whats, happening and what must be done. We can try to solve this issue, but I think we need support.

**Comment by gjwnc** [comment]
@bwaidelich @Sebobo

Imho, to get the NodeTypes folder we need two things:
1. Parse yaml files recursively from a custom folder
2. Let the configurationManager handle the parsed configuration

If you look at [NodeTypeManager:loadNodeTypes()](https://github.com/neos/neos-development-collection/blob/198c0f9db540b727112aa1bcbc44df32f63570c0/Neos.ContentRepository/Classes/Domain/Service/NodeTypeManager.php#L190), it only reads the configuration via the configurationManager. This makes sense, since the configurationManager basically deals with everything regarding yaml files in Neos including caching and such.

So I wouldn't want to modify loadNodeTypes() at all, which means we need a new [configurationProcessingType](https://github.com/neos/flow-development-collection/blob/d9a090148579cadd188272b1782a9532a3aa7f12/Neos.Flow/Classes/Configuration/ConfigurationManager.php#L384) to be able to load recursive configurations from various locations, e.g. first in `NodeTypes` folder in all Packages, then the Configuration in all pacakges.

Since, this kind of configuration, is a bit special, I would suggest, that we add the possibility, to provide a callback driven custom configurationProcessingType and use Neos.CR/Classes/Package.php to setup the callback.

This could look like the following, compared to the [original](https://github.com/neos/neos-development-collection/blob/198c0f9db540b727112aa1bcbc44df32f63570c0/Neos.ContentRepository/Classes/Package.php):
```
        $dispatcher->connect(ConfigurationManager::class, 'configurationManagerReady', function (ConfigurationManager $configurationManager) {
            $configurationManager->registerConfigurationType('NodeTypes', ConfigurationManager::CONFIGURATION_PROCESSING_TYPE_CUSTOM, true, function(){
                 $nodeTypeSettings = [];

                 ... read the NodeTypes.*.yaml files recursively from NodeTypes folder followed by configuration folder

                 return $nodeTypeSettings;
            });
        });
```

This means, this whole needs a change in Flow itself to provide a ConfigurationManager which allows custom configuration sources.
What do you think? Are there any other/better approaches?

**Comment by gjwnc** [comment]
@bwaidelich @Sebobo I just created a PR which could be used to solve this issue. An example implementation  which already works for the ContentRepository can be found in the PR.  
Please keep in mind, that the PR needs further discussion and I'm not sure if this is an acceptable solution.

**Comment by bwaidelich** [comment]
Re @mficzel's comment (https://github.com/neos/neos-development-collection/pull/3332#issuecomment-820447297):

> Not sure we should rush this, i would love to discuss first wether there is a way to colocate NodeTypes
> with the fusion integration or vice versa.

Yep, no need to rush this (it's probably too late for 7.1 anyways) but with the current approach it would be easily possible to co-locate Fusion prototypes with their corresponding Node types (see #issuecomment-799250409):

```
/NodeTypes
  /Document
    Page.yaml
    Page.fusion
```

Locating NodeType definitions underneath `Resources/Private/Fusion` would not make sense to me (though it would easily be possible with https://github.com/neos/flow-development-collection/pull/2449 in place, as @gjwnc  pointed out)

**Comment by mficzel** [comment]
Using NodeTypes/**/* as folder for the NodeType and (later) also the integration fusion can be a very good idea. 

The more i think about it the more i like it.
