### ISSUE TITLE
Login Screen fails if backendLoginForm.backgroundImage is unset 

### ISSUE THREAD

**Issue by paavo** [neos/neos-development-collection#3004]
### If you unset the Login Background-Image a broken URL to the Background-Imagewill be rendered. 
Removing the background image should be a Feature because you only want a brand-colored background styled with css.  
This worked well in Neos 4.3

### Steps to Reproduce

1. Unset backgroundImage _Neos.Neos.userInterface.backgroundImage: >_
2. Visit the Neos Login at /neos
3. background-image with broken URL will be rendered (_background-image: url(.../_Resources/Static/Packages/Neos.Neos/_)

#### Expected behavior
NO background-image should be rendered to display the CSS-Background Color. 

#### Actual behavior
background-image with broken URL is rendered (_background-image: url(.../_Resources/Static/Packages/Neos.Neos/_)

### Affected Versions
Neos: 5.2.1
_This worked well in Neos 4.3_

**Comment by jonnitto** [comment]
Hi @paavo 
Thanks for your report! I'll take care of that.

BTW, the correct setting would be
```yaml
Neos:
  Neos:
    userInterface:
      backendLoginForm:
        backgroundImage: ''
```

**Comment by jonnitto** [comment]
So, the fix was merged into the 5.1 branch. Thanks again for your report.

**Comment by jonnitto** [comment]
BTW, it is already released. This was a really short report -> bugfix -> release time 😄

**Comment by paavo** [comment]
Hell yeah, this was pretty fast 🚀 
Thank you 🎉
