### ISSUE TITLE
Could LazyProps be Countable?

### ISSUE THREAD

**Issue by PRGfx** [neos/neos-development-collection#3054]
### Description

In an older component I passed all the `props` into a `RawCollection`'s `collection` (same for a `Map`). However the `MapImplementation` calls `count` on the collection and everything breaks with the new LazyProps.

This probably is not a good practice, but is there a reason to not implement `\Countable` (e.g. return `count($this->keys)`)?

### Steps to Reproduce

For example like that, but with 5.2:
https://fusionpen.punkt.de/fusionpen/17b5b314655f7a7927821a106bdb336d65104952.html

### Affected Versions

Neos: ^5.2

**Comment by mhsdesign** [comment]
with #3359 we dont rely on the items beeing countable anymore, so id close this ;)
