### ISSUE TITLE
FontAwesome Icon in Neos backend module flash messages missing

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#3069]
### Description

![image](https://user-images.githubusercontent.com/642226/90003580-91f14480-dc94-11ea-8f9c-4241d236750f.png)

### Steps to Reproduce

1. Go to the user module
2. Edit a user
3. Save it

#### Expected behavior

Icon is there

#### Actual behavior

it is not

### Affected Versions

Neos: 5.2, master
Flow: ~

**Comment by markusguenther** [comment]
Maybe I forgot somthing while the last upgrade :/
Sorry for that.

**Comment by markusguenther** [comment]
Thanks for reporting that @daniellienert ...obviously we all oversees it 🤭
