### ISSUE TITLE
Add Afx Template for SiteKickstarter

### ISSUE THREAD

**Issue by Wyndala** [neos/neos-development-collection#3074]
Currently the SiteKickstarter Command generates a some kind of deprecated site package with fluid template. 

I suggest extending the package to accept different kind of generators to be more flexible in the future (maybe some best practices get changed etc.). I made a small alpha version of what I think would fit good to this approach:

https://github.com/queoGmbH/neos-site-kickstarter

The namespace and command name is just for the purpose to have this package aside of the build in site kickstarter.

I would really appreciate feedback and after some work would like to make a PR.

**Comment by skurfuerst** [comment]
Thanks for your work, I like it a lot :+1: :)
