### ISSUE TITLE
Fluid placeholders ignored in Neos.Media.Browser template

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#3096]
### Description

From https://neos-project.slack.com/archives/C050C8FEK/p1598436037092500:

----

Just have a problem with following:

    <script type="text/javascript">
        var uploadUrl = "{f:uri.action(action: 'upload', additionalParams: {__csrfToken: '{f:security.csrfToken()}'}, absolute: true) -> f:format.raw()}";
        var maximumFileUploadSize = {maximumFileUploadSize};
        if (window.parent !== window && window.parent.NeosMediaBrowserCallbacks && window.parent.NeosMediaBrowserCallbacks.refreshThumbnail) {
            window.parent.NeosMediaBrowserCallbacks.refreshThumbnail();
        }
    </script>

Every Fluid Placeholder get ignored in this part. When I remove a space inside the if{ }  it works. It also works when I split this segment in 2 <script> blocks. Could be a Regex that cause this issue. I use macOS 10.15.5 with PHP 7.3.21.

----

This is in https://github.com/neos/neos-development-collection/blob/42cf7b763c82494655f809a600dc5674a126ba9a/Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html#L319-L326

### Affected Versions

Neos: ?

**Comment by kdambekalns** [comment]
Possible solution:

```
<script type="text/javascript">
    var uploadUrl = "{f:uri.action(action: 'upload', additionalParams: {__csrfToken: '{f:security.csrfToken()}'}, absolute: true) -> f:format.raw()}";
    var maximumFileUploadSize = {maximumFileUploadSize};
<![CDATA[
    if (window.parent !== window && window.parent.NeosMediaBrowserCallbacks && window.parent.NeosMediaBrowserCallbacks.refreshThumbnail) {
        window.parent.NeosMediaBrowserCallbacks.refreshThumbnail();
    }
]]>
</script>
```

**Comment by MarcoPNS** [comment]
Tested it with 5.2.1 but don't know if an earlier version could also be affected.

**Comment by arsors** [comment]
@kabarakh @dfeyer @kitsunet Unfortunately, we receive complaints from customers on a weekly basis. Our customers cannot upload multiple assets at once. They also cannot use the drag and drop function. We need a solution that will not be reversed in future updates. So I ask for more attention to this topic. Thanks ❤️

**Comment by kdambekalns** [comment]
So this is even older, it rurns out: https://github.com/neos/neos-development-collection/issues/2906
