### ISSUE TITLE
Breaking Change in Neos.Neos:ContentCollectionRenderer going from 5.1 to 5.3

### ISSUE THREAD

**Issue by bweinzierl** [neos/neos-development-collection#3114]
### Description

A breaking change has been introduced in the fusion prototype `Neos.Neos:ContentCollectionRenderer` going from neos 5.1 to 5.3. The PR #2772 introduced a change where the fusion key `collection` was deprecated in favour of `items`. There is a implementation for backwards compatibility (`items.@processor.collectionLegacy`) but that is insufficient. It does not account for the case that collection can be set to an epmty array and it is actually wanted to display no content at all.
To be really backwards compatible there would have to be a check for the existance of the key `collection` inside the fusion code. To check if it is `null` or `0` is not enough.

### Steps to Reproduce 

1. Add the. following fusion somewhere into your site:
```
Neos.Neos:ContentCollectionRenderer {
    collection = ${[]}
}
```

#### Expected behavior

No content should be displayed.

#### Actual behavior

All children of the current node are displayed. But this was not the case in Neos 5.1

### Affected Versions

Neos: 5.3

**Comment by bweinzierl** [comment]
@putzwasser @Sebobo @kdambekalns Could you take a look at this?

**Comment by kdambekalns** [comment]
Thanks for the detailed report. That sounds like a regression, indeed.

**Comment by klfman** [comment]
Can confirm.
What do you think about temporarily documenting this change as breaking here, as the fix is easy, if you know it:
https://docs.neos.io/cms/references/upgrade-instructions/upgrade-instructions-5-2-5-3

Just replace the fusion key `collection` with `items`

**Comment by mhsdesign** [comment]
Hi, can this be closed now?
