### ISSUE TITLE
``is()`` operation does not behave as described

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#3115]
Jira issue originally created by user @gerhard-boden:

``` java
 imageSettings = TYPO3.TypoScript:Case {
        isWide {
            condition = ${q(node).property('size') == 'wide'}
            renderer = TYPO3.TypoScript:RawArray {
                preset = 'GesagtGetan.SportRenothDe:GalleryWide'
                size = '1400x720'
                logo = ${false}
                logoRight = ${q(this.logo).is()}
            }
        }
```

Why is logoRight true here, but when i change  logoRight = ${q(this.logo).is()} to logoRight = ${this.logo ? true : false} logoRight is correctly false
Don't mind the logic, it's just for understanding

The documentation says:
"Without arguments is evaluates to TRUE if the context is not empty. If arguments are given, they are used to filter the context before evaluation."

[~christianm] already mentioned it's a type casting issue

 Jira-URL: https://jira.neos.io/browse/FLOW-461

**Comment by mficzel** [comment]
The flowQuery context is always an array so with this fusion
```
test = ${q(false).is()}
```
the context will be 
```
[false]
```
and the is operation will return true because the context is not empty but contains an element which is false.

I do not think it makes sense to adjust the definition here. Also the documentation is correct as the context is not empty it contains a boolean item.

**Comment by mficzel** [comment]
@gerhard-boden since you created this originally do you agree to close this?

**Comment by gerhard-boden** [comment]
yea, let's close it! I think it's a little pitfall, but changing the behavior would be breaking and even more confusing now. Plus my use-case is weird as well, wouldn't do it like this 4 years later 😂
