### ISSUE TITLE
Resource clean with Neos breaks

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-development-collection#3117]
Neos 2.3

The `resource:clean` command uses AssetUsageStrategies, of which one is delivered with Neos to check for usage in Node properties. Unfortunately that expects a user (and it's workspace to exist) which isn't the case on command line. It should behave gracefully and fall back to live for example.

**Comment by mhsdesign** [comment]
The issue seems to be lost while being transferred.

Will continue the conversation in https://github.com/neos/neos-development-collection/issues/865
