### ISSUE TITLE
Should neos/fluid-adaptor be required with a specific version in neos/neos

### ISSUE THREAD

**Issue by sorenmalling** [neos/neos-development-collection#3120]
Question and hint, so this doesn't get lost:

As https://github.com/neos/flow-development-collection/pull/2152 is being merged into master, it might be nescessary to require neos/fluid-adaptor as a specific version.

**Comment by bwaidelich** [comment]
Master should allow the latest version of Fluid and older versions are restricted by the Flow dependencies (see https://github.com/neos/flow-development-collection/pull/2298)

@sorenmalling I'm closing this since IMO this is resolved. Feel free to comment/re-open if you don't agree
