### ISSUE TITLE
Add support for AVIF format

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#3132]
Currently, these files formats are supported:
[jpg, jpeg, gif, png, wbmp, xbm, webp and bmp](https://github.com/neos/neos-development-collection/blob/master/Neos.Media/Classes/Domain/Service/ImageService.php#L81)

But there is already the next generation of image formats here: AVIF. [You can read more about it here](https://reachlightspeed.com/blog/using-the-new-high-performance-avif-image-format-on-the-web-today/)

With this option, we could even serve faster websites with Neos 🚀

**Comment by bwaidelich** [comment]
I removed this feature from the Neos 6.0 project board for now since this requires an update of imagine

**Comment by putzwasser** [comment]
What's the status of this?

I think imagine got updated:

https://github.com/php-imagine/Imagine/pull/759
