### ISSUE TITLE
Add StaticResource EEL Helper to Fusion defaults

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#3133]
A EEL helper to get the content or uri of static resources would be very useful in afx. 

The FusionObject ResourceUri already does parts of this but cannot be used in afx attributes. 
This can be solved via `@path` or other fusion tricks but those never felt just right.

The intention is to enable afx like this:
```
  <!-- create static resource uri -->
  <link rel="stylesheet" href={StaticResource.uri('Neos.Demo', 'Public/Styles/Main.css')} media="all" />

  <!-- get static resource content -->
  <style>{StaticResource.content('Neos.Demo', 'Public/Styles/Main.css')}</style>
```

**Comment by markuspfeifenberger** [comment]
Should the second Helper only be limited to StaticResource? The secound paramter can be `Private/Styles/Main.css` ->   
\`\`\`  
\<style>{Resource.content('Neos.Demo', 'Private/Styles/Main.css')}\</style>  
\`\`\`

**Comment by mficzel** [comment]
Hello Markus,

that is actually intended, that way you can use the content of private
static resources like (json,svg) etc. without making them public.
Only side effect is that creating a uri for a non-public resource will
fail. But this is obvious and to be expected
with a path that starts with "/Private". I preferred to use the same
pathes for both methods rather than assuming
/Public for the uri method.

Regards, Martin

PS: Why did'nt you ask that on github directly?

Am So., 18. Okt. 2020 um 03:42 Uhr schrieb Markus Pfeifenberger <
notifications@github.com>:

**Comment by mficzel** [comment]
I just gave it a shot. Trying to create a uri for a private resource already yields an exception with the message: 
`The path "resource://Neos.Demo/Private/Fusion/Root.fusion" which was given must point to a public resource.`

This already happens in the ResourceManager or Storage and should not be the concern of the eel helper.
