### ISSUE TITLE
CreateNodePrivilege must check parent NodeTypes

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#3136]
If you define a matcher like `createdNodeIsOfType("Some.Package:Mixin")`, the creation of a node using this mixin should match.
Currently, only the final NodeType is checked (ignoring inheritance). Imho here we should do the same inheritance checks as everywhere else.

**Comment by mhsdesign** [comment]
Duplicated and fixed via https://github.com/neos/neos-development-collection/issues/2960
