### ISSUE TITLE
User menu broken on modules other then the content module

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#3143]
### Description

![image](https://user-images.githubusercontent.com/642226/96847339-5cff2c00-1453-11eb-88c8-f9aed5cabc58.png)

On backend modules, apart from the content module, the username is not shown on the user module and the menu is not shown completely when opened

### Affected Versions

Neos: master

**Comment by markusguenther** [comment]
Hey Daniel,

tried to check this and did not have the issue :/
<img width="1141" alt="Screenshot 2020-10-24 at 21 04 07" src="https://user-images.githubusercontent.com/1014126/97091503-9ba40a80-163c-11eb-8ea6-eade1a05e686.png">

**Comment by daniellienert** [comment]
Oha, thanks for checking. let me double check on a vanilla installation first ...

**Comment by jonnitto** [comment]
@daniellienert Can we close this one?

**Comment by daniellienert** [comment]
If it's only me, I guess so.
