### ISSUE TITLE
You can't install Neos with composer 2.0

### ISSUE THREAD

**Issue by Blumen-topf** [neos/neos-development-collection#3146]
### Description
Neos didn't install with composer 2.0
I try it with the simple installation guide 
https://docs.neos.io/cms/installation-development-setup/mac-os-linux-using-the-embedded-web-server

### Steps to Reproduce

1. go to https://docs.neos.io 
2. follow the simple installation guide
3. in step 3 is it flawed

#### Expected behavior

I expected that Neos install
#### Actual behavior

it didn't work in combination with composer 2.0
<img width="1509" alt="Bildschirmfoto 2020-10-27 um 09 35 18" src="https://user-images.githubusercontent.com/73471148/97278677-5b11e000-183a-11eb-9e0f-2fa86b74bca7.png">

### Affected Versions

Neos: 5.3

Flow: 6.3

You can get this information by running `composer show` or using the package management module within Neos.

**Comment by markusguenther** [comment]
Thanks for reporting your very first issue @Blumen-topf 🎉 
We will adjust the documentation in first place to prevent that others run into that issue and add a hint that while installing neos the people should use composer 1.

```
composer self-update --1
```

Will solve that temporary until neos and all used packages are working with composer 2.

**Comment by Blumen-topf** [comment]
<img width="740" alt="Bildschirmfoto 2020-10-27 um 11 21 27" src="https://user-images.githubusercontent.com/73471148/97288966-e2fde700-1846-11eb-848d-5aae3459ea82.png">
We have optimist the document that people should use composer version 1

**Comment by kdambekalns** [comment]
Fixed with https://github.com/neos/flow-development-collection/pull/2188, release pending.

**Comment by markusguenther** [comment]
@kdambekalns Cool after release we will remove the info in the docs :)

**Comment by kdambekalns** [comment]
Fixed with latest release(s), see also #2187 and https://github.com/neos/flow-development-collection/issues/2120

@markusguenther The documentation can be updated again…

**Comment by markusguenther** [comment]
@kdambekalns Thanks for the quick release... I removed the notice box in the docs :)
