### ISSUE TITLE
Images with exif-orientations are not resized properly.

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#3148]
When images are resized that use the exif orientation feature the thumbnails and crops are flipped. Since this is used by some cameras it should be supported by neos. Imagine has an autorotate feature that can be used for that.

### Steps to Reproduce

1. Go to the media module
2. Upload an image with exif orientation like https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_6.jpg
3. Look at the generated thumbnails

#### Expected behavior

Thumbnail should have the same orientation as original.

#### Actual behavior

Thumbnail is rotated 90°

### Affected Versions

Neos: afaik all

**Comment by fleigm** [comment]
Good day everyone,

I can reproduce this issue in neos 5.3.1 and 7.0 despite the merged bugfix.
Does anyone else have this problem too?

**Comment by dlubitz** [comment]
I had this issue today on a customers instance with Neos 7.3 and also checked other ones (incl. 8.3). All of them show the same incorrect result, but after *cropping* the image. 

![image](https://github.com/neos/neos-development-collection/assets/13046100/b850d713-26ab-4b22-a2ba-ad1425c9ae47)

I found this open issue at imagine, which seems to be related. After adding the suggested solution , it works fine for me.
https://github.com/php-imagine/Imagine/issues/467

**Comment by dlubitz** [comment]
Also stripping the image (removing exif) solves this issue:
```
        $stripFilter = new \Imagine\Filter\Basic\Strip();
        $stripFilter->apply($imagineImage);
```
