### ISSUE TITLE
JS error and UI unusable when publishing changes

### ISSUE THREAD

**Issue by dogawaf** [neos/neos-development-collection#3154]
### Description

Editor experiences weird behavior in the backend after publishing changes.
The backend become unresponsive to some click, and he has to reload the interface in order to continue editing.

I found that the bug is caused by a JS error `Empty or non existent "message" passed to the addFlashMessage reducer. Please specify a string containing your desired message.` thrown by `Neos.Neos.Ui/packages/neos-ui-redux-store/src/UI/FlashMessages/index.ts:77`.
The code is trying to display a flash message, but the message is `null`.
I check what flash message should be displayed when publishing, and found the label `changesApplied` of `Neos.Neos.Ui:Main.xlf`.
This label exists only in EN and DE, and the editor set his language to FR.
Setting the editor's language to EN makes the error disappear and the flashMessage is displayed.

So either the translation fallback is not working, either the UI is too strict when displaying an untranslated flash message.

### Steps to Reproduce

1. Set the user's language preference to something different that EN or DE
2. Open the browser JS console
3. Edit a node property and publish it
4. A JS error is thrown and is visible in the browser console

#### Expected behavior

I should see the flash message saying "The change has bee published" in the user language (or in the fallback language)

#### Actual behavior

I see no flash message and there is a JS error.

### Affected Versions

Neos:  5.3.0

Flow: 6.3.1

**Comment by dogawaf** [comment]
I've just crontributed the missing FR translation on crowdin, but of course this is not the solution.

**Comment by markusguenther** [comment]
Thanks for reporting that issue @dogawaf 
The neos-ui has sadly another repository but I will create an Issue there and cross reference that :)

Greetings to france 👋

**Comment by markusguenther** [comment]
Closing in favour of https://github.com/neos/neos-ui/issues/2819
