### ISSUE TITLE
Links for switching to custom collection incorrect after switch to All collection

### ISSUE THREAD

**Issue by andrehoffmann30** [neos/neos-development-collection#3161]
### Description

In the Neos media browser the links for switching to another collection are incorrect after switch to the All collection. Therefore you can not switch to a custom collection after you switch to the All collection. 

### Steps to Reproduce

1. Open the Media module in the Neos backend
2. switch to a custom collection; create a custom collection if one does not exist
3. Switch to the All Collection
4. Switching back to the custom collect ist not possible anymore

#### Expected behavior

I can switch from the All Collection back to the custom collection

#### Actual behavior

I can not switch back to the custom collection

### Affected Versions

Neos: 5.3 and up

**Comment by jonnitto** [comment]
I can confirm the bug
