### ISSUE TITLE
Creating a variant with changed urlPathSegment leads to wrong results

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#3173]
### Description

Changing the url path segment of a page leads to a 404, since the new URI is not used in the frontend, but the old URI no longer works.

### Steps to Reproduce

1. Set up a Neos site with a content dimension "language", two languages and a fallback from the "second" to the "first"
2. Install the Neos redirecthandler adapter
3. Create a page in the "first" language and publish it, using "unchanged" as url path segment
4. Switch to the second language
5. Change the url path segment of the page to "changed" and publish
6. Reload the frontend and check the URLs for the two pages

#### Expected behavior

Two URLs, one pointing to `unchanged` and one to `changed`.

#### Actual behavior

Both URLs point to `unchanged`, but one of them results in a 404. Manually navigating to `changed` returns the expected page.

Flushing the `Flow_Mvc_Routing_Resolve` and `Neos_Fusion_Content` caches fixes the issue.

### Affected Versions

Neos: 4.3 (and later, probably)

**Comment by kdambekalns** [comment]
Hours of debugging resulted in

- happens only when creating a variant, changes to existing variants or "lone" documents work
- only happens when the Neos redirecthandler adapter is active

The cause is the `FirstLevelNodeCache` used in `Neos\ContentRepository\Domain\Service\Context` that is not flushed as needed after publishing a newly created variant.

**Comment by TheLalaMan** [comment]
This would be great to have, then we can start translating our websites for real ;-)

**Comment by kdambekalns** [comment]
> This would be great to have

For anyone wondering: Adding that signal/slot connection to your own `Package.php` class works as a workaround

(Check the PR I created for you, @TheLalaMan…)

**Comment by kdambekalns** [comment]
What happens is this:

1. The URL is changed
2. Publish is invoked
3. Routing and Fusion caches are flushed correctly
4. The Redirecthandler builds redirects afterwards, but receives a cached node (from the 1st level cache) still pointing to the "old" node
5. That creates a wrong routing cache entry that is no longer flushed (as caches were flushed already)
