### ISSUE TITLE
Neos backend login broken due to convertNodeToContextPathForRouting returning string

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#3181]
The method `convertObjectToIdentityArray` is AOPed in `NodeIdentityConverterAspect` and is returning a string when a Node is given. This breaks now due to typing added with https://github.com/neos/flow-development-collection/pull/2231

Neos:  master
Flow: master

**Comment by daniellienert** [comment]
@kdambekalns a simple `['__identity' => $objectArgument->getContextPath()]` got me one step further but the backend still didn't load.

**Comment by kdambekalns** [comment]
Huh… what!? That code is old! Added 2012, last change 2016–and that wasn't substantial at all… I'll try to dig into this now. And I already wonder: what do tests give us, simulating being logged in and all, if we don't test an actual login? 🤔
