### ISSUE TITLE
BUG: Neos.Media.Browser: Select a tag is not possible after selecting the tag `all`

### ISSUE THREAD

**Issue by gjwnc** [neos/neos-development-collection#3196]
### Description

If you click on the tag `All` in the Neos Media Browser, `neos/management/media`, you cannot click any other tag anymore.

### Steps to Reproduce

1. Open the Media Browser `neos/management/media`.
2. Click on the tag `All`
3. Click on any other tag than `All` and `Untagged`

#### Expected behavior

Show only the assets with the choosen tag.

#### Actual behavior

All assets are shown

### Affected Versions

Neos.Media.Browser: 5.3.1 up to current 5.3.4 is affected. I'm not sure if this also happend before.

### Possible cause and solution

The tags are rendered in `Packages/Application/Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html`. The `All` and `Untagged` tags have `tagMode` set to `1` and `2` respectively.  
I think the tagMode overrules which tag is choosen in the current request and if a `tagMode` is set, it sticks to the rendered links of the other tags, which may be because of browserState used in `Packages/Application/Neos.Media.Browser/Classes/Controller/AssetController.php`.

One solution I can think of, is just adding `tagMode` to the other tag links like this:
```
arguments="{tag: tag.object, tagMode: 0}
```

**Comment by jonnitto** [comment]
Thanks for reporting this issue. I think this is similar to #3161 
Do you want to create a PR?

**Comment by gjwnc** [comment]
Yes, I'll provide at PR with the fix I mentioned in the bugreport. I was not sure if this was the way to go here, but #3161 is pretty similar.
