### ISSUE TITLE
Missing documentation for PR 2989

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#3238]
With PR #2989 a third parameter was introduced to the sort function in Flow Query. But in the comment above the function, the description of this third parameter is missing. https://github.com/neos/neos-development-collection/blob/7.0/Neos.Neos/Classes/Eel/FlowQueryOperations/SortOperation.php#L44-L53

**Comment by jonnitto** [comment]
@tdausner, can you take care of that and create a fresh PR against the 7.0 branch?

**Comment by tdausner** [comment]
Documentation added.
