### ISSUE TITLE
Exception with Neos.Media in projects without Neos.Neos installed.

### ISSUE THREAD

**Issue by radmiraal** [neos/neos-development-collection#3258]
### Description

Since https://github.com/neos/flow-development-collection/commit/a82e8309148a2b163a8982eae22fdbb67bb0eeca the PositionalArraySorter throws exceptions if keys do not exist. Before this change the PositionalArraySorter allowed for sorting arrays which contained positions that might not lead to a really deterministic position.

I tend to agree to the exceptions in the sorter as it seems up to the context where the sorter is used to supply a valid sortable list. But I think there might be more places where we depend on the "loose" handling of the sorter. So I'm unsure if this change would require some extra thought to see if there's more areas involved (like maybe the package ordering with the `extra.neos.loading-order` configuration in the composer.json.

The first solution would be to remove the configuration of the Neos.Media package that lead to the error:

```
    mvc:
      routes:
        Neos.Media:
          position: 'before Neos.Neos'
```

If I remember it correctly this snippet was introduce to allow overriding some of the routes in the media package so they could be loaded in a view that was opened from within the Inspector in the old Neos UI. The current Neos.Media package only has a thumbnail route, which is not overwritten by Neos at all. So I assume it's safe to remove the position completely.

### Steps to Reproduce

1. Have a Flow 7 project (without Neos.Neos!)
2. Install Neos.Media
3. Try to run a CLI command like ./flow help

#### Expected behavior

Should display the help

#### Actual behavior

Fails with an exception:
`PHP Fatal error:  Uncaught Neos\Utility\Exception\InvalidPositionException: The positional string "before Neos.Neos" (defined for key "Neos.Media") references a non-existing key.`

### Affected Versions

Flow: 7.0+

**Comment by albe** [comment]
Question/possible solution: Can we configure that as `position: end` instead of relative to `Neos.Neos`? Or does it need to be `before` something else?

**Comment by radmiraal** [comment]
I see 2 possible solutions, the configuration syntax allows for 2 data types. Boolean and array.

```
      # Syntax:
      # 'Some.Package': true
      # 'SomeOther.Package':
      #   position: 'after Some.Package'
```

Solution 1:
If we make it a boolean with `'Neos.Media': true` it would work, but then I don't know if there will be issues if one extended the configuration and uses it as an array. No clue if I'm seeing ghosts here though.

Solution 2:
Just give it a value `NULL` by using `position: ~`. That's how I made my project work again locally, but it feels less clean than solution 1 as the possible issues might be ghosts...

**Comment by radmiraal** [comment]
Ah, and if it really needs to have that position I think the dependency does not belong to the Neos.Media package, but to Neos.Neos... So than I would think about moving it and then making it 'start'

**Comment by bwaidelich** [comment]
FYI: If someone comes across this issue when trying to use Neos.Media without Neos. A quick work around would be to add a few lines of `Settings.yaml` like:
```yaml
Neos:
  Flow:
    mvc:
      routes:
        'Neos.Media':
          position: 'start'
```

**Comment by albe** [comment]
☝️ I guess that's the optimal fix and we should do that in Neos.Media

**Comment by bwaidelich** [comment]
@radmiraal Currently trying to reproduce this but I already fail to install `neos/media` in my Flow 7.0 distribution because
```
neos/media 7.0.0 requires doctrine/common ^2.7 -> found doctrine/common[v2.7.0, ..., 2.13.3] but the package is fixed to 3.1.0
```

didn't you come across this issue?

**Comment by radmiraal** [comment]
> ☝️ I guess that's the optimal fix and we should do that in Neos.Media

Why would you call this optimal? The Media package only defines one route and that route is not present in the Neos.Neos package. So IMHO it's leftover config which should be cleaned instead of just "ordered to another place". I would suggest using the `position: ~` or completely remove the position by using `Neos.Media: true`.
Changing the position to `start` implies that the package routing configuration for some reason has to be loaded really early, which is not the case. And is it's not required at all we should better leave it out.

@bwaidelich nope, I didn't have that exception. Probably because I ran into it while upgrading an existing project.

**Comment by radmiraal** [comment]
@bwaidelich did you try to remove your Package folder and composer.lock? The "locked at" means that version is read from the composer state if I remember correctly.

**Comment by bwaidelich** [comment]
>  So IMHO it's leftover config which should be cleaned instead of just "ordered to another place"

Fair enough, I think that makes sense. I updated #3268 accordingly.

> did you try to remove your Package folder and composer.lock?

Doh, of course. Thanks for the hint, that works :)

**Comment by kitsunet** [comment]
I guess roughly what I was afraid of when discussing this change. But all for the better as these weird cross dependencies get uncovered.

**Comment by bwaidelich** [comment]
> I guess roughly what I was afraid of when discussing this change.

I still stand to my claim that any exception that the change produces
1. is easy to detect & fix
2. (more importantly) reveals an invalid configuration. In this case an implicit bi-direction to Neos that leads to nondeterministic behavior when used without Neos

**Comment by albe** [comment]
> Changing the position to start implies that the package routing configuration for some reason has to be loaded really early

I was under the impression that this is indeed required, because Neos.Neos contains a route that will also match and would hence make the Media package not work correctly. That was just an assumption though and I didn't check this. If it's really not the case, then yes, let's go for `Neos.Media: true`

**Comment by radmiraal** [comment]
> > Changing the position to start implies that the package routing configuration for some reason has to be loaded really early
> 
> I was under the impression that this is indeed required, because Neos.Neos contains a route that will also match and would hence make the Media package not work correctly. That was just an assumption though and I didn't check this. If it's really not the case, then yes, let's go for `Neos.Media: true`

Yes, I thought so too in the beginning as I'm sure those routes were present at some point. I think those where overwritten by Neos to allow loading the media package from within an iframe that was opened from within the inspector. But currently the media package only has 1 route (`media/thumbnail/{thumbnail}`), and there're no routes with 'thumb' in the Neos.Neos package as far as I can see ;)

**Comment by bwaidelich** [comment]
Please review #3268 - it removes the position from the `Neos.Media` package, but re-adds it in the `Neos.Neos` package. So the order is exactly the same when using Neos and depending on the package dependencies/loading order if not – just like  before
