### ISSUE TITLE
Neos.Media Tag class has incorrect doctrine mappings

### ISSUE THREAD

**Issue by tvt** [neos/neos-development-collection#3264]
### Description

The Tag class has two properties, children and parent. Their relationship is incorrectly mapped and causes doctrine validation to fail.

### Steps to Reproduce

1. Add Neos.Media 5.2 to a project
2. Run ./flow doctrine:validate

#### Expected behavior

Validation should pass.

#### Actual behavior

```
$ ./flow doctrine:validate
Mapping validation FAILED!
  Neos\Media\Domain\Model\Tag
    The field Neos\Media\Domain\Model\Tag#children is on the inverse side of a bi-directional relationship, but the specified mappedBy association on the target-entity Neos\Media\Domain\Model\Tag#parent does not contain the required 'inversedBy="children"' attribute.
```

### Affected Versions

Neos.Media version 5.2

**Comment by albe** [comment]
cc @daniellienert 

This should be easy to fix. I wonder why the mapping seems to work at runtime though?
