### ISSUE TITLE
problem whit install missing folder setup

### ISSUE THREAD

**Issue by spikerrbg** [neos/neos-development-collection#3282]
Hello. Im follow instrction for install composer whit xampp.
All its ok for extract but missing folder/ setup ?
How to install when missing folder /setup ?
You can check folder /setup missing
Good day.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Affected Versions

Neos: 

Flow: 

You can get this information by running `composer show` or using the package management module within Neos.

**Comment by spikerrbg** [comment]
![Screenshot_32](https://user-images.githubusercontent.com/79044119/107876366-41ba9f80-6ece-11eb-8ca4-865df5394c09.png)

**Comment by jonnitto** [comment]
Hi @spikerrbg 
I think it is better if you ask your question in [Slack](http://slack.neos.io) or on [Discuss](https://discuss.neos.io)

**Comment by jonnitto** [comment]
And: Welcome to the Neos world! :heart:
