### ISSUE TITLE
AFX drops whitespace unexpectedly

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#3331]
### Description

Whitespace from line breaks is removed from the output, leading to unexpected results.

### Steps to Reproduce

```
prototype(WhitespaceTest) < prototype(Neos.Fusion:Component) {
    renderer = afx`
        <p>This is a
        sentence with multiple
        words.</p>
    `
}
```

#### Expected behavior

Either 
```
<p>This This is a
sentence with multiple
words.</p>
```

or 

```
<p>This is a sentence with multiple words.</p>
```

#### Actual behavior

```
<p>This is asentence with multiplewords.</p>
```

### Affected Versions

Neos: 5.3.2 (with `neos/fusion-afx` v1.4.1)

**Comment by kdambekalns** [comment]
Aha, https://github.com/neos/fusion-afx/issues/11 handles this, too.

**Comment by kdambekalns** [comment]
Thread in https://neos-project.slack.com/archives/C050C8FEK/p1624603600107800 gave some insights:

@nezaniel said

> That's not a bug, it's a feature for minimizing content size

To which Viktor repliad:

> The feature seems to have an insufficiency. Content of a paragraph, anchor, span etc always contains only meaningful and explicitly wanted characters – even if it's trailing whitespaces – and thus should not be trimmed, in particular when the trailing space is not actually a trailing space but a space before a linebreak in the middle of the content string.
Trailing spaces within divs etc are debatable.

My take:

> I get the point about the benefits of stripping whitespace, but plain HTML handles my example from the issue just fine. Even applying HTML compression doesn't break that. So I feel rightfully upset. :slightly_smiling_face:

**Comment by creative-resort** [comment]
> ```
> afx`
>         <p>This is a 
>         sentence with multiple 
>         words.</p>
> `
> ```
should be transpiled to something like

```
Neos.Fusion:Tag {
    tagName = 'p'
    content = ${'
        This is a 
        sentence with multiple 
        words.
    '}
}
```

or

```
Neos.Fusion:Tag {
    tagName = 'p'
    content = ${'This is a sentence with multiple words.'}
}
```

If there are no whitespaces before the linebreak, none should be in the result — on the other hand, if there are, they are verbatim the content of the tag and should be retained faithfully.

**Comment by kdambekalns** [comment]
Some more stuff I wrote in Discourse:
---
I think I came across this in this code:

    renderer = afx`
        <footer class="footer container">
            <div class="grid">
                <div class="footer__header">
                    <Acme.Com:Component.Layout.SocialMedia />
                </div>
                <div class="footer__content row">
                    … more stuff here …
                </div>
                <div class="footer__disclaimer">
                    © {Date.format(Date.now(), 'Y')} Acme Inc. All rights reserved.
                    <Neos.Fusion:Loop items={props.legalPages} itemName="legalPage"> | <a href={legalPage.href}>{legalPage.title}</a></Neos.Fusion:Loop>
                </div>
            </div>
        </footer>
    `
Now there is a loop, but earlier it had this:

                <div class="footer__disclaimer">
                    © {Date.format(Date.now(), 'Y')} Acme Inc. All rights reserved.
                    <a href={legalPage1.href}>{legalPage1.title}</a> |
                    <a href={legalPage2.href}>{legalPage2.title}</a> |
                    <a href={legalPage3.href}>{legalPage3.title}</a> |
                </div>

The result was:

    © 2021 Acme Inc. All rights reserved.<a href="1">Title 1</a>|<a href="2">Title 2</a>|<a href="3">Title 3</a>

Which renders as:

    © 2021 Acme Inc. All rights reserved.Title 1|Title 2|Title 3

Way too littl whitespace for my… No, this is not the time to discuss solutions involving `:after` on links in the footer. And using a `Value`object here seems over the top, too.

When I came across the case above, I remembered another one, where I also "lost" whitespace, _simply because I wanted to format my source nicely_. (TBH: If I want my HTML compressed, I do this explicitly. Usually I like well-formatted source code, including HTML.)

This seems to try to replicate whitespace handling of XML, but that is a tad bit more complex, I fear. :wink:

**Comment by kdambekalns** [comment]
Ok, this is what the AFX documentation says, go to point number 5: https://docs.neos.io/cms/manual/rendering/afx#html-to-fusion-in-a-nutshell
