### ISSUE TITLE
BUG: Error occurs when trying to delete an asset in the media UI

### ISSUE THREAD

**Issue by beromir** [neos/neos-development-collection#3349]
### Description

An error occurs when trying to delete an asset in the media UI in Neos.
We tested it with a fresh installation of Neos, so no other package should have an impact.

**Error message:**  
```
Exception in line 477 of /var/www/html/Data/Temporary/Development/SubContextDocker/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Controller_ActionController.php: Argument 1 passed to Neos\Media\Browser\Controller\AssetController::deleteAction() must be an instance of Neos\Media\Domain\Model\Asset, null given, called in /var/www/html/Data/Temporary/Development/SubContextDocker/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Controller_ActionController.php on line 477

43 Neos\Media\Browser\Controller\AssetController::deleteAction(NULL)
42 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
41 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
40 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
39 Neos\Flow\Mvc\Dispatcher_Original::dispatch(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
38 Neos\Neos\Controller\Backend\ModuleController_Original::indexAction(array|3|)
37 Neos\Neos\Controller\Backend\ModuleController::indexAction(array|3|)
36 Neos\Neos\Controller\Backend\ModuleController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
35 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
34 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
33 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
32 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
31 Neos\Neos\Controller\Backend\ModuleController::indexAction(array|3|)
30 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
29 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
28 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
27 Neos\Flow\Mvc\Dispatcher_Original::dispatch(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
26 Neos\Flow\Mvc\DispatchMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
25 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
24 Neos\Flow\Http\Middleware\SecurityEntryPointMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
23 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
22 Neos\Flow\Http\Middleware\RequestBodyParsingMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
21 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
20 Neos\Flow\Mvc\FlashMessage\FlashMessageMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
19 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
18 Neos\Flow\Http\Middleware\PoweredByMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
17 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
16 Neos\RedirectHandler\RedirectMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
15 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
14 Neos\Flow\Mvc\Routing\RoutingMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
13 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
12 Neos\Neos\Routing\RequestUriHostMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
11 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
10 Neos\FluidAdaptor\Core\Widget\AjaxWidgetMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
9 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
8 Neos\Flow\Http\Middleware\SessionMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
7 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
6 Neos\Flow\Http\Middleware\TrustedProxiesMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
5 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
4 Neos\Flow\Http\Middleware\StandardsComplianceMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
3 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
2 Neos\Flow\Http\RequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()
```

### Steps to Reproduce

1. Go to the media module in the Neos backend
2. Click `Delete` in the dropdown on an asset
3. Error occurs

#### Expected behavior

The asset should be deleted without an error.

#### Actual behavior

The asset is not deleted and it comes to an error.

### Affected Versions

Neos: `7.1.0`

Flow: `7.1.0`

**Comment by kdambekalns** [comment]
It works when deleting from the details screen (viable workaround for now)…

**Comment by kdambekalns** [comment]
Link from dropdown:

`https://…/neos/management/media?moduleArguments%5B%40package%5D=neos.media.browser&moduleArguments%5B%40controller%5D=asset&moduleArguments%5B%40action%5D=index&moduleArguments%5B%40format%5D=html#delete-asset-modal`

Link from details screen:

`https://…/neos/management/media?moduleArguments%5B%40package%5D=neos.media.browser&moduleArguments%5B%40controller%5D=asset&moduleArguments%5B%40action%5D=edit&moduleArguments%5B%40format%5D=html&moduleArguments%5BassetSourceIdentifier%5D=neos&moduleArguments%5BassetProxyIdentifier%5D=e315c76a-cce9-41ea-a26e-b397c638b334&moduleArguments%5B%40subpackage%5D=#asset-e315c76a-cce9-41ea-a26e-b397c638b334`

I think the `#delete-asset-modal` is the interesting part – looks as if that should trigger a confirmation, no trigger some action immediately.

**Comment by kdambekalns** [comment]
In 7.0 of the UI it works, a conformation modal is shown. In 7.1 it is broken…

**Comment by kdambekalns** [comment]
🤔 Now it works, after I opened the developer tools (i.e. flushed browser caches). But I get a ton of these:

`Uncaught TypeError: window.NeosCMS.Tools is undefined` from `collections-and-tagging.js:133:29`

**Comment by kdambekalns** [comment]
Responsible code: https://github.com/neos/neos-development-collection/blob/895d0b9170d58d386705a382af9ea34ef5979bbd/Neos.Media.Browser/Resources/Public/JavaScript/collections-and-tagging.js#L131-L140

**Comment by kdambekalns** [comment]
`Tools` added with https://github.com/neos/neos-development-collection/commit/f27feb779ccc4421d06cf0f105d3da779922939c and renamed to `Helper` with https://github.com/neos/neos-development-collection/commit/c0ce02222e34ca5a0e972fd294ed322fca6ab3f1 – both part of the same PR #3302. It seems as if the media browser was adjusted after the first but forgotten with the second change.

**Comment by mhsdesign** [comment]
### I have the same Problem with Neos 7.1

Additionally, no asset name is shown when trying to delete an item from the 'Content workspace'.
`Do you really want to delete asset "{0}"?`
![image](https://user-images.githubusercontent.com/85400359/121139888-8d0c0b80-c839-11eb-93da-303d4a6d19da.png)
Console:
(no logs until "Yes, delete the asset" is clicked)
![image](https://user-images.githubusercontent.com/85400359/121142602-73b88e80-c83c-11eb-8b6d-54648ae5356f.png)

-----------

The 'Media workspace' seems fine:
![image](https://user-images.githubusercontent.com/85400359/121139956-9dbc8180-c839-11eb-9458-3cce4ba821ae.png)
Console:
(this is logged, when using the dropdown menu and selecting "Delete")
![image](https://user-images.githubusercontent.com/85400359/121142340-2d632f80-c83c-11eb-962a-566eb6cd7af9.png)

-----------

Both button clicks will either way lead to the Error stated above (https://github.com/neos/neos-development-collection/issues/3349#issue-910392203).

----------

Only the workaround is working ;) https://github.com/neos/neos-development-collection/issues/3349#issuecomment-856078263

**Comment by markusguenther** [comment]
Hello,

I took some time to check that, and it should work now. Feel free to review the change and then it will be part of the next bugfix release ;)


https://user-images.githubusercontent.com/1014126/123411349-a38fc200-d5b0-11eb-818a-de5a9d7011c0.mp4
