### ISSUE TITLE
DimensionsMenu shows links to documents having hidden parent(s)

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#3363]
### Description

The `DimensionsMenu` links to documents that are not accessible due to a hidden parent somewhere in the tree.

### Steps to Reproduce

1. In the demo site hide the "Features" page in "English (UK)"
2. Go to …/en/features/shortcuts/shortcut-to-child-node/down-the-rabbit-hole.html
3. In the language switch click the "English (UK)" link, pointing to …/uk/features/shortcuts/shortcut-to-child-node/down-the-rabbit-hole.html
4. Look at the 404 page, puzzled

#### Expected behavior

The language switch should not link to the hidden document.

#### Actual behavior

It links to the hidden document.

### Affected Versions

Neos: 5.3 and probably above

**Comment by kdambekalns** [comment]
The `DimensionsMenuImplementation` has a check method called `hasHiddenNodeParent(…)`:

https://github.com/neos/neos-development-collection/blob/12a5a1a98a0f004c188f181478cddbf22d09de49/Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php#L235-L241

The comparison in this is wrong. Because the depth is 0-based, but the nodes returned by `getNodesOnPath(…)` contain the root node, less-than-or-equal must be used.

**Comment by lorenzulrich** [comment]
If anyone should land here after the DimensionsMenu doesn't show other "languages" anymore (after updating from an old version of Neos 5.3), consider using `./flow node:repair --only removeContentDimensionsFromRootAndSitesNode` as documented in https://github.com/neos/neos-development-collection/issues/3690.
