### ISSUE TITLE
no pdf thumbnail generation Imagick

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3373]
### Description

i have an issue with pdf thumbnail generation on Neos 7.1 with Imagick.

### Steps to Reproduce

1. install neos demo
2. go to the media module
3. find the pdf `neos-1.2.0-deps-graph.pdf`

#### Expected behavior

you see a thumbnail

#### Actual behavior

you see an endless loading spinner:
![image](https://user-images.githubusercontent.com/85400359/124516910-09671f80-dde3-11eb-8597-fed93043ce30.png)

#### Digging further:

when you inspect (dev tools) the loading spinner, and search for the img tag which should display the thumbnail, and follow the source (something like: `http://my-cool.site/media/thumbnail/4b1f64bb-14d9-47fc-98e9-4a4ae6161faa`), you will get a 500 error:

-------------
-------------
-------------
<div class="Flow-Debug-Exception-Header"><h1 class="ExceptionSubject">Unable to generate thumbnail for the given document (filename: neos-1.2.0-deps-graph.pdf, SHA1: c0e682d8e660aa3f102d6269915c6a13fa69ed3e)</h1><table class="Flow-Debug-Exception-Meta"><tbody><tr><th>Exception Code</th><td class="ExceptionProperty">1433109652</td></tr><tr><th>Exception Type</th><td class="ExceptionProperty">Neos\Media\Exception\NoThumbnailAvailableException</td></tr><tr><th>Log Reference</th><td class="ExceptionProperty">20210705210423f47a6e</td></tr><tr><th>Thrown in File</th><td class="ExceptionProperty">Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Media_Domain_Model_ThumbnailGenerator_DocumentThumbnailGenerator.php</td></tr><tr><th>Line</th><td class="ExceptionProperty">95</td></tr><tr><th>Original File</th><td class="ExceptionProperty">Packages/Application/Neos.Media/Classes/Domain/Model/ThumbnailGenerator/DocumentThumbnailGenerator.php</td></tr></tbody></table><br><h2>Nested Exception</h2><h1 class="ExceptionSubject">attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408</h1><table class="Flow-Debug-Exception-Meta"><tbody><tr><th>Exception Code</th><td class="ExceptionProperty">499</td></tr><tr><th>Exception Type</th><td class="ExceptionProperty">ImagickException</td></tr><tr><th>Thrown in File</th><td class="ExceptionProperty">Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Media_Domain_Model_ThumbnailGenerator_DocumentThumbnailGenerator.php</td></tr><tr><th>Line</th><td class="ExceptionProperty">63</td></tr><tr><th>Original File</th><td class="ExceptionProperty">Packages/Application/Neos.Media/Classes/Domain/Model/ThumbnailGenerator/DocumentThumbnailGenerator.php</td></tr></tbody></table></div>

-------------
-------------
-------------

![image](https://user-images.githubusercontent.com/85400359/124517266-d709f200-dde3-11eb-98b2-59d876df2195.png)

#### More detail:

This happens with all pdfs. Also newly uploaded.
The detail view works fine:

![image](https://user-images.githubusercontent.com/85400359/124517083-5a771380-dde3-11eb-9c36-9543bd41ac2a.png)

### Affected Versions
The 'default' driver GD (when i comment out `Neos -> Flow -> Imagine`) seems to work. GD doesnt create a thumbnail, and you will see a pdf icon svg (`/_Resources/Static/Packages/Neos.Media/IconSets/vivid/pdf.svg`):
![image](https://user-images.githubusercontent.com/85400359/124518620-2d2c6480-dde7-11eb-980d-be6d4b16960a.png)

To my knowledge:

Neos: 7.1

Flow:  7.1

**Comment by PRGfx** [comment]
The error with the security policy gives a clear hint on the ImageMagick policy.xml (https://imagemagick.org/script/security-policy.php) which by default forbids actions on PDF files.
You would need to adjust the configuration in your ImageMagick Policy to something like `<policy domain="coder" rights="read|write" pattern="PDF" />`.
(The details-view is a JS PDF viewer)

**Comment by mhsdesign** [comment]
Oops thanks it worked @PRGfx !

I only needed to create a config file, where ImageMagick expects it: `$HOME/.config/ImageMagick/policy.xml`
(One can also set the environment variable `MAGICK_CONFIGURE_PATH` to the directory where your policy.xml is in.)
And added in this policy.xml your snippet:

> `<policy domain="coder" rights="read|write" pattern="PDF" />`.

(This policy.xml will now override the default one in `/etc/ImageMagick-6/policy.xml`)
