### ISSUE TITLE
Discard of the deletion of a page-node does not discard everything

### ISSUE THREAD

**Issue by GuangHa** [neos/neos-development-collection#3387]
### Description

Discarding of **all** selected changes in workspaces does not discard all the changes.

### Steps to Reproduce

1. Delete a page with content in document tree
2. Go to workspaces and click on "Überprüfen"
3. Select all Checkboxes
![grafik](https://user-images.githubusercontent.com/12826344/127321311-3faa99c2-c113-4b47-b7a6-511d3d828ebd.png)
4. Discard the selected changes
![grafik](https://user-images.githubusercontent.com/12826344/127321398-f73c3c26-9e18-44dc-aaca-050564b8858b.png)
5. Go back to the Content
6. You are now able to see that there are still open changes
7. The page that you deleted (and then discarded the changes via the described steps) is now broken

#### Expected behavior

It should discard all the changes made.

#### Actual behavior

It discards not all the changes, some are left even if it doesn't show it:
![grafik](https://user-images.githubusercontent.com/12826344/127323250-7c58b6b4-44cc-4108-aa2d-ae2d8e1f7471.png)
But when you go to the Content it shows that there are changes to be published:
![grafik](https://user-images.githubusercontent.com/12826344/127323336-e3ad58e1-3f8b-4b2d-8a28-79aa3c9ddcea.png)

### Affected Versions
I tested it on two Neos versions.

Neos: 4.3.19
Flow: 5.3.26

Neos: 5.3.3
Flow: 6.3.11

### Additional Question
Sometimes people misclick the Button "Ausgewählte Änderungen verwerfen" (don't know the used english term for this button). If it's clicked you lose the selected changes and it cannot be recalled. Is it possible to add a popup to confirm the discarding? There is a confirm-popup for "Alle Änderungen verwerfen" but not for "Ausgewählte Änderungen verwerfen".

**Comment by kdambekalns** [comment]
Essentially the same as #3274

**Comment by kdambekalns** [comment]
Fixed in 7.1.1 – 7.0.3 – 5.3.4
