### ISSUE TITLE
Fusion: "Neos.Fusion:Case" object - combine key with @process

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3388]
### Description

When using a process (that changes the 'value' in any kind) directly on a false key of "Neos.Fusion:Case" a following true key wont be rendered with success.

### Steps to Reproduce

1. Goto https://fusionpen.punkt.de/fusionpen/3d4e4215ad94834cef22ee1ab8ddeef9fbf528cf.html
2. or run:

```
prototype(My:Case) < prototype(Neos.Fusion:Case) {

    isFalse {
        condition = ${false}
        renderer = "should not be displayed"
        @process.anything= ${value + ' test'}
    }

    isTrue {
        condition = ${true}
        renderer = "should be displayed"
    }
}

```

#### Expected fusion behavior

```
should be displayed
```

#### Actual fusion behavior 

```
"_____________NO_MATCH_RESULT_____________"
```

### What works:

1. rendering the condition with the process
`isFalse.condition = ${true}` -> renders `should not be displayed test`
2. moving the isFalse key to the bottom (in the code or via `@position = "end"`)
3. removing the process
4. using this process `isFalse.@process.anything= ${value}`
5. using `isFalse.renderer.@process.anything` - but that wont work for renderPath
6. using renderer with an additional "Neos.Fusion:Renderer"

**Comment by Sebobo** [comment]
But your Fusionpen example works fine when changing the process to apply to the `renderer`.

Don't think there is an adjustments needed therefore. 
`isFalse` is not the actual result of the implementation, but the `renderer`. So applying the process to the condition doesn't make too much sense IMO.

**Comment by mhsdesign** [comment]
Yes; you are right - applying it on the condition doesnt make sense. And i was using a too complex renderPath wrongly with the `@process`.

I was playing around with the `renderPath` like a `type` (https://fusionpen.punkt.de/fusionpen/76384575e49fdc9c7ac72a4aa7a434a69da5ee46.html):

and found out that this is just wrong:
```
renderPath = ${"<My:Prototype>/data"}
renderPath.@process.json = ${Json.stringify(value)}
```

instead this would work:
```
renderPath = ${"element<My:Prototype>/data"}
element.data.@process.json = ${Json.stringify(value)}
```
