### ISSUE TITLE
Asset search is case sensitive depending on the used database

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#3432]
### Description

When searching for assets in the media module or directly via the AssetRepository you get different results based on the connected database.

MySQL runs the used `like` queries case insensitive.
Postgres runs the same queries case sensitive.

### Steps to Reproduce

1. Setup two Neos demo sites with different databases (MySQL and Postgres)
2. Search for a lowercased named asset with an uppercase searchword
3. Compare results

#### Expected behavior

Queries with both databases return the same results

#### Actual behavior

Postgres returns less results or none

### Affected Versions

Neos: all up until 7.1

**Comment by Alex-Schulte** [comment]
I found a workaround to get this to work (in Neos 8.2.5)  (but didn't check the performance)
The postgres like match with lower() could be optimized

[AssetRepositoryAspect.txt](https://github.com/neos/neos-development-collection/files/12370911/AssetRepositoryAspect.txt)

**Comment by Sebobo** [comment]
Thx @Alex-Schulte works fine, and I see no big performance impact! Will create a PR to fix this.
