### ISSUE TITLE
Allow asset sources to change the count of assets per tag in the MediaBrowser

### ISSUE THREAD

**Issue by pKallert** [neos/neos-development-collection#3452]
### Description
When creating a new asset source for the Media Browser, the interface does not allow changing the count of assets per tag in the left sidebar. 

### Steps to Reproduce

1. Create a new media asset source (like this one: https://github.com/flownative/neos-canto)
2. Implement the supportsTaggingInterface in the ProxyRepository 
3. Make the assets source not-readonly 

#### Expected behavior
When changing the asset source, I would expect that the count of assets per tag in the left sidebar change according to the new asset soure. 

#### Actual behavior
When changing the asset source, the count of assets per tag in the left sidebar counts the assets in the Neos asset source.  

### Affected Versions
Neos: 7.3

**Comment by markusguenther** [comment]
As I am not the media expert, maybe @daniellienert or @kitsunet have some comments.
TBH I don't know why this is not part of the interface but maybe caused by the proxys.

Anyway, awesome that @pKallert created the first PR and issue 🎉

**Comment by jonnitto** [comment]
Cudos for you first issue and PR @pKallert
