### ISSUE TITLE
BUG: Fusion does not clear lastEvaluationStatus in certain case

### ISSUE THREAD

**Issue by gjwnc** [neos/neos-development-collection#3469]
### Description

We noticed, that in the `Neos.Seo` package, the rendered fusion output depends on the order of the evaluated properties which, I think, is based on a bug regarding an internal fusion state.  

As an example, the following fusion code is relevant:  
- [Neos.Seo:StructuredData.Website](https://github.com/neos/neos-seo/blob/master/Resources/Private/Fusion/StructuredData/RootObjects/Website.fusion)
- [Neos.Seo:StructuredData.Website.SearchAction](https://github.com/neos/neos-seo/blob/master/Resources/Private/Fusion/StructuredData/Objects/WebsiteSearchAction.fusion)
- [Neos.Seo:StructuredData.Object](https://github.com/neos/neos-seo/blob/master/Resources/Private/Fusion/StructuredData/Object.fusion)

In, `Neos.Seo:StructuredData.Website`, the rendererd fusion output is different if you rearrange the properties to the following order:
```
    potentialAction = Neos.Seo:StructuredData.Website.SearchAction
    name = ${site.label}
    url = Neos.Neos:NodeUri {
        absolute = true
        node = ${site}
    }
```

If no `targetNode` is set and `potentialAction` is not the last one rendered, the output is correct.  
On the other hand, if no `targetNode` is set and `potentialAction` is the last line evaluated, then `@apply` in `Neos.Seo:StructuredData.Object` is not evaluated correctly.

### Which code steps are causing this behaviour

Assumptions and short overview:  
Let's assume that `targetNode` is null. The property `targetNode` is used by the last rendered property `potentialAction` in `Neos.Seo:StructuredData.Website.SearchAction`. Thus the statement ` @if.hasTargetNode = ${this.targetNode}` will be `false`.

What is happening:  
In `Neos.Seo:StructuredData.Object` the `@apply.attributes = ${props.attributes ? Array.filter(props.attributes, attribute => attribute != null) : []}` will be evaluted incorrectly.  
So let's start in [`evaluateApplyValues`](https://github.com/neos/neos-development-collection/blob/master/Neos.Fusion/Classes/Core/Runtime.php#L762). In `$key` is the value `attributes` which is the correct fusion path to evaluate.  
The `@apply` is then calling [`evaluate`](https://github.com/neos/neos-development-collection/blob/master/Neos.Fusion/Classes/Core/Runtime.php#L775) for all the attributes available, that is `name`, `url` and `potentialAction`. The last one evaluated is `potentialAction`.  
For `potentialAction`, the method [`evaluateObjectOrRetrieveFromCache`](https://github.com/neos/neos-development-collection/blob/master/Neos.Fusion/Classes/Core/Runtime.php#L455) set's the local `$evaluationStatus` to `EVALUATION_SKIPPED` and then test's the `@if` condition using the `targetNode` which results in `false`, thus [`$evaluateObject = false`](https://github.com/neos/neos-development-collection/blob/master/Neos.Fusion/Classes/Core/Runtime.php#L466).  
Now the global [`lastEvaluationStatus`](https://github.com/neos/neos-development-collection/blob/master/Neos.Fusion/Classes/Core/Runtime.php#L474) is, kind of, correctly, set to skipped. Since this was the last evaluated statement, we get back to [`evaluateApplyValues`](https://github.com/neos/neos-development-collection/blob/master/Neos.Fusion/Classes/Core/Runtime.php#L776). Since the internal `lastEvaluationState` is skipped, the `@apply` is completely ignored and `$combinedApplyValues` is empty - which it shouldn't in this example, since `name` and `url` were successful.

### Steps to Reproduce

1. Install Neos.Seo package for demonstration purpose
2. Open the home of the site package
3. You should find something like this in `<head>`
```
<script type="application/ld+json">{"@context":"http:\/\/schema.org","@type":"WebSite"}</script>
```
This is wrong, since `name` (= `site.label`) and `url` should be in the json.
4. Rearrange the fusion properties of `Neos.Seo:StructuredData.Website`, such that `potentialAction` is not evaluated as the last one:
```
    potentialAction = Neos.Seo:StructuredData.Website.SearchAction
    name = ${site.label}
    url = Neos.Neos:NodeUri {
        absolute = true
        node = ${site}
    }
```
5. Now you get correct result in `<head>`
```
<script type="application/ld+json">{"@context":"http:\/\/schema.org","@type":"WebSite","name":"Some test site","url":"http:\/\/some.domain\/"}</script>
```

#### Expected behavior

The rendered fusion should be independent of the `@if` condition of the last evaluated property of a fusion prototype.

#### Actual behavior

`@apply` is not evaluated if the last evaluated property has `false` `@if` condition.

### Affected Versions

Neos: >= 5.3 (very likely also earlier versions)

Flow:

**Comment by mhsdesign** [comment]
Thanks for the report. I can confirm this.

Browserfied version: https://fusionpen.punkt.de/fusionpen/a414603d113183f17bcfb7573be746c19490651f.html

<details>

<summary>Fusion Code</summary>


```ts

prototype(Neos.Seo:StructuredData.Website) < prototype(Neos.Fusion:Component) {

    //                  //
    // Uncomment me!    //
    //                  //
    // potentialAction = Neos.Seo:StructuredData.Website.SearchAction
    name = ${site.label}
    url = Neos.Neos:NodeUri {
        absolute = true
        node = ${site}
    }
    //                  //
    // Comment me out!  //
    //                  //
    potentialAction = Neos.Seo:StructuredData.Website.SearchAction

    renderer = afx`<Neos.Seo:StructuredData.RootObject type="WebSite" attributes={props}/>`
}


prototype(Neos.Seo:StructuredData.RootObject) < prototype(Neos.Seo:StructuredData.Object) {
    context = 'http://schema.org/'
    @process.toJson = ${Json.stringify(value)}
    // @process.wrap = ${'<script type="application/ld+json">' + value +  '</script>'}
}


prototype(Neos.Seo:StructuredData.Object) < prototype(Neos.Fusion:Component) {
    // Optional context. Usually "http://schema.org" for root objects
    context = ''

    // The required `schema.org` type for this object
    type = ''

    // Inherit props from parent object into data. These can be accessed in the renderer via props.data.
    data = ${props}

    // All attributes will be applied to the resulting object
    attributes = Neos.Fusion:DataStructure

    renderer = Neos.Fusion:DataStructure {
        '@context' = ${props.context}
        '@context'.@if.isSet = ${props.context}
        '@type' = ${props.type}
        @apply.attributes = ${props.attributes ? Array.filter(props.attributes, attribute => attribute != null) : []}
    }
    @if.hasType = ${this.type}
}

prototype(Neos.Seo:StructuredData.Website.SearchAction) < prototype(Neos.Fusion:Component) {
    @if.hasTargetNode = ${this.targetNode}

    targetNode = null
    queryInput = 'required name=search_term_string'
    queryParameters = Neos.Fusion:DataStructure {
        search = '{search_term_string}'
    }

    renderer = afx`
        <Neos.Seo:StructuredData.Object type="SearchAction" attributes.query-input={props.queryInput}>
            <Neos.Neos:NodeUri absolute={true} node={props.targetNode} additionalParams={props.queryParameters}
                @path="attributes.target"
                @process.decode={String.rawUrlDecode(value)}/>
        </Neos.Seo:StructuredData.Object>
    `
}


prototype(Neos.Seo:StructuredData.Object) < prototype(Neos.Fusion:Component) {
    // Optional context. Usually "http://schema.org" for root objects
    context = ''

    // The required `schema.org` type for this object
    type = ''

    // Inherit props from parent object into data. These can be accessed in the renderer via props.data.
    data = ${props}

    // All attributes will be applied to the resulting object
    attributes = Neos.Fusion:DataStructure

    renderer = Neos.Fusion:DataStructure {
        '@context' = ${props.context}
        '@context'.@if.isSet = ${props.context}
        '@type' = ${props.type}
        @apply.attributes = ${props.attributes ? Array.filter(props.attributes, attribute => attribute != null) : []}
    }
    @if.hasType = ${this.type}
}

```


</details>

**Comment by mhsdesign** [comment]
Shrinked down version to reproduce bug easily:

```ts


prototype(Neos.Apply.Bug:Demo) < prototype(Neos.Fusion:Component) {
    @process.htmlViewAble = ${Json.stringify(value)}

    //                  //
    // Uncomment me!    //
    //                  //
    // unevalObject = Neos.Fusion:Value {
    //     @if.never = false    
    // }
    
    normal = "things"
    foo = "bar"
    
    //                  //
    // Comment me out!  //
    //                  //
    unevalObject = Neos.Fusion:Value {
        @if.never = false    
    }

    renderer = Neos.Fusion:Component {

        explicit = "hello"
        attributes = ${props}

        renderer = Neos.Fusion:DataStructure {
            '@explicitPropsWork' = ${props.explicit}
            @apply.attributes = ${props.attributes ? Array.filter(props.attributes, attribute => attribute != null) : []}
        }
    }
}


```

**Comment by mhsdesign** [comment]
i think the problem lies somewhere in passing the lazy props and force the evaluation of those via an eel helper.

the props are here `${props.attributes ? Array.filter(props.attributes, attribute => attribute != null) : []}`  still lazy i think: eg not evaluated `Array.filter` will enforce the evaluation of the props ... and then something breaks.


when one leaves out the filter eg. only uses: `@apply.attributes = ${props.attributes}` it works...

**Comment by mhsdesign** [comment]
@gjwnc i looked at the runtime code now and can confirm its excacly like you said ;)

so lesson learned: never only use the `$this->getLastEvaluationStatus()` but also check if what you got is actually null.
