### ISSUE TITLE
Content cache containing internal links is not flushed when the target page is changed

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#3482]
### Description

When creating internal links to other pages, the content containing those links should be updated whenever the target page is disabled or removed in order to prevent broken links.

### Steps to Reproduce

1. Edit text content on a page (a) linking to another page (b)
2. Render the page (a) in Frontend to make sure the link is displayed (and a cache entry is being created)
3. Disable the target page (b)
4. Refresh the Frontend

#### Expected behavior

The link to page (b) is removed (i.e. `...<a href="...">link</a>...` is turned into just `...link...`)

#### Actual behavior

The link still exists and leads to a 404 when clicked.

### Affected Versions

Neos: 5.3

**Comment by jonnitto** [comment]
Can we close this, as the PR is merged?
