### ISSUE TITLE
Deprecate Fusion Namespaces

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#3498]
The fusion namespace feature is not used by projects we are aware of in ages.

I suggest to deprecate this with 7.3 and to remove it with 8.0.

- [x] Add deprecation notice for namespace to parser and parser interface
- [ ] adjust fusion documentation https://docs.neos.io/cms/manual/rendering/fusion/in-depth

**Comment by kitsunet** [comment]
Yes!

**Comment by mhsdesign** [comment]
can we implement something that the fusion parser writes a warning to the log/website/js-console when the namespace alias feature is used?

**Comment by mficzel** [comment]
We probably could use https://github.com/symfony/deprecation-contracts but i think that is to much for this issue. Maybe we can write an RFC about using deprecation contracts on discuss and then if we agree upon it add it to flow separately.

For the issue here i would just add it to the release notes of Neos 7.3 and the docs.

**Comment by mhsdesign** [comment]
i made the Changes in the docs already they just need to be reviewed: https://docs.neos.io/neos/management/workspaces/show?moduleArguments[workspace][__identity]=to-be-reviewed-marc-henry-pciv5

and adding the '@depreceated' wont take long. Can we get this still into 7.3 so it would be possible in 8.0 to have a parser without namespace support?

**Comment by jonnitto** [comment]
Yes, I think this should go into 7.3

**Comment by mficzel** [comment]
Also think adding @deprecated would still be fine but the Release Managers have to decide.

Question is where to add it as the only api method that will change the behavior is Parser->parse which is not deprecated entirely but slightly alters behavior.

Sending a Notice when namespace is used would be nice but i would not start that for this case. We should discuss that for Neos and Flow in general. I would really like to have framework support for deprecations.

For now i think it is important to adjust the docs as you prepared and make sure the Release Notes and Blogpost contain a section about the deprecations.

**Comment by mhsdesign** [comment]
added this one to the Reviews Needed board okay? @jonnitto

**Comment by jonnitto** [comment]
Who will take care of the PR?

**Comment by mficzel** [comment]
@jonnitto the documentation update needs review other than that this is a thing for the release post.
