### ISSUE TITLE
Absolute include paths in Fusion

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3507]
FYI: This issue leads with the solution instead of the problem... 

---

There was the idea to have absolute includes starting with '/' (Like include: `/NodeType/**/*.fusion`) which should symbol the root of the package. (will be resolved to resource://Vendor.Name/../NodeTypes/**/*.fusion)

The problem is the current parser treats absolute looking paths (starting with a '/') like relative paths. That means the dirname of the currentFileNameContext will be appended and one gets a path like `resource://Neos.Demo/Private/Fusion//file.fusion` what one might think doesnt make sense and shouldnt work - but php seems to ignore the second slash and the path works nicely with file get contens. That means that for the current parsing progress `include: /file.fusion` or `include: /**/*` behaves like `include: file.fusion` or `include: **/*`.

The question is, should absolute paths get an actual use and did someone accidentally put a '/' infront of their includes (what would mean that the change is breaking - but i consider this a bug)?

**Comment by mhsdesign** [comment]
As discussed with @mficzel the idea is that we will just break this 'functionality' at first. Later we can decide whether we want support paths like `include: /.....`

> and `resource://Vendor.Name/../NodeTypes/**/*.fusion` still suffers from a ..  in the middle, I think we should find a better  way to include those fusion files.
resource:// refers to resources … maybe we define package:// in addition to that

**Comment by mhsdesign** [comment]
we could also of course introduce a `package://` or `nodetypes://` file stream wrapper....

**Comment by mficzel** [comment]
I think package:// would make most sense.

**Comment by mhsdesign** [comment]
well `package://Vendor.Site/Configuration/Settings.yaml` can be archived today via `resource://Vendor.Site/../Configuration/Settings.yaml` same with classes ... but i do get your point ^^

**Comment by mhsdesign** [comment]
Closing in favor of #3903
