### ISSUE TITLE
@if not handled correctly in "sparse" DataStructure

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#3513]
### Description

When using `Neos.Fusion:DataStructure` in "sparse" format, like this:

    foo = Neos.Fusion:DataStructure {
        bar {
            baz = 1
        }
    }

the "missing types are filled in" by the implementation: https://github.com/neos/neos-development-collection/blob/3eefe80a99a69526474823b195cc6ae513f10f14/Neos.Fusion/Classes/FusionObjects/DataStructureImplementation.php#L41-L43

Now, when using `@if` in such code, things break.

### Steps to Reproduce

```
prototype(YourVendor:FusionPrototype) < prototype(Neos.Fusion:Component) {
    searchValue = Neos.Fusion:DataStructure {
        foo {
            is {
                visible = 1
            }
            not {
                @if.test = true
                visible = 10
            }
        }
    }
    renderer = ${'<pre>' + Json.stringify(props.searchValue, ['JSON_PRETTY_PRINT']) + '</pre>'}
}
```

#### Expected behavior

The above code should result in:

```json
{
    "foo": {
        "is": {
            "visible": 1
        },
        "not": {
            "visible": 10
        }
    }
}
```

#### Actual behavior

As can be seen on https://fusionpen.punkt.de/fusionpen/89494fb81a307936503032379f283654ef0da1ec.html this is the actual result:

```json
{
    "foo": {
        "is": {
            "visible": 1
        }
    }
}
```

It can be fixed by declaring the type, as in https://fusionpen.punkt.de/fusionpen/690964c11a0c19be1e0b11f9a47f5394c3ba8669.html

Weird behaviour **BONUS** issue with `@process` in the mix: https://fusionpen.punkt.de/fusionpen/a166a8451d875a48c8d85c192272368911255997.html 😵

### Affected Versions

Neos: 5.3+ (possible earlier versions, too)

**Comment by kitsunet** [comment]
IMHO to make this work correctly the type must be known to the runtime (which it is not in the current implementation), so basically the parser would have to add that type silently.

**Comment by kdambekalns** [comment]
Which poses the question if this is even desired. Right now the magic to allow this is in the DataStructure implemenation, the parser has no clue. I'm not sure the parser should even know such tricks that are isolated to a certain prototype.

In this case that would mean: `@if` without a known type should not "fail silently" but throw an exception that hints at a cause and thus solution. WDYT?

**Comment by bwaidelich** [comment]
IMO it would be cool if the parser _could_ support this "untyped" datastructures like
```
prototype(YourVendor:FusionPrototype) < prototype(Neos.Fusion:Component) {
    searchValue = {
        foo {
            is {
                visible = 1
            }
            not {
                @if.test = true
                visible = 10
            }
        }
    }
}
```

**Comment by mhsdesign** [comment]
@bwaidelich the syntax `= {` would be easy to implement with the rewritten parser ;)

> Which poses the question if this is even desired. Right now the magic to allow this is in the DataStructure implemenation, the parser has no clue. I'm not sure the parser should even know such tricks that are isolated to a certain prototype.

makes sense to me, parser only parses without object specific logic.

**Comment by kdambekalns** [comment]
> makes sense to me, parser only parses without object specific logic

Is parsing `@if` and/or `@process` reliably possible for untyped structures? Because that's what would need to happen - the parser cannot fill in types here, without knowing the implementation.

**Comment by kdambekalns** [comment]
> IMO it would be cool if the parser _could_ support this "untyped" datastructures like

@bwaidelich What would the type be for those keys?

**Comment by bwaidelich** [comment]
> What would the type be for those keys?

Maybe I'm being too naïve here, but I expected

```
searchValue = {
  foo = 'bar'
}
```
to be the same as
```
searchValue = ${{foo: 'bar'}}
```

**Comment by kdambekalns** [comment]
> Maybe I'm being too naïve here, but I expected

Fair enough, so no prototypes involved at all. Then again, do we need that syntactic sugar, if it "saves" three characters?

**Comment by kitsunet** [comment]
That's not _as_ easy I think, if the parser would convert that straight to an array, then no  meta operations would work inside it, we would have keys named `@if.whatever` or it makes no sense to me. and if we want to allow the latter we need processing in the runtime which means a prototype (unless we want to add some magic but no please) so that means only sensible option is to make those DataStructures I guess.

**Comment by mhsdesign** [comment]
the runtime configuration could transform the AST to make all untyped children of datastructure 'real' datastructures.

ah okay i thought `= { ` was meant to be a shortcut for DataStructure...

> Is parsing `@if` and/or `@process` reliably possible for untyped structures?
yes the ast is similar to when `@if` is used with an objekt - only that there is no object type in the ast set...

**Comment by kdambekalns** [comment]
🎉
