### ISSUE TITLE
Add Login wallpaper for Neos 7.3 LTS

### ISSUE THREAD

**Issue by sorenmalling** [neos/neos-development-collection#3522]
Once the vote is done, add new login wallpaper

**Comment by sorenmalling** [comment]
Voting is open

https://discuss.neos.io/t/neos-7-3-lts-login-wallpaper/5710/8

**Comment by markusguenther** [comment]
Voting is closed and PR is open. Unsure if we get the image still bit smaller.
Used the same width as before.
