### ISSUE TITLE
UriBuilder in CLI not working

### ISSUE THREAD

**Issue by sbruggmann** [neos/neos-development-collection#3525]
### Description

Since Neos 7.0 it's no longer working to generate frontend URLs via CLI, like it was before.

### Steps to Reproduce

Create a command which is generating frontend URLs, and execute it.
For example: https://gist.github.com/sbruggmann/a7aee77a7e605469267c2844e72467f1

#### Expected behavior

Valid URL is returned.

#### Actual behavior

Error is thrown:
> Could not resolve a route and its corresponding URI for the given parameters. This may be due to referring to a not existing package / controller / action while building a link or URI.

### Affected Versions

Neos 7.x

Neos 5.3 does work with the same code.

**Comment by kdambekalns** [comment]
I found this in a recent project of mine, where this is used for node indexing and works fine in the shell, IIRC:

```php
    private function getMockActionRequest(): ActionRequest
    {
        if ($this->mockActionRequest === null) {
            $httpRequest = new ServerRequest('GET', '');
            $routeParameters = RouteParameters::createEmpty()->withParameter('requestUriHost', $httpRequest->getUri()->getHost());
            $httpRequest = $httpRequest->withAttribute(ServerRequestAttributes::ROUTING_PARAMETERS, $routeParameters);
            $this->mockActionRequest  = ActionRequest::fromHttpRequest($httpRequest);
        }
        return $this->mockActionRequest;
    }

    public function buildNodeUrl(TraversableNodeInterface $node, bool $forceAbsoluteUrl = false): Url
    {
        $uriBuilder = new UriBuilder();
        $uriBuilder->setRequest($this->getMockActionRequest());
        $action = $node->getContext()->getWorkspace()->isPublicWorkspace() && !$node->isHidden() ? 'show' : 'preview';
        $uri = $uriBuilder
            ->reset()
            ->uriFor($action, ['node' => $node], 'Frontend\Node', 'Neos.Neos');
        $nodeUrl = Url::fromString($uri);
        if ($forceAbsoluteUrl && $nodeUrl->isRelative()) {
            $nodeUrl = Url::fromString((string)(new Uri($this->frontendBaseUrl))->withPath($nodeUrl->toString()));
        }
        return $nodeUrl;
    }
```

Similar to your code, but does fancy magic around `ServerRequestAttributes::ROUTING_PARAMETERS`.

🤷‍♂️

**Comment by sbruggmann** [comment]
:ok_hand: Use `getMockActionRequest()` does solve my issue.

I did not expect that this does break from 5.3 to 7.x even knowing that a lot around the routing did change.

But now we have a documented workaround :-)
