### ISSUE TITLE
neos/nodetypes-contentreferences is missing release 7.3.0

### ISSUE THREAD

**Issue by zickgraf** [neos/neos-development-collection#3536]
The last release of `neos/nodetypes-contentreferences` is 7.2.2, so `neos/nodetypes` 7.3.0 cannot be installed because it depends on `neos/nodetypes-contentreferences` 7.3.0. Even worse, when installing `neos/nodetypes` with Neos 7.3, the ancient version 2.3.27 is installed because that's the last version of `neos/nodetypes` not requiring a specific version of Neos.

**Comment by kdambekalns** [comment]
The tag exists: https://github.com/neos/nodetypes-contentreferences/releases/tag/7.3.0

**Comment by kdambekalns** [comment]
And now it's on Packagist, too: https://packagist.org/packages/neos/nodetypes-contentreferences#7.3.0

Even though it is auto-updated, that didn't happen. 🤷‍♂️

Thanks for letting us know!

**Comment by zickgraf** [comment]
I can confirm that installing `neos/nodetypes` 7.3.0 now works. Thanks for the quick fix!
