### ISSUE TITLE
Bug: Cant create a new asset collection if no exists

### ISSUE THREAD

**Issue by mbiberger** [neos/neos-development-collection#3547]
### Description

In a new NEOS Instance if i have no asset collection, i can't create a new one. Because in the Issue  [3480](https://github.com/neos/neos-development-collection/issues/3480) is the asset creation dialog wrapped in a count condition (`... <f:if condition="{assetCollections -> f:count()}"> ...`).

### Steps to Reproduce

1. Go to the Management /  Media Modul
2. Ensure that no asset collection already exists
3. Try to create a new asset collection

#### Expected behavior

The asset collection dialog will be shown.

#### Actual behavior

Nothing happens because the required dialogue box is never rendered.

### Affected Versions

Neos: 
7.3.0

### Pull request:
https://github.com/neos/neos-development-collection/pull/3546

**Comment by mhsdesign** [comment]
Fixed via https://github.com/neos/neos-development-collection/pull/3622
