### ISSUE TITLE
ImageVariants have no asset collection assigned

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#3560]
### Description

When an `ImageVariant` is created by means of cropping in the Neos UI inspector, it is not assigned to an `AssetCollection`. This leads to issues if access to assets not being in an asset collection is limited.

### Steps to Reproduce

1. Block access to assets without an assigned asset collection
2. Have an asset in an asset collection
3. Create a crop of that asset

#### Expected behavior

The crop is created and assigned to the node property, becoming visible in the inspector (and the content, once applied.)

#### Actual behavior

The crop is in fact created, but since it is not accessible (due to step 1 above), it's metadata cannot be fetched (an error notice is shown) and the property will in fact be emptied.

### Affected Versions

Neos: 5.3+

**Comment by kdambekalns** [comment]
For a customer I solved this by using an aspect on `ContentController.createImageVariantAction()`, which includes a crude fix to solve #3559 through `ObjectAccess.setProperty()`.

A possible proper solution would be: When an `ImageVariant` is created, have the constructor in https://github.com/neos/neos-development-collection/blob/5.3/Neos.Media/Classes/Domain/Model/ImageVariant.php#L84-L96 set the asset collections to those from the original asset.

**Comment by kdambekalns** [comment]
Created a draft PR, so we can discuss this solution. Potential issue: When the original asset's asset collections are changed later, should that be kept in sync?

**Comment by kdambekalns** [comment]
ping… any opinions on the above question?

**Comment by mficzel** [comment]
If the variants get collections assigned we should keep them in sync with the original asset, otherwise it gets really confusing.

**Comment by ru3fu5z** [comment]
Seems like this is still in issue in 7.3.10
Editors with asset restrictions by assetcollection run in an error, when using cropping images
