### ISSUE TITLE
Feature AFX: <></> as alias for Neos.Fusion:Fragment

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3580]
### Description

proposal to introduce `<></>` for afx:

```
< @if={false}>
   <h1>bar</h1>
   foo
</>
```

as alias for `Neos.Fusion:Fragment`

```
<Neos.Fusion:Fragment @if=false>
   <h1>bar</h1>
   foo
<Neos.Fusion:Fragment/>
```

### Implementation detail:

it should be discussed, if attributes on the fragment do need a leading space to make parsing easier:
`< @if={false}></>`
or
`<@if={false}></>`

**Comment by mhsdesign** [comment]
hmm but jsx does it like this... (to group stuff)

**Comment by mhsdesign** [comment]
im also fine with closing this, as the fragment is not in much demand

**Comment by jonnitto** [comment]
I would prefer it to have it with no leading space

**Comment by mhsdesign** [comment]
hmm im not sure if this really justifies extending afx.
Since i wrote this - i never needed to use fragment at all. So if @jonnitto doenst oppose i would lile to close this ^^ Or maybe you can show me some coll usages of fragment - who would profit from this syntax
