### ISSUE TITLE
Neos.Fusion:Augmenter can't handle html5 properties

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#3582]
## Neos.Fusion:Augmenter handles attributes differently than Neos.Fusion:Tag

If you have the given Fusion Code:

```
tag = Neos.Fusion:Tag {
    tagName = 'div'
    attributes {
        x-data = true
        x-test = ''
    }
}
augmenter = Neos.Fusion:Augmenter {
    x-data = true
    x-test = ''
    content = Neos.Fusion:Tag {
        tagName = 'div'
    }
}
```

The first one returns `<div x-data x-test></div>`, which is correct.
The second one returns `<div x-data="1"></div>`, which is not correct.

Code example from fusion pen: 
https://fusionpen.punkt.de/fusionpen/f199187e5dce661f197ca885f7ef998ec29be917.html

**Comment by sorenmalling** [comment]
Further details: Augmenter uses the HtmlAugmenter class to add to a tag (by regex and XML tools), where as the Tag object creates the attributes of the content, by looping over the attributes and "putting them" inside the tag

**Comment by mficzel** [comment]
Also the tagAttributes concatenate arrays (with space between) and the Augmenter does not. 


```
tag = Neos.Fusion:Tag {
    tagName = 'div'
    attributes {
        class = ${['content', 'main']}
    }
}
augmenter = Neos.Fusion:Augmenter {
    class = ${['content', 'main']}'
    content = '<div></div>'
}
```

The first one returns `<div class="content main"></div>`, which is correct.
The second one will yield an error.
