### ISSUE TITLE
BUG: Node `_name` property won't get updated/changed if you copy a node

### ISSUE THREAD

**Issue by putzwasser** [neos/neos-development-collection#3586]
### Description

If you copy a node, the node's `_name` property (e.g. `node-x8jf11h4yg1x8`) gets copied, too. The newly created (i.e. copied) node gets the same `_name` property as its origin node.

While `node._name` doesn't claim to be a unique identifier, every newly created node gets a distinct name.
As the probability for a name collision within a single document is relatively low, it can be used to certain things.

For example: I use the `_name` property for creating `id` attributes. If I copy/paste some nodes, I get the same `id` multiple times, which breaks anchoring (`<h1 id="x8jf11h4yg1x8">`) or selecting HTML nodes via JS based on their id.

### Steps to Reproduce

1. Create a node
2. Copy the node
3. Check the Name property in the inspector for both nodes.

#### Expected behavior

A copied node gets a new `_name` property value.

#### Actual behavior

A copied node gets the same `_name` property value as the origin node.

### Affected Versions

* Neos: 7.3
* Flow: 7.3

I guess, every version has this behaviour.

**Comment by jonnitto** [comment]
Thank you for your report. 


Hint: it is better to use the `node.identifier` for id's

**Comment by putzwasser** [comment]
> Hint: it is better to use the node.identifier for id's

Yes, I know. But I was looking for a short identifier and as `_name` was short and sufficient random for my use cases I just used it.

**Comment by mhsdesign** [comment]
i cant reproduce this on the `Neos.Demo` with v7.1.1

i created a new node - and dublicated it - i get different names:

![image](https://user-images.githubusercontent.com/85400359/158241940-85a66ea0-853e-46ca-a68f-ba552f597296.png)

![image](https://user-images.githubusercontent.com/85400359/158241919-87d30b2c-232e-4ac3-af9e-a460c042ebad.png)

**Comment by putzwasser** [comment]
> i cant reproduce this on the Neos.Demo with v7.1.1
> i created a new node - and duplicated it - i get different names:

Okay I guess, I could narrow it down. Here's what I'm doing, which lead so the duplications:

Generally speaking: I have a node type that inherits from `ContentCollection` and serves as content sections. I use it to structure my texts.

Since I need a few of them I create one `Section` node type and create a `Text` content node within it. I then copy & paste the content collection, which holds the empty text node.

The text copied node will have the same `_name` as the original node.

**Comment by putzwasser** [comment]
Accidentally closed the issue.

**Comment by kitsunet** [comment]
Yes, this is how it's supposed to work, node name was never htought to be unique and the check across everything would be horrendously expensive. We deduplicate node names IF they end up in the same hierarchy (so when they are siblings) so you can be sure that the name is unique within it's parent. Not a bug, Just something it doesn't do by design. I doubt we are goign to change this. You could experiment with either truncating the uuid or hashing and then truncating, not perfect but should be relatively robust still for this.

**Comment by mhsdesign** [comment]
@kitsunet what is the nodename for?
I like the usecase, to use it as id, as its not that looong ...

**Comment by putzwasser** [comment]
> Yes, this is how it's supposed to work, node name was never htought to be unique and the check across everything would be horrendously expensive. @kitsunet 

Okay I understand that.

I'd like to counter with two points, though:

1. As you say: It's not intended to be unique. AFAIK it's even stated somewhere in the docs (or the source code). _But_ just copying it is IMHO a bad idea, too, as people—like me—might rely on it for different reasons.
Why not just ensure, it gets recreated randomly when nested nodes get copied? Even if the `_name` would be duplicate, it'd be very unlikely that it was in the same document. That would be fine for me (and probably most others :man_shrugging:  ).
When `_name` just gets re-created randomly during copy paste it's as good/bad as simply inserting a completely new node of the same node type.

2. The `_identifier`, unlike `_name`, property gets "updated" for every node when copying nested nodes. And AFAIK the node identifier is intended to be unique. This makes me believe that ensuring new node names would only be small change—given there's no duplication check. And we don't have a check for duplicate node names anyhow.
