### ISSUE TITLE
Write better Fusion tests (with behat)

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#3594]
It would be great if tests for the fusion language could be written in fusion directly.

**Comment by bwaidelich** [comment]
@kitsunet just brought up the idea of some tested Fusion "best practices" or "examples". We can use the [basis](https://github.com/neos/neos-development-collection/pull/4641) for this as well, e.g. create a folder `Features/Fusion/Examples/FlowQuery` or similar for some integrated Fusion examples that use multiple prototypes and or FlowQuery

**Comment by bwaidelich** [comment]
We solved the basis for this with #4651 – now it would be great to increase the coverage
