### ISSUE TITLE
Feature: Backend translation helper in Fusion

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3638]
we discussed, that we want to modernize the backend modules with fusion and also this task https://github.com/neos/neos-development-collection/issues/3261 is in need to translate in the language of the current backend user. - This language can differ from the language of the general content.

there a two main ways to archive this:

1 - build a `BackendTranslationHelper` that 'uses' the normal TranslationHelper
2 - build a `BackendUserLanguageHelper` or have another way to access the user language with fusion, and composite it together yourself.

- option 1 would lead to lots of dirty code inheritance stuff (like how fluid archived the `<neos:backend.translate>` https://github.com/neos/neos-development-collection/blob/ddf0b3f273395cb4dee316c5d0205b603abba5f7/Neos.Neos/Classes/ViewHelpers/Backend/TranslateViewHelper.php#L94) or when using composition lots of duplication, and one might be wondering if the api is the same like for the normal translationhelper.

- option 2 would be much more understandable and transparent, as we just composite ourselfs the functionality and know how the Translation helper works:
```
${Translation.id('someId').locale(Neos.BackendUserLanguageHelper.get())}
```

but the constant duplication of `locale(Neos.BackendUserLanguageHelper.get())` will get tiring

can/should we introduce a prototype for this or simplify this?

**Comment by mhsdesign** [comment]
i approve your general idea, but isnt your example missing out on the language part?

- i think in general the `Translation` Helper is due for a refactor - i dont like fx. that one can put in a shorthand translation string or something in the same method.

**Comment by mficzel** [comment]
Agree that the translation helper needs a brushover alone since it currently does not support immutability. I do not get the language problem you mentioned. Usually the translation service already knows the language or otherwise one would.

translation = ${Translation.package('Neos.Flow').source('main')}
renderer = afx`
   {props.translation.id("example").locale('fr')} - {props.translation.id("other-example").locale('en')}
`

I agree that the translate method on the TranslationParameter token is obsolete and redundant.

**Comment by mhsdesign** [comment]
i mean the `language(Neos.BackendUserLanguageHelper.get())` part and if the constant duplication is okay - which i think, since one can re use the helper:
 
```
translation = ${Translation.package('Neos.Flow').source('main').language(Neos.BackendUserLanguageHelper.get())}
renderer = afx{props.translation.id("example").locale('fr')} - {props.translation.id("other-example").locale('en')}
```

(btw in the current case one needs to call the final `translate` method on the TranslationParameterToken - but this can also be solved maybe with some __toString magic ...)

**Comment by mficzel** [comment]
Totally agree that the translation helper needs additions and a method to get the current language makes sense to me.

The __toString magic is already in place but sometimes code does not like that yet. We could support string|stringable in eel helpers and fusion where possible.

**Comment by mhsdesign** [comment]
jop sometimes `__toString` doenst work - maybe fusion could check after evaluating a path, if the result is stringable and then call `toString` ?

**Comment by mhsdesign** [comment]
@mficzel oops i used in my demos above `language` instead of `locale` - is corrected.

**Comment by mhsdesign** [comment]
So i think we need a `Neos.BackendUser.getCurrentUserLanguage()` eel helper that can be used as argument in `${Translation.package('Neos.Flow').source('main').locale(Neos.BackendUser.getCurrentUserLanguage()).id('foo-bar')}`

Instead of mimicking the way fluid did it - which is creating a whole new translation view helper instead of using composition and reusing the "normal" translation helper.
