### ISSUE TITLE
!!! TASK: Cleanup Inheritence of ArrayFusionObjects

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#3646]
Many FusionObjects inherit from DateStructure or Join because they used methods like sortNestedFusionKeys. This leads to interesting effects like unnamed keys of Joins beeing treated as DataStructures.

The relations of those objects should be revised.

Examples for problems that are caused by this:
- https://github.com/neos/neos-development-collection/issues/3513
- https://github.com/neos/neos-development-collection/issues/3441
- https://github.com/neos/neos-development-collection/issues/3576

**Comment by mhsdesign** [comment]
first one actually ^^ https://github.com/neos/neos-development-collection/issues/3577

we should close one of these similar issues right?
