### ISSUE TITLE
Rendering results in $array must be of type iterable|scalar got: NULL

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#3657]
### Description

`$array must be of type iterable|scalar got: NULL`

### Steps to Reproduce

1. On master, import demo site
2. Create user, log in to backend

#### Expected behavior

The homepage is shown in the content module

#### Actual behavior

<img width="837" alt="image" src="https://user-images.githubusercontent.com/95873/159797406-44e48c35-c92c-4d95-92fe-694f9211a503.png">

### Affected Versions

Neos:  master as of 2022-03-23 22:19 CET

**Comment by mhsdesign** [comment]
because of https://github.com/neos/neos-development-collection/pull/3654
