### ISSUE TITLE
FEATURE: AFX prop `int` and `bool` support 

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3676]
Allow not only string an eel in prop values but also other types like `int` and `bool`

afx:
```html
<Vendor:Foo
    a=true
    b=false
    c=132
/>
```

which would transpile to this fusion:
```html
Vendor:Foo {
    a = true
    b = false
    c = 132
}
```

currently we need to use eel:

```html
<Vendor:Foo
    a
    b={false}
    c={132}
/>
```

**Comment by Sebobo** [comment]
AFX already supports simply having an attribute without value defined as `true` value like html does.
F.e.
```html
<Vendor.Icon icon="spinner" spin />
```

**Comment by mhsdesign** [comment]
As discussed with @sjsone we probably dont need this feature and should rather compile simple eel to native fusion.
