### ISSUE TITLE
Neos tries to render thumbnails for PDFs - but the default config of ImageMagick on Ubuntu denies reading PDFs

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#3678]
Since it's only checked that Imagick is available, several of our Neos instances started to try to render thumbnails for PDFs - running into an issue, since the default config of ImageMagick on Ubuntu denies reading PDFs (see the `/etc/ImageMagick-6/policy.xml` file).

In a first step we just modified that policy file to allow reading PDFs which works, but this issue also applies to other Document formats like Word files.

We're aware that we can disable rendering thumbnails per document type - but this is kind of cumbersome in >90 Neos installations of a whole fleet of customer setups.

So if one of you sees a generic solution to this, I'm all ears :-)

One approach I'd see would be to not only check if the `imagick` PHP-Module is loaded, but also if it's config allows the current document type to be read. Somehow, PHP **must** be aware of that config from the policy.xml file, as changing it does not change Neos behaviour unless the php-frpm process is restarted.

Or alternatively put the effective generation of thumbnails for Documents into a try/catch block and if getting a thumbnail fails, do

1. ignore this (e.g. do not write out an Exception file)
2. fall-back to showing the icon file instead of the thumbnail from the effective file

_Originally posted by @mrimann in https://github.com/neos/neos-development-collection/issues/3617#issuecomment-1079117378_

**Comment by kdambekalns** [comment]
Indeed, the change that caused this changes behaviour slightly, leading to the use of imagick even though it's not configured to be sued actively for Neos. The question now is, revert that change (for the sake of clear assumptions) or extend the check to cover PDF handling?

**Comment by mrimann** [comment]
Thanks @kdambekalns for taking my concern and put it into it's own issue!

**Comment by kdambekalns** [comment]
@mrimann Could you check if

```php
<?php
$imagick = new Imagick();  
$formats =  $imagick->queryFormats('*PDF*');
print(print_r($formats, true));
```

works, i.e. does it return PDF only of actually using it is possible? Or does that merely say "I could", even if not allowed?

**Comment by mrimann** [comment]
That would have been to cool if that would have been a solution - but my test did not look like it's working.

Running your code snippet results in the following output on a server here:
```

Array
(
    [0] => EPDF
    [1] => PDF
    [2] => PDFA
)
```

This was with the modified line in the policy file and thus "to be expected":
```
<policy domain="coder" rights="read" pattern="PDF" />
```

I then changed the policy file back to what I think is the default value:
```
<policy domain="coder" rights="none" pattern="PDF" />
```

And without restarting the PHP-FPM service, the same output was returned (also to be expected).

Then restarted php-fpm service and hoped to see a different output, but it's **still showing exactly the same output** :-(

I think that's "correct" as the method only checks if the particular format is *supported* and it is - whether it's allowed by policy seems to be a different story (and I couldn't find a different method to check for that detail).

**Comment by kdambekalns** [comment]
> I think that's "correct" as the method only checks if the particular format is supported and it is - whether it's allowed by policy seems to be a different story (and I couldn't find a different method to check for that detail).

Too bad. Well, I guess then trying to actually read is the only way to find out.

**Comment by kdambekalns** [comment]
The linked PR has more details on the journey, but here is the current suggestion to solve this:

1. Bring back the check for `$this->imagineService instanceof \Imagine\Imagick\Imagine` that https://github.com/neos/neos-development-collection/pull/3617 removed.
2. Add a feature flag to be able to use the `DocumentThumbnailGenerator` even when not using `\Imagine\Imagick\Imagine`, solving the need expressed in https://github.com/neos/neos-development-collection/pull/3617 without changing existing behaviour.
3. Add the error check from https://github.com/neos/neos-development-collection/pull/3783 to the `ThumbnailGeneratorStrategy` to make use of the "fallback chain" in case of an error.

**Comment by kdambekalns** [comment]
3. is in https://github.com/neos/neos-development-collection/pull/3828

**Comment by DrillSergeant** [comment]
Perfect, works now as intended for us.
