### ISSUE TITLE
NodeTypeConfigurationCache actually slows down requests

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#3681]
The `Neos_ContentRepository_FullNodeTypeConfiguration` cache is used in https://github.com/neos/neos-development-collection/blob/771a5c262d61b7b136196edf1481e3d58f0e45d1/Neos.ContentRepository/Classes/Domain/Service/NodeTypeManager.php#L197

For every request related to nodes all nodetypes are loaded including their configuration.
Due to the `NodeTypeConfigurationAspect` also labels are loaded when NodeTypes are instantiated.

The fully postprocessed `fullConfiguration` is only generated when the nodetypes `initialize` method is called.
This happens when the cache is not filled due to the call to `$nodeType->getFullConfiguration()`.

So in `Development` context in which the cache has a `NullBackend` this happens basically for every Neos related request that includes nodes.

In Production this only happens once and the resulting `fullConfiguration` of each nodetype is stored in the cache.

BUT ... the stored configuration is retrieved for subsequent requests and passed to `loadNodeType` but there it is never used.
To actually make it work, it would have to be forwarded to the `NodeType` constructor to skip generating the `fullConfiguration` and instead use the cached one.

Therefore all requests are actually faster if the whole cache related code is removed. Especially during development in a project with many nodetypes.

*Simple solution:*

Remove the cache, the nodetypes are anyway lazy loaded

*Better but more complex solution*

Pass the cached configuration to the nodetype constructor (or access it there in some other way) to skip all the configuration and label merging.

**Comment by Sebobo** [comment]
@kitsunet do you still know what you wanted to do with this cache 7 years ago?

**Comment by kitsunet** [comment]
Ha! That is an interesting find, I guess I wanted to give the third argument? No clue what happened there.

**Comment by kitsunet** [comment]
I mean, given that it's currently doing nothing, I am not opposed to removing it (even as a bugfix) and reconsidering if there is any sensible part to cache afterwards.
