### ISSUE TITLE
Deprecation warnings with PHP 8.1

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#3682]
### Description

When using PHP 8.1 the tests emit a lot of deprecation warnings.

#### Expected behavior

No warnings.

#### Actual behavior

Tons of warnings.

### Affected Versions

All current versions.

**Comment by kdambekalns** [comment]
See https://github.com/neos/flow-development-collection/issues/2797 for the "Flow side"

**Comment by jonnitto** [comment]
Can we close this one?
