### ISSUE TITLE
Feature: Simplify nested components `@apply.props` syntax

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3702]
### Description

im referring to the `@apply` pattern shown here: https://gist.github.com/mficzel/5c9c8e54f5a327123f07d762b34e2053

### sugarfied?
```diff
prototype(Vendor.Site:Example) < prototype(Neos.Fusion:Component) {
  foo = null

  renderer = Neos.Fusion:Component {
    # pass all outer props to the renderer
+   ...props
-   @apply.props = ${props}
    
    renderer = afx`{props.foo}`
  }
}
```

i think the es spread operator is easier to understand and also the syntax is less verbose.
and this syntax is already know from afx: `<My.Component {...props}/>`

similar to es6, we can also implement a `Object Property Value Shorthand`

```diff

root = Neos.Fusion:Value {
    @context.bar = "123"
    value = Neos.Fusion:DataStructure {
+       bar
-       bar = ${bar}
    }
}


```

**Comment by mficzel** [comment]
I like that idea.

**Comment by mhsdesign** [comment]
or like this `...${props}`

**Comment by mhsdesign** [comment]
i think this will be obsolete with #3943 as this will lower the demand for `@apply` so im proposing to close this and not touch the fusion syntax ^^
