### ISSUE TITLE
RawContent mode shows rendering exception for nodetypes without Fusion prototypes

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#3705]
### Description

The `RawContent` mode was able to render pages and content without Fusion prototypes in the past thanks to the default prototype generator. The later was removed in Neos 5.

Therefore the feature to build an initial site without creating Fusion prototypes for rendering broke.

### Steps to Reproduce

1. Setup a Neos 5-8 demo
2. Create a new content nodetype
3. Add the nodetype to a page
4. Switch to the RawContent mode
5. See a rendering exception

#### Expected behavior

The `RawContent` mode should be able to render a page with all collections and content in a way so that every element can at least be selected and modified in the inspector like it was in the past. This could be done with an override of the `Neos.Neos:Content:Case` inside the raw content mode to add a fallback if a prototype is not defined and providing a simple fallback type to render a nodes label and an optional note regarding the problem.

Example how it could look instead:

<img width="791" alt="Bildschirmfoto 2022-05-01 um 09 06 31" src="https://user-images.githubusercontent.com/596967/166135946-957e3c43-14f5-40fe-bca7-b7821b460613.png">

#### Actual behavior

The `RawContent` mode throws an exception for missing Fusion prototypes when trying to render a nodetype.

<img width="779" alt="Bildschirmfoto 2022-05-01 um 09 06 22" src="https://user-images.githubusercontent.com/596967/166135938-920e2c8b-7b20-44ba-aa0b-d89c30eeb5c4.png">

### Affected Versions

Neos: 5.x - 8.x

**Comment by Sebobo** [comment]
@mficzel and me discussed to integrate something like https://github.com/sitegeist/Sitegeist.Stencil into the core to replace the raw content mode and make it more usable.

**Comment by mhsdesign** [comment]
I like the stencil idea better too. The current raw content mode feels too hacky...

**Comment by mficzel** [comment]
Will experiment with that ... the principle of stencil with a more friendly look would be great

**Comment by Sebobo** [comment]
Should we then go with the fallback like in my example as a bugfix for 5.3+?

**Comment by mficzel** [comment]
@Sebobo Providing a fallback for older neos makes 100%sense

**Comment by Sebobo** [comment]
> the fallback should render all inline editable properties right?

Yes I will adjust that

**Comment by Sebobo** [comment]
I was actually mistaken. Neos <5 didn't need a Fusion prototype to render something in den `rawContentMode` but instead a Fluid template. Still makes sense to provide a proper fallback.
