### ISSUE TITLE
Rename master branch to 8.2

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#3713]
## Rename `master` branch to `8.2`

To minimize confusion, we need to rename `master` to `8.2` in all repositories that have a `9.0` now. And we should do the rename for Flow (dev dist/collection), too, to stay consistent.

- [x] https://github.com/neos/neos-development-collection
- [x] https://github.com/neos/neos-development-distribution
- [x] https://github.com/neos/neos-base-distribution
- [x] https://github.com/neos/flow-development-collection
- [x] https://github.com/neos/flow-development-distribution
- [x] https://github.com/neos/flow-base-distribution
- [x] neos/welcome
- [x] neos/kickstarter
- [x] neos/behat
- [x] neos/buildessentials
- [x] neos/demo
- [x] neos/imagine
- [x] neos/party
- [x] neos/setup
- [x] neos/twitter-bootstrap
- [x] neos/neos-ui
- [x] neos/neos-ui-compiled
- [x] neos/doctools
- [x] neos/site-kickstarter
- [ ] are these all that are affected?

Renaming will move all open PRs, set the default branch on GH and provide a nice reminder to people that `master` has been renamed.

## Other adjustments

Things will need to be adjusted, if they rely on `master` being there:

- [x] Jenkins jobs
- [x] readthedocs rendering
- [x] build tooling in the repositories
- [x] BuildEssentials
- [x] Weblate
- [x] branch name in README files (badges, text, …)
- [ ] … probably more?

**Comment by mhsdesign** [comment]
the Readme for contributing should also be edited...

**Comment by kdambekalns** [comment]
`8.1` has been branched off of `master` by now. The `master` will thus be renamed to `8.2` instead.

**Comment by kdambekalns** [comment]
I'll close this - feel free to fix anything broken by this directly and just comment here. Or create a new issue, if needed.
