### ISSUE TITLE
Simple Fusion linter

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3766]
The idea is to provide more debugging help for devs using Fusion.
One might write something like
`foo.@process = ${...}`
This is valid fusion Grammer and thus the parser won't and shouldn't complain. But the runtime will ignore the line silently as there is no subkey like: `foo.@process.subkey = ${...}`

The example above is super primitive but a first implementation won't be to able to actually understand your fusion and provide something like type safety. If you know other examples that could be easily analized (without _understanding_ fusion) then it might be worth and a good improvement for fusion.

**Comment by Sebobo** [comment]
There is a package for that already by @cvette, not sure if it's public yet. We used it in a customer project with some custom rules.

**Comment by cvette** [comment]
You can find it here: https://github.com/cvette/neos-code-style

Already works quite well for manual usage, but still lacks some features to have it easily embedded into CI/CD pipelines (that is one of my goals for this project).

However, for your example, I would actually prefer a warning or even an exception from the Fusion runtime. Better to fail early, than to discover some weird behavior later.
