### ISSUE TITLE
Make Component props unsorted to improve performance

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-development-collection#3792]
As Fusion Components are a defacto standard in rendering now and are widely used, any performance bottleneck in those will multiply to a big performance problem in bigger sites. Currently components sort their props as they historically inherit from the Array and DataStructure objects in which sorting makes sense. While the sorting is not a hugely expensive operation, it is not negligible and adds up with many components to render, therefore we should remove sorting there and streamline them as much as possible.

**Comment by Sebobo** [comment]
We also lost some performance when `Neos.Fusion:Tag` switch from `Neos.Fusion:Attributes` to `Neos.Fusion:DataStructure`.
Probably same reason, as now all keys are sorted which the Attributes didn't do.
