### ISSUE TITLE
BUG: Imagine\Vips\Imagine not found when running cli installer

### ISSUE THREAD

**Issue by simonschaufi** [neos/neos-development-collection#3811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running all the steps in the cli installer crashes

### Expected Behavior

Running `./flow setup:imagehandler` works without problems

### Steps To Reproduce

I ran:

```bash
./flow setup:imagehandler

Class "Imagine\Vips\Imagine" not found

  Type: Error
  File: Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Imagine_Imag
        ineFactory.php
  Line: 52
```

### Environment

```markdown
- Neos: 8.0.2
- PHP: doesn't matter
- vips php extension installed
```

### Anything else?

Don't assume that `rokka/imagine-vips` is installed, and check that first before calling methods on classes of that package.

**Comment by sorenmalling** [comment]
@simonschaufi Did you configure "Vips" in your Settings.yaml before running the command? By default that value is `Imagine` so the Vips value seems to come from somewhere else first.

> Don't assume that rokka/imagine-vips is installed, and check that first before calling methods on classes of that package.

And we should not assume a specific package, but instead check the expected classname used by the ImagineFactory class, if it really exists

**Comment by simonschaufi** [comment]
@sorenmalling as I said, i just ran the composer installer and then each step that is listed afterwards without configuring anything. There is a list of possible options in the neos-cli package and each is then rendered as list item in the cli without checking if it's actually available. The visual installer via the browser works totally different and doesn't have this problem.

**Comment by mhsdesign** [comment]
thats not true there is a check made if the extension is loaded:
https://github.com/neos/neos-development-collection/blob/f8e64887233eda2e4afd1a1a7327429b7694dd22/Neos.CliSetup/Classes/Infrastructure/ImageHandler/ImageHandlerService.php#L49

**Comment by simonschaufi** [comment]
Vips is not a php extension but a simple class which is missing a check here

**Comment by mhsdesign** [comment]
if its not a php extension the above check:
```
var_dump(extension_loaded("vips"));
```

will never pass - so vips would be never selectable and yield no errors...

im missing something here ...

**Comment by simonschaufi** [comment]
Why don't you try to reproduce the error yourself?

**Comment by mhsdesign** [comment]
> i have the feeling that you have this php extension installed but not installed the php library mentioned. and we dont check for this case...

so as i guessed.

we then need to wrap the call to `$this->findUnsupportedImageFormats()` into a try catch ...

**Comment by crydotsnake** [comment]
Hello @simonschaufi

It's a dependency problem. I had the same issue as you have. I've installed the `rokka/imagine-vips` package with `composer require rokka/imagine-vips` and it worked for me. You also need the FFI package. You can find more information in the 0.20.0 release notes of the `rokka/imagine-vips` package: https://github.com/rokka-io/imagine-vips/releases/tag/0.20.0

**Comment by simonschaufi** [comment]
I know the solution but the installer should not crash because of the missing dependency. That's the issue!

**Comment by kitsunet** [comment]
I agree it should not, I prepared a little refactoring of the ImagineFactory to be used here and in other places to amke things nicer....

https://github.com/neos/imagine/pull/22

**Comment by mhsdesign** [comment]
hmm but the call to `$imagine = $this->imagineFactory->create();` would still fail right? we need to catch it or is this fixed with your pr and i dont see it? :see_no_evil:

**Comment by simonschaufi** [comment]
The cli installer should behave the same way as the web installer.

**Comment by mhsdesign** [comment]
Thanks for reporting. Will be fixed via https://github.com/neos/neos-setup/pull/12

**Comment by simonschaufi** [comment]
Thank you!
