### ISSUE TITLE
9.0: Simplify NodeAggregateWasMoved event structure

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#3825]
The current structure of the NodeAggregateWasMoved is rather complex. Especially the `NodeMoveMappings` are hard to grasp.

Besides, the *hash* of the affected ContentDimensionSpacepoints is expected as keys for `NodeVariantAssignments::createFromArray()` which makes this error prone. Also it makes the internal implementation detail part of the event payload.

**Comment by bwaidelich** [comment]
## Idea

### Now:

```json
{
  "movedNodeOrigin": {
    "language": "ch"
  },
  "newParentAssignments": {
    "1041cc1fe1030c1a82ac24346f8c69a7": {
      "nodeAggregateIdentifier": "b",
      "originDimensionSpacePoint": {
        "language": "de"
      }
    }
  },
  "newSucceedingSiblingAssignments": []
}
```

### Then:

```json
{
  "movedNodeOrigin": {
    "language": "ch"
  },
  "newLocations": [
    {
      "coveredDimensionSpacePoint": {
        "language": "ch"
      },
      "newParent": {
        "nodeAggregateIdentifier": "b",
        "originDimensionSpacePoint": {
          "language": "de"
        }
      },
      "newSucceedingSibling": {
        "nodeAggregateIdentifier": "c",
        "originDimensionSpacePoint": {
          "language": "de"
        }
      }
    }
  ]
}
```

**Comment by nezaniel** [comment]
I really like the idea of grouping the locations by covered dimension space point and using its value instead of or additionally to its hash. It should help decouple projectors from the variation graph's state.

I prefer keeping events consistently on node aggregate level, so we have information available on the projection side accordingly. I'm not sure whether we explicitly use that bonus information at some point currently, but it might make sense and it's the current default for all events I think

**Comment by skurfuerst** [comment]
BTW: it would be awesome if 

```

    /**
     * This specifies all "edges" which should move to the END of their siblings.
     * All dimension space points included here must NOT be part of any MoveNodeMapping.
     *
     * This case is needed because we can only specify a new parent or/and a new succeeding sibling in the
     * MoveNodeMappings; so we need a way to "move to the end".
     *
     * @var DimensionSpacePointSet
     */
    private DimensionSpacePointSet $repositionNodesWithoutAssignments;
```

could be gone after the refactor :D

**Comment by skurfuerst** [comment]
implemented and merged :)
