### ISSUE TITLE
BUG: Delete Button in UserManagement Backend Module doesn't work

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-development-collection#3830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I navigate to the User Management module in the Neos backend, and I click on the "Delete" button, nothing happens.

## Demo:
![neos-user-managment-module-delete-button-does-not-work](https://user-images.githubusercontent.com/39345336/177049714-6638899c-4e4e-49b8-beb3-364bd92560be.gif)

But if I edit the user, and then click "Delete user", it works as it should be.

## Demo:
![neos-user-managment-module-delete-button-does-work](https://user-images.githubusercontent.com/39345336/177049747-068e78c9-691c-44ef-953a-95aa825927a6.gif)

### Other Versions I tested it with:
Just to be sure, I also tested it with Neos version 7.3. There the problem did not occur

### Expected Behavior

I should be able to delete a backend user directly in the index view in the UserManagment module.

### Steps To Reproduce

1. Install a fresh Neos installation
2. Login to the Backend
3. Navigate to the User Management Module
4. Click the "Delete user" Button

### Environment

```markdown
- Flow: 8.0.4
- Neos: 8.0.3
- PHP: 8.0.18
```

**Comment by mficzel** [comment]
@crydotsnake i can confirm the issue and could pin it down to the UserManagement Neos.Neos/Resources/Public/JavaScript/Module/Administration/UserManagement.js 
from pr https://github.com/neos/neos-development-collection/pull/3648

To verify i removed the line `import { UserManagement } from './Module/Administration'` from Packages/Neos/Neos.Neos/Resources/Public/JavaScript/index.js and build the js again.
`cd Packages/Neos/Neos.Neos && yarn && yarn build:js`

**Comment by mficzel** [comment]
@crydotsnake found a solution in #3832 ... not sure this is the correct way since i am no fe-dev

**Comment by crydotsnake** [comment]
Fixed with: #3832
