### ISSUE TITLE
BUG: Usermanagement > Electronic Addresses > Is a bit broken

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3841]
Meta Issue with following sub issues:

# ~1~

(edit: seems to be fixed - idk when and how but doesnt appear in Neos 7.3)
the preselected option `private` or `workspace` seems not be correctly saved (on the initial creation, as this field is empty in the list)

![image](https://user-images.githubusercontent.com/85400359/179779034-5e37c731-a7a9-4e0d-805b-0c7b51813292.png)

# 2
no error on invalid input:
https://github.com/neos/neos-development-collection/issues/1807

# ~3~

(edit: seems to be fixed - it doesnt appear in Neos 7.3)

one cannot delete an adress due to:

```
htmlspecialchars() expects parameter 1 to be string, object given

Original File: Packages/Application/Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
00445: 
00446:         $this->addFlashMessage(
00447:             $this->translator->translateById('users.electronicAddressRemoved.body', [htmlspecialchars($electronicAddress->getIdentifier()), htmlspecialchars($electronicAddress->getType()), htmlspecialchars($user->getName())], null, null, 'Modules', 'Neos.Neos'),
00448:             $this->translator->translateById('users.electronicAddressRemoved.title', [], null, null, 'Modules', 'Neos.Neos'),
00449:             Message::SEVERITY_NOTICE,
```

i think 3 might be due to some added xss security stuff by @kitsunet ?
I will look who to blame ^^

Neos 7.1

**Comment by mhsdesign** [comment]
# 4

the "Identifier" can also be edited for existing electronic addresses in the `/neos/user/usersettings` user page.

but there its no validation :O

[Bildschirmaufzeichnung vom 03.11.2022, 11:57:10.webm](https://user-images.githubusercontent.com/85400359/199703714-11ffdc55-5ac9-46ef-a580-a80a6e9a2a1e.webm)

Neos 7.3

**Comment by bwaidelich** [comment]
@mhsdesign did you see https://youtu.be/xdT9ywTNQlY?t=1017 ?

**Comment by bwaidelich** [comment]
Apparently this has been fixed as of Neos 7.3 and since older versions are in security-updates-only-mode, I'll close this

**Comment by mhsdesign** [comment]
@Pingu501 whats the status on this?

After testing 2 & 4 are still valid for Neos 7.3

**Comment by Pingu501** [comment]
@bwaidelich @mhsdesign I only started looking into the first two points.

* Point one (private or workspace) seems to be fixed.
* Point two is wip, coming next week ;)
* Point three and four are still open

I think it's fine to keep this issue open till we validated the last two points.

**Comment by bwaidelich** [comment]
Ah, these are *four* issues in one and one of them is a duplicate :D
Sorry, I didn't realize, I thought those were steps to reproduce 1 to 4.

@Pingu501 I can help you fix the issue in a pair programming session, if you'd like

**Comment by bwaidelich** [comment]
The remaining bugs should be fixed with https://github.com/neos/party/pull/34
