### ISSUE TITLE
BUG: Fusion Runtime `@process` with simple string

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You cannot use `@process` with an normal string.
Only EEL or FusionObjects are allowed - but for replacing something independingly of loading order this is sometimes the last resort - also it make no obvious sense why it should not, even if it doesnt make real sense ^^ 

```
root >
root = "foo"
root.@process.set = "bar"
```

```
count(): Argument #1 ($value) must be of type Countable|array, string given

count("foo")

Original File: Packages/Neos/Neos.Fusion/Classes/Core/Runtime.php
00792: 
00793:             # If there is only the internal "__stopInheritanceChain" path set, skip evaluation
00794:             if (count($processorConfiguration[$key]) === 1 && isset($processorConfiguration[$key]['__stopInheritanceChain'])) {
00795:                 continue;
00796:             }


Original File: Packages/Neos/Neos.Fusion/Classes/Core/Runtime.php
00504: 
00505:         if (isset($fusionConfiguration['__meta']['process'])) {
00506:             $evaluatedValue = $this->evaluateProcessors($evaluatedValue, $fusionConfiguration, $fusionPath, $contextObject);
00507:         }
00508: 

```

### Expected Behavior

the value in path "root" will be overriden with "foo"

### Environment

```markdown
- Neos: >= 8.0 / All
- PHP: doesnt matter, but dont turn of error reporting like in the codePen ^^
```

**Comment by Kleisli** [comment]
why not just writing?
`root = "bar"`

"process" means doing something with the current value, if you want to replace a value completely, it's an assignment..

**Comment by mhsdesign** [comment]
sure but why dissallow it - its a [regression](https://github.com/neos/neos-development-collection/pull/3847#issuecomment-1192828741).

**Comment by Kleisli** [comment]
I consider this a “conceptual bug“, this would be equivalent to a php method

`public function getBar “bar“`

Instead of 
`public function getBar() {return “bar“;}`

As you wrote 
> it doesnt make real sense ^^

And I think it is better for Fusion to omit things that don't make sense. :)
