### ISSUE TITLE
9.0: Tree Structure Comparison Tool

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#3853]
A CLI command that can create a plaintext file containing all nodes for “old” and “new world” in order to verify that the migration produces the right events in all cases.

Possible command signature

    ./flow cr:dump <content-dimensions> <sites> <include-properties>

The resulting output should be one file per site & dimension combination.

**Comment by bwaidelich** [comment]
A first version (compatible with 6.x - 8.x and 9.x) is ready: https://github.com/bwaidelich/Wwwision.ContentRepositoryDumper

**Comment by skurfuerst** [comment]
Great work 😊😊
