### ISSUE TITLE
9.0: maybe clean up naming for public APIs

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#3860]
```
Subgraph::findNodeByNodeAggregateIdentifier Naming 
NodeAggregateIdentifier -> NodeAggregateId ??
120-char-line-length?
```

**Comment by bwaidelich** [comment]
> NodeAggregateIdentifier -> NodeAggregateId ??

@skurfuerst I think we can go ahead with this, see https://discuss.neos.io/t/rfc-use-id-instead-of-identifier-for-neos-9/6001/9

**Comment by skurfuerst** [comment]
done / implemented :)
