### ISSUE TITLE
FEATURE: Command for creating a node migration

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-development-collection#3881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It would be great to have a command for creating a node migration: `./flow node:migrationcreate`

**Comment by crydotsnake** [comment]
@mhsdesign The Neos.Kickstarter Package is inside the flow-development-collection :)

**Comment by mhsdesign** [comment]
Hi ;) @crydotsnake 

i get the confusion ^^

but believe me the issue belongs here :P hear me out:


The [Node Migrations](https://docs.neos.io/cms/manual/content-repository/node-migrations) are a part of the neos cms so flow is too low level. That way we can exclude the flow-development-collection already architecturally.

Now the question is, at what place the migration logic is implemented, to find the right spot for the kickstarter.

The command
```
./flow node:migrate ...
```
is found here:
https://github.com/neos/neos-development-collection/blob/38a2d39868cc346926666ee4ce26b7c2e3e7f118/Neos.ContentRepository/Classes/Migration/Command/NodeCommandController.php#L76

And this is in the 'neos-development-collection'.


------

Also flows command line does something nice you wont expect: Its extensible by default. So while its true that [Neos.Kickstarter](https://github.com/neos/flow-development-collection/tree/master/Neos.Kickstarter) is in the flow collection, other packages can also provide `flow kickstart:*` commands, just by creating a command-controller named `KickstartCommandController`. So [Neos.Kickstarter KickstartCommandController](https://github.com/neos/flow-development-collection/blob/0be0e915b38c5c60e6db49426912522e42c004fe/Neos.Kickstarter/Classes/Command/KickstartCommandController.php#L26) is not even the true one and only `flow kickstart:*` command, they just get all merged ;)

Infact there is already a kickstart command you might now in the neos collection: https://github.com/neos/neos-development-collection/blob/38a2d39868cc346926666ee4ce26b7c2e3e7f118/Neos.SiteKickstarter/Classes/Command/KickstartCommandController.php#L24
This one provides `kickstart:site`

so lets close your dub in flow: https://github.com/neos/flow-development-collection/issues/2889

**Comment by crydotsnake** [comment]
Current status:

The functionallity has been implemented in the `Neos.ContentRepository` package.
