### ISSUE TITLE
BUG: Click on a checkbox of a single change in the changes list, selects the page and all content elements

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#3928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clicking on a single change (one node) selects all the changes of the same page

### Expected Behavior

Only the selected change is selected ;)

### Steps To Reproduce

Have a workspace with more than one change on a apage
Click on one of the checkboxes

### Environment

```markdown
- Flow:latest
- Neos:latest
```

**Comment by crydotsnake** [comment]
We took another look at the problem and realized that the behavior described above is not a bug.
