### ISSUE TITLE
BUG: Possible typo in SCSS

### ISSUE THREAD

**Issue by simonschaufi** [neos/neos-development-collection#3960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

probably this line should be "border-..." instead of "bborder-..."
https://github.com/neos/neos-development-collection/blob/8.2/Neos.Neos/Resources/Private/Styles/Foundation/_mixins.scss#L257 and https://github.com/neos/neos-development-collection/blob/8.2/Neos.Neos/Resources/Private/Styles/Foundation/_mixins.scss#L261

### Expected Behavior

no errors in SCSS

### Environment

```markdown
- Neos: 7.3
```

**Comment by crydotsnake** [comment]
Yes. Thanks for reporting it.
