### ISSUE TITLE
FEATURE: Fusion `@internalPaths` paths

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3966]
When developing https://github.com/neos/neos-development-collection/pull/3943 the question came up, whether we would allow to set `@private` from outside:

```
root = Vendor.Site:Foo {
   @private.hiddenSecretProp = 123
}
```

an by design this should not be possible - never the less, it is - because a fusion object itself doesnt know if a path was declared at "call time" or is declaration. https://github.com/neos/neos-development-collection/pull/3943#pullrequestreview-1188187176

Im proposing an official, generic way to disallow accessing certain paths like `@private` from outside.

Im against creating a super specific solution that will only suit our case (for Neos.Fusion:Component and extended implementations)
As this will most likely involve hacking and mixing up boundaries, when fx. implementing this logic inside the Runtime directly.

So how about a more general approach like:

```
prototype(Foo.Bar:Lol) {
   @internalPaths = ${["@private"]}
}

```

im not sure if we would want anything the like - as it might slow things down at runtime, but i wanted to start the conversation.

**Comment by kitsunet** [comment]
Yeah, totally like the idea, I _think_ we might even be able to pull this off wiht minimal impact?

**Comment by mhsdesign** [comment]
I opted in for: less generic and simpler implementation instead of this approach see b24eece609da7ec87783fc46c45fd5753c47997f.
So fusion will feature this behavior only for `@private` paths.

to be continued: https://github.com/neos/neos-development-collection/pull/3943
