### ISSUE TITLE
BUG: Workspace publishing of new pages not consistent

### ISSUE THREAD

**Issue by pKallert** [neos/neos-development-collection#3991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding a new page in a workspace, the behavior on the review page is not consistent. 

On the left side of the table of changes, checking one checkbox automatically checks all of the other elements in the page for publishing. 
On the right side of the table there is a possibility for publishing a single element inside the new page. 

I would suggest disabling the checkbox on the right side if the page is new or moved. 

### Expected Behavior

I personally would expect that a user cannot publish content of an unpublished page. 
I would also expect that the behavior of the checkboxes on the left and the check icon on the right side are consistent. That means publishing elements of new pages should be either possible or not possible using either method. 

### Steps To Reproduce

1. Create a new workspace 
2. Inside the workspace, add a new page in the page tree
3. Add content / nodes to the page 
4. Go to the workspace module and have a look at the workspace changes
5. Publish one of the changes using the check icon on the right side:
![Bildschirmfoto 2023-01-04 um 17 21 28](https://user-images.githubusercontent.com/91674611/210601340-b6111c96-9496-4b69-8e01-09e17a5b29a2.png)

**Comment by kdambekalns** [comment]
And that really publishes only the selected element without the document node? That sounds like a regression… Doh!

**Comment by pKallert** [comment]
Yes, it only publishes the one element to live workspace as far as I can see in the database

**Comment by crydotsnake** [comment]
Hello @pKallert !

Thanks for working on that. And i completley agree with you!

I'm just wondering if it wouldn't be better to hide the checkboxes on the left side as well. 

![SCR-20230512-lzus](https://github.com/neos/neos-development-collection/assets/39345336/2a0ee796-da41-4c50-b475-f902e9f71a60)

Because when I create a new page as an editor, I have only two options:

1. I publish all changes
2. I delete all my changes


And in the use case described here, the checkboxes would be unnecessary anyway.

**Comment by pKallert** [comment]
@crydotsnake 
I had a talk with our editors and  they agree that it is confusing, but it seems that the usability of the whole workspace change details page is not the best. 
If the checkbox on the left side are hidden, I think the header element with "Path: Home/test" should be fixed so that with a lot of changes editors can always check the current page they are looking at. 

Perhaps with the new workspace module from @Sebobo we can rethink the usability of the detail page?

**Comment by crydotsnake** [comment]
> @crydotsnake I had a talk with our editors and they agree that it is confusing, but it seems that the usability of the whole workspace change details page is not the best. If the checkbox on the left side are hidden, I think the header element with "Path: Home/test" should be fixed so that with a lot of changes editors can always check the current page they are looking at.

You mean if i review the changes of a completely new page, i only have the checkbox in the header element (Path: Home/Test)? If so, this makes more sense imo.

> Perhaps with the new workspace module from @Sebobo we can rethink the usability of the detail page?

👍🏽
