### ISSUE TITLE
BUG: No Fusion object found in path "error"

### ISSUE THREAD

**Issue by sebastiansommer** [neos/neos-development-collection#3995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems like that the fusion object path "error" does not exist anymore which prevents the configuration of custom error pages.

**Configuration:**
```afx
error {
    4xx {
        ...
    }
}
```

### Expected Behavior

To be able to configure custom error pages.

### Steps To Reproduce

[https://www.neos.io/FORCE404ERROR](https://www.neos.io/FORCE404ERROR)

### Environment

```markdown
- Flow: 8.2
- Neos: 8.2
- PHP: 8.1
```

**Comment by Sebobo** [comment]
Thx for reporting!

This is a regression due to https://github.com/neos/neos-development-collection/pull/3915. Will take care
