### ISSUE TITLE
BUG: Fusion based Backend Modules do not render flash messages

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#3998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a backend module is rendered via fusion flash messages are never show.

### Expected Behavior

Flash messages should always be rendered in the backend.

### Environment

```markdown
- Flow: *
- Neos: *
- PHP: *
```

**Comment by mhsdesign** [comment]
Nice solution you found in https://github.com/neos/neos-development-collection/pull/3999 ;)
