### ISSUE TITLE
FEATURE: Improve feedback of workspace review submit buttons / publishing process

### ISSUE THREAD

**Issue by Benjamin-K** [neos/neos-development-collection#4003]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

When reviewing a workspace and you do not want to publish or discard all changes, you will probably select multiple changes to hit the `Publish selected changes` or `Discard selected changes` button. But if you do not do this at regular intervals, you might possibly hit the wrong button.

This has the following reasons:

- Both buttons for the selected changes have the same color (grey).
- Both buttons have the same color on hover (blue, see screenshot below).
- The order of the buttons is in reversed order than the buttons for all changes.

<img width="807" alt="Submit buttons in workspace review for selected changes when hovering `Discard selected changes`" src="https://user-images.githubusercontent.com/3098031/212305992-cc65dd04-9b93-43d1-b8ab-36f332099a07.png">

Submit buttons in workspace review for selected changes when hovering `Discard selected changes` 

### Possible Solution

As many editors already are used to the order of the buttons, we should change the hover color for the button to `Discard selected changes` to the same color used for `Discard all changes`. This will give better visual feedback and therefore prevent users from clicking the wrong button.

**Comment by crydotsnake** [comment]
Hello @Benjamin-K 

Thanks, for raising this up! And i agree with you too 100%. This can definitely be improved.

**Comment by manuelmeister** [comment]
Maybe these buttons should also move closer to the checkboxes.

**Comment by ghost** [comment]
Just did a quick design suggestion:
![Artboard](https://user-images.githubusercontent.com/32840810/214038854-209f8705-c707-4238-8fa4-9bd64a2442ed.png)
What I did:
* Added icons
* Put the discard and publish buttons together
* Added consistency regarding the expected color schemes (red = discard, blue = publish)
* Added the concept of primary and secondary buttons so that users can visually distinguish their functionality

**Comment by bwaidelich** [comment]
I like the idea of adding icons and unifying button colors. But maybe we should try to avoid introducing yet another button style and icons. What about using warning for the second one like
![image](https://user-images.githubusercontent.com/307571/214057130-303450ae-5861-41c9-b314-d5e899e33bda.png)

Also: The order @fabiantschoek suggested makes sense IMO, but it leads to the buttons jumping when (de-)selecting items to change. Is that a problem?

And lastly I would suggest to activate the confirmation modal for the "Discard selected changes" button too to prevent changes from getting lost by accident

**Comment by bwaidelich** [comment]
btw: I couldn't find the icons Fabian used for the "publish" buttons. They fit better than the one I chose. But in the publish menu we actually use check marks:
![image](https://user-images.githubusercontent.com/307571/214058026-edd8904d-71b0-48c5-99a1-4bfd21556caf.png)

So what about 
![image](https://user-images.githubusercontent.com/307571/214058625-2f08900f-645e-4ed1-8597-36261738dee9.png)

**Comment by bwaidelich** [comment]
..or maybe just
![image](https://user-images.githubusercontent.com/307571/214058802-b18cb505-cf59-46ef-9a7d-88097d3b8c26.png)

/spam

**Comment by ghost** [comment]
@bwaidelich I created the publish icon myself :) If we chose that, I'm happy to provide that. I'm also good with the trash bin icon to discard changes. That makes total sense to use. But I don't like the grey button to publish selected changes. Grey isn't really a color that means "confirm" by any chance in any other UI I've ever seen.

There is also some inconsistency in your suggestion: orange is used to discard selected changes but also notifies users about unpublished changes. I would therefore not go with orange for `discard selected changes`. We could also use the grey color for this. That would make more sense to me.

I'd love to see some color/design differences between the four options. Also, I like the tiny difference in the checkmark icon :)

**Comment by bwaidelich** [comment]
Ah, thanks :)
I just thought of a completely different approach, hiding the "discard/publish all" buttons if nodes are selected:

## default

![image](https://user-images.githubusercontent.com/307571/214061997-cd6eac13-c281-4d47-afc7-1363acda5f93.png)

## changes selected

![image](https://user-images.githubusercontent.com/307571/214062131-91dc4da2-c4e2-46eb-b6f7-2e2f031c0f25.png)

This in combination with the confirmation dialog for both "dangerous" buttons should do the trick IMO

**Comment by Benjamin-K** [comment]
I'd prefer not to have a wide list with four buttons. Either we make two rows or we switch to @bwaidelich's suggestion

**Comment by crydotsnake** [comment]
> Ah, thanks :) I just thought of a completely different approach, hiding the "discard/publish all" buttons if nodes are selected:
> ## default
> 
> ![image](https://user-images.githubusercontent.com/307571/214061997-cd6eac13-c281-4d47-afc7-1363acda5f93.png)
> ## changes selected
> 
> ![image](https://user-images.githubusercontent.com/307571/214062131-91dc4da2-c4e2-46eb-b6f7-2e2f031c0f25.png)
> 
> This in combination with the confirmation dialog for both "dangerous" buttons should do the trick IMO

I like @bwaidelich's suggestion ! 🙂

**Comment by bwaidelich** [comment]
_ping_ PR is ready to be reviewed :)
