### ISSUE TITLE
9.0: CR Legacy migration does not produce NodeReferencesWereSet events

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4004]
For each reference(s) property in the Content Repository a corresponding `NodeReferencesWereSet` event has to be published such that the references actually end up in the referencerelation read model but this is currently not the case

**Comment by skurfuerst** [comment]
Bastian takes care of this (already seen this at his laptop)

**Comment by bwaidelich** [comment]
I think, this is fixed already (see https://github.com/neos/neos-development-collection/blob/9.0/Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/References.feature)
