### ISSUE TITLE
9.0: Document new CLI commands

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4017]
At least add some inline doc comments to make `./flow help <command>` work.
For example `./flow help cr:setup`

**Comment by crydotsnake** [comment]
## List of the Neos 9 CLI commands that needs documentation

### Package: Neos.ContentRepositoryRegistry

- [ ] `./flow content:refreshrootnodedimensions`
- [ ] `./flow content:movedimensionspacepoint`
- [ ] `./flow content:createvariantsrecursively`
- [ ] `./flow contentgraphintegrity:runviolationdetection`
- [ ] `./flow contentstream:export`
- [x] `./flow cr:prune`
- [ ] `./flow structureadjustments:detect`
- [ ] `./flow structureadjustments:fix`
- [ ] `./flow subprocessprojectioncatchup:catchup`

### Package: Neos.ContentRepository.BehavioralTests

- [ ] `./flow performancemeasurement:prepareperformancetest`
- [ ] `./flow performancemeasurement:testperformance`

### Package: Neos.ContentRepository.BehavioralTests.ProjectionRaceConditionTester

- [ ] `./flow raceconditiontracker:reset`
- [ ] `./flow raceconditiontracker:analyzetrace`


ℹ️ List will be updated directly in the PR => #4230
