### ISSUE TITLE
9.0: Make welcome CLI command work with 9.0

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4018]
* Check that `./flow welcome` works with 9.0
* Add additional steps (like`cr:setup`, `cr:migrateLegacyData`)
see https://github.com/neos/neos-development-collection/tree/9.0#setup

**Comment by crydotsnake** [comment]
Hello @bwaidelich !

> Check that ./flow welcome works with 9.0

Do you mean only check if the command itself is working? Or also the listed commands on `./flow welcome` ?

I tested it and `./flow welcome` works great!

**Comment by crydotsnake** [comment]
Also i could not find the `./flow contentrepositorymigrate:run` command in the list 🤔

**Comment by bwaidelich** [comment]
> Do you mean only check if the command itself is working?

The command should basically lead you through the steps described here: https://github.com/neos/neos-development-collection/tree/9.0#setup

> Also i could not find the ./flow contentrepositorymigrate:run command in the list 🤔

That command is now called `cr:migrateLegacyData` – I updated the description above
