### ISSUE TITLE
9.0 BUG: Neos backend throws error on discarding newly created document node

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I create a new **document** node and immediately discard the change, the following error is thrown:

> TODO: SITE NOT FOUND; should not happen (for address NodeAddress[contentStream=2085e25a-107c-4fed-8cf0-4a5ac75595c2, dimensionSpacePoint={"language":"en"}, nodeAggregateIdentifier=c4eb7c78-2f5d-48b5-99c8-4ffd04ab0b5c, workspaceName=user-xyz]

On the other hand: discarding changes relating to a published document node leads to no error.

### Expected Behavior

As a user, I would like to be able to discard document nodes without publishing them first.

### Steps To Reproduce

1. Create a new page
2. Discard changes immediately without publishing while having the new page selected

### Environment

```markdown
- Flow: 8.2-dev
- Neos: 9.0-dev
- PHP: 8.1
```

**Comment by nezaniel** [comment]
This seems to be UI related... if the creation of the document you're currently on is discarded, there is no redirect feedback being sent

I see two solutions here:

- enhance the request by adding context information "WHERE have the nodes been discarded and is that location still available afterwards
- catch the "missing site" error properly and redirect to the site node matching the request URI

wdyt?

**Comment by ahaeslich** [comment]
By WHERE you think of the parent node(s)? Wouldn't we need to check which is the next parent that is not included in the discard process? And can the UI provide this context information?

**Comment by skurfuerst** [comment]
I think I have some idea what's happening here :) Will provide a PR soon.

**Comment by kitsunet** [comment]
Works for me today, closing as it seems to be solved with the mentioned PRs
