### ISSUE TITLE
9.0 BUG: Updating a workspace via the neos ui throws an error

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to save changes to an internal workspace the following error is thrown:

`Could not convert target type "Neos\ContentRepository\Core\Projection\Workspace\Workspace": Property "workspaceTitle" has neither a setter or constructor argument, nor is public, in target object of type "Neos\ContentRepository\Core\Projection\Workspace\Workspace".`

I suspect that this applies not only to the title.

### Expected Behavior

I can update all properties of a workspace which are editable in the ui.

### Steps To Reproduce

1. Create an internal workspace (fyi: it must be an internal workspace as the private ons won't show up in the backend module)
2. Edit the title field
3. Save 

### Environment

```markdown
- Flow: 8.2-dev
- Neos: 9.0-dev
- PHP: 8.1
```

### Anything else?

Related issues I encountered while using the workspaces:

- #4042
- #4043
- neos/neos-ui#3377

**Comment by skurfuerst** [comment]
Tjamls @dlubitz <3 merged
