### ISSUE TITLE
9.0 BUG: Private workspaces don't show up in the workspace module

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you create a new workspace and select `Visibility:private` the workspace won't show up in the list of available workspaces.

I checked the database and found that all workspaces regarded as internal don't have a `workspaceowner`:

```
workspacename  baseworkspacename  workspacetitle  workspacedescription	 workspaceowner  currentcontentstreamid  status
live           NULL               Live            Public live workspace  NULL            a5a965de...             UP_TO_DATE
test-2-p1596   live               Test 2                                 NULL            e403ca15...             UP_TO_DATE
test-lllmy     live               Test                                   1f34eb32...     6a2b760e...             UP_TO_DATE
user-admin     live               Admin Admin                            NULL            4b8c4d65...             UP_TO_DATE
```

### Expected Behavior

A private workspace is visible and usable by the user wich creates it.

### Environment

```markdown
- Flow: 8.2-dev
- Neos: 9.0-dev
- PHP: 8.1
```

### Anything else?

Related issues I encountered while using the workspaces:

- #4041
- #4043
- neos/neos-ui#3377

**Comment by skurfuerst** [comment]
resolved :)
