### ISSUE TITLE
9.0 BUG: Trying to review changes via the workspace module throws error

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While trying to review changes via the workspace module the following error is thrown:

`Tried to convert an object of type "Neos\ContentRepository\Core\SharedModel\Workspace\WorkspaceTitle" to an identity array, but it is unknown to the Persistence Manager.`

### Expected Behavior

Show all unpublished changes in the selected workspace.

### Steps To Reproduce

First use case - direct acces via "Publish dropdown":
1. Create some changes in your node tree
2. Open "Publish dropdown"
3. Click on the button "Review changes"

Second use case - using the workspace backend module:
1. Create some changes in your node tree
2. Go to the workspace backend module (/neos/management/workspaces)
3. Click on the button "Review"

### Environment

```markdown
- Flow: 8.2-dev
- Neos: 9.0-dev
- PHP: 8.1
```

### Anything else?

Related issues I encountered while using the workspaces:

- #4041
- #4042
- neos/neos-ui#3377

**Comment by skurfuerst** [comment]
resolved :)
