### ISSUE TITLE
FEATURE: Define `default` group for inspector properties

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#4060]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

When an integrator defines a new property for the inspector it will not show up unless a valid group is assigned which leads to unnecessary frustration especially when trying out Neos.

### Possible Solution

Define a group "default" for Neos nodes and use this for all properties that have an `inspector` configuration and no explicit `group` set. 

The proposed solution is a logical extension since the same happens already with the tab "default".

**Comment by mficzel** [comment]
@markusguenther @mhsdesign since you were looking for little easy but helpful improvements for 8.3 this could be a quick win.

**Comment by mhsdesign** [comment]
Yesss why haven’t I thought of this before - this is indeed a major hurdle for newcomers … either your default proposal or strict validation with helpful errors
