### ISSUE TITLE
!!! Make Value Objects stricter

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4133]
We use a lot of `Value Objects` in the code for 9.0 but most of them lack validation.

IMO we should introduce some validation before a first release because that's impossible to do in a backwards--compatible manner lateron (it will always be possible to _relax_ the rules without breaking changes).

We should also get rid of the magic `__toString()` methods from Value Objects in order to prevent accidental type conversion.

## Example:

```php
final class PropertyName implements \JsonSerializable
{
    private function __construct(
        public readonly string $value
    ) {
        if ($value === '') {
            throw new \InvalidArgumentException('Property name must not be empty.', 1519745994);
        }
    }
    // ...

    public function __toString(): string
    {
        return $this->value;
    }
}
```

could become sth like

```php
final class PropertyName implements \JsonSerializable
{
    private const PATTERN = '/\w{1,100}/';

    private function __construct(
        public readonly string $value
    ) {
        if (preg_match(self::PATTERN, $value) !== 1) {
            throw new \InvalidArgumentException(sprintf('"%s" is not a valid Property Name because it does not match the regex pattern: %s", $value, self::PATTERN), 1519745994);
        }
    }
    // ...
}
```

**Comment by bwaidelich** [comment]
Reopening, because #4156 only addresses the `__toString()` part of this, but I would like to go over the validation rules still

**Comment by skurfuerst** [comment]
We decided that:

- NodeAggregateId should be 64 chars long max
- ContentStreamId should be 40 chars long max

**Comment by skurfuerst** [comment]
I think #4241 solves most things, but I am not sure if this is completely fixed already. @bwaidelich can look over this when he's back :)

**Comment by bwaidelich** [comment]
IMO this is done \o/
