### ISSUE TITLE
Adjust neos/redirecthandler packages for Neos 9

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#4149]

**Comment by dlubitz** [comment]
Something to discuss:

How should we handle the existing feature **restrictByPathPrefix**?
https://neos-redirecthandler-adapter.readthedocs.io/en/latest/#restrict-generation

As we don't have any paths anymore, this seems to be obsolete. But maybe there is an alternative, which might be still usefull for users?

**Comment by skurfuerst** [comment]
@dlubitz I'd drop **restrictByPathPrefix** and see how often this use case comes up.
