### ISSUE TITLE
BUG: Updating node properties of type `reference` or `references` can't be published

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Changing the value of a node property of type `reference` or `references` will update the value in the user workspace but the publish button will not be "activated". The Workspace module will also not show any changes on the updated node. Therefor the change will be shown in the user workspace but cannot be published on it's own.

Changing e.g. a `text` node property afterwards and publishing all changes will also publish the changes on the `reference` node property.

### Expected Behavior

Changing the value of a node property of type `reference` or `references` should lead to an "active" publish button.

### Steps To Reproduce

1. Define a node property of type `reference` or `references`
2. Edit the property in the inspector panel and apply the changes.

Example YAML

```
MyFancy.Site:Document.BugHunter:
  ui:
    inspector:
      groups:
        debug:
          label: 'Debugging'

  properties:
    textProp:
      type: string
      ui:
        label: 'Text prop'
        inspector:
          group: 'debug'

    referencesProp:
      type: references
      ui:
        label: 'References prop'
        reloadPageIfChanged: true
        inspector:
          group: 'debug'
          editorOptions:
            nodeTypes: ['Neos.Neos:Document']
```

In comparison with changing e.g. a node property of type `string`, the payload of the API call for `references` to the backend contains an empty array on `feedbacks.0.payload.publishableNodes`. Additionally looking into the database the table `cr_default_p_neos_change` will only indicate the changes on a `text` node property.

### Environment

```markdown
- Flow: 8.3
- Neos: 9.0
- PHP: 8.1
```

### Anything else?

I'm not so sure if this should be fixed here or in https://github.com/neos/neos-ui

**Comment by skurfuerst** [comment]
I will take care of this :)

**Comment by bwaidelich** [comment]
The same is true when the node type was changed.
I assume that there are just some `when*` cases missing from the `\Neos\Neos\PendingChangesProjection\ChangeProjection`

**Comment by ahaeslich** [comment]
Not quite sure if this is related: if you change a date property in the inspector the publish butten will be activated but the value in the inspector field will be reset to the published value instead of the workspace value. And the backend preview will show the new date.

![image](https://user-images.githubusercontent.com/1756367/231553003-b6966f84-8c42-4e3b-bca3-e7e4d42be21a.png)


PS: Tested on the current v9 branch.

**Comment by ahaeslich** [comment]
Moved it to "In Progress" again as we mentioned other cases here. I don't want them to go missing.

**Comment by dlubitz** [comment]
> The same is true when the node type was changed.

I put that into a separate issue:
https://github.com/neos/neos-development-collection/issues/4191

**Comment by dlubitz** [comment]
I also moved the datetime issue into a separate issue:
https://github.com/neos/neos-development-collection/issues/4192

So we can use this ticket for the reference issues only? @ahaeslich
