### ISSUE TITLE
Execute Behat tests only for a single content graph adapter at a time

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4179]
With the introduction of the `Neos.ContentGraph.PostgreSQLAdapter` the behat tests have been adjusted to run against both implementations.

This was done for performance reasons mainly. But it has some drawbacks:

* Tests are far more complex because they have to keep state of multiple adapters in memory and compare them individually
* Failure resolution is more difficult because one has to determine the failing implementation from the (sometimes misleading) error message
* Currently the way to skip tests for certain adapters is to use the `@adapters` tag in the feature files – this concept can't be used for future 3rd party implementations
* Tests for multiple adapters can't be executed in parallel

I would suggest to simplify the implementation again and allow to specify the adapter via `behat.yml` configuration.
To allow certain tests to be skipped during development, we could either use an allow (or deny) list of tests in the configuration or introduce feature specific annotations (like `@features=contentSubgraph.findDescendantNodes, contentSubgraph.findChildNodes` or similar).

*Note:* Previously our CI took ~1.25 hrs to execute behat tests (for PHP 8.1 and 8.2 *each*). With the sync mode (activated with #4110) they take less than 15 minutes. Besides we could probably execute them in parallel

**Comment by mhsdesign** [comment]
Current workaround for only executing maria is to add

```php
        if ($excludePostgres = true) {
            $adapterKeys = array_filter($adapterKeys, fn ($key) => $key !== 'Postgres');
        }
```

to `\Neos\ContentRepository\Core\Tests\Behavior\Features\Bootstrap\EventSourcedTrait::beforeEventSourcedScenarioDispatcher`

**Comment by nezaniel** [comment]
Has been adjusted in #4455; Which adapter to use can now be set via configuration

**Comment by nezaniel** [comment]
has been merged and thus is resolved
