### ISSUE TITLE
BUG: Node search in reference editor doesn't return results

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I search for a content node via content reference editor, I don't get any results. 

As it seems the query is internally build for doctrine to search for 'searchTerm%', which excludes all nodes where the property doesn't exactly start with the search term e.g if it contains also HTML.

### Expected Behavior

I'd like to get all matching nodes as result.

### Steps To Reproduce

1. Create a content element which has 'Neos.Neos:Content' as supertype (e.g Neos.Demo:Content.Headline)
2. Set the headline to "My Headline"
3. Create a node of type `Neos.NodeTypes.ContentReferences:ContentReferences`
4. Search for "My" or "Headline"

### Environment

```markdown
- Flow: 8.3
- Neos: 9.0
- PHP: 8.1
```

### Anything else?

See: https://github.com/dlubitz/neos-development-collection/blob/1ebc9af8ee66760b8c9375b570f06e54f0540909/Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php#L606-L606

**Comment by skurfuerst** [comment]
Resolved in https://github.com/neos/neos-development-collection/pull/4233
