### ISSUE TITLE
BUG: Changing a NodeType type doesn't get marked as "changed"

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4191]
If you change the type of a NodeType the workspace doesn't get marked as "changed". So you are not able to publish this particular change without changing something else.

As in the new CR nodes are consistently typed across variants there are some open questions to clarify:
- How shall we mark this change as "changed" without having a dimension space point for this change
- Does it make sence to mark all dimension space points as "changed"?
- How does publishing than work? Do I need to publish each dimension space point or just one to get this change published?
- How do we deal with permissions if a user has e.g. permissions for language A but not for language B?

See also: https://neos-project.slack.com/archives/C3MCBK6S2/p1681472294867779

**Comment by mhsdesign** [comment]
cc @nezaniel this might be also interesting to you ;)

**Comment by nezaniel** [comment]
yep, that's the next elephant on my list (and the last element on my testing graph)

**Comment by kitsunet** [comment]
Weirdly the described problem no longer exists. A change is triggered on changing the nodetype, however, discarding the change does not reset the nodetype to it's previous state.
