### ISSUE TITLE
Progress bar for projection replay

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4200]

**Comment by bwaidelich** [comment]
Idea: Use `ProjectionInterface::getSequenceNumber()` to determine progress?
Also: maybe parallel execution of replays (inspiration: https://github.com/bwaidelich/Wwwision.BatchProcessing)

**Comment by crydotsnake** [comment]
Hello Bastian!

Is this only related too:
https://github.com/neos/neos-development-collection/blob/9a6f8d2925e08451b64c83a8c5c7a13576764fc4/Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php#L53
https://github.com/neos/neos-development-collection/blob/9a6f8d2925e08451b64c83a8c5c7a13576764fc4/Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php#L57 ?

Or is this also needed in other places?

**Comment by bwaidelich** [comment]
yes, that's related
