### ISSUE TITLE
BUG: Fusion Augmenter removes existing paramters if set to `null`

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I pass `null` as value to the Augmenter, it removes also existing paramter values within the augmented element.

This behavior is new and maybe intended. But it's a breaking change in a minor update (8.2 => 8.3). 

### Expected Behavior

I'd expect, nothing happens if I augment an element with `null`.

If this is an intended behavior I would at least expect this change in a major update.

### Steps To Reproduce

```
prototype(VIVOMEDIA.Test:Component) < prototype(Neos.Fusion:Component) {

    background = ${null}

    renderer = afx`
        <Neos.Fusion:Augmenter class={props.background}>
            <div class="foo">content</div>

        </Neos.Fusion:Augmenter>
    `
}
root = VIVOMEDIA.Test:Component
```

Result in 8.2:
```
<div class="foo">content</div>
```

Result in 8.3
```
<div>content</div>
```

### Environment

```markdown
- Flow: 8.3
- Neos: 8.3
- PHP: 8.1
```

**Comment by mficzel** [comment]
That is not intendet afaik. We will investigate @mhsdesign seems augmenter and null continues to be interesting

**Comment by mhsdesign** [comment]
Thx for reporting this. Yes seems like it @mficzel ;)

Cause: https://github.com/neos/neos-development-collection/pull/4081
