### ISSUE TITLE
BUG: Specified key was too long (MySQL & Neos 9)

### ISSUE THREAD

**Issue by anianweber** [neos/neos-development-collection#4229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While running `./flow cr:setup` the following exception is thrown:
```
An exception occurred while executing 'CREATE TABLE cr_default_p_neos_asset_usage (assetid VARCHAR(40) DEFAULT '' NOT NULL, originalassetid VARCHAR(40) DEFAULT NULL, contentstreamid VARCHAR(255) DEFAULT '' NOT NULL, nodeaggregateid VARCHAR(255) DEFAULT '' NOT NULL, origindimensionspacepoint LONGTEXT DEFAULT NULL, origindimensionspacepointhash VARCHAR(255) DEFAULT '' NOT NULL, propertyname VARCHAR(255) DEFAULT '' NOT NULL, UNIQUE INDEX assetperproperty (assetid, originalassetid, contentstreamid, nodeaggregateid, origindimensionspacepointhash, propertyname), INDEX assetid (assetid), INDEX originalassetid (originalassetid), INDEX contentstreamid (contentstreamid), INDEX nodeaggregateid (nodeaggregateid), INDEX origin_dsp_hash (origindimensionspacepointhash)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB':
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was
too long; max key length is 3072 bytes
```

### Expected Behavior

`./flow cr:setup` doesn't throw an exception.

### Steps To Reproduce

- Use MySql 8
- Run `./flow cr:setup`

### Environment

```markdown
- MySql: 8.0.32
- Flow: 8.3.x-dev
- Neos: 9.0.x-dev
- PHP: 8.1
```

### Anything else?

The problem is (as far as i can see) caused by the Uniquie Index.
Removing the Uniquie Index in https://github.com/neos/neos-development-collection/blob/c98694b91630f48dfade9c8c8d9fa4f7639b102b/Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepository.php#L84 solves the issue. Furthermore, removing any `VARCHAR(255)` column form the Unuquie Index solves the problem.

**Comment by skurfuerst** [comment]
thanks for reporting, we should check to shorten some columns. thanks :)

**Comment by anianweber** [comment]
The issue is resolved. Thanks everybody!
