### ISSUE TITLE
9.0 `Node` easy access to string representation for debugging / logging

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4231]
I know we recently remove quite a few __toString implementations, but it still would be nice to have maybe a `toString` method (that is not automatically called) which returns something like:

`[Foo.Bar:NodeType] 32423-42344-234234`

anyone against it? (The old node was string castable btw thats why) and its always useful for logging.

Format of the old node:

> Node /sites/test-site/homepage/node-85xy7jgl1bpko@live[Your.Vendor:NodeType]

**Comment by kitsunet** [comment]
I am actually not a huge fan after talking to basti about removing those. Especially for an object like nodes, it could happen that an implicit conversion is triggerd and you get quite unexpected and hard to debug results.

**Comment by mhsdesign** [comment]
Maybe `Node::__debugInfo` would be helpful? https://www.php.net/manual/en/language.oop5.magic.php#object.debuginfo

edit: not really, as we must return an array i think, and the properties are var_dumped fine already

**Comment by mhsdesign** [comment]
In the old cr i think it was always helpful to have the node string cast to show its full context path. That gave in logs information about the workspace and also the node path. The node aggregate id is not really human readable and one doesnt know where in the site the node lies.

What do you say? How would you like nodes to be serialized in logs or in errors for editors in the ui?

ping @nezaniel @bwaidelich

**Comment by bwaidelich** [comment]
I think
```php
public function __debugInfo(): array
{
    return [
        'type' => $this->nodeType->value,
        'id' => $this->id->value,
    ];
}
```
would totally make sense

**Comment by bwaidelich** [comment]
(or including workspace and whatever might be useful of course)

**Comment by mhsdesign** [comment]
`__debugInfo` seems to only be used for var_dump, and the current var dump output is fine as is.

@dlubitz and @ahaeslich though of a `NodeUtility`  which has access to the cr registry and can print out a nice debug string for nodes:


```php
public function nodeToDebugString(Node $node): string
{
        $workspace = $this->contentRepositoryRegistry->get($node->subgraphIdentity->contentRepositoryId)->getWorkspaceFinder()->findOneByCurrentContentStreamId(
            $node->subgraphIdentity->contentStreamId
        );

        return sprintf('[%s] %s %s', $node->nodeType->name->value, $node->nodeAggregateId->value, $workspace->workspaceName->value);
}
```

alternatively, in case the legacy nodepath is more helpful for debugging, we could also use $subgraph->retrievePathForNode

**Comment by bwaidelich** [comment]
`__debugInfo` is fine to improve logging and debugging output. For everything else I would _not_ suggest to add yet another utility until it is really required because the desired output is depending on the specific use case.

E.g. for the UI you might want to display the type, id and path and it make sense to do that in the exact part that converts the node instance to a human readable string IMO

**Comment by mhsdesign** [comment]
Okay i also dislike a utility, but what about a simple `toDebugString` in the node itself?

```php
public function toString(): string
{
        return sprintf('Node<%s, %s>', $this->nodeType->name->value, $this->nodeAggregateId->value);
}
```

```
Node<Neos.Demo:Lol, 1234-1234-1234-1234>
```

**Comment by mhsdesign** [comment]
We discussed this in the weekly and i agreed with @bwaidelich that really depends on the context where the exceptions is thrown and the is no generic best solution for it.

As you said earlier

> E.g. for the UI you might want to display the type, id and path and it make sense to do that in the exact part that converts the node instance to a human readable string IMO


And writing 

```php
throw SomethingIsWrongException(
  sprintf('The Node "%s" of type "%s" ...', $this->nodeAggregateId->value, $this->nodeType->name->value)
);
```

in ones code doesn't justify the complexity of a yet another utility class ;)
