### ISSUE TITLE
9.0 rewrite`${node.context}` to `${Neos.Node.subgraphForNode(node)}`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4232]
In the effort of avoiding passing the old node everywhere i tried to reduce the usage of the old node and passed the NodeContext instead when it sufficed.  ((R) pattern by @nezaniel ^^)

so my fusion looks like this in places:

```
foo = SomeFunny:Object {
   subgraph = ${node.context}
}
```

id like to migrate it to something like:

```
foo = SomeFunny:Object {
   subgraph = ${Neos.Node.subgraphForNode(node)}}
}
```

`Neos.Node.subgraphForNode` has to be written yet ...

what do you say?

**Comment by skurfuerst** [comment]
yeah, subgraphForNode is a good idea IMHO :) @mhsdesign feel free to impl :)
