### ISSUE TITLE
9.0 BUG: DocumentUriPathProjection produces false uris on replay

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As the DocumentUriPathProjection caches the node in memory, this cached node (incl. node uri path) get's used for all events. This leads to two issues:
1. The node uri path in the projection get's wrongly replaced in the database table, if multiple changes where tracked in the events.
2. The signal gets different `oldPath` values in replay vs. the actually event. `oldPath` is during a replay always set to the "first" nodes uri path.

We need to disable the runtime cache during a projection replay to solve that issue.

See: 
https://github.com/neos/neos-development-collection/blob/7349577c23d43e56e433b0d3ebdaa8d5f89b1deb/Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php#L542
https://github.com/neos/neos-development-collection/blob/7349577c23d43e56e433b0d3ebdaa8d5f89b1deb/Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathFinder.php#L77-L77

### Expected Behavior

The `oldPath` / old node needs to be loaded for each event. 
1. So the replay produces proper uris paths
2, So the behavior of the signal is the same in the replay as during the actual event handling

### Steps To Reproduce

1. Create a node and publish
2. Change uriPathSegment and publish
3. Change uriPathSegment to longer one and publish
4. Run replay of the projection

### Environment

```markdown
- Flow: 8.3
- Neos: 9.0
- PHP: 8.1
```

**Comment by skurfuerst** [comment]
Awesome, this should be rather easy to fix. If you want to try , I can sketch out the idea tomorrow; otherwise I can prepare a PR :)

**Comment by dlubitz** [comment]
Sure, you can show me your idea!

**Comment by skurfuerst** [comment]
also fixed by PR #4266 now.

**Comment by skurfuerst** [comment]
merged :)
