### ISSUE TITLE
BUG: Neos 7.2 is not compatible with php < 8.0 other than communicated in system requirements

### ISSUE THREAD

**Issue by klfman** [neos/neos-development-collection#4254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just updated to Neos 7.2 in a php 7.4 environment. I got a php exception that makes me think that Neos 7.2 is in fact not compatible with php < 8.0 as stated [here](https://docs.neos.io/guide/installation-development-setup/system-requirements).

```
syntax error, unexpected '=>' (T_DOUBLE_ARROW)
Type: ParseError
  File:
Packages/Application/Neos.Fusion.Afx/Classes/Service/AfxService.php
  Line: 46
```

And that line uses a `match` expression, that does not work below php 8.0.

The installed version of neos/fusion-afx is 8.3.0.

### Expected Behavior

Compliance with https://docs.neos.io/guide/installation-development-setup/system-requirements by updating the requirements or downgrading the Version of neos/fusion-afx to match the requirements.

### Environment

```markdown
- Flow: 7.2
- Neos: 7.2
- PHP: 7.4
- The installed Version of neos/fusion-afx is 8.3.0
```

**Comment by kitsunet** [comment]
This will fix it: https://github.com/neos/neos-development-collection/pull/4258
