### ISSUE TITLE
9.0 BUG: DocumentUriProjection doesn't respect fallback nodes

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I change the `uriPathSegment` of a node in a dimension with a fallback dimension, the uriPath gets only updated for the changed node in this dimension. The fallback node (which just shines through) has still the old uriPath.

### Expected Behavior

The uriPath should also get updated to the new `uriPathSegment`.

### Steps To Reproduce

Create a multi-dimensional setup with a fallback dimension. E.g:
language: en_US => fallback en_GB

Create a document node in en_US with uriPathSegment "test" and publish. 
=> /en_US/test.html
=> /en_GB/test.html

Change the uriPathSegment of the node in en_US to "new-test" and publish.
=> /en_US/new-test.html
=> /en_GB/test.html

### Environment

```markdown
- Flow: 8.3
- Neos: 9.0
- PHP: 8.1
```

**Comment by skurfuerst** [comment]
Thanks for the detailed explanation! I will look into this :)

**Comment by skurfuerst** [comment]
merged :)
