### ISSUE TITLE
TASK: Within collection require packages as self.version

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-development-collection#4257]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

To ensure packages released together from the same mono-repository are always installed in matching versions, those should require each other as `self.version`, possible since Composer 2.2.8 (see https://github.com/composer/composer/issues/10593).

This would provide and eaasy way to avoid `*` constraints that otherwise might lead to unintentional upgrades (or downgrades) of packages.

As an added bonus it would make it easier to spot failed mono-repo splits.

**Comment by kdambekalns** [comment]
Related: https://github.com/neos/flow-development-collection/issues/3034

**Comment by kitsunet** [comment]
Note dispite this being closed, I think we should make a final pass on this in 9.0 with all the new packages. Will tke care before beta on tuesday.

**Comment by kdambekalns** [comment]
> make a final pass on this in 9.0 with all the new packages.

That _should_ be done, I went through that with my "extraction PR" during the sprint. Nut checking again does no harm. 😎

**Comment by ahaeslich** [comment]
It worked as expected
