### ISSUE TITLE
9.0: Add affected dimension space points to NodePropertiesWereSet event types

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#4265]
Other than the related events the events NodePropertiesWereSet and NodeReferencesWereSet don't contain the dimension space points that were affected.

This is required to fix https://github.com/neos/neos-development-collection/issues/4256

As a result it is not possible to tell which node variants were updated without tracking the dimension fallback chain

Original issue: https://github.com/neos/contentrepository-development-collection/issues/163

**Comment by skurfuerst** [comment]
merged :)

**Comment by mhsdesign** [comment]
Just for reference (no pun intended) i think the `NodeReferencesWereSet` also misses the information for affected DSP's - nothing to fix now - but this will bite us in the future when we want to reimplement the change projection ;) -> maybe well find a way to migrate existing events then, but the clever step by step replay will be super expensive and fragile and not due for production ...
i hope we can easily look into all variation events to find out a nodes covered dimensions at any time.

Also related that `NodeAggregateTypeWasChanged` does not know it affected dsp's https://github.com/neos/neos-development-collection/pull/5395
