### ISSUE TITLE
9.0 BUG: Shortcut settings are not updated in `DocumentUriPathProjection` table on document creation

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a user creates a new document of type shortcut the changes on `targetMode` wont be persisted in `cr_default_p_neos_documenturipath_uri`. It will always contain `parentNode` on first creation although the data in `cr_default_p_graph_node` is updated correctly.

As I debugged the data in `cr_default_p_neos_documenturipath_uri` I did disable the cache in `DocumentUriPathFinder`. In this case all new shortcut nodes were updated in the `DocumentUriPathProjection`.

But this behaviour couldn't be reproduced with `targetMode` set to `firstChildNode`.

Example from the database:
| uripath | shortcuttarget |
| - | - |
| test-shortcut-cached | {"mode":"parentNode","target":"https:\/\/www.google.com"} | 
| test-shortcut-firstChild-cached | {"mode":"firstChildNode","target":null} |
| subfolder/test-shortcut-cached | {"mode":"parentNode","target":"node:\/\/28255929-524f-4461-b125-78a11e1559a4"} | 
| test-shortcut-uncached | {"mode":"selectedTarget","target":"https:\/\/www.google.com"} | 

### Expected Behavior

Switching `targetMode` on document node creation to `selectedTarget` should be persisted in projection table.

### Steps To Reproduce

1. Create a node of type shortcut
2. Change `targetMode` to `selectedTarget`
3. Select a document node for `target` or choose an external link
4. Publish

### Environment

```markdown
- Flow: 8.3
- Neos: 9.0
- PHP: 8.1
```

### Anything else?

⚠️ Testing this with: #4266 

Relates: #4253

**Comment by ahaeslich** [comment]
@skurfuerst your commit https://github.com/neos/neos-development-collection/pull/4266/commits/fa0ed72bdd7e2bbedf3275d65d1c59b9fbf2f9d9 also fixes this bug

**Comment by skurfuerst** [comment]
merged :)
