### ISSUE TITLE
BUG: newly created node is not selected

### ISSUE THREAD

**Issue by so-grimm** [neos/neos-development-collection#4280]
### Description
When creating a new content node on a page, the new node used to get automatically selected and therefore also scrolled into view in previous Neos versions. In Neos 9, when a new node is created, the previously selected node stays selected and therefore the new node is not scrolled into view. 

### Steps to Reproduce

1. Click on the main content collection
2. Click the plus sign to create a new node
3. Choose any content module and create it

#### Expected behavior

After executing the steps described above, the newly created node should be selected/focused

#### Actual behavior

After executing the steps described, the main content collection is still selected/focused

### Affected Versions

Neos: 9.0

UI: 9.0.x-dev

**Comment by skurfuerst** [comment]
My analysis so far:

## old behavior

- Request:
  <img width="983" alt="SCR-20230515-qodj" src="https://github.com/neos/neos-ui/assets/190777/02e647d1-12b9-4561-aafa-6b8b413f1c60">

- Response: 
  <img width="769" alt="SCR-20230515-qolu" src="https://github.com/neos/neos-ui/assets/190777/60bad8d5-1f10-403f-be18-e959ef3e11f6">

## New behavior
<img width="535" alt="SCR-20230515-qoqh-2" src="https://github.com/neos/neos-ui/assets/190777/827af0be-a5e1-41a2-bdeb-7cc6e9b51f2a">

<img width="533" alt="SCR-20230515-qpdo" src="https://github.com/neos/neos-ui/assets/190777/6f84a632-e046-4695-8bf6-4eeb8c96dc8c">

**Comment by skurfuerst** [comment]
# old

<img width="687" alt="SCR-20230515-qpwr" src="https://github.com/neos/neos-ui/assets/190777/d7db6f4e-aba8-4b1c-9127-11cc29395a25">

# new

<img width="773" alt="SCR-20230515-qqav" src="https://github.com/neos/neos-ui/assets/190777/9cff1c45-d521-4b99-8c23-1e1a13cdf24b">

# Next question: Why did this change? :)

**Comment by skurfuerst** [comment]
# in 8.3

https://github.com/neos/neos-ui/blob/8.3/Classes/Aspects/AugmentationAspect.php#L126-L127


# in 9.0

https://github.com/neos/neos-development-collection/blob/794f197ba40564c27ca0078fae8fafd9c3d9e65f/Neos.Neos/Classes/Service/ContentElementWrappingService.php#L133https://github.com/ClaraRuna/neos-development-collection/blob/794f197ba40564c27ca0078fae8fafd9c3d9e65f/Neos.Neos/Classes/Service/ContentElementWrappingService.php#L133

=> class out of sync, and wrongly converted

**Comment by skurfuerst** [comment]
(moved the issue because the fix is in neos-development-collection)
