### ISSUE TITLE
Improve performance for publish/discard of workspaces by using the synchronous mode

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#4285]
During publishing of nodes, we usually fork sub-processes for event processing (for every event). This drastically slows down these operations. We can enable synchronous mode in these methods, to speed up the system at least by a factor 2-3 for these operations.

It *could* have some side-effects if caches were not properly cleared,
but at least I did not see any yet (and we run tests often with this flag).

Related: #4388

**Comment by mhsdesign** [comment]
For testing i enabled the synchronous mode for publishing Nodes in the Neos.Ui and yes the performance will be drastically improved.

Maybe by only blocking for the content graph we can speed up the process while still maintaining our philosophy? (as suggested by @bwaidelich)

```php
$cr->handle($command)->block(ContentGraphProjection::class);

// next code that requires the ContentGraphProjection to be up to date but doest "care" about other projections.
```

Related: https://github.com/neos/neos-development-collection/issues/4746

I think releasing Neos 9 without any further performance improvements - especially if the are so easy and only our own concepts are holding us back - would be a mistake.

**Comment by bwaidelich** [comment]
This will be obsolete with #4746
