### ISSUE TITLE
Rename (and overhaul?) NodeHiddenStateProjection

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4315]
As @mhsdesign correctly [brought up](https://github.com/neos/neos-development-collection/issues/4312#issuecomment-1580230420), the term `NodeHiddenState` is not in sync with the notion of **disabled** nodes.

I guess, with the suggestions from #3732 we could that projection into one that calculates "attributes" (or what we end up calling these) for nodes and their descendants, such that instead of
```php
$nodeHiddenStateFinder->findHiddenState();
```
we could do something like
```php
$nodeAttributeResolver->hasAttribute(NodeAddress $node, 'disabled');
```

**Comment by mhsdesign** [comment]
@nezaniel and me discussed to rename the `NodeHiddenState` directly to `NodeRestrictionState` so we can later with Neos 9.1 enrich this feature with more than just two states (frontend users and backend users): https://github.com/neos/neos-development-collection/issues/3732

**Comment by mhsdesign** [comment]
We want to move this projection into Neos.Neos to make this less "stable api"

**Comment by mhsdesign** [comment]
might be solved with the introduction of attributes: https://github.com/neos/neos-development-collection/issues/4550

**Comment by mhsdesign** [comment]
Solved via https://github.com/neos/neos-development-collection/issues/4550

`$nodeIsDisabled = $node->tags->contain(SubtreeTag::disabled());`
