### ISSUE TITLE
BUG: `NodeType` `$fullConfiguration` is accessed when nodeType is not initialized.

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4333]
The NodeType (in 9.0) Has a TODO at the top

> TODO: REFACTOR TO immutable readonly; and value objects

and that is pretty valid, as currently the nodeType is mutable and lazyloads its configuration.

This is problematic, in cases when we forget to call `$this->initialize()` before accessing `$this->fullConfiguration`.

I encountered this problem while testing, in my case `getPropertyType` didnt return the expected result.

https://github.com/neos/neos-development-collection/blob/b217795f8e3fc97ab168836b9e33cbe4affcf645/Neos.ContentRepository/Classes/Domain/Model/NodeType.php#L436-L442

doesnt initialize the nodetype ... but other methods trigger this sideeffect correctly like `getProperties`

https://github.com/neos/neos-development-collection/blob/b217795f8e3fc97ab168836b9e33cbe4affcf645/Neos.ContentRepository/Classes/Domain/Model/NodeType.php#L424-L428

A workaround is to call `getFullConfiguration()` before `getPropertyType` to initialize.

Other affected methods are fx.  `getTypeOfAutoCreatedChildNode`

Affected Versions:

7.3 ... 9.0

**Comment by mhsdesign** [comment]
WOW https://github.com/neos/neos-ui/blame/a6d78fef508a3fd5dcaa397de746d0813bdfdff9/Classes/Domain/Service/NodePropertyConversionService.php#L47-L50

**Comment by mhsdesign** [comment]
And helllo there


![](https://media.tenor.com/gEsYJu_Xqq0AAAAC/morning-star-hello-there.gif)


 https://github.com/neos/neos-development-collection/blob/6e1f233e41eeac510b8ff89646282adcca923237/Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToAssetsProcessor.php#L46

**Comment by bwaidelich** [comment]
Great to _finally_ have a bug report for this – we kept hacking around this issue, as you realized :)

IMO we should just add the `initialize()` call to all methods in the `NodeType` that require it.

For 9.0 I still hope that we can turn the `NodeType` into a less magic self-translating, lazy-loading beast with [#4228](https://github.com/neos/neos-development-collection/issues/4228)
