### ISSUE TITLE
9.0 BUG: Changing node names allows to create two nodes with identical names below a single 

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#4343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i alter a node name via the command `ChangeNodeAggregateName` it is possible to set the name to the name of an existing node resulting in the parent having two children with the same name.

### Expected Behavior

The name collision should be detected and an exception should be thrown as is the case for the command `CreateNodeAggregateWithNode`.

### Steps To Reproduce

1. create a parent node 
2. create a childnode with name `foo`
3. create another childnode with name `bar` -> is allowed
4. create another childnode with name `foo` -> Exceotion is thrown righfully
5. rename childnode `bar` to `foo` -> !!! is allowed but should not be !!!

### Environment

```markdown
- Flow: 9.0-dev
- Neos: 9.0-dev
- PHP: 8.1
```

**Comment by bwaidelich** [comment]
~I hope that this will be fixed with #4313~
