### ISSUE TITLE
!!! TASK: Replace `ArrayIterator` return types with `Traversable`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4353]
There should be a way to retrieve the raw nodes as array.

Currently we hack our way around this sometimes with 

```php
getIterator()->getArrayCopy();
```

which is odd, as we over qualify the interface from `\Traversable` to `\ArrayIterator`, and are bound to this implementation forever.

For example it might be more performant to use `yield from` like this: But it doesn't satisfy `\ArrayIterator`  

```php
public function getIterator(): \Traversable
{
   yield from $this->items;
}
```

**Comment by nezaniel** [comment]
I'd use iterator_to_array for Nodes.
The overqualification should be removed, though, yes

**Comment by mhsdesign** [comment]
is there actually a reason to cache the iterator? seems dangerous as isnt it mutable?

```php
/**
 * @var \ArrayIterator<string,NodeAggregate>
 */
private \ArrayIterator $iterator;

/**
 * @param array<string,NodeAggregate> $nodeAggregates
 */
public function __construct(array $nodeAggregates)
{
    // ...
    $this->iterator = new \ArrayIterator($nodeAggregates);
}

/**
 * @return \ArrayIterator<string,NodeAggregate>
 */
public function getIterator(): \ArrayIterator
{
    return $this->iterator;
}
```

id prefer a `yield` here (@grebaldi pointed me onto this in another project once ^^)

**Comment by grebaldi** [comment]
Yep, should definitely look somewhat like this:

```php
/**
 * @param array<string,NodeAggregate> $nodeAggregates
 */
public function __construct(private readonly array $nodeAggregates)
{
}

/**
 * @return \Traversable<string,NodeAggregate>
 */
public function getIterator(): \Traversable
{
    yield from $this->nodeAggregates;
}
```

to a) safely preserve immutabiliy
and b) not expose anything more than is strictly necessary.

After that `\iterator_to_array` should be perfectly fine - so, no need for `Nodes::toArray()`.

**Comment by mhsdesign** [comment]
fyi, `iterator_to_array` is all fun and games until you do so:

```php
class Lol implements \IteratorAggregate
{
    public function getIterator(): Traversable
    {
        yield "foo"; // usecase: yield the $first item which is separate in this collection
        yield from ["bar", "baz"]; // yield the $rest / additional items
    }
}

echo json_encode(iterator_to_array(new Lol()));
// ["bar","baz"]

echo json_encode(iterator_to_array(new Lol(), preserve_keys: false));
// ["foo","bar","baz"]
```

since the index `0` exists twice once in the single yield and from the yielded array, only the last one is preserved by default (as we keep keys)

so using `iterator_to_array` must be done carefully and might not yield (pun intended) the results as expected ^^

but currently we dont happen to uses this kind of `yield` in our codebase so we are fine ^^

so one should probably use in this cases 

```php
        yield "foo";
        foreach (["bar", "baz"] as $item) {
            yield $item;
        }
        // or
        yield from ["first", ...[ "bar", "baz"]];
```
