### ISSUE TITLE
BUG: Investigate invalid `nodetypes://Neos.Demo\Collection` stream wrapper on windows in fusion

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4358]
The new NodeTypes stream wrapper might not function correctly on windows.
This was a new feature for Neos 8.2 in https://github.com/neos/neos-development-collection/pull/3903 and was only lately utilized by the Neos 8.3 demo.

The problem was originally reported by @eartahhj in step 11 here: https://github.com/neos/neos-development-collection/issues/4356

When using the Neos.Demo package the following problem appears on :

> 11. I login to the backend. It works but I cannot edit the contents of the pages because I have this error:
> 
> ```
> Invalid resource URI "nodetypes://Neos.Demo\Collection": Package "Neos.Demo\Collection" is not available.
> Exception Code	1309269952
> Exception Type	Neos\Flow\ResourceManagement\Exception
> Log Reference	20230622182009078c95
> Thrown in File	C:\Programs\laragon\www\neos\Data\Temporary\Development\Cache\Code\Flow_Object_Classes\Neos_Neos_ResourceManagement_NodeTypesStreamWrapper.php
> Line	506
> 
> Nested Exception
> Package "Neos.Demo\Collection" is not available.
> 
> Please check if the package exists and that the package key is correct (package keys are case sensitive).
> Exception Code	1166546734
> Exception Type	Neos\Flow\Package\Exception\UnknownPackageException
> Log Reference	20230622182009c58bc5
> Thrown in File	C:\Programs\laragon\www\neos\Packages\Framework\Neos.Flow\Classes\Package\PackageManager.php
> Line	208
> 
> Toggle backtrace code
> 
> Instance root	C:/Programs/laragon/www/neos/
> Application Context	Development
> Request Handler	Neos\Flow\Http\RequestHandler
> ```
> 
> ![image](https://user-images.githubusercontent.com/21332112/247997429-fda99c59-475b-4710-acc1-94d5c3db82be.png)
>
>
> ### Environment
> ```
> - Flow: Neos 8.3.3
> - PHP: 8.1.0
> - WebServer: Apache 2.4.54 on Laragon
> - DBMS: MySQL 8.0.30
> - OS: Windows 11
> ```
>
> Worth to mention: Neos 8.2.5 seems to work much better on Windows, so far. At least, it worked for me with many less issues.

**Comment by dlubitz** [comment]
This looks also like a "/" (slash) issue.

**Comment by mhsdesign** [comment]
yes, I think the fusion glob resolver doesnt transform the found path into a unix path, and this results in this malformed resource stream path.

`nodetypes://Neos.Demo/Collection` would be valid (forward-slash instead of `\`)

**Comment by mhsdesign** [comment]
@eartahhj  i found a possible fix in #4359 for your step 11 problem ;)

**Comment by mhsdesign** [comment]
will be released with the next patch ;)
