### ISSUE TITLE
TASK: `requireTetheredDescendantNodeTypesToExist` seems like a noop

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4360]
It is called when creating a node but does absolutely nothing

https://github.com/neos/neos-development-collection/blob/c1edb149d95157535b6c2abf540188aeb80d7a84/Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php#L146-L151

**Comment by bwaidelich** [comment]
That made my brain explode 🧠

**Comment by mhsdesign** [comment]
@gjwnc wrote on slack

> I think the goal of this method is to make sure that the configured childNodes actually exist. The method getAutoCreatedChildNodes() throws an Exception if the nodeTypeManager cannot initialize a nodeType instance, e.g. because of a typo somewhere.
>
> 
> ```yaml
> 'Some.Package:Some.NodeType':
>   childNodes:
>     some-property:
>       type: 'Neos.Neos:ContentCollectionn' # Typo here
> ```
> See the typo in type


in that case we should add an inline doc comment and add the necessary throws annotation in the docblock with the reason why - well there is one `@throws NodeTypeNotFoundException` but my brain just ignores this docblock stuff ...
