### ISSUE TITLE
BUG: Creation of dynamic property ResourceStreamWrapper::$Flow_Injected_Properties is deprecated

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-development-collection#4371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you install the `neos/base-distribution` with Neos 8.3 and PHP 8.2, you get an error message with Deprecated warnings right after the installation.

Affected are, if I understood it correctly, the `NodeTypesStreamWrapper`, and the `ResourceStreamWrapper` class.

## Exception:

```
Exception #1: Warning: Cannot modify header information - headers already sent by (output started at /Users/USERNAME/Workspace/Projects/neos-bakery/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_ResourceManagement_Streams_ResourceStreamWrapper.php:591) in /Users/USERNAME/Workspace/Projects/neos-bakery/Packages/Framework/Neos.Flow/Classes/Http/RequestHandler.php line 166

5 Neos\Flow\Error\ErrorHandler::handleError(2, "Cannot modify header information - headers already…eManagement_Streams_ResourceStreamWrapper.php:591)", "/Users/USERNAME/Workspace/Projects/neos-bakery/Packag…ramework/Neos.Flow/Classes/Http/RequestHandler.php", 166)
4 header("HTTP/1.1 200 OK", false)
3 Neos\Flow\Http\RequestHandler::sendResponse(GuzzleHttp\Psr7\Response)
2 Neos\Flow\Http\RequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()


HTTP REQUEST:
target: /
Host: 127.0.0.1:8081
Connection: keep-alive
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en,en-US;q=0.9
Cookie: csrftoken=tBhrUOnFcjC7G1oInBc402p7SjTq9aHq; sessionid=qb0ux0of7fra1e78jwh7oyujb6x3qic7; Neos_Session=kTeGx05PUIpK1jkQg4dkX7gaQDo3nOI7

PHP PROCESS:
Inode: 40408537
PID: 68577
UID: 501
GID: 20
User: USERNAME
```

## Screenshot

![SCR-20230629-imto](https://github.com/neos/neos-development-collection/assets/39345336/e9ad505a-b63b-47b1-acbd-82150601ac70)

### Expected Behavior

The page should open normally after installation without warnings.

### Steps To Reproduce

- Make sure you are using PHP 8.2 (check with `php -v`)
- Install the `neos/base-distribution` as usual with `composer`:
  - `composer create-project neos/neos-base-distribution neos-example`
- fire up a database container with docker (https://gist.githubusercontent.com/crydotsnake/ca14612247dcd0818861ee8bceeac3b2/raw/72876ea52add236babad39badb387a3c2b509e43/docker-compose.yaml)
- run the server `./flow server:run`
- Install Neos as usual

### Environment

```markdown
- Flow: 8.3
- Neos: 8.3
- PHP: 8.2
```

### Anything else?

If i take a look at the auto generated classes of:

 - `Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_ResourceManagement_Streams_ResourceStreamWrapper.php`
 - `Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Neos_ResourceManagement_NodeTypesStreamWrapper.php`

I see the following auto generated PHP Code:

#### Neos_Flow_ResourceManagement_Streams_ResourceStreamWrapper.php in line 591

```php
    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->packageManager = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Package\PackageManager');
        $this->Flow_Proxy_LazyPropertyInjection('Neos\Flow\ResourceManagement\ResourceManager', 'Neos\Flow\ResourceManagement\ResourceManager', 'resourceManager', '5c4c2fb284addde18c78849a54b02875', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\ResourceManagement\ResourceManager'); });
        $this->Flow_Injected_Properties = array (
  0 => 'packageManager',
  1 => 'resourceManager',
);
    }
```

#### Neos_Neos_ResourceManagement_NodeTypesStreamWrapper.php in line 611

```php
    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->packageManager = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Package\PackageManager');
        $this->Flow_Injected_Properties = array (
  0 => 'packageManager',
);
    }
```

I **assume** that it breaks at this point.

**Comment by dlubitz** [comment]
It's a duplicate of: https://github.com/neos/flow-development-collection/issues/2946
IIRC it's fixed but not released yet.

**Comment by kitsunet** [comment]
I just did upmerges yesterday, will do releases across versions today, which should get this fix out.

**Comment by crydotsnake** [comment]
It would have been smart of me to also look for this kind of issue in the flow repository as well 😄 🤦🏽 

Thank you both! I will close this issue then :)
