### ISSUE TITLE
9.0 BUG: Behat tests in Neos.RedirectHandler.NeosAdapter do not run pipeline

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4376]
Running the behat tests of the `Neos.RedirectHandler.NeosAdapter` package in Github Actions, raises following error for all scenarios:

```
Failed to acquire checkpoint lock for subscriber "Neos\Neos\FrontendRouting\Projection\DocumentUriPathProjection_Original" because a transaction is active already (Neos\EventStore\Exception\CheckpointException)
```

The tests are running fine on local environment.

PR:
https://github.com/neos/redirecthandler-neosadapter/pull/60

Build action log:
https://github.com/neos/redirecthandler-neosadapter/actions/runs/5401638101/jobs/9811724908?pr=60

**Comment by bwaidelich** [comment]
dedicated distribution branch for testing: https://github.com/neos/neos-development-distribution/tree/feature/90/redirect-adapter

**Comment by dlubitz** [comment]
This is fixed by refactoring Neos Behat test suite and proper fixes in the pipeline.
