### ISSUE TITLE
9.0 BUG: Accessing a disabled page will throw "SITE NOT FOUND" error

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading to the latest Neos 9.0 version and disabling a page in backend the following error will be thrown:

```
TODO: SITE NOT FOUND; should not happen (for address NodeAddress[...]
```

### Expected Behavior

Neos should return a 404 status code

### Environment

```markdown
- Flow: 9.0
- Neos: 9.0
- PHP: 8.2
```

**Comment by dlubitz** [comment]
The showAction in NodeController throws the exception:
https://github.com/neos/neos-development-collection/blob/552e52ebe05b8b3d438d05e7dde51bd692fd2fb5/Neos.Neos/Classes/Controller/Frontend/NodeController.php#L216-L222

ATM I don't understand, how it can reach this point.

**Comment by ahaeslich** [comment]
Will dig further today unless someone else is faster 😉

**Comment by dlubitz** [comment]
I guess this is cache related. If I clear the cache after the exception and re-request the URL I get the expected 404.

**Comment by kitsunet** [comment]
Sounds like routing cache then?

**Comment by dlubitz** [comment]
Not sure where to look at. I already tried:
1. New signal on NodeAggregateWasDisabled with to flush cache with router caching service. Similar to https://github.com/neos/neos-development-collection/blob/552e52ebe05b8b3d438d05e7dde51bd692fd2fb5/Neos.Neos/Classes/Package.php#L149-L150
2. Flush one cache for `Flow_Mvc_Routing_Route`
3. Flush one cache for `Flow_Mvc_Routing_Resolve`

But all of them without any effect.

**Comment by dlubitz** [comment]
Neh.... so I double checked... and flushing `Flow_Mvc_Routing_Route` solves the issue.

**Comment by dlubitz** [comment]
Ok, so I nailed it down to this issue: https://github.com/neos/neos-development-collection/issues/4379
