### ISSUE TITLE
9.0 BUG: Router cache flush on "documentUriPathChanged" uses wrong tag

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4378]
When a document uriPath has changed the router cache for the affected nodes/uris need to get flushed. Otherwise the node is still accessable on the old uri.

This current implementation uses the `uriPath` of the DocumentUriPathProjection, which does not contain the dimension prefixes and uri suffix. So the calculated hash/tag does not match the original entry.

https://github.com/neos/neos-development-collection/blob/552e52ebe05b8b3d438d05e7dde51bd692fd2fb5/Neos.Neos/Classes/Package.php#L150

**Comment by skurfuerst** [comment]
Merged - YAY <3 Thanks!
