### ISSUE TITLE
9.0 BUG: Router cache needs get flushed after node aggegate got disabled

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4379]
When a NodeAggregate gets disabled, we need to flush the cache for the affected nodes. Otherwise the routing will try to show the node, even if they isn't enabled anymore.

See: #4377 

We need a new signal in the DocumentUriPathProjection or catchup hook to handle the cache flush properly. 
See also: https://github.com/neos/neos-development-collection/issues/4378

Actually we should also check if it is needed after enabling a node too.

**Comment by skurfuerst** [comment]
Merged - YAY <3 Thanks!
