### ISSUE TITLE
BUG: NEOS installation fails in DDEV context

### ISSUE THREAD

**Issue by fe-hicking** [neos/neos-development-collection#4381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

NEOS installation fails with a Foreign Key Contstraint failure

### Expected Behavior

NEOS can be installed

### Steps To Reproduce

I followed the steps in https://docs.neos.io/guide/installation-development-setup/ddev-local-beach/all-platforms-using-ddev-and-docker.

When calling the Web UI after executing Step 1 I get a HTTP/500 Error. An exception is logged.

If I manually call `flow doctrine:create` then the Webinterface allows me to get to Step 2. Filling in the DB credentials, it throws the same exception on Step 3 though.

The error is:

```
An exception occurred while executing 'ALTER TABLE typo3_party_domain_model_abstractparty_accounts_join ADD CONSTRAINT FK_1EEEBC2F58842EFC FOREIGN KEY (flow_security_account) REFERENCES neos_flow_security_account (persistence_object_identifier) ON DELETE CASCADE':

SQLSTATE[HY000]: General error: 1826 Duplicate foreign key constraint name 'FK_1EEEBC2F58842EFC'

The exception details have been logged to the Flow system log.
Exception in line 182 of /var/www/html/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php: An exception occurred while executing 'ALTER TABLE typo3_party_domain_model_abstractparty_accounts_join ADD CONSTRAINT FK_1EEEBC2F58842EFC FOREIGN KEY (flow_security_account) REFERENCES neos_flow_security_account (persistence_object_identifier) ON DELETE CASCADE':

SQLSTATE[HY000]: General error: 1826 Duplicate foreign key constraint name 'FK_1EEEBC2F58842EFC' - See also: 202307051251247e95ae.txt
```

I'm not familiar enough to understand how/if I can remove that specific migration or table structure. If I just drop the mentioned database table (that has been created by `flow doctrine:create` I suppose), it errors out with a message that the table is missing.

### Environment

```markdown
- Flow: 8.3.2
- Neos: ~8.3.0 = 8.3.3
- PHP: 8.1.16
- DB: Both mariadb 10.4 and MySQL 8.0
- DDEV: 1.21.6
```

**Comment by dlubitz** [comment]
The HTTP/500 error is already a known issue in setup:
https://github.com/neos/neos-setup/issues/11

**Comment by dlubitz** [comment]
Please use `flow doctrine:migrate` instead. This should work. Maybe you need to clear the database before as the state could be broken at this point.

**Comment by fe-hicking** [comment]
@dlubitz Thanks for replying - sorry, I only searched the issues here, I wasn't aware of a seperate tracker (just getting into neos).

I reset the project and then only used `doctrine:migrate` and not `doctrine:create` beforehand. Seems that was my mistake; not used to using these doctrine migrations yet. Setup works now, so I hope once the HTTP/500 error is fixed, these workarounds aren't needed. Would be great if Neos could be installed by newbies like me without these undocumented steps :-) 

Thanks for your work,
Garvin

**Comment by dlubitz** [comment]
No worries, it's not easy to see what is coming from which package. I'll close this ticket as it's solved for you.

If you need further support you could also use Discuss or Slack for your questions: https://www.neos.io/community/support.html

**Comment by mhsdesign** [comment]
Dont worry, we are already working on improving the setup by something much more stable and user friendly ;)

See the current status of the project https://github.com/neos/neos-development-collection/issues/4243
