### ISSUE TITLE
TASK: Deprecate Use Of Gui/Visual Neos Setup in favor of  CLI `./flow welcome`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4383]
Maintaining the gui neos setup is a bigger burden and right now no one seems to feel responsible for it - which makes sense as no one of the core team is using it themselves.

With the introduction of the Neos Cli Setup i also have never touched anymore the visual setup.

As discussed here: https://neos-project.slack.com/archives/C04Q0TC15/p1680685799429459 i like to deprecate the use of the web based tool and tell people to favor the cli when its possible.
Later we can think of fully removing the package - as without maintenance, it will eventually completely stop working.

Todos:
- [ ] Document the cli setup on the docs.neos.io
- [ ] Move the docs of the visual setup to a legacy page: https://docs.neos.io/guide/installation-development-setup/running-the-setup-tool
- [ ] Show a warning when opening the gui setup tool, that one should use the new cli tool (with reference to the docs)
- [ ] Put a note in the release notes 
- [ ] figure out how the main error page should now look like:

![](https://docs.neos.io/_Resources/Persistent/595e5312c9afafd5a436ec7e8b88f9bf65af68f1/Step-1-Neos-Setup-Tool-1920x1160.png)

- [ ] polish the cli setup even further so that first time users are guided well like in the web based setup
  - [ ] image handling (please select an image handler blaba we have found following handler on your system and we recommend vips : tableview
  - [ ] provide step by step cli ux interactively (that I don’t have to remember the next command)
  - [ ]  doctrine migrate generates a lot of output and the above printed flow welcome will be lost
  - [ ] at the end tell the user of all options how to create / import a site
    - [ ] use the neos demo and import from the demo content 
    - [ ] Use the neos demo but create plain site.xml
    - [ ] kickstart own site package

**Comment by mhsdesign** [comment]
@markusguenther said:

> I  think we should keep both. Although I only use the CLI. But I am not everyone ;)

**Comment by crydotsnake** [comment]
I agree too @markusguenther's comment.

**Comment by kitsunet** [comment]
I would also say there is definitely a userbase that avoids the CLI and woudl rather want to see more backend options (cache clear etc.) and I guess setup is one of those processes that is epseically important to get beginners going.

**Comment by markusguenther** [comment]
@mhsdesign WDYT can we postpone the deprecation and discuss this a bit? The setup is pretty old and definitely needs some love, but removing it will hurt some users.

**Comment by mhsdesign** [comment]
superseded by the approach https://github.com/neos/neos-development-collection/issues/4243
