### ISSUE TITLE
Reduce number of NodePropertiesWereSet events during inline editing

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4387]
Currently when inline-editing a text in the Neos content module, changes are sent to the server during typing leading to sometimes multiple `NodePropertiesWereSet` properties per second!

This produces needles load and makes rebasing, replays etc. less performant. 

A solution might be to compress similar `NodePropertiesWereSet` events during rebase (see #4263).

But it might be more sensible to avoid the similar _commands_ to be triggered already on the client side:
We could postpone the `/neos/ui-services/change` request to when the editor has actually finished typing (e.g. on blur and or navigation).
Obviously this is more involved and concerns UX. E.g. the pending changes should probably kept in the local storage such that they are not lost if the browser is closed etc.

Note: I could imagine unsaved text to be  highlighted somehow:

![image](https://github.com/neos/neos-development-collection/assets/307571/201c14c9-7b30-48c6-978e-6029ef35fcda)

**Comment by mhsdesign** [comment]
With the Neos Ui change: https://github.com/neos/neos-ui/pull/3751 we were able to reduce the events send during inline editing. Additionally on top we still can experiment with compaction on publish https://github.com/neos/neos-development-collection/pull/4263 but for now i think we can close this.
