### ISSUE TITLE
FEATURE: Fusion `renderingMode` semantic correct `inBackend`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4396]
## current `inBackend` state

currently in 8.3 and 9.0-dev we check if a node is in the backend by checking if the workspace is not live.

In Neos 8.3 it looks like `node.context.inBackend`
and for Neos 9.0-dev of July 2023 we currently use [`Neos.Node.inBackend(node)`](https://github.com/neos/neos-development-collection/pull/4074).
The edit preview modes are at this time not implemented in Neos 9 (see https://github.com/neos/neos-development-collection/issues/4086).

```php
public function inBackend(Node $node): bool
{
    $contentRepository = ...;
    $workspace = $contentRepository
        ->getWorkspaceFinder()
        ->findOneByCurrentContentStreamId($node->subgraphIdentity->contentStreamId);
    return !$workspace->workspaceName->isLive();
}
```

The assumption that nodes in non-live workspaces should render in backend mode is understandable but not fully semantically correct.
It currently happens to be that way that one cannot directly edit the live workspace via Neos Ui or that workspaces cannot be rendered in frontend mode, but it should not be fundamentally impossible.

## problems workspace determined check `inBackend = !workspace.live`

The workspace based rendering logic works well for when editing nodes in the Ui and rendering live nodes only for frontend.

But the downside is that the external preview mode will still be treated as `inBackend`.

It's not possible to render every workspace for frontend.
Without any content element wrapping and possible backend notes.

Also, the node uris are not correctly rendered see: https://github.com/neos/neos-development-collection/issues/2347

The current workaround in 8.3 is to check if the preview is in `user-admin` or in its base workspace, as the "Show preview" will always show the node in its base workspace (see `NodeInfoHelper::createRedirectToNode`):

```
inEdit = ${node.context.workspace.personalWorkspace}
```

## problems of the 8.3 rendering mode attached to the nodes context

Accessing the _actual_ rendering mode in fusion is done via `node.context.currentRenderingMode.edit` which is implemented here:
https://github.com/neos/neos-development-collection/blob/bc68159ab37e94b9a384704ae7cacb2e171f6ce1/Neos.Neos/Classes/Domain/Service/ContentContext.php#L168-L171

But this always requires the rendering mode to be set globally and it cannot be changed individually for one rendering. 

A separate variable is preferred.

## proposed solution with Neos 9

With 9.0 we have a chance to clean this up. Using `node.context.inBackend` won't work anymore as Neos 9 doesnt have a `context`, and the check has to be migrated either way.
~~_(currently this is done via rector to `Neos.Node.inBackend(node)`)_~~

The concept of custom Fusion global variables would allow us to introduce node/request independent helpers like `renderingMode.isEdit` and `renderingMode.isPreview`.

The introduction of the `renderingMode` per se will not solve the above outlined problem fully, but we would also have set the `renderingMode` to not edit if we use the "Show Preview" button.
Followup issue: https://github.com/neos/neos-development-collection/issues/4959

### Fusion global vs regular Fusion context variable 

Introducing Fusion globals to allow a `request` like global is important so the variable is always available and will not be "lost" if not specified in `@cache.mode = 'uncached'` segments.

A "regular" Fusion context variable would have to be breaking and would need manual adjustments in every dynamic and uncached cache configuration:

```
@cache {
   mode = 'uncached'
   context {
     0 = 'node'
     1 = 'renderingMode'
   }
}
```
We also discussed to introduce a default cache context like `Neos.Fusion:GlobalCacheIdentifiers` so this is less breaking but discarded this idea at the dresden sprint 23.

### Fusion global vs attached to `request`

Silently attaching the rendering mode to the `request` or worse having some singleton and eel helper to fetch it will make custom use cases of rendering a page super tricky. We would have to expect a similar workaround like this now reverted change: https://github.com/neos/neos-ui/commit/ce395ca9e3614ec32f7af7a82d2759a74e68f62d
Passing the rendering mode explicitly from outside will hopefully solve that two tabs can have a distinct rendering mode which is not determined by the session: https://github.com/neos/neos-development-collection/issues/965

## migration

We discussed to remove our "temporary" 9.0-dev method `Neos.Node.inBackend(node)` and replace it with `renderingMode.isEdit`

A simple migration for current 9.0 projects can be done by hand or via a regex replace from `Neos.Node.inBackend\([a-zA-Z]*\)` to `renderingMode.isEdit`.

The rector migration https://github.com/neos/rector/pull/22 will take care of migrating `node.context.inBackend` to `renderingMode` for Neos 8.3

## implementation

- [!!! FEATURE:  Global variables for the Fusion runtime `FusionGlobals`](https://github.com/neos/neos-development-collection/pull/4425)
- [!!! FEATURE: Reimplement EditPreviewModes for Neos 9](https://github.com/neos/neos-development-collection/pull/4505)
- Refactor workspace based `isBackend` checks in php land to use the current rendering mode. For example inside content element wrapping service.
  - [TASK: #4396 prefer renderingMode::isEdit over node::isLive](https://github.com/neos/neos-development-collection/pull/4733)
  - [TASK: Use `renderingMode.isEdit` in `NodeController`](https://github.com/neos/neos-development-collection/pull/4874)

**Comment by crydotsnake** [comment]
Good point!: `Neos.Node.inBackend(node)` looks definetly better.

**Comment by kitsunet** [comment]
I see two lines of arguing here:

Option 1: Your line of thought that basically replaces it with "edit or preview mode", but in that case I really think we should offer the syntactic sugar of `inBackend` and do the or internally, given that probalby inBackend is the 90% case.

Option 2: we assume that `inBackend` mostly means "you are in edit mode" despite a preview mode also being `inBackend`, because usually you want to make something easier for editors (or more accessible eg. sliders) in that case we could even rector directly ot just a check for edit mode, and then we also need nothing else in terms of syntactic sugar. I feel this is actually the way things should be, but I have no numbers to back that up :D I guess we could ask what people use inBackend for atm.

**Comment by mhsdesign** [comment]
Im for Option 2, as `Neos.Backend.isPreviewMode` [would be true](https://github.com/neos/neos-development-collection/pull/4067#issuecomment-1627757844) when you open the page externally:

![image](https://github.com/neos/neos-development-collection/assets/85400359/35efe3db-4921-4e1b-9079-b9dd7ada0ece)

And thus when we use `inBackend == Neos.Backend.isEditMode(request) || Neos.Backend.isPreviewMode(request)` it would still be true even if one left the Neos Ui.

**Comment by mficzel** [comment]
I also would prefer the strictness of option 2 since we usually mean the editMode. An `inBackend` method does not add any meaning compared to `Neos.Backend.isEditMode(request) || Neos.Backend.isPreviewMode(request)`. 

If we decide to add a convenience method i would prefer to call it `Neos.Backend.isEditOrPreviewMode(request) `

**Comment by skurfuerst** [comment]
I also prefer option 2 (and support the proposal in general) :+1: Thanks for taking care!

**Comment by kitsunet** [comment]
> ... as Neos.Backend.isPreviewMode https://github.com/neos/neos-development-collection/pull/4067#issuecomment-1627757844 when you open the page externally:


this is another implementaiton problem we have right now, IMHO it should not and the PR from martin  should fix that.

**Comment by skurfuerst** [comment]
@mhsdesign Can we get this to a done state? Seems we agree on a solution here :) (or did I overlook the solution already?) All the best!

**Comment by mhsdesign** [comment]
https://github.com/neos/neos-development-collection/pull/4505 will actually only solve half of it.
We will also remove `Neos.Node.inBackend(node)` for beta 2!


We have several places in php where we check against the live content stream (which as written above should NOT say anything about if the node is in backend or not!)

https://github.com/neos/neos-development-collection/blob/4cf807a991ab81a9678ef5b807d7049ccb08c7ee/Neos.Neos/Classes/FrontendRouting/NodeUriBuilder.php#L67C1-L67C1

https://github.com/neos/neos-development-collection/blob/4b9c5bf7dcf7cf1e84dd66f92120eed696fde23e/Neos.Neos/Classes/Service/ContentElementWrappingService.php#L98

**Comment by mhsdesign** [comment]
first goal would be to find out all paces to touch and determine breakiness and maybe migrate the breaking parts for 9.0 already ;)

Edit was quite doable see https://github.com/neos/neos-development-collection/pull/4733 and https://github.com/neos/neos-development-collection/pull/4874 ;)

**Comment by mhsdesign** [comment]
I created a followup issue for all the leftover problems that are now fixable with the newly introduced concept of the `renderingMode`

https://github.com/neos/neos-development-collection/issues/4959

I updated the issues description and consider this part closed.
