### ISSUE TITLE
FEATURE: Use something other than 303 for Neos Shortcut redirect

### ISSUE THREAD

**Issue by pKallert** [neos/neos-development-collection#4410]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

Currently, the Neos Shortcut redirects with the HTTP Status code 303. 
Our SEO team suggest using 302 for those redirects for SEO reasons. 
Right now, the 303 status code is hard-coded into the redirect function. 

### Possible Solution

There are three possible solutions I can think of: 

- globally setting the HTTP Status code for Neos Shortcuts
- Hard coding a 302 HTTP Status code for Neos Shortcuts 
- Using a dropdown in the Neos UI to set the status code for each Neos Shortcut

**Comment by MiauzGenau** [comment]
The SEO reasoning is: 

> it allows any Pagerank to pass

**Comment by MiauzGenau** [comment]
Seems to be handled in `/Neos.Neos/Classes/Controller/Frontend/NodeController.php`, Line 199 function: `handleShortcutNode`.

Uses `redirectToUri` and `redirect` of the `AbstractController`, which has the default status code 303.

**Comment by kdambekalns** [comment]
I could not care less about "Pagerank" passing something. But looking at the spec, it seems 302 is the better choice – and that I consider a good reason to change this.

MDN says in short form (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#redirection_messages)…

… about 303:

> The server sent this response to direct the client to get the requested resource at another URI with a GET request.

… about 302:

> This response code means that the URI of requested resource has been changed temporarily. Further changes in the URI might be made in the future. Therefore, this same URI should be used by the client in future requests. 

From there the difference seems to be mostly the emphasis on _temporarily_. But for that we have 301. Looking at the HTTP spec gives a better view. On [302 Found](https://www.rfc-editor.org/rfc/rfc9110.html#name-302-found) it says (emphasis mine):

> The 302 (Found) status code indicates that the target resource resides temporarily under a different URI. Since the redirection might be altered on occasion, the _client ought to continue to use the target URI for future requests_.

On [303 See Other](https://www.rfc-editor.org/rfc/rfc9110.html#name-303-see-other) OTOH it says (emphasis mine):

> This status code is applicable to any HTTP method. It is _primarily used to allow the output of a POST action to redirect the user agent_ to a different resource, since doing so provides the information corresponding to the POST response as a resource that can be separately identified, bookmarked, and cached.
> A _303 response to a GET request indicates_ that the origin server _does not have a representation_ of the target resource _that can be transferred_ by the server _over HTTP_. […]

---

While this interpretation might be "relatively new" in terms of web history, we should follow it. My vote would be to

- add a configuration option for shortcut redirection to switch between 302 & 303.
- change the default to 302 for the underlying methods in Flow 9.

Making this configurable *per shortcut* seems over the top, IMHO.

**Comment by pKallert** [comment]
@kdambekalns sounds good :) 

I was wondering where the best place would be to add the configuration option, any hints there?

**Comment by markusguenther** [comment]
Hmm, we have something like `Neos.RedirectHandler.statusCode`. But these are from the Redirect Handler and not part of this repository. So would be not the best choice. Maybe @kitsunet or @kdambekalns have good recommendations. But I see not real section that matches the case at the moment.

**Comment by bwaidelich** [comment]
Regarding

> it allows any Pagerank to pass

We never generate URIs for the shortcut page itself, but always to the _target_. Therefore those should never be indexed in the first place, right?

I'm not fully convinced that `302` would be the better choice _in all circumstances_ due to that [part](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302):

> A browser redirects to this page but search engines don't update their links to the resource

`301` seems lke a better fit to me, but it probably depends on the scenario

For those reasons I would vote against a (global) configuration option and in favor of a corresponding _property_ on the shortcut node.

If you think that it's not for the editor to choose, that property could be hidden from the inspector by default – but it would still be a good place to configure this IMO:

```yaml
'Neos.Neos:Shortcut':
  # ...
  properties:
   'httpStatusCode':
      type: int
      defaultValue: 303
      ui:
        inspector:
          # change this to ....
          hidden: true
          group: 'document'
```

**Comment by dlubitz** [comment]
Sorry for steping into that bit late. From my POV it's a bit overdone to make it configurable per node in the node editors. But as it seems to have many very different opinions on the choosen status I would vote for a global configuration, that is used for all short cut redirects.

As I wasn't aware of any use case, but got it from @pKallert, I'd like to document it here:

- A user creates a page, which gets indexed by any search engine. Afterwards the user changes the nodetype to a short cut with some target.

**Comment by bwaidelich** [comment]
> From my POV it's a bit overdone to make it configurable per node in the node editors

Even not with the hidden option as mentioned above?
What do you suggest instead?

**Comment by dlubitz** [comment]
Yes, especially that.
I would simply add a global setting:
```
Neos:
  Neos:
    frontend:
      shortcutRedirectHttpStatusCode: 302
```

**Comment by kdambekalns** [comment]
Missed that one… sorry! I'd say a global config is sufficient, and I like the suggestion in https://github.com/neos/neos-development-collection/issues/4410#issuecomment-1846994394

If we want to make it configurable per node, add a three-state selector (null, 302, 303) and use the global setting if "undefined". That way it's possible to change the default easily but people can still override (if they need it.)

**Comment by kitsunet** [comment]
I thought about this too and am on @bwaidelich side on this, per node (maybe hidden in the inspector by default), allows you to show it in the inspector eiher freely configurable or via dropdown or just overwrite and hardcode your own global default if needed. Or and that is one important factor, create specific Shortcut variants per site (or any other separation you like) and have different codes hardcoded for them.

**Comment by pKallert** [comment]
Opinion poll: 

❤️  use global setting 
🚀 use property in Node Type  

Voting open until I continue to work on the feature 

Poll closed :) Result: 3:2  for using global setting!
