### ISSUE TITLE
9.0 BUG: Postgres index names not unique across schema

### ISSUE THREAD

**Issue by cvette** [neos/neos-development-collection#4427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Executing cr:setup leads to the following exception:

```
An exception occurred while executing 'CREATE INDEX contentstreamid ON cr_default_p_neos_asset_usage (contentstreamid)':
SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "contentstreamid"
already exists
  Type: Doctrine\DBAL\Exception\TableExistsException
  File: Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQ
        LDriver.php
  Line: 85
```

### Expected Behavior

Index name should be unique across the schema, so maybe add table/entity prefix. Already tried with "assetusage_contentstreamid" and it worked.

### Steps To Reproduce

Clean install

./flow doctrine:migrate
./flow cr:setup

### Environment

```markdown
- Flow: 9.0.x-dev
- Neos: 9.0.x-dev
- PHP: 8.2
- Postgres: 14.2
```

**Comment by dlubitz** [comment]
As this is a known postgres thing, we should consider to pre/suffix all keys.

https://www.postgresql.org/docs/current/sql-createindex.html
> The name of the index must be distinct from the name of any other relation (table, sequence, index, view, materialized view, or foreign table) in that schema.

**Comment by bwaidelich** [comment]
IIRC we can just omit the index name to let PG create a unique one:
```php
->addIndex(['contentstreamid'])
```

**Comment by dlubitz** [comment]
Docs say:
> If the name is omitted, PostgreSQL chooses a suitable name based on the parent table's name and the indexed column name(s).

**Comment by skurfuerst** [comment]
merged
