### ISSUE TITLE
9.0 BUG: ContentStreamFinder->findAllIds() fails with warning

### ISSUE THREAD

**Issue by cvette** [neos/neos-development-collection#4428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Executing `cr:prune` leads to the following warning:

`Warning: Undefined array key "contentStreamId" in /data/Packages/Neos/Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamFinder.php line 128`

This is because the database row is lowercase "contentstreamid"

### Expected Behavior

No warning

### Steps To Reproduce

Execute ./flow cr:prune

### Environment

```markdown
- Flow: 9.0.x-dev
- Neos: 9.0.x-dev
- PHP: 8.2
- Postgres: 14.2
```

**Comment by bwaidelich** [comment]
I really wonder what happens here since
```sql
SELECT contentStreamId
```

should (tm) return rows with the same casing o.O

**Comment by dlubitz** [comment]
```
CREATE TABLE films (
    code        char(5) CONSTRAINT firstkey PRIMARY KEY,
    title       varchar(40) NOT NULL,
    did         integer NOT NULL,
    date_prod   date,
    kind        varchar(10),
    len         interval hour to minute
);
```

```
db=# SELECT CoDe, TITLE FROM films;
 code  | title
-------+-------
 code1 | title
```

🤷‍♂️

**Comment by bwaidelich** [comment]
Interesting.. https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive

This seems to work though:
```sql
SELECT code "CoDe", title "TITLE" FROM films;
```

**Comment by dlubitz** [comment]
```
db=# SELECT code "CoDe", title "TITLE" FROM films;
 CoDe  | TITLE
-------+-------
 code1 | title
```

Hahah, yes. But this is doesn't help us. If we define an alias or query the correct fieldname doesn't matter, right?

**Comment by bwaidelich** [comment]
> Hahah, yes. But this is doesn't help us. If we define an alias or query the correct fieldname doesn't matter, right?

What do you mean?
```php
$connection->executeQuery('SELECT contentstreamid "contentStreamId" FROM ' . $this->tableName)->fetchAllAssociative()
```
should now return an array with `contentStreamId` elements (with proper case).

I decided to adjust the using part instead, though.
Also for the actual bugfix we don't need the mapping at all by loading just the first column: https://github.com/neos/neos-development-collection/blob/e72d767b6414001fea43f9810d8e3a4f6e81b99c/Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamFinder.php#L120-L124

**Comment by dlubitz** [comment]
Yes, that's what I mean. No value in adding an alias, as we can simply adjust the usage.

**Comment by skurfuerst** [comment]
merged - thanks everybody!
