### ISSUE TITLE
9.0 FEATURE: Dynamic placeholders in Neos.Neos:Editable

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-development-collection#4430]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

## Description

The idea came up in a [blog post](https://www.uhlmann.pro/blog/2023/dynamische-placeholder-im-inline-editor) from @jonnitto and i quite liked the idea.

Currently its possible to set a placeholder via the NodeType configuration when `InlineEditable` is set too true.

But what is when i would like to output the title of a document for example? Like in the example from the blog post it could look like:

```
headline = Neos.Neos:Editable {
    property = 'headline'
    block = false
    fallback = ${q(node).property('title')}
}
```

And then the fallback will be rendered in the frontend.

## Important to know

But if I now set a fallback in my fusion component, it should check if a placeholder is already set in the NodeType (ui.inspector.editorOptions.placeholder). Then we should decide whether the fallback in the fusion part or the placeholder part in the NodeType should be output. However, the placeholder in the NodeType is ONLY displayed in the backend and not in the frontend. Therefore, I would rather tend to use the fallback in the Fusion part.

I believe the check for that would be part of the Neos UI ?

**Comment by mhsdesign** [comment]
Hmm. I think we need to think about where we want to define how the editor works. For example the `block` option is made in fusion but other settings, like which formatting is in yaml. The placeholder can currently also be only set via yaml and im not sure how we can improve this total situation. I dont dislike this idea i just think before doing something like this we need a complete well sounding concept of where which is declared.

See also i have a similar issue with the autoparagaph false thingy: https://github.com/neos/neos-ui/issues/3545

**Comment by crydotsnake** [comment]
> Hmm. I think we need to think about where we want to define how the editor works. For example the `block` option is made in fusion but other settings, like which formatting is in yaml. The placeholder can currently also be only set via yaml and im not sure how we can improve this total situation. I dont dislike this idea i just think before doing something like this we need a complete well sounding concept of where which is declared.
> 
> See also i have a similar issue with the autoparagaph false thingy: [neos/neos-ui#3545](https://github.com/neos/neos-ui/issues/3545)

Hm. We could check, if a placeholder is set via the UI, or a fallback via the fusion. And then decide which case we will output.
