### ISSUE TITLE
Node Migrations

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4442]
The current implementation could use some documentation and tweaking:

- [ ] Document the new API and CLI commands on [docs.neos.io](https://docs.neos.io)
- [ ] Adjust the behavior of the `nodemigration:migrate` command such that it applies changes to the `live` workspace by default
  * There should be an option to allow creating that explicit "migration workspace" which is the default behavior currently
- [ ] Apply all migrations to a single content stream (by default?) – currently an array of `contentStreamIdsForWriting` is passed

**Comment by crydotsnake** [comment]
Also the `./flow nodemigration:migrationstatus` command is still missing (if i checked the existing code correctly)

**Comment by dlubitz** [comment]
ATM the ExecuteMigration can get passed an array of `contentStreamIdsForWriting`. Which means per entry in a migration file, I could pass a different contentStreamId as target. Is this really necessary?

https://github.com/neos/neos-development-collection/blob/d0067c79f35f811bb5c982ad35bb69a674848211/Neos.ContentRepository.NodeMigration/src/Command/ExecuteMigration.php#L65

I would like to replace that with a targetWorkspace and apply the migrations there (default "live"). If no targetWorkspace is given, we create a new one with unique name.

I would also remove the logic of "submigrations" where each submigration creates a new content stream. IMHO this creates unnecessary complexity, moreover I would consider each migration(-file) as ONE atomic migration.

https://github.com/neos/neos-development-collection/blob/d0067c79f35f811bb5c982ad35bb69a674848211/Neos.ContentRepository.NodeMigration/src/Command/ExecuteMigration.php#L43-L48

**Comment by bwaidelich** [comment]
IIRC the idea was to be able to recover from failed migrations more easily but I agree that this makes things rather complex.. Maybe we can make the "submigrations" an option, too?

**Comment by dlubitz** [comment]
* No "Submigrations"
* Create new workspace per migration(-file) ("targetworkspacename-20231102123456")
* Rename "workspace" to "sourceWorkspace"
* Flag to publish targetWorkspace to sourceWorkspace after success ("publishOnSuccess", default: true)
* Remove content stream ids from outside
* Behat Tests
