### ISSUE TITLE
BUG: TIMEOUT while waiting for projection when add, edit and delete nodes

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-development-collection#4445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding, change existing or deleting nodes from the page it throws an error message in: `Neos\Neos\PendingChangesProjection\ChangeProjection`

Interesting part is, that even that i dont published my changes, the changes seems to be live after reloading the backend when getting the exception. Since i can see the changes live without pressed the publish button.

## Demo Video

https://github.com/neos/neos-development-collection/assets/39345336/324b1cde-1098-4f0d-a053-9f86315cf364

### Exception Log

You can find the log file below ⬇️

### Expected Behavior

I should be able too delete, edit add nodes too/from the page.

### Steps To Reproduce

1. Try too edit, delete, or add new/existing nodes.

### Environment

```markdown
- Flow: 9.0
- Neos: 9.0
- PHP: 8.2
```

## Exception log file

[20230805111626e6e470.txt](https://github.com/neos/neos-development-collection/files/12266914/20230805111626e6e470.txt)

**Comment by mhsdesign** [comment]
Closed, because

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'neos.cr_default_p_neos_change_livecontentstreams' doesn't exist

this `cr_default_p_neos_change_livecontentstreams` is from a recent change https://github.com/neos/neos-development-collection/pull/4411

so a cr:setup fixed it ;)
