### ISSUE TITLE
BUG: SiteDetection fails if no site exists

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4446]
Neos totally breaks if no site is set. Not even other flow routes work

<img width="1031" alt="image" src="https://github.com/neos/neos-development-collection/assets/85400359/ff1bb02a-16d0-4e8d-9e34-98c426620117">

when the middle ware would just be okay with no site, it correctly only fails for probable neos pages:

<img width="714" alt="image" src="https://github.com/neos/neos-development-collection/assets/85400359/004bd610-2cf5-4dd5-a9f5-84da809b1a00">

or 

> Exception in line 513 of /Flow_Object_Classes/Neos_Neos_Controller_Frontend_NodeController.php: TODO: SITE NOT FOUND; should not happen (for address NodeAddress[contentStream=62c42194-8d0b-4835-80ab-b8032968cc5a, dimensionSpacePoint={"language":"en_US"}, nodeAggregateId=66807a8d-1914-4904-b531-309b3b241c2f, workspaceName=live]

expected:

routing works for normal flow routes, and other middlewares work

screen for unmatched routes (where it might be a neos page)

<img width="659" alt="image" src="https://github.com/neos/neos-development-collection/assets/85400359/08c223f3-7b12-4da6-b7db-e0b5d2388828">

**Comment by mhsdesign** [comment]
This is sadly not completely working in all cases. As a rule of thumb: If the flow functional tests work with neos installed we are a good step ahead. Otherwise this should be kept open ^^

**Comment by kitsunet** [comment]
yep, I noticed that too 😆

**Comment by kitsunet** [comment]
We not only need to cover the case were there isn't even a CR setup yet, but also handling afterwards in routing when there is no site.

**Comment by mhsdesign** [comment]
yes i have so many try catch return in my stash to make it work :D

**Comment by mhsdesign** [comment]
related https://github.com/neos/flow-development-collection/pull/2431#issuecomment-1623281844
maybe we should run flow in neos ci?

And also related: https://github.com/neos/neos-development-collection/issues/4345
