### ISSUE TITLE
FEATURE: High level `cr:import` / Read `site:import`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4448]
Neos 8 holds the well known site:import command:

```
COMMAND:
  neos.neos:site:import

USAGE:
  ./flow site:import [<options>]

OPTIONS:
  --package-key        Package key specifying the package containing the sites
                       content
  --filename           relative path and filename to the XML file containing
                       the sites content
```

but in Neos 9 this is currently removed and the user has to run a few other (counter intuitive steps)

- (./flow cr:setup) 
- ./flow site:create neosdemo Neos.Demo Neos.Demo:Document.Homepage
- ./flow cr:prune
- ./flow cr:import resource://Neos.Demo/Private/Content

imo it would be great to have a high level command like `site:import` again.
It would imo lookup the `Sites.xml` in `Resources/Private/Content/Sites.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<root crexport="resource://Neos.Demo/Private/Content">
  <site name="Neos Demo Site" state="1" siteResourcesPackageKey="Neos.Demo" siteNodeName="neosdemo">
  </site>
</root>
```

When adding the site import, we of course also need the site export again ^^

## TODOS

- [ ] Re-add `site:import` command
- [ ] Make sure that `Site` & Live Workspace (including metadata & role assignments) are created and selected CR is set up!

**Comment by mficzel** [comment]
Its sounds dangerous to run ./flow cr:prune inside site:import. This would be fine in single site environments but would kill multisite setup that already have sites that should be persisted.

**Comment by bwaidelich** [comment]
@mficzel 

> Its sounds dangerous to run ./flow cr:prune

I agree, the command should not just silently kill all sites, but I didn't expect @mhsdesign to have that in mind.
I would expect the command to be interactive, and allow to prune a single site if needed.

**Comment by mhsdesign** [comment]
The cr:export should allow neos.neos to specify additional meta data

**Comment by mficzel** [comment]
Suggestion: implement commands like `exportAll(string $cr = 'default')`  and `importAll(string $cr = 'default', $file)`  first. Later commands like `export` and `import` for single sites should be reintroduced that should be able to deal with multisite environments.

**Comment by ahaeslich** [comment]
Possibly could be moved to 9.1
