### ISSUE TITLE
!!! 9.0 Node should only know properties defined in current schema

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4460]
The node factory should only fill the node properties with properties which match the schema. This ensures a more solid behavior as discussed here: https://github.com/neos/neos-development-collection/issues/4304#issuecomment-1604042784

**Comment by skurfuerst** [comment]
UPDATE (2023-9-1): As discussed in todays [weekly](https://neos-project.slack.com/docs/T04HF7TKV/F05NL5CE6E5) we decided, to keep the current behavior and let PropertyCollection return the (deserialized) values like they are stored in the db (not verifying schema compliance)
