### ISSUE TITLE
Remove `PropertyCollectionInterface`

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4464]
As discussed in todays [weekly](https://neos-project.slack.com/docs/T04HF7TKV/F05NL5CE6E5) we decided to replace the `PropertyCollectionInterface` by a final `PropertyCollection`.

The reason is that the collection should have a defined behavior (e.g. return _all_ properties as stored in the database, don't throw on non-existing props, ...)
See related discussion in https://github.com/neos/neos-development-collection/issues/4304#issuecomment-1604042784

**Comment by mhsdesign** [comment]
<details><summary>Moved https://github.com/neos/neos-development-collection/issues/4317#issuecomment-1725654764</summary>
<p>

Just to be noted, i like to stub my nodes (without providing a correct node type) and currently the interface allows me to do this simple thing:


```php
        $properties = ['foo' => "bar"];

        $propertyCollection = new class ($properties) extends \ArrayObject implements PropertyCollectionInterface {
            public function serialized(): SerializedPropertyValues
            {
                throw new \BadMethodCallException(sprintf('Method %s, not supposed to be called.', __METHOD__));
            }
        };
```

after:

```php
$textNodeProperties = new PropertyCollection(
    SerializedPropertyValues::fromArray([
        'foo' => new SerializedPropertyValue('bar', 'string')
    ]),
    new PropertyConverter(
        new Serializer([
            new DateTimeNormalizer(),
            new ScalarNormalizer(),
            new BackedEnumNormalizer(),
            new ArrayNormalizer(),
            new UriNormalizer(),
            new ValueObjectArrayDenormalizer(),
            new ValueObjectBoolDenormalizer(),
            new ValueObjectFloatDenormalizer(),
            new ValueObjectIntDenormalizer(),
            new ValueObjectStringDenormalizer(),
            new CollectionTypeDenormalizer()
        ])
    )
);
```


related: https://github.com/neos/neos-development-collection/issues/4317

</p>
</details> 


~im currently trying to find a good solution - i hijacked this pr to also implement this task https://github.com/neos/neos-development-collection/pull/4328~

**Comment by mhsdesign** [comment]
Moved https://github.com/neos/neos-development-collection/issues/4483#issuecomment-1706613548

**Comment by mhsdesign** [comment]
Related https://github.com/neos/neos-development-collection/issues/4483

**Comment by mhsdesign** [comment]
<details><summary>Moved https://github.com/neos/neos-development-collection/issues/4317#issuecomment-1725654764</summary>
<p>


For a mock helper i like to have an option to tell the node that these are its properties in a simple array format.

i experimented with using the serializer to archive this:


```php
    public function createNode(
         ?NodeAggregateId $nodeAggregateId = null,
         SerializedPropertyValues|array|null $propertyValues = null,
     ): Node {
         if (is_array($propertyValues)) {
             $propertyValues = $this->propertyConverter->serializePropertyValues(
                 PropertyValuesToWrite::fromArray($propertyValues), // hacky as we are using this NodeModification command dto model
                 $nodeType // i also want to pass the nodeType here hacky, as it needs to have the correct property type defnitions
             );
         }
      # ...

      return new Node($propertyValues);
```


</p>
</details>
