### ISSUE TITLE
!!! Remove shallow methods from `Node`?

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4483]
Those three methods are super shallow and dont provide any additional information.

```php
public function getProperty(string $propertyName): mixed;
public function hasProperty(string $propertyName): bool;
public function getLabel(): string;
```

i just want to open the discussion to make the `Node` even cleaner ;)

https://github.com/neos/neos-development-collection/blob/71e64ed8fdd4c2b1ae9b771d2b887c7521be995c/Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php#L86-L112

about the `label` it should imo be a constructor property given from the nodeFactory

**Comment by skurfuerst** [comment]
I am unsure about this, because people rely on this right now very heavily. It's of course debatable whether this should be changed, but I right now am unsure about this because of backwards breakiness...

**Comment by kdambekalns** [comment]
What would the replacement be? Using `$properties` and go from there? Sounds as if a few months from now someone will open a PR to add `hasProperty()` and `getProperty()`… 🙃

**Comment by mhsdesign** [comment]
today we discussed this issue and wether to remove the array access from `properties`:


> Why do our properties actually need to implement `\ArrayAccess` this is totally useless for php land - and out of sight of the content repository core there is no interest if something like a expression language like eel "requires" it to do funny stuff (see below) - i mean we also dont randomly implement the `ProtectedContextAwareInterface` because it might make things easier??

```php
<?php

$node->getProperty("foo");

// vs

$node->properties["foo"];
```

(and eel)

```
${node.properties.bla}

# vs

${q(node).property("bla")}
```

~imo - if we want this behavior, it should be implemented in eel, but please lets spare the cr xD~

--------

the conclusion of our weekly and[ this discussion](https://neos-project.slack.com/archives/C3MCBK6S2/p1693816556852519) is, that we want to keep the _ArrayAccess_ behavior of the properties as this ensures a better backwards compatibility. If we would have started out from a fresh state we would certainly rethink all the ways but currently we will keep all of the property accessors

- `${q(node).property("foo")}`
- `${node.properties.foo}`
- `$node->getProperty(“foo”)`
- `$node->properties["foo"]`
- `$node->properties->offsetGet("foo")`
