### ISSUE TITLE
Node search can return incorrect results based on given nodetypes filter

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#4502]
This can happen in the following situation when using the reference editor for example:

The `nodeTypes` option of the reference editor is set to `['My.Vendor:Mixin.SearchableDocument']`

Then we have the following nodetypes:

```yaml
'My.Vendor:Mixin.SearchableDocument': 
  abstract: true

'Neos.Neos:Document':
  superTypes:
    'My.Vendor:Mixin.SearchableDocument': true

'My.Vendor:Document.Folder':
  superTypes:
    'Neos.Neos:Shortcut': true
    'My.Vendor:Mixin.SearchableDocument': false
```

**What happens:**

In the reference editor we search and get `My.Vendor:Document.Folder` in the results even though we disabled the inheritance.
This happens due to the `NodesController` collecting all non-abstract subnodetypes of `My.Vendor:Mixin.SearchableDocument` which includes `Neos.Neos:Shortcut`.
See https://github.com/neos/neos-development-collection/blob/c480e239be07da98be4c4d7924f6cafd0200eb63/Neos.Neos/Classes/Controller/Service/NodesController.php#L104
But then the NodeDataRepository again collects all subnodetypes of the given list of subnodetypes which again include `My.Vendor:Document.Folder` as it inherits from `Neos.Neos:Shortcut` in https://github.com/neos/neos-development-collection/blob/c480e239be07da98be4c4d7924f6cafd0200eb63/Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php#L1136

**Comment by dlubitz** [comment]
Fixed with #4503
