### ISSUE TITLE
BUG: Running `./flow structureadjustments:fix` doesn't mark workspaces as outdated

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running `./flow structureadjustments:fix` will add your changes to the live workspace but not marking any of the other workspaces as outdated. Thus running `./flow workspace:rebaseoutdated` afterwards will do nothing. Logging in again in a user workspace will rebase again.

### Expected Behavior

Workspaces that doesn't contain the adjustments to be marked as outdated.

### Environment

```markdown
- Flow: 9.0
- Neos: 9.0
- PHP: 8.2
```

Relates: #4442

**Comment by ahaeslich** [comment]
@skurfuerst in a slack conversation

> ah. I think I understand why this is happening:
the "outdated" handling is in WorkspacesProjection::markDependentWorkspacesAsOutdated
=> called e.g.  whenWorkspaceWasPublished.
=> when we directly publish new events on the live workspace, the system does not recognize that is has to mark the other workspaces as outdated.
I am not yet 100% sure how to fix this most cleanly. Either we emit a new event; or we somehow listen to all workspace changes (which I dislike)

**Comment by bwaidelich** [comment]
> or we somehow listen to all workspace changes (which I dislike)

I actually think, that this is the way to go.
IMO we should keep "Publishing" as much out of the core logic as possible so that it is just a way to coordinate.
=> we would never really listen to publish/discard events (apart from directly affected projections) but to the actual node related events

**Comment by mhsdesign** [comment]
Yes we noticed this problem as well when testing https://github.com/neos/neos-development-collection/pull/4817 

>  Logging in again in a user workspace will rebase again.

yes that _was_ the behaviour but with https://github.com/neos/neos-development-collection/pull/4865 it will be a noop like `./flow workspace:rebaseoutdated` due to the check.


See also https://github.com/neos/neos-development-collection/issues/4783
