### ISSUE TITLE
BUG: ProjectionContentGraph - succeedingSiblingRelation can be false 

### ISSUE THREAD

**Issue by pKallert** [neos/neos-development-collection#4510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When migrating the content repository, an error came up. 

<img width="1021" alt="Bildschirmfoto 2023-09-14 um 14 27 05" src="https://github.com/neos/neos-development-collection/assets/91674611/5d083fa0-e9c7-41ea-8733-f7fcfc791d82">

The screenshot says line 266, but it is actually line 265: https://github.com/neos/neos-development-collection/blob/8cb03d53f230cde28b7bcd39736267f3c0e44c3a/Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php#L265. $succeedingSiblingRelation is expected to be an array, but it can also be false(according to the method return type), like in this case. 

### Expected Behavior

I would expect the migration to run through 

### Environment

```markdown
- Flow:
- Neos: 9.0
- PHP: 8.2
```

**Comment by mhsdesign** [comment]
@nezaniel wrote here https://github.com/neos/neos-development-collection/pull/4574

> As far as I can see this is a bug in the migration script and cannot be solved [in the projection]

**Comment by mhsdesign** [comment]
> The error occurred only once during one of many migration attempts and I cannot definitely say how I got there. There were lots of errors during lots of attempts, and I can only assume that  it has something to do with this bug: https://github.com/neos/neos-development-collection/issues/4504#issuecomment-1735759814 

so now we just show a better error instead of having an offset error shown
