### ISSUE TITLE
Impersonation cant click "edit" button in workspace module

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4512]
<img width="1570" alt="image" src="https://github.com/neos/neos-development-collection/assets/85400359/3323773c-74cf-4732-8b9a-604d7cbf7d82">

maybe close this as wont fix? (My actual personal workspace contained changes but not the impersonised)

what do you say @markusguenther?

EDIT: Closed as wont fix and probably unfixed.

**Comment by markusguenther** [comment]
I guess the issue is solved by the new release of the module and the PR https://github.com/neos/neos-development-collection/pull/4823
