### ISSUE TITLE
!!! Move and possibly rename `NodeTypeConstraints`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4522]
As discussed in slack https://neos-project.slack.com/archives/C3MCBK6S2/p1694797399762309 the naming of `NodeTypeConstraints` when used as `"instanceof Foo.Bar"` filter has naming wise some overlap to actual NodeType Constraints https://docs.neos.io/guide/manual/content-repository/nodetype/node-constraints

```yaml
'Neos.Demo:Document.Chapter':
  constraints:
    nodeTypes:
      'Neos.Neos:Document': false
      'Neos.Demo:Document.Chapter': true
```

This might not be ideal and we should maybe discuss alternative namings, while we can ^^
Early suggestions include: `NodeTypeInstanceOf` `NodeTypeAllowList` (no they are not ideal! ^^)

A second more clear task is to move the `NodeTypeConstraints` (and the internal `NodeTypeConstraintsWithSubNodeTypes`) from the `Neos\ContentRepository\Core\Projection\ContentGraph`  namespace two level deeper (`Filter\NodeTypeConstraints`) to the other filters: `Neos\ContentRepository\Core\Projection\ContentGraph\Filter\NodeTypeConstraints`

**Comment by mhsdesign** [comment]
@bwaidelich and me discussed that we want to move it into the `Filter` namespace and possibly rename it to `NodeTypeFilter`.

We will discuss this matter again on Friday.

About the breakiness -> we discussed, that we wont keep a backwards compatible layer for `NodeTypeConstraints` in beta 1.

**Comment by bwaidelich** [comment]
New suggestion from todays weekly:
`NodeTypeConstraints` => `Filter\NodeType\NodeTypeCriteria`
`NodeTypeConstraintsWithSubNodeTypes` => `Filter\NodeType\ExpandedNodeTypeCriteria`

@skurfuerst do you have an opinion on this one?

**Comment by bwaidelich** [comment]
The change is implemented with https://github.com/neos/neos-development-collection/pull/4551

The `Neos\ContentRepository\Core\Feature\Common\ConstraintChecks` [still refers to "nodeTypeConstraints"](https://github.com/neos/neos-development-collection/blob/task/4522-renameNodeTypeConstraints/Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php#L220-L223) – but in that case it seems fine because it is actually about the constraints imposed by the node type schema.

Or do we need a separate VO for those?

**Comment by mhsdesign** [comment]
@bwaidelich hmm indeed this is not perfectly clean but this method and the `Expanded` thing is internal either way.

so we might find at some point a better place for this logic or rename it -> we don’t need a second vo but rather only a better name.
If we don’t come up with anything I’m okay with keeping it as proposed in your pr.

One suggestion for this internal helper is to put it here `Neos\ContentRepository\Core\NodeType`

and name it `ExpandedNodeTypeList` or `NodeTypeNamesWithSubNodeTypeNames` or `NodeTypeInstanceOfMatcher` idk but it’s internal either way so we don’t need to worry to much

**Comment by mhsdesign** [comment]
@bwaidelich the solution in my comment above would also solve a dilemma in christians pr: https://github.com/neos/neos-development-collection/pull/4520#issuecomment-1732401145

**Comment by kitsunet** [comment]
Yes please
