### ISSUE TITLE
9.0 `Neos.Neos:NodeUri` relative uris?

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4524]
what should happen to relative node uris and `baseNodeName`

https://github.com/neos/neos-development-collection/blob/cdce7c8b7a3f0ae20394af0780367aaf451030c9/Neos.Neos/Classes/Fusion/NodeUriImplementation.php#L109-L112

Currently we just removed the whole relative logic, and "baseNodeName" will be unused. :D

And while were at it - baseNodeName was not such a cool idea after all: https://github.com/neos/neos-development-collection/issues/2274

**Comment by mhsdesign** [comment]
Okay i did a little research. Little did i know about neos 8.3 node paths syntax.

Regarding to https://github.com/neos/neos-development-collection/blob/140f3bbeac44948c30e80838d3837548fcb374b7/Neos.Neos/Classes/TYPO3CR/NeosNodeService.php#L32 it seems that its possible to enter following nodepaths in a neos 8.3 `Neos.Neos:NodeUri` or `<neos:uri.node />`

- `~/about/us` tilde means site relative
- `/sites/acmecom/about/us` absolute from the root
- `./neos/info` relative (or without dot`neos/info`)
- `../foo/../../bar` possibly some kind of traversal see https://github.com/neos/neos-development-collection/blob/072186e1601d82a8565942a05c9fe7253cf7f85d/Neos.ContentRepository/Classes/Domain/Utility/NodePaths.php#L174

not a nodepath but an id will do as well:

- `node://30e893c1-caef-0ca5-b53d-e5699bb8e506`

-------

Neos 9 discourages nodepaths and only supports mandatory simple syntax on the cr side.

- `some/relative/path` -> see [NodePath](https://github.com/neos/neos-development-collection/blob/5b7e06c5f029f3a3a9910f638ea641f98e2f2842/Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodePath.php#L29)
- `/<Neos.ContentRepository:Root>/my/site` (new) see [AbsoluteNodePath](https://github.com/neos/neos-development-collection/blob/5b7e06c5f029f3a3a9910f638ea641f98e2f2842/Neos.ContentRepository.Core/Classes/Projection/ContentGraph/AbsoluteNodePath.php#L33)

custom traversal logic or the magic tilde `~` has to be implemented from the outside.

it seems that the view helpers [`neos:link.node`](https://github.com/neos/neos-development-collection/blob/e20071e0295c61e319cd493dc5f082bedf22bc36/Neos.Neos/Classes/ViewHelpers/Link/NodeViewHelper.php#L127) and `neos:uri.node` have already been adjusted to allow:
-  `some/relative/path`
- and special `~/some/site/relativepath`

In contrast the `Neos.Neos:NodeUri` awaits to be implemented:

https://github.com/neos/neos-development-collection/blob/1801fbb862fdb16f431d143fcff2cf7a19da94b4/Neos.Neos/Classes/Fusion/NodeUriImplementation.php#L132-L142

The question is which are the desired syntax we want to allow.

Additionally we most likely need to update our documentation.

**Comment by kitsunet** [comment]
I guess the `~` could be implemented as we _can_ have a contextual knowledge about which site is active here? The rest 🤷 I am fine to axe. 🔥

**Comment by mhsdesign** [comment]
okay so allow 

- `/<Neos.ContentRepository:Root>/my/site`
- `some/relative/path`
- `~/about/us` will be transformed to `/<Neos.Neos:Sites>/mysite/about/us`

and that handling should be uniformed for those two viewhelpers and fusion in one place. Maybe `Neos\Neos\Utility\LegacyNodePathNormalizer` which we will also deprecate.
