### ISSUE TITLE
!!! FEATURE: Add `Neos.Neos:Site` (singular) NodeType for site nodes

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4531]
## upgrade instructions -> https://github.com/neos/neos-development-collection/issues/5400

@nezaniel suggested in [slack](https://neos-project.slack.com/archives/C3MCBK6S2/p1693574101993769)
> What do you think of introducing the Document type "Neos.Neos:Site" (singular) for site nodes? Should make stuff a lot easier (think of "find current site node" or "decide whether this should have an uriPathSegment"). It's breaky because Projects already on 9.0 need to adjust their NodeTypes config, but it's just one line per site type.

(this got actually 7 thumbs up :D)

and @kitsunet answered with
> makes sense to me, maybe even :SiteRoot to make it even clearer it's that single root per site?

---------

Our current way of fetching the sideNode is really not ideal or fast:

https://github.com/neos/neos-development-collection/blob/d9c374afb1b73267973e53e3789b949d45cb64df/Neos.Neos/Classes/Domain/Service/SiteNodeUtility.php#L40-L57

@nezaniel then i guess it would make sense to leverage https://github.com/neos/neos-development-collection/pull/4519 `findClosestNode` to write:

```php
$siteNode =  $subgraph->findClosestNode($node->nodeAggregateId, FindClosestNodeFilter::create(nodeTypeConstraints: 'Neos.Neos:Site');
```

**Comment by mhsdesign** [comment]
The `site:create` must then expect the `Neos.Neos:Site` type as homepage node

Or better the `Neos.Neos:Sites` should declare the constraint to only `Neos.Neos:Site`

And the `Neos.Neos:Document` must declare a constraint to not allow `Neos.Neos:Site` -> never!

**Comment by bwaidelich** [comment]
add constraints to `Neos.Neos:Sites` to only allow child nodes of type `Neos.Neos:Site`

**Comment by mhsdesign** [comment]
`\Neos\Neos\Domain\Service\NodeSiteResolvingService::findSiteNodeForNodeAddress` and `\Neos\Neos\Domain\Service\SiteNodeUtility::findSiteNode`

should be refactored to use

```php
$siteNode = $subgraph->findClosestNode($node->nodeAggregateId, FindClosestNodeFilter::create(nodeTypeConstraints: 'Neos.Neos:Site');
```

**Comment by ahaeslich** [comment]
@mhsdesign you already mentoined

> The site:create must then expect the Neos.Neos:Site type as homepage node

And don't we also have to adjust the legacy data migration? Do we expect users to migrate the old data and change the root node type configuration afterwards? Or do we inform them about the needed adjustments?

**Comment by mhsdesign** [comment]
Yes i was thinking about this too. Now the legacy migration service asserts that the site node must be of type `Neos.Neos:Site`.

**Comment by mhsdesign** [comment]
Existing projects might crash while rendering the site (as we expect the `siteNode` to be of type Site)

but structure adjustments should find the issue:

```
./flow structureadjustments:detect

The parent node type "Neos.Neos:Sites" is not allowing children of type "Neos.Demo:Document.Homepage",
                        and the grandparent node type "" is not allowing grandchildren of type "Neos.Demo:Document.Homepage".
                        Thus, the node is invalid at this location and should be removed.

```

this is ofcourse not ideal and we just need to inform everyone to add this new super type to the homepage - i do hope they have a separate nodeType for that already 🤞

**Comment by dlubitz** [comment]
>  i do hope they have a separate nodeType for that already

Most on my projects don't have that 🤷‍♂️

**Comment by mhsdesign** [comment]
> Most on my projects don't have that 🤷‍♂️

okay i see this is definitely a case we need to take care of. Lets move the migration discussion over here:

https://github.com/neos/neos-development-collection/issues/5400
