### ISSUE TITLE
TASK: Remove deprecated Fusion prototypes

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#4538]
Subtask of https://github.com/neos/neos-development-collection/issues/4498

### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

The prototypes "Array", "RawArray", "Collection", "RawCollection" and "Attributes" are deprecated since at least Neos 5 and should be removed.

**Comment by mhsdesign** [comment]
Hheheh i found some old fusion inside the neos ui e2e tests which needs to be adjusted ^^ https://github.com/neos/neos-ui/tree/9.0/Tests/IntegrationTests/TestDistribution/DistributionPackages

**Comment by bwaidelich** [comment]
@mficzel Thanks again for your great efforts on this one, it feels much cleaner.

I stumbled upon a regression though: Fluid based prototypes that used `Attributes` now fail with a "Array to string conversion" exception (see [Slack discussion](https://neos-project.slack.com/archives/C3MCBK6S2/p1697203200656909)).

IMO there are four possible solutions:

a) re-add `Neos.Fusion:Attributes` and use it for all Fluid based prototypes
b) adjust affected prototypes with some `@process` magic that converts the arrays
c) replace Prototypes using Fluid with Fusion implementations and remove Fluid dependency from Neos.Fusion
d) adjust affected Fluid templates, e.g. by adding a dedicated AttributesViewHelper
