### ISSUE TITLE
TASK: Reduce stored payload data for `WorkspaceRebaseFailed` in database

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4545]
Context: In a project the `WorkspaceRebaseFailed` event logged up to ~50MB of data in the `payload` database column.

As discussed in [Slack](https://neos-project.slack.com/archives/C3MCBK6S2/p1695126992771149) we want to:
- strip the payload down to only include the event UUIDs where the commands were reapplied f.e.
- maybe we can log the rest instead

**Comment by mhsdesign** [comment]
Yes this is a critical bug. I just discovered that the starship also suffers from it. During a replay i get:

```
flow cr:replayAll          
Replaying events for all projections of Content Repository "default" ...
Failed to decode data of event "e9d12a09-16ef-41ae-82b7-b2485e69ee95": Control character error, possibly incorrectly encoded

  Type: InvalidArgumentException
  Code: 1651839461
  File: Packages/Neos/Neos.ContentRepository.Core/Classes/EventStore/EventNormalize
        r.php
  Line: 154
```

which is meaningless, after improving the error i new that the event `66534`, a `WorkspaceRebaseFailed` could not be deserialized.

After looking into the event, i found that the json string just ends before its closes.
Maybe that happend due ex/importing the stream but still it should not be that big. And the error must be better on replay.

`\Neos\ContentRepository\Core\EventStore\EventNormalizer::denormalize`

**Comment by mhsdesign** [comment]
do you need a migration to remove the existing garbage for your existing project?

**Comment by ahaeslich** [comment]
Nope. No migration needed in this case. And I already cleaned up those events anyway😉
