### ISSUE TITLE
9.0 State of History Module

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4553]
The history module is currently not implemented/working and its heart mostly commented out:

https://github.com/neos/neos-development-collection/blob/73bf90f9348a1c560b61a8f112f8d0bc80942925/Neos.Neos/Classes/EventLog/Integrations/ContentRepositoryIntegrationService.php

## Option A:

create a simple implementation, which might not even be able to do more than the old history module. (Reusing the fluid templates?)

there was a wip implementation from 2021 which we might get some inspiration from:

https://github.com/neos/contentrepository-development-collection/pull/168

## Option B:

Create a way improved history module with way more possibilities - completely rewritten from scratch - dont say undo ^^

## Option C:

remove it (as there is no working code, only dead code) and add it as feature with 9.x

**Comment by mhsdesign** [comment]
Maybe we could also adopt https://github.com/aertmann/history as a flowpack package and use it as foundation for neos 9.

**Comment by markusguenther** [comment]
But the package from Aske is just extending the old package. So it would be still a rewrite to get rid of fluid, jQuery and the old event log ;)

But having a flowpack package is a good idea.
