### ISSUE TITLE
Command for node migration status

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4571]
> Also the ./flow nodemigration:migrationstatus command is still missing (if i checked the existing code correctly)

https://github.com/neos/neos-development-collection/issues/4442#issuecomment-1697952794

As @crydotsnake stated out, we have no "node migration status" in Neos 9.0 anymore. 

In general this was a useful feature to check if node migrations had already applied or not. But due to the changes in the node migration we can't guarantee anymore, that a migration really got applied to the content. E.g. a migration could be applied to a review workspace and partially or fully reverted.

Is it worth to store the migration executions nevertheless?

**Comment by bwaidelich** [comment]
We decided in our [weekly](https://neos-project.slack.com/docs/T04HF7TKV/F05NL5CE6E5) to skip this for now as it can get quite complex (we need to store CR instance, affected content streams and there are potential issues with eventual consistency). Also it is relatively easy to work around this issue with 3rd party packages, for example https://github.com/swisscomeventandmedia/Swisscom.CommandMigration
