### ISSUE TITLE
BUG: determineHierarchyRelationPosition can load position with only $succeedingSiblingAnchorPoint

### ISSUE THREAD

**Issue by pKallert** [neos/neos-development-collection#4575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While fixing #4510  I noticed that you have to set either the parent or the child anchor point in determineHierarchyRelationPosition(). 

In the code you do not need to set parent or child anchor point and can only use the $succeedingSiblingAnchorPoint to get the position. 

Short explanation of how stuff is loaded in the function: 

```
if ($succeedingSiblingAnchorPoint) {
   //load parent node anchor from succeeding sibling
   //load preceding sibling anchor from (new) parent node anchor
   //get position from $succeedingSiblingPosition and $precedingSiblingPosition
} else {
   if (!$parentAnchorPoint) {
      //load parent anchor from child anchor 
   }
   //load $rightmostSucceedingSibling from parent anchor
   //get position from $rightmostSucceedingSibling
}
```

### Expected Behavior

Right now, the position should be returned if either of the three variables is set. 

We can think about implementing a "fallback" to use the parentAnchorPoint if the succeedingSiblingAnchorPoint fails, but I am not sure if we want to load the position at any cost. 

### Environment

```markdown
- Flow:
- Neos:
- PHP:
```

**Comment by mhsdesign** [comment]
paula and me discussed that well close this as we cannot come up with a failing test and the logic seems correct
