### ISSUE TITLE
Discarding nodes tries to discard node from base workspace

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#4577]
I'm currently working on a bug for a customer in which they get errors when trying to discard/delete several workspaces.
Neos runs into an exception as nodes from "live" cannot be discarded as it has no base workspace.

So the `PublishingService->doDiscardNode` collects child nodes of the nodes in the desired workspace, but `nodeDataRepository->findByParentAndNodeType` returns a mixed list of child nodes from "live" and the target workspace.
See https://github.com/neos/neos-development-collection/blob/f328dd8c4d8366dcf802dab8820a0ad839ea4a6d/Neos.ContentRepository/Classes/Domain/Service/PublishingService.php#L185

I currently don't see exactly where `findByParentAndNodeType` makes sure that only matching nodes are returned.

So IMO the correct solution must be to add the following check before trying to discard the found child nodes:
```
if (!$affectedChildNodeData->matchesWorkspaceAndDimensions($node->getWorkspace(), $node->getDimensions())) {
    continue;
}
```

The bug only appears since they upgraded to 8.3, but it might affect 7.3 too and something else had changed.

**Comment by dlubitz** [comment]
Is there a way to reproduce that behavior?

**Comment by Sebobo** [comment]
So far I was only able to reproduce this in my customers project but not in the demo yet as it got a bit late yesterday.
Will try to do that today or Monday to fully understand the history of the issue.

**Comment by Sebobo** [comment]
But it must be something like this:

You have the workspace chain `"live" -> "A" -> "B"`

You modify a content element in `A` which has children and also modify one of it's children.
Then you modify the same element in `B` but not the children.

Then try to discard the changes from `B`.
Now I expect the changed child from `A` to appear in the nodes to discard which would discard it, as a base workspace exists.

Still thinking about the Problem with only live + A and the thrown exception that live has no base workspace.

**Comment by dlubitz** [comment]
Based on the place in the code, it needs to be some moved node, right?

**Comment by Sebobo** [comment]
Modified should be enough, why do you think moved?
It's definitely not added or removed from what I saw in the database.

**Comment by dlubitz** [comment]
It's all located in the iteration of the result of `findOneByMovedTo` .

https://github.com/neos/neos-development-collection/blob/cf4077dcdc71f96843d41f1ab350e0283fe06092/Neos.ContentRepository/Classes/Domain/Service/PublishingService.php#L181-L197

**Comment by Sebobo** [comment]
Ah yes 🤦 
Could explain, why it wasn't noticed more often.
