### ISSUE TITLE
Extend static analysis to all core packages

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4579]
Currently `composer lint` only respects the packages:

* `Neos.ContentGraph.DoctrineDbalAdapter`
* `Neos.ContentGraph.PostgreSQLAdapter`
* `Neos.ContentRepository.BehavioralTests`
* `Neos.ContentRepository.Core`
* `Neos.EventSourcedContentRepository.LegacyApi`
* `Neos.EventSourcedNeosAdjustments`
* `Neos.Neos`

we should extend that to more packages, for example `Neos.ContentRepositoryRegistry`

**Comment by mhsdesign** [comment]
and the ui ;) https://github.com/neos/neos-ui/issues/3631
