### ISSUE TITLE
BUG: Cannot create page in dimension a second time

### ISSUE THREAD

**Issue by pKallert** [neos/neos-development-collection#4583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, when publishing, deleting and publishing a page in a different dimension an error is thrown:

![Bildschirmfoto 2023-10-06 um 12 14 47](https://github.com/neos/neos-development-collection/assets/91674611/ec0a978c-5f44-4538-99a4-9fdd2c33c40f)

After reloading the whole page, there are two unpublished changes. 

When publishing the changes, and using the dimension switcher to switch to german, it shows the following error:
```
No content collection of type Neos.Neos:ContentCollection could be found in the current node (/[99f81405-8781-4f3b-a6ba-8606a8be66d6]/neosdemo) or at the path "teaser". You might want to adjust your node type configuration and create the missing child node through the "flow structureadjustments:fix --node-type Neos.Demo:Document.LandingPage" command.
```

### Expected Behavior

The page should be copied and the UI should show the 'new' page. 

### Steps To Reproduce

discovered on Neos Demo

1. Go to page 'Features'
2. Click on 'German' in dimension Dropdown to create new page in different dimension
3. Choose 'Create and copy' to create new page 
4. Publish to live workspace 
5. Delete 'Features' in the current german dimension 
6. Switch back to English dimension and go to 'Features' page
7. Click on German in dimension dropdown to create new page in german
8. Chose 'Create and copy' to create new page in german 

### Environment

```markdown
- Flow:
- Neos: 9.0
- PHP: 8.2
```

**Comment by nezaniel** [comment]
should be fixed with https://github.com/neos/neos-development-collection/pull/4943

**Comment by nezaniel** [comment]
fix confirmed, Neos now properly uses the publication API
