### ISSUE TITLE
Draft idea: Query thumbnails in batches to improve performance 

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#4589]
**Idea regarding thumbnail generation performance:**

I was able to speed up page generation for a customer quite a bit where they use a lot of source sets (3-6 variants) for each of their pictures.
So instead of querying every thumbnail on it’s own, I query all thumbnails for an asset in the `ThumbnailService` when the first one is requested and prefill the existing `thumbnailCache`.
This way, all following calls are much faster and I was able to reduce the query count and rendertime quite a bit.
Isn’t this something that would be a valid improvement for any project and the slightly increased memory usage should be negligible?

**Example:**

Page queries the following tables: 
* 113 * `neos_media_domain_model_image`
* 192 * `neos_flow_resourcemanagement_persistentresource` 
* 196 * `neos_media_domain_model_thumbnail`

Add the above mentioned optimisation in the `ThumbnailService`:
* 113 * `neos_media_domain_model_image`
* 192 * `neos_flow_resourcemanagement_persistentresource` 
* 67 * `neos_media_domain_model_thumbnail`

So the queries against the `ThumbnailRepository` are down by 2/3.

Maybe there can be even more achieved by batching more queries.

**Comment by Sebobo** [comment]
@mficzel did you ever look deeper into optimising thumbnail generation/resolving in relation to Kaleidoscope?
To me it seems that any page with lots of image variants creates a lot of overhead.

**Comment by Sebobo** [comment]
Solved in https://github.com/neos/neos-development-collection/pull/4624

**Comment by mficzel** [comment]
@Sebobo did not check this. For me performance was ok since async images are default. It makes sense to lookup all image variants at once to avoid separate requests for each item. Not sure how this relates to the Neos_Media_ImageSize cache.
