### ISSUE TITLE
BUG: Workspaces are not created / deleted during user creation / deletion

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4590]
User workspaces are only created when the user logs in to the backend. For example, using the impersonation button after creating a new user leads to an endless redirect loop (/neos/login -> /neos -> /neos/content -> /neos/login ...). Essentially it's the same outcome as in #4401.

Additionally I also discovered that user workspaces are not deleted anymore.

### Environment

```markdown
- Flow: 9.0
- Neos: 9.0
- PHP: 8.2
```

**Comment by mhsdesign** [comment]
yes i also noticed that in: https://github.com/neos/neos-development-collection/issues/4566

the workspace zookeeper doesnt do a particular good job :P

**Comment by kitsunet** [comment]
We should consider if that expectation (workspace(s) created when user created) is necessary for something or just something we are used to.

**Comment by mhsdesign** [comment]
Closing as part of https://github.com/neos/neos-development-collection/issues/4566

**Comment by mhsdesign** [comment]
Deletion is now also implemented via https://github.com/neos/neos-development-collection/pull/5470
