### ISSUE TITLE
BUG: Using "Publish all changes to live" in the workspace modul throws error

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While testing #4588 we found this behaviour while there was just **1 user** logged in:

Selecting all nodes by using "Select all current changes" and click on " Publish selected changes to live" (Calls `publishOrDiscardNodesAction`) works. ✅ 

Selecting nothing and click on "Publish all changes to live" (Calls `publishWorkspaceAction`) will lead to this error message:

> The base workspace has been modified in the meantime; please rebase.

Edit: ... sometimes 🤯

### Expected Behavior

Publishing via content module and workspace module works similar.

### Steps To Reproduce

1. Edit a page or content
2. Create a new page with subpages and e.g. content
3. Publish only the new parent page via "Publish to Live" button
4. Review all other changes in the workspace module (If your neos instance doesn't contain #4588 you need more than just new pages to get access to the discard/publish buttons)
5. Try to publish your all changes via "Publish all changes to live" (aka don't select the checkboxes)

Result: `The base workspace has been modified in the meantime; please rebase.`

1. Go to the content module
2. Click "Publish all"
3. Everything is published

### Environment

```markdown
- Flow: 9.0
- Neos: 9.0
- PHP: 8.2
```

**Comment by kitsunet** [comment]
I currently can't reproduce this anymore? I guess _sometimes_ and I just didn't find that some time yet?

**Comment by ahaeslich** [comment]
> I currently can't reproduce this anymore? I guess _sometimes_ and I just didn't find that some time yet?

Yes that was the confusing part. Will try to reproduce it and otherwise close this issue for now ... Thx for the reminder

**Comment by ahaeslich** [comment]
Can't reproduce it anymore. Therefore, we can close this issue.
