### ISSUE TITLE
Remove outdated doctrine migrations in Neos.Neos?

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4594]
i like to cleanup the migrations in neos.neos which are with neos 9 completely useless.

```
rm -f `find Migrations/{Mysql,Postgresql}/*.php | xargs grep -li neos_contentrepository_domain_model_nodedata `
```

see https://github.com/neos/neos-development-collection/pull/4240 where we also removed migrations ;)

outdated things:

```
neos_contentrepository_domain_model_nodedata
typo3_typo3cr_domain_model_workspace
typo3_typo3cr_domain_model_contentobjectproxy
typo3_typo3cr_domain_model_nodedata
typo3_neos_eventlog_domain_model_event
neos_neos_eventlog_domain_model_event`
```

**Comment by mhsdesign** [comment]
Its not worth the hassle for now

**Comment by mficzel** [comment]
Notes from weekly:

Main problem is handling of custom migrations that may rely on structure created by one of our migrations. 
Also we would have to rewrite some old migrations from Altering a table multiple times to a single create table which has some inherent complexity. 

Even if we would find a good way to rewrite and compact migrations we would then have to distinct between setups that were migrated fro the beginning of time and other that were created after the migration update. 

We are not aware of any good strategy for that and decide to look into that topic again once we see a good practice established in any other projects that use migrations over a long time.
