### ISSUE TITLE
Fusion ParserCache crashes when generated value is not a FusionFile

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#4595]
In https://github.com/neos/neos-development-collection/blob/6fcba54e22bdecc4dc70cf689dea2edce2583e8b/Neos.Fusion/Classes/Core/Cache/ParserCache.php#L65 the ParserCache just returns a value from another method that can return a `mixed` value and doesn't check if the value is actually a `FusionFile`. 
That leads to a crash when the generated value is `false` due to some other issue with the composer state or stale file cache.

**Comment by Sebobo** [comment]
Not 100% sure what would be the correct solution here. Even if the main issue is somewhere else, we have to check the type.

**Comment by mhsdesign** [comment]
A little peace offering: https://github.com/neos/neos-development-collection/pull/4839

**Comment by mhsdesign** [comment]
Is this possibly related? https://github.com/neos/flow-development-collection/issues/3284

Edit sorry no i thought the above happened with redis but seb negated this

**Comment by Sebobo** [comment]
> Is this possibly related? [neos/flow-development-collection#3284](https://github.com/neos/flow-development-collection/issues/3284)

How and why?

**Comment by kitsunet** [comment]
I don't think so, this is a rather special case and should show up as such in the log.

**Comment by mhsdesign** [comment]
@kitsunet do you like this fix? https://github.com/neos/neos-development-collection/pull/4839

feels a bit weird as on other places we are not that forgiving if the cache is broken and would just crash...

it seems `$this->parsePartialsCache->has` returns true but `$this->parsePartialsCache->get` false. Impossible. :D

**Comment by kitsunet** [comment]
Is why I almost never use "has" in caches, it is never atomic, you cannot know what happens between has and get. I prefer

```
$cacheEntry = $cache->get(...);
If ($cacheEntry === false)  {
   die(); // early return, exception, whatever
}
```

**Comment by mhsdesign** [comment]
Should be fixed via https://github.com/neos/neos-development-collection/pull/4839
