### ISSUE TITLE
`Neos.Neos:Site` NodeType should not show `uriPathSegment` property

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4621]
We briefly discussed this in our weekly:
Actually the `uriPathSegment` property should not be part of the homepage.
It would be rather nasty to remove the property from this type even though it is declared in the super type.. But I would say that this is the most pragmatic solution in this case. _If_ the following works:

```yaml
Neos.Neos:Site:
  'Neos.Neos:Document': true
  properties:
    'uriPathSegment': ~
```

(untested!)

Otherwise we should at least disable the UI editor for this property

_Originally posted by @bwaidelich in https://github.com/neos/neos-development-collection/pull/4563#discussion_r1358029375_

**Comment by mhsdesign** [comment]
Unsetting properties is currently not possible see tests: https://github.com/neos/neos-development-collection/pull/4620

But we could allow this see: https://github.com/neos/neos-development-collection/pull/4618

This still has to be discussed and it might not be a good idea as @kitsunet stated:

> I am not a fan, as said on Slack, I think if something proclaims to be `isOfType($nodeTypeName)` one should also be able  to expect the set of properties from said $nodeTypeName

**Comment by mhsdesign** [comment]
@bwaidelich wrote 

> But maybe we can at least hide it from the inspector by default?

**Comment by mhsdesign** [comment]
proposal from @mficzel 

```yaml
Neos.Neos:Mixin.UriPathSegment:
  properties:
    uriPathSegment:

'Neos.Neos:Document':
  superTypes:
    Neos.Neos:Mixin.UriPathSegment: true

Neos.Neos:Site:
  superTypes:
    'Neos.Neos:Document': true
    'Neos.Neos:Mixin.UriPathSegment': false
```

- UriPathSegment has a intransitive dependency on the composing nodetype that the inspector group "document"
- the i18n translation needs to be moved


additionall for another time we could add a `Neos.Neos:Folder` with `'Neos.Neos:Mixin.UriPathSegment': false`

and @kitsunet noted to forbid changing inherited types -> maybe only allow to get narrower? -> new issue.

**Comment by mhsdesign** [comment]
- The node creation processor should not set the value to "home" (with condition instance of Neos.Neos:UriPathSegment)
- Uri path projection should check against UriPathSegment

hiding the property would possibly result in validation error as its hidden: https://github.com/neos/neos-ui/issues/3549 and also its not clean to be able to set this property via php api.

We came to the conclusion that unsetting supertypes is not necessary clean, but its a feature an we might as well use it for this.

```yaml
 properties:
     uriPathSegment:
       ui:
         inspector:
           hidden: true
```

**Comment by mhsdesign** [comment]
Oh no. I just found out that the `uriPathSegment` property still exists for node types inheriting from `Neos.Neos:Site` as that will not be inherited?

```
'Neos.Demo:Document.Homepage':
  superTypes:
    'Neos.Neos:Site': true
```

this Homepage for example WILL show the uriPathSegment `flow nodetypes:show Neos.Demo:Document.Homepage --path properties.uriPathSegment` while `Neos.Neos:Site` doesnt.
One would have to add here `'Neos.Neos:UriPathSegment': false` as well explicitly. But this is of course unacceptable.

**Comment by kitsunet** [comment]
I still think it would make sense to create a new AbstractDocument or something without uriPath and add it for the regular Document or a new DocumentWithUri and Document becomes the base one, either way people would have to refactor something though.

**Comment by mhsdesign** [comment]
As removing a nodeType from the inheritance only works for the current (local) nodeType and is not further inherited, see:

https://github.com/neos/neos-development-collection/blob/e7b74c6f4deaabaac1ef841b8fb81250ef4d846a/Neos.ContentRepository.Core/Classes/NodeType/NodeType.php#L176-L180

we decided to against a mixin based solution for now. Also introducing a `DocumentWithUri` right now doesnt make much sense without a full concept for Folders https://github.com/neos/neos-development-collection/issues/4829 in mind.

I will reopen my initial simpler pr which would just hide the property in the ui. https://github.com/neos/neos-development-collection/pull/4826 and close https://github.com/neos/neos-development-collection/pull/4828
