### ISSUE TITLE
Make `ContentRepositoryServiceFactoryInterface` internal, and remove usages in Neos.Neos

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4634]
Initially it seemed that the `ContentRepository` should not know much about all things, thus we have the `ContentRepositoryServiceFactoryInterface` pattern.

That lead to `@deprecated really un-nice :D` cr services, that will do funny hanstands to get the variation graph or dimension source:

- DimensionControllerInternals.php
- WorkspacesControllerInternals.php
- DimensionsMenuItemsImplementationInternals.php
- FusionExceptionViewInternals.php

The variation graph and dimension source were exposed on the cr via https://github.com/neos/neos-development-collection/pull/3906

The question is if we should follow that lead and expose all things on the cr via getters (at least the api stuff)
and maybe have an internal `getInternals` method for the leftovers from `ContentRepositoryServiceFactoryDependencies`.

With https://github.com/neos/neos-development-collection/pull/4310 the services where also no singletons per cr anymore see removed `ContentRepositoryRegistry::$contentRepositoryServiceInstances` and by that the `buildService` pattern has no real gain.

@grebaldi suggested that instead of adding a `getInternals` to the cr, we could use a custom content repository factory for testing that will expose the dependencies somehow (hole through space) and thus we would be able to fetch them.

Currently we are relying on reflection to get the NodeFactory for example: https://github.com/neos/neos-development-collection/blob/00a60f391d749b146812b6153362a12d50bff7e3/Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Bootstrap/FeatureContext.php#L130

**Comment by bwaidelich** [comment]
We have to weight each case. Making `InterDimensionalVariationGraph` and `ContentDimensionSourceInterface` available makes sense because they are essential core concepts.

`ContentRepository` is our single most important API and I would be strongly against adding some `getInternals()` method to it.
Let's discuss this on concrete examples

**Comment by bwaidelich** [comment]
> Initially it seemed that the ContentRepository should not know much about all things

That wasn't the reason. The CR should not _expose_ internal things that allow users to circumvent it (easily).

I actually like the `ContentRepositoryServiceFactoryInterface` – it is quirky but it allows us to provide more features to domain services without breaking any API or exposing low-level concepts to the userland API

**Comment by mhsdesign** [comment]
I dont think the `ContentRepositoryServiceFactoryInterface` and the way we pass the internal dependencies along is a bad idea per se.

And regarding the behat tests i agree with [your](https://github.com/neos/neos-development-collection/pull/5028#discussion_r1594187753) idea, or we could still make a custom cr factory expose its dependencies as a hole through  space.

> We should probably just create some CR Service for the behat tests – that has access to all the `ContentRepositoryServiceFactoryDependencies` including the `propertyConverter` that is the only thing we're extracting here.
> 
> But we can certainly solve that in a follow-up!
> ...
> Actually this is much more an issue of the `LegacyMigrationService` in this case. We can definitely fix that and make it easier to be used from tests!


-------

I think what my main complaint is regarding the `ContentRepositoryServiceFactoryInterface` that we wind up making things really hard to get which are useful for the user. In that case people might just give up and declare it impossible. But seeing our hacks `DimensionControllerInternals`, `WorkspacesControllerInternals` etc we almost didnt expose them until recently.

But we seem to now have figured out what to expose or not.

So my actual points regarding the services now that we can use getVariationGraph and getContentDimensionSource are:

1) A user of the cr should never need to use the content repository service pattern. Its only a matter for highly internal core things.

2) Access to the factory dependencies must be treated with care so only services that absolutely need such low level control should use this pattern. Using them in Neos.Neos can mostly be avoided as only the `ContentRepository` is passed.

Things that dont need special dependencies:
- `NodeMigrationService`
- `GlobalAssetUsageService` (actually just implements this interface but is not such a service)
- `AssetUsageSyncService`
- `SiteServiceInternals`

That actually means were only left with the Core itself needing this extension point and sub packages like `Export` and `LegacyNodeMigrations`.
That being said we can make this extension vector fully internal, what it is.

3) The mechanism is marked as api, but its clearly internal
... because most of the things in the `ContentRepositoryServiceFactoryDependencies` are internal:
- EventNormalizer, PropertyConverter, EventPersister, Projections

4) We should not expose this extension mechanism further as part of the Neos.Neos api

imo extension points like say implementing a custom node uri path segment generator should not require to use this pattern for the reason that its just pretty much overkill to have the EventPersister suddenly at hand.

The reason im mentioning this is because you came up with the idea of using these domain services as extension point for implementing a custom node creation handler.


TLTR: Keep the mechanism but only use it wisely and thus not in higher level parts like in Neos.Neos or the ui, and declare it internal.

**Comment by bwaidelich** [comment]
I am really convinced that we should decide on concrete cases, so thanks for coming up with a couple of them!
`InterDimensionalVariationGraph` and `ContentDimensionSource` (and `ContentDimensionZookeeper`) are purely readonly core concepts and I would be fine with exposing those through the CR directly (rendering `DimensionControllerInternals` and `WorkspacesControllerInternals` obsolete – btw: `Controller<Something>` is IMO mostly a bad idea, see `ControllerContext` as a controller should just.. well.. control the flow).

I suggest not to just expose the three classes confusing users with three new concepts – but some methods for the common Content Dimension queries are fine I think.

`NodeTypeManager` is another thing that should be exposed on the top-level API IMO.

But the rest (`EventStore`, `EventNormalizer`, `PropertyConverter`, `EventPersister` and `Projections`) should absolutely not be accessible via the CR directly in my strong opinion :)

**Comment by mhsdesign** [comment]
Okay after talking we agreed to keep the ContentRepositoryServiceFactoryInterface but make them internal only used by low level packages like Export and LegacyNodeMigrations.

Neos.Neos and the other mentioned places can already rewrite its DimensionControllerInternals and further to use `ContentRepository::getVariationGraph` or just the content repository directly without indirection.

We also did question why the cr has to expose another class regarding this one concept of the content dimensions? We should check the usages of `getContentDimensionSource` and see why its a separate thing from `getVariationGraph`. Generally there could even exist a higher level thing to ask the content repository about dimensions but that is just future music.
