### ISSUE TITLE
Potential race condition when publishing nodes leading to lost content

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4680]
Changing content while a publish is in progress leads to the new changes being lost because the corresponding events are published to the _old_ content stream.

## Background

Currently, when handling `PublishWorkspace` and `PublishIndividualNodesFromWorkspace` commands, the following steps are performed:

1. The content stream is forked and all events from the former content stream (`cs1`) are re-published to the new CS 
2.  (`cs2`): `ContentStreamWasForked`, `<Event1FromCS1>`, `<Event2FromCS1>`, ...)
3. The workspace is published (`WorkspaceWasPublished` or `WorkspaceWasPartiallyPublished`) 
4. The workspace read model is updated to point to the new CS (`cs2`)

```
         props were set
               ┌─┐
       cs1 ────┼┼┼───────────────────────────
               └─┘

                 cs was forked  props were set
                       ┌─┐         ┌─┐
       cs2 ────────────┼┼┼─────────┼┼┼───────
                       └─┘         └─┘


                                     workspace was published
                                            ┌─┐
       ws1 ─────────────────────────────────┼┼│
                                            └─┘
```

If between step 1 and 3 a new Command for the same workspace (`ws1`) is handled, the corresponding event(s) will end up in in the previous content stream `cs1`:

To solve this, we should publish a new event (for example `ContentStreamWasClosed`) *before step 1* and add a write constraint that fails if new events ought to be published to that CS afterwards:

```
   props were set  cs was closed
         ┌─┐          ┌─┐
 cs1 ────┼┼┼──────────┼┼┼─────────────────────────
         └─┘          └─┘

                      cs was forked  props were set
                            ┌─┐         ┌─┐
 cs2 ───────────────────────┼┼┼─────────┼┼┼───────
                            └─┘         └─┘


                                          workspace was published
                                                 ┌─┐
 ws1 ────────────────────────────────────────────┼┼│
                                                 └─┘
```

NOTE: This won't completely solve the problem, but lead to an exception in that case such that the UI can re-send the command. In a follow-up we could introduce some re-try mechanism for aggregate failures to resolve these cases automatically

**Comment by ahaeslich** [comment]
Because of this issue we removed the auto publishing checkbox in neos/neos-ui: https://github.com/neos/neos-ui/commit/5306eea28f490552cde663eeeb1f4a3fe1cc4190

**Comment by ahaeslich** [comment]
@bwaidelich would the contentstream also be closed before a rebase?

**Comment by bwaidelich** [comment]
> would the contentstream also be closed before a rebase?

Yes, I think so – whenever we want to avoid that new events are published to some content stream.
I gave it a first try (WIP) with #4692
