### ISSUE TITLE
!!! TASK: Use consistently value objects in ESCR Core in `Workspace` related api code

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4683]
Additionally we should evaluate if we should allow to attach other metadata to the workspace, and dont treat users as escr concept.

- Workspace::$workspaceOwner should be UserId instead of string
- WorkspaceFinder::findOneByWorkspaceOwner should use UserId instead of string
- WorkspaceFinder::findOutdated and findByBaseWorkspace should return Workspaces instead of array

**Comment by mhsdesign** [comment]
Might be solved when @bwaidelich refactors the stuff :D

**Comment by bwaidelich** [comment]
Will be solved with #4726
