### ISSUE TITLE
BUG: Incorrect Image Caching

### ISSUE THREAD

**Issue by so-grimm** [neos/neos-development-collection#4707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you have an image component that displays the metadata (caption, copyright notice, etc.) of an image and then the metadata is changed in the media module, these changes aren't shown in the frontend until the cache is flushed.

### Expected Behavior

When changing the metadata of an image, those changes should show up immediately in frontend.

### Steps To Reproduce

1. build an image component with an image caption
2. fill the image caption with `${this.image.caption}`
3. add module to a page, fill it with an image that has a caption
4. go to the media module and change the caption of the image
5. go back to your page -> the caption will still have the old text

### Environment

```markdown
- Flow: 9.0
- Neos: 9.0
- PHP: 8.2
```

### Anything else?

I tested the behavior on Neos 8 as well and it's working correctly there.

**Comment by mficzel** [comment]
Is this really different in Neos 8.3? I would suspect this data beeing cached with the html from the Fusion Cache. 

Maybe we should add something like `${Neos.Caching.resourceTag()}` to ensure caches are flushed when resources change. AFAIK we do not have something like that in anywhere.

**Comment by so-grimm** [comment]
Yes, it is. I tested it on Neos 8.3 and 7.3 and in both cases the caption changes immediately, but in Neos 9.0 I need to flush the cache to get the new value.

**Comment by bwaidelich** [comment]
@mficzel I think we do: https://github.com/neos/neos-development-collection/blob/bb4cfc2447114eb1bdf132445f790c749024d9d0/Neos.Neos/Classes/Package.php#L102-L108

**Comment by kitsunet** [comment]
Yep that! and there is some hidden _magic_ in the uri converter implementation where we convert the asset://<uuid> to an actual asset and append a tag to the rendering

**Comment by bwaidelich** [comment]
I guess the code from above still stems from a time where we had a "global content cache"..
But with the `AssetUsage` projection in place it should be possible to re-wire this somehow

**Comment by kitsunet** [comment]
> had a "global content cache"..

huh? what do we have now?

**Comment by bwaidelich** [comment]
> what do we have now?

Well it's still global, but it depends on the Content Repository.
@dlubitz didn't we have a similar topic (or was it the same) were we thought about some configuration option to opt into "asset usage management"?

**Comment by mficzel** [comment]
Hmmm ... interesting  did not know that. 

Currently the inner working of `registerAssetChange` as simply commented out on Neos 9 with `TODO: re-implement this based on the code below`

Not sure i really like this. We could still decide to add AssetTags like NodeTags explicitly.  

```
  entryTags {
     1 = ${Neos.Caching.assetTag(asset)}
  }
```

**Comment by dlubitz** [comment]
TBH I can't remember. 

AFAIS, nothing has changed here, as the AssetRepository still emit the signal.

**Comment by dlubitz** [comment]
Good catch @mficzel ... 🙈

**Comment by kitsunet** [comment]
This is interesting, that means we need to flush asset changes on every repository I guess? given that they are global and we can't really know which repository uses it

**Comment by dlubitz** [comment]
@kitsunet That's covered internally as the AssetUsage iterates over all CRs
