### ISSUE TITLE
WIP: TASK: Add `Neos.Node.identifierForNode(node): string`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4716]
This 8.3 way doesnt work anymore `node.identifier`

and we dislike those options:

```
node.nodeAggregateId.value

q(node).property('_identifier')
```

**Comment by ahaeslich** [comment]
Wouldn't this apply to a lot of places where this is needed now? E.g. `nodeTypeName.value` ...

And I can vaguely remember that we discussed this in an ESCR weekly (it feels like ages ago ...) and decided to not inroduce something like this 🤔

**Comment by kitsunet** [comment]
I still dislike the root cause ... `nodeType.value` :D but if we do this then at least short as  `Neos.Node.identifier(node)` ?

**Comment by mhsdesign** [comment]
okay i agree. hmmm i accidentally introduced `getNodeType` and `subgraphForNode` in the node helper which should be for consistency renamed to `nodeType` and `subgraph`

**Comment by mhsdesign** [comment]
on the other hand. it was decided to name it `nodeAggregateId` so im not sure this makes things more clear.

i think `node.nodeAggregateId.value` is fine for the few times you need it. Will close this for now
