### ISSUE TITLE
Don't rebase the user workspace on Login if not required

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4728]
Currently the user workspace is being rebased during every login, even if the workspace is up-to-date.
This leads to a reduced performance and needless content streams and events.

**Comment by ahaeslich** [comment]
> Don't rebase the user workspace on Login if not required

I'm trying to remember what we would define as "if not required"? Meaning if the workspace status is `UP_TO_DATE`? Or do we also skip a rebase if the status is `OUTDATED_CONFLICT`?

**Comment by ahaeslich** [comment]
ping @Wyndala 😉

**Comment by mhsdesign** [comment]
so i implemented it with skipping `OUTDATED_CONFLICT` makes no sense to force an error imo and prevent logging in.
