### ISSUE TITLE
9.0 Avoid `getActiveRequestHandler` in node property mapper for uncached fusion rendering

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4732]
For fusions uncached context variables (in the `uncached` mode) to work one needs a property mapper to serialize the variable to a string [see code](https://github.com/neos/neos-development-collection/blob/c8bb9d8bee36efdd4b3d92869e2523e70d358684/Neos.Fusion/Classes/Core/Cache/ContentCache.php#L344-L348).

This is problematic for nodes in neos 9 as its string representation (the NodeAdress) doesnt serialize the content repository id: https://github.com/neos/neos-development-collection/issues/4441

Previously in Neos 8.3 this was not a problem as a node could be easily resolved from a context path as there was no ambiguity of multiple content repositories.

To solve this obstacle (temporary?) we currently have this [`NewNodeConverter`](https://github.com/neos/neos-development-collection/blob/9dd4ed5e657bcbb227b64e3991fc8268bdca539f/Neos.Neos/Classes/Fusion/NewNodeConverter.php#L36) which has quite a side effect to get a content repository out of the blue:

https://github.com/neos/neos-development-collection/blob/9dd4ed5e657bcbb227b64e3991fc8268bdca539f/Neos.Neos/Classes/Fusion/NewNodeConverter.php#L70-L76

Using the `activeRequest` of the bootstrap like this will make it impossible to render fusion from the cli.

This fix was introduced with https://github.com/neos/neos-development-collection/commit/763f2930055924d15c9013ed5bd706f23ebde7c2

I would not like to ship this code for Neos 9 final release as this property mapping would also allow implicit code like this to work:

```
public function nodeAction(Node $node): {}
``` 

This might be dangerous as its abstracts away the `request`, to `content repository id` mapping and besides is not testable as it doesnt use the action request of the controller but the one from the bootstrap.

-> extracted discussion to here: https://github.com/neos/neos-development-collection/issues/4873

**Comment by mhsdesign** [comment]
@kitsunet wrote

> Why do we not have a fully qualified node serialization format, that would help it I guess

Thats what i implemented here: https://github.com/neos/neos-development-collection/pull/4734

but i guess maybe this should rather be part of the cr itself see `NodeIdentity` in https://github.com/neos/neos-development-collection/issues/4564

**Comment by kitsunet** [comment]
I am not so good with discussion here where here is not "there" 😂 too many place overflow...
Anyways yes I would rpefer a more unified solution, that also potentially gets rid of the `\Neos\Neos\FrontendRouting\NodeAddress::serializeForUri` in favor of a fully qualified format.

**Comment by mficzel** [comment]
We will have to add the cr id to a node address anyways. So why not do it sooner than later.
