### ISSUE TITLE
BUG: 9.0 - Translating document nodes leads to wrong ordering

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#4742]
Currently the ordering behavior of the CR is undefined for the following scenarios:

- [x] CreateNodeAggregateWithNode with fallbacks
- [x] Create Peer Variant
- [x] Create Generalization

This leads to the problem that different projections implement ordering differently then; leading to subtle bugs.

For instance, the `DocumentUriPathProjection` needs the ordering as well to find the first child node for FirstChild-shortcuts -- and it currently does it **differently** than the Content Graph.

That is what I originally wanted to fix; when I stumbled into this rabbit hole ;)

### Current Behavior

On the demo site, let's say you have the following english nodes:

- a
- b
- c
- d

=> now, you translate `b` to german; leading to the following structure:

- b

=> now, you translate `a` to german, leading to the following structure:

- b
- a

=> this is wrong, expected would be:

```
- a
- b
```

### Fixing Plan

- [x] NodePeerVariantWasCreated
  - **highest priority**, because it is relevant when simply having a language dimension and starting to translate
  - [x] extend event to have s.th. like `PositionMapping` (modeled after `MoveNodeMapping`)
  - [x] in command handler, use same logic to determine positionMapping as in MoveNode
  - [x] write testcase
  - [x] ensure ordering is respected in graph projection
  - [x] ensure ordering is respected in Routing projection
- [x] NodeGeneralizationVariantWasCreated
- [x] NodeAggregateWithNodeWasCreated with fallbacks

NOTE: NodeSpecializationVariantWasCreated does not need to be adjusted, because it only leads to re-wiring of edges, and not to new edges.

**Comment by nezaniel** [comment]
FYI: I can't detect any issues with only CreateNodeAggregateWithNode alone, which commands are needed for this to fail?
Edit: Edge case found, tested and fixed

**Comment by nezaniel** [comment]
the content graph part will be fixed in https://github.com/neos/neos-development-collection/pull/4961
still missing is the uri path projection part, which will happen in a follow-up

**Comment by nezaniel** [comment]
follow-up is ready: https://github.com/neos/neos-development-collection/pull/4975

**Comment by nezaniel** [comment]
Also: NodeSpecializationVariantWasCreated needed to be adjusted for edge cases where a succeeding sibling is deleted in a variant that is to be created by variation.
