### ISSUE TITLE
BUG: FusionView does not set valid locale so we always have default locale used on the frontend

### ISSUE THREAD

**Issue by soee** [neos/neos-development-collection#4766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If we have 2 languages used on our website, and Flow configured like this for example:

```
Neos:
  Flow:
    i18n:
      defaultLocale: pl
      fallbackRule:
        order:
          - pl
          - en
```
than on the frontend side always Polish language will be used (transaltions from XLF filed referenced in fusion), even if we switch language to English.

I have done some debugging steps and it seems it might be related to this code:

https://github.com/neos/neos-development-collection/blob/9.0.0-beta5/Neos.Neos/Classes/View/FusionView.php#L75

In Neos `8.3.x` there was call to `$this->setFallbackRuleFromDimension($currentNode);` but it is missing in `9.0-dev` even though the related trait is used.

For tests i have added this line on the 9.0 branch:
`$this->setFallbackRuleFromDimension($currentNode->originDimensionSpacePoint->toDimensionSpacePoint());`
and the translation were resolved as they should. 

This might be some regression in `9.0-dev`.

### Expected Behavior

If we have configured 2 languages for Flow and content repository dimension, if we switch the dimension, than also static translation from XLF files should match selected language dimension.

### Steps To Reproduce

- configure languages dimension with 2 languages
- configure Flow to use default locale, configure fallbacks etc.
- add some static translation in both languages in `Main.xlf` file and reference them in Fusion with `I18n.translate(...)`
- switch languages on the frontend
- the default locale configured for Flow will be used for both languages

### Environment

```markdown
- Flow: 9.0-dev
- Neos: 9.0-dev
- PHP: 8.2.11
```

**Comment by mhsdesign** [comment]
Closing as duplicate https://github.com/neos/neos-development-collection/issues/4930#issuecomment-1993811781
and it was fixed :)


Btw it seems you already did all the debugging, so feel free to open up a pr for that (even the github ui can help with oneliners ^^)
