### ISSUE TITLE
9.0 Improve CLI commands for the new ESCR

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4772]
- [ ] ~`cr:setupall` (analog to `cr:replayall`~ -> makes no sense
~- `cr:eventlog` to show events of a content stream?~ -> own package for now
- [x] `cr:prune --assume-yes` flag for https://github.com/neos/neos-ui/blob/5a897ef57b85228073f825bc619fa3310979c5cd/Tests/IntegrationTests/e2e.sh#L14
- [ ] `site:prune` without exit code 1 if no site: https://github.com/neos/neos-ui/blob/b6bd93c68ac2413425e2df15d1c04c896cd31bb2/Tests/IntegrationTests/e2e.sh#L29-L31 -> also this regex `"*"` is not used in any other cli api. -> later ;)
- [x] `cr:setup --empty-tables-except-the-events` or `cr:prune --keep-event-log` for cases when the `cr:setup` fails because the projections are filled and they have to be emptied first and then replayed. https://github.com/neos/neos-development-collection/pull/4791#issuecomment-1910213133
- [x] Unifiy naming of `--content-repository-identifier` to `--content-repository` for example in `workspace:discard`https://github.com/neos/neos-development-collection/pull/5115

**Comment by crydotsnake** [comment]
@kitsunet There are still two todos left on the list:

![SCR-20240605-jazt](https://github.com/neos/neos-development-collection/assets/39345336/d1cc4ebd-c11f-43a6-9bce-e24d4165259c)


Which have not been solved with my PR #5115 

Or why did you close the issue 🤔

**Comment by kitsunet** [comment]
hahaha, no because I merged the PR it closed this

**Comment by crydotsnake** [comment]
> hahaha, no because I merged the PR it closed this

Ahh yes ! now i remember 🤦🏽

**Comment by crydotsnake** [comment]
@mhsdesign Could you please give me more details about the other open todos?
