### ISSUE TITLE
BUG: Login As (user impersonation) not working with subfolders

### ISSUE THREAD

**Issue by so-grimm** [neos/neos-development-collection#4797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When working in a Neos installation in a subfolder, the user impersonation functionality doesn't work and I get an error saying "Could not switch to the selected user." In Neos installations without subfolder, it's working fine.

### Expected Behavior

It should always be possible to switch users, regardless of using subfolders or not.

### Steps To Reproduce

1. use a Neos installation in a subfolder (e.g. www.myproject.com/subfolder/neos)
2. go to User Management
3. click on the crossed arrows at the very end of the table row for any user

### Environment

```markdown
- Flow: 8.0 (?)
- Neos: 8.0
- PHP:
```

**Comment by dlubitz** [comment]
Maybe this static location here is causing this:
https://github.com/neos/neos-development-collection/pull/3648/files#diff-dcd63ecf706315f7e80ff36392ab0f6995243cec061273247ede46454a7a7e92R82

**Comment by so-grimm** [comment]
Yeah, it is. There was a PR to fix this (sorry, forgot to add that in the report), but it was never merged: https://github.com/Unikka/login-as/pull/16/files
But I'm not quite happy with that fix and I think there has to be a better one. I'll look into it as soon as I have the time, but I figured it would be a good idea to create an issue for it already, so I don't forget (and in case someone else wants to fix it).

**Comment by kitsunet** [comment]
Given that this script is included in pretty much all backend modules I guess we have to generate the correct url in the generic Module/Index.html template in Neos.Neos and then grab it from the markup in this script.

**Comment by so-grimm** [comment]
So far I haven't encountered any problems with other backend modules, though 🤔 I can do some more testing, but everything else seems to be working fine.

**Comment by ahaeslich** [comment]
> So far I haven't encountered any problems with other backend modules, though 🤔 I can do some more testing, but everything else seems to be working fine.

Well there is another issue in the UI which is not that breaking: https://github.com/neos/neos-ui/issues/3712
