### ISSUE TITLE
FEATURE: Use the Neos logo in the top bar as "home button"

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#4799]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

I often want to directly jump to the content module which is the default first available `preferredStartModules` setting.

So instead of clicking to open the module dropdown then selection the content module etc. one click on the Neos logo would direct me there instead.

If the `preferredStartModules` is configured differently or users are restricted to another module, for them the "home" would just be that next module then and hopefully not be confusing.

### Possible Solution

Link the logo to the first available (defined by policies) entry in `preferredStartModules`.

**Comment by dlubitz** [comment]
+1
I also clicked the logo thousend times to get to the content module 🙈

**Comment by crydotsnake** [comment]
I Like it ! :)
