### ISSUE TITLE
BUG: Asset collection is empty and throwing error

### ISSUE THREAD

**Issue by auwaerter** [neos/neos-development-collection#4801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We do have a multisite setup using the default media management. For each site, we use a different media collection which we restrict via policies e.g.:

Restrict:

```yaml
privilegeTargets:
  'Neos\Flow\Security\Authorization\Privilege\Entity\Doctrine\EntityPrivilege':

    'Vendor.Vendor:Site.Vendor':
      matcher: 'isType("Neos\Neos\Domain\Model\Site") && property("nodeName") == "vendor-vendor"'
```
Restriction 1:
```yaml
  'Neos\Media\Security\Authorization\Privilege\ReadAssetPrivilege':
    'Vendor.Vendor:P01.ReadAllFiles':
      matcher: 'isInCollection("collectionp01")'
```
Restriction 2:
```yaml
  'Neos\Media\Security\Authorization\Privilege\ReadAssetCollectionPrivilege':
    'Vendor.Vendor:P01.ReadAssetCollection':
      matcher: 'hasId("<collectionid>")'
```

Whitelist:

```yaml
roles:
  'Neos.Neos:P01':
    label: 'Project P01'
    privileges:

      - # Access to site
        privilegeTarget: 'Vendor.Vendor:Site.Vendor'
        permission: GRANT

      - # Negate default deny, and gives access to all files in specific asset collection
        privilegeTarget: 'Vendor.Vendor:P01.ReadAllFiles'
        permission: GRANT

      - # Negate default deny, and gives access to specific collection
        privilegeTarget: 'Vendor.Vendor:P01.ReadAssetCollection'
        permission: GRANT
```

However, the media collection is empty but images are visible within `All` and appear to be assigned correct:

![image](https://github.com/neos/neos-development-collection/assets/6923945/7c164230-7b03-46fa-a265-5df3f2bfd75d)

Each time i'm trying to access any asset collection, the following exception is thrown:

`Exception in line 306 of /var/Neos/Packages/Libraries/doctrine/orm/lib/Doctrine/ORM/Query.php: Too many parameters: the query defines 1 parameters and you bound 2 - See also: 20231213121220a100e3.txt`

20231213121220a100e3.txt:

```
Exception in line 306 of /var/Neos/Packages/Libraries/doctrine/orm/lib/Doctrine/ORM/Query.php: Too many parameters: the query defines 1 parameters and you bound 2

61 Doctrine\ORM\Query\QueryException::tooManyParameters(1, 2)
60 Doctrine\ORM\Query::_doExecute()
59 Doctrine\ORM\AbstractQuery::executeIgnoreQueryCache(NULL, 4)
58 Doctrine\ORM\AbstractQuery::execute(NULL, 4)
57 Doctrine\ORM\AbstractQuery::getSingleResult(4)
56 Doctrine\ORM\AbstractQuery::getSingleScalarResult()
55 Neos\Flow\Persistence\Doctrine\Query_Original::count()
54 Neos\Flow\Persistence\Doctrine\QueryResult_Original::count()
53 Neos\Media\Domain\Model\AssetSource\Neos\NeosAssetProxyQueryResult::count()
52 Neos\Media\Browser\Controller\AssetController_Original::indexAction("Thumbnail", NULL, NULL, NULL, 0, NULL, NULL, 0, Neos\Media\Domain\Model\AssetCollection, NULL)
51 Neos\Media\Browser\Controller\AssetController::indexAction("Thumbnail", NULL, NULL, NULL, 0, NULL, NULL, 0, Neos\Media\Domain\Model\AssetCollection, NULL)
50 Neos\Media\Browser\Controller\AssetController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
49 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
48 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
47 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
46 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
45 Neos\Media\Browser\Controller\AssetController::indexAction("Thumbnail", NULL, NULL, NULL, 0, NULL, NULL, 0, Neos\Media\Domain\Model\AssetCollection, NULL)
44 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
43 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
42 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
41 Neos\Flow\Mvc\Dispatcher_Original::dispatch(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
40 Neos\Neos\Controller\Backend\ModuleController_Original::indexAction(array|3|)
39 Neos\Neos\Controller\Backend\ModuleController::indexAction(array|3|)
38 Neos\Neos\Controller\Backend\ModuleController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
37 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
36 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
35 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
34 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
33 Neos\Neos\Controller\Backend\ModuleController::indexAction(array|3|)
32 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
31 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
30 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
29 Neos\Flow\Mvc\Dispatcher_Original::dispatch(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
28 Neos\Flow\Mvc\DispatchMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
27 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
26 Neos\Flow\Http\Middleware\SecurityEntryPointMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
25 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
24 Neos\Flow\Http\Middleware\RequestBodyParsingMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
23 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
22 Neos\Flow\Mvc\FlashMessage\FlashMessageMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
21 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
20 Neos\Flow\Http\Middleware\PoweredByMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
19 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
18 Neos\RedirectHandler\RedirectMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
17 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
16 Neos\Flow\Mvc\Routing\RoutingMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
15 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
14 Neos\Neos\Routing\RequestUriHostMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
13 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
12 Neos\FluidAdaptor\Core\Widget\AjaxWidgetMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
11 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
10 Neos\Flow\Http\Middleware\SessionMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
9 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
8 Neos\Flow\Http\Middleware\MethodOverrideMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
7 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
6 Neos\Flow\Http\Middleware\TrustedProxiesMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
5 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
4 Neos\Flow\Http\Middleware\StandardsComplianceMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
3 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
2 Neos\Flow\Http\RequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()


HTTP REQUEST:
target: /neos/management/media?moduleArguments%5B%40package%5D=neos.media.browser&moduleArguments%5B%40controller%5D=asset&moduleArguments%5B%40action%5D=index&moduleArguments%5B%40format%5D=html&moduleArguments%5Bview%5D=Thumbnail&moduleArguments%5BassetCollection%5D%5B__identity%5D=18095071-e91c-49ed-8092-c413bde09768&moduleArguments%5BcollectionMode%5D=0&moduleArguments%5B%40subpackage%5D=
Cookie: neosUserId=Bearer%20<bearer>
Accept-Language: de-DE,de;q=0.9,pl;q=0.8,en-US;q=0.7,en;q=0.6
Accept-Encoding: gzip, deflate, br
Referer: https://<host>/neos/management/media?moduleArguments%5B%40package%5D=neos.media.browser&moduleArguments%5B%40controller%5D=asset&moduleArguments%5B%40action%5D=index&moduleArguments%5B%40format%5D=html&moduleArguments%5Bview%5D=Thumbnail&moduleArguments%5BassetCollection%5D%5B__identity%5D=18095071-e91c-49ed-8092-c413bde09768&moduleArguments%5BcollectionMode%5D=0&moduleArguments%5B%40subpackage%5D=
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Upgrade-Insecure-Requests: 1
Sec-Ch-Ua-Platform: "Windows"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
X-Scheme: https
X-Original-Uri: /neos/management/media?moduleArguments%5B%40package%5D=neos.media.browser&moduleArguments%5B%40controller%5D=asset&moduleArguments%5B%40action%5D=index&moduleArguments%5B%40format%5D=html&moduleArguments%5Bview%5D=Thumbnail&moduleArguments%5BassetCollection%5D%5B__identity%5D=18095071-e91c-49ed-8092-c413bde09768&moduleArguments%5BcollectionMode%5D=0&moduleArguments%5B%40subpackage%5D=
X-Forwarded-Scheme: https
X-Forwarded-Proto: https
X-Forwarded-Port: 443
X-Forwarded-Host: <host>
X-Forwarded-For: <IP>
X-Real-Ip: 163.116.173.65
X-Request-Id: 6296a82eb0e4cf94dbfc31308e5db737
Host: <host>
Authorization: ****
Content-Length:
Content-Type:

PHP PROCESS:
Inode: 19952484
PID: 9883
UID: 0
GID: 0
User: root
```

### Expected Behavior

Using flow 8.3.6, but beside that the very same setup (DEV, also running in Production context):

![image](https://github.com/neos/neos-development-collection/assets/6923945/da3f0c94-dc5a-4a86-b4eb-5ebccfb796d8)

### Environment

```markdown
- Flow: 8.3.7
- Neos: 8.3.4
- PHP: 8.2.12-fpm-alpine3.18
```

### Anything else?

Thread in [Slack](https://neos-project.slack.com/archives/C050C8FEK/p1702470547795349) where it has been reported that this error does not occur within flow 8.3.6 and there as an potential fix here: https://github.com/neos/neos-development-collection/pull/4724

**Comment by dlubitz** [comment]
Issue is caused by https://github.com/neos/neos-development-collection/pull/4724.

**So affected Neos versions are: 7.3.17, 8.0.14, 8.1.9, 8.2.9, 8.3.7.**

It seems not to be a good choice to create the QueryBuilder multiple times. Sorry for the trouble.

**Comment by dlubitz** [comment]
Is fixed with a bugfix release:
https://discuss.neos.io/t/neos-bugfix-releases-7-3-18-8-0-15-8-1-10-8-2-10-8-3-8/6469

**Comment by digipublica** [comment]
VIELEN DANK FÜR IHRE NACHRICHT,

Für laufende Projekte (Installationen, Update-, Hotline- oder
Wartungsversträge) gilt : Es meldet sich bevorzugt ihr persönlicher
Ansprechpartner schnellstmöglich bei Ihnen.
Für Zusatzleistungen gilt: Aufwandserfassung im engmaschigen
15-Minuten-Takt, nach aktuellem Stundensatz.

IHRE TICKET-NUMMER:  Ticket #4260 - "Re:
[neos/neos-development-collection] BUG: Asset collection is empty and
throwing error (Issue #4801)"

AKTUELLE ANTWORTZEIT: Bis zu 2 Werktage (bei regulärer Auslastung 1
Werktag)
IHRE AKTUELLE TICKETÜBERSICHT: einsehbar über unser Endnutzerportal
[https://support.digiportal.de/help/1181393294/auth](Keine
Registrierung notwendig) 

WEITERE INFOS HINZUFÜGEN:
_Nutzen Sie die Zwischenzeit eventuell zur Ergänzung Ihres Tickets,
um hilfreiche Informationen zur schnelleren Bearbeitung. Beispiele
für nützliche Informationen:_
_- Sind direkte Verlinkungen zu betreffenden Seiten im Backend oder
im Frontend auf der Website im Ticket vorhanden?_
_- Könnte ein Screenhot hilfreich für die Orientierung unserer
Support-Mitarbeiter sein?_
_- Auf welchem Weg sind Sie zu ihrem Ergebnis gekommen (z.B. Klick auf
Bild in linker Spalte dann Klick auf Zurück-Button des Browsers,
Aufruf über Suchergebnis auf Google,...)_
_- Handelt es sich um einen Fehler: Wie äußerte ich der Fehler
(weiße Seite, welche Fehlermeldung), um wieviel Uhr trat der Fehler
auf, Welche Geräte wurden zum testen genutzt,..._

Zur Ergänzung einfach auf diese E-Mail antworten - oder über
das  Endnutzerportal.
[https://support.digiportal.de/help/1181393294/auth]_
_

IHR SUPPORT-TEAM

TEL +49 (8142) 6 69 32 – 500
FAX +49 (8142) 6 69 32 – 299
***@***.***
WEB www.digipublica.de [http://www.digipublica.de]

INFOBRIEF PER MAIL – BLEIBEN SIE AUF DEM LAUFENDEN

Unser Infobrief für Kommunen ist mehr als nur ein Newsletter. Er
behandelt neueste digitale Entwicklungen, die direkt bei Ihnen im
Postfach landen – immer dann, wenn es wichtig ist.

→ JETZT UNVERBINDLICH ABONNIEREN
[https://www.digipublica.de/digital-sein/newsletter]

digiPublica – eine Marke der econix GmbH | Johann-G.-Gutenberg-Str.
15 | DE-82140 Olching | www.digipublica.de [http://www.digipublica.de]
[http://www.digipublica.de/]
Amtsgericht München HRB 190789 | Geschäftsführer: Jürgen Hein

**Comment by digipublica** [comment]
VIELEN DANK FÜR IHRE NACHRICHT,

Für laufende Projekte (Installationen, Update-, Hotline- oder
Wartungsversträge) gilt : Es meldet sich bevorzugt ihr persönlicher
Ansprechpartner schnellstmöglich bei Ihnen.
Für Zusatzleistungen gilt: Aufwandserfassung im engmaschigen
15-Minuten-Takt, nach aktuellem Stundensatz.

IHRE TICKET-NUMMER:  Ticket #4261 - "Re:
[neos/neos-development-collection] BUG: Asset collection is empty and
throwing error (Issue #4801)"

AKTUELLE ANTWORTZEIT: Bis zu 2 Werktage (bei regulärer Auslastung 1
Werktag)
IHRE AKTUELLE TICKETÜBERSICHT: einsehbar über unser Endnutzerportal
[https://support.digiportal.de/help/1181393294/auth](Keine
Registrierung notwendig) 

WEITERE INFOS HINZUFÜGEN:
_Nutzen Sie die Zwischenzeit eventuell zur Ergänzung Ihres Tickets,
um hilfreiche Informationen zur schnelleren Bearbeitung. Beispiele
für nützliche Informationen:_
_- Sind direkte Verlinkungen zu betreffenden Seiten im Backend oder
im Frontend auf der Website im Ticket vorhanden?_
_- Könnte ein Screenhot hilfreich für die Orientierung unserer
Support-Mitarbeiter sein?_
_- Auf welchem Weg sind Sie zu ihrem Ergebnis gekommen (z.B. Klick auf
Bild in linker Spalte dann Klick auf Zurück-Button des Browsers,
Aufruf über Suchergebnis auf Google,...)_
_- Handelt es sich um einen Fehler: Wie äußerte ich der Fehler
(weiße Seite, welche Fehlermeldung), um wieviel Uhr trat der Fehler
auf, Welche Geräte wurden zum testen genutzt,..._

Zur Ergänzung einfach auf diese E-Mail antworten - oder über
das  Endnutzerportal.
[https://support.digiportal.de/help/1181393294/auth]_
_

IHR SUPPORT-TEAM

TEL +49 (8142) 6 69 32 – 500
FAX +49 (8142) 6 69 32 – 299
***@***.***
WEB www.digipublica.de [http://www.digipublica.de]

INFOBRIEF PER MAIL – BLEIBEN SIE AUF DEM LAUFENDEN

Unser Infobrief für Kommunen ist mehr als nur ein Newsletter. Er
behandelt neueste digitale Entwicklungen, die direkt bei Ihnen im
Postfach landen – immer dann, wenn es wichtig ist.

→ JETZT UNVERBINDLICH ABONNIEREN
[https://www.digipublica.de/digital-sein/newsletter]

digiPublica – eine Marke der econix GmbH | Johann-G.-Gutenberg-Str.
15 | DE-82140 Olching | www.digipublica.de [http://www.digipublica.de]
[http://www.digipublica.de/]
Amtsgericht München HRB 190789 | Geschäftsführer: Jürgen Hein
