### ISSUE TITLE
BUG: ContentCache entries and keys are not workspace/contentstream aware

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4810]
In Neos <9.0 we stored the workspace name of a node, within the content cache key to be able to flush caches more precisely and prevent exposing cached user-workspace content to live.

We need to discuss, what fits best here: **workspace name** or **contentstream id**
And add the addional identifier to the cache keys in cache creation and flushing.

We also should check if it's still needed to iterate over workspace hirarchy for cache flushing, as we do it in Neos <9.0.

**Comment by mhsdesign** [comment]
As discussed in https://github.com/neos/neos-development-collection/pull/4940#discussion_r1531217463

requiring the contentStreamId in `CacheTag::forDynamicNodeAggregate` will be tedious as with the `NodeIdentity` refactoring and the `NodeAdress` removal, the content stream id will no longer be available.

See https://github.com/neos/neos-development-collection/pull/4892/files#r1531772541

As we want to remove the content stream id from userland it will be hard to fetch and there is (i believe) no gain in preferring it for caching.

**Comment by kitsunet** [comment]
I think we _have_ to use workspaceName as we still need to flush based on the workspaceName when the csId changes, probably has broken edge cases with csId around publishing anyways.

**Comment by dlubitz** [comment]
This has acually been discussed and we decided to switch it to workspace name. It's on my todo list. But I was also depending on Workspace aware commands etc.
