### ISSUE TITLE
BUG: Content Change Projection never get's cleaned up

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#4813]
It seems, the content change projection never get's cleaned up. Each change in a user workspace gets added to the projection. But it never gets removed.

I would assume, that for example a publish to live workspace would remove regarding change entries in the projection. Also `flow contentstream:prune` seems not to remove any entries.

**Comment by ahaeslich** [comment]
During the sprint we discovered that `discard` or `discardAll` via NeosUi doesn't discard all changes.

**Comment by ahaeslich** [comment]
@dlubitz can we close this issue in favour of #4998?
