### ISSUE TITLE
FEATURE: Relocate User Menu to the Left Drawer

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-development-collection#4825]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

The current positioning of the user menu in the primary bar has been identified as a potential area for improvement. Considering user behavior, where the user menu is primarily utilized for actions like logging out, we propose relocating it to the left drawer. This adjustment aligns with established UX patterns observed in other systems, where the user menu is de-emphasized and accessed when needed.

### Possible Solution

We have identified some areas where the UI can be enhanced to provide a better user experience. However, we also need to adjust the regular backend module interface to make these improvements work seamlessly.well. More informations regarding the user menu in the following UI issue: https://github.com/neos/neos-ui/issues/3685

We have also planned to extend the user management module and user with an avatar. This will help us to have a better visual recognition of user changes in a potential new view for content changes.

**Comment by laurahaenel** [comment]
I would like to help with that topic at the upcoming sprint in Hamburg :)

**Comment by markusguenther** [comment]
Good morning,

As @laurahaenel wants to work on that, it is maybe a good idea to share my thoughts a bit.
I made some rough sketches to demonstrate the idea.

**Drawer with closed User-Menu**
![Image](https://github.com/neos/neos-development-collection/assets/1014126/7d070007-2656-45ed-9248-e3f0c8a14c87)

**Drawer with open User-Menu**


![Image](https://github.com/neos/neos-development-collection/assets/1014126/218f310d-d3e2-431b-8a60-7aeacbe6d825)
![Image](https://github.com/neos/neos-development-collection/assets/1014126/c7d08898-651a-439a-901b-34ebb71087cc)







The user should get an avatar image in. the future. So I would add a component that renders the avatar or, if we don't have one, a circle with the initials of the user or so. As we drop the version number here, I think it would be neat to have an extra info button where we can open a dialog and show the version or something like that. Main information we also need for issues for instance ;)

I hope that helps, the issue is that we need to do that at two places. The neos-ui with react and the Neos/Neos package where we use VanillaJS. I would also support here :)

**Comment by laurahaenel** [comment]
I guess the info button in the user dropdown should only show information regarding the user, not the neos version. Would leave this info button out of scope and add the version information elsewhere. Any ideas on that? @markusguenther 

- Leave it in the drawer but on top of the user dropdown or ...
<img width="474" alt="image" src="https://github.com/neos/neos-development-collection/assets/150482551/61d5e406-a7db-49db-a7e6-8761049f7027">

- add an (i) Icon somewhere?

**Comment by markusguenther** [comment]
> I guess the info button in the user dropdown should only show information regarding the user, not the neos version. Would leave this info button out of scope and add the version information elsewhere. Any ideas on that? @markusguenther
> 
>     * Leave it in the drawer but on top of the user dropdown or ...
> 
> 
> <img alt="image" width="474" src="https://private-user-images.githubusercontent.com/150482551/312061947-61d5e406-a7db-49db-a7e6-8761049f7027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDQyNjQsIm5iZiI6MTcxMDI0Mzk2NCwicGF0aCI6Ii8xNTA0ODI1NTEvMzEyMDYxOTQ3LTYxZDVlNDA2LWE3ZGItNDlkYi1hN2U2LTg3NjEwNDlmNzAyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxMTQ2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGM2MzUyY2NmMDY4YWIyNDEzYmIyNmE1YTQ1YTkzMTgyMjMwYzRiZDUxNmE1OWMwMmUzOTdmNzg1MmRmNjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4Q6CasjALl1-KszHpauUQ_5ezgE942lb_oJxysBdo-Q">
> 
>     * add an (i) Icon somewhere?

Personally, I would just remove the version panel then. In the "old" Neos User interface, we don't have the information at all. On the other hand, I often use it as quick notice what version the Neos would be because it is faster than the Packages list.

Any opinions from the others @mhsdesign @grebaldi @Sebobo @ahaeslich ???

**Comment by laurahaenel** [comment]
As agreed by @mhsdesign and @grebaldi we will leave the info as seen in the last screenshot.
The version information for Neos.Neos should then be added respectively for Neos.Neos.

**Comment by Sebobo** [comment]
Love the change so far!

Keep in mind that it also affects the `Back to user "My Name"` action when impersonating another user. Maybe this mode can be better reflected too?

IMO the version thing is useless if it just shows the UI version. I mostly check out the package management module to find out exact versions. Maybe a drawer with a list of version of configured packages would be better and be mostly hidden by default.

**Comment by laurahaenel** [comment]
This change is affected by the open bug [#4590](https://github.com/neos/neos-development-collection/issues/4590)
