### ISSUE TITLE
TASK: Deprecate `Neos.Fusion:Plugin`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4889]
This is an outdated concept from typo3 times.
And the manipulation of `$this->runtime->getControllerContext()->getResponse()` is a smell and the easiest to avoid it here is to avoid the fusion plugin in general :P

related https://github.com/neos/neos-development-collection/issues/4855

**Comment by kitsunet** [comment]
No ;) It's not outdated and has it's uses IMHO. What is the argument here?

**Comment by mhsdesign** [comment]
Idk @Sebobo wanted that :D
I dont have a strong opinion.
