### ISSUE TITLE
Migrating old cr data with additional root nodes and their children

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4895]
Migrating Neos 8 content to Neos 9 will, as of now, migrate all nodes residing below the sites root node. Nodes residing below other root nodes, like e.g. taxonomies, won't be migrated into the new CR.

https://github.com/neos/neos-development-collection/blob/783e08a1b03f33bbb4052b3611c46596f6e934b9/Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php#L126-L142

**Comment by dlubitz** [comment]
AFAIS this is not that easy. We need a definition of the RootNodeAggregate for each of these "RootNodeAggregates" (a NodeType) and a mapping of the old "path" to the new RootNodeType.

For example the RootNodeAggregate definition was already done by Sitegeist in the Sitegeist.Taxonomy package:
https://github.com/sitegeist/Sitegeist.Taxonomy/blob/neos-9/NodeTypes/Root.yaml
