### ISSUE TITLE
9.0 DataTime property with string (defaultValue) like `now`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4901]
There is some weird behaviour about the type DateTime when being used with a `defaultValue` of a string representation like `yesterday`.

According to https://discuss.neos.io/t/date-picker-is-one-day-off/6421 or probably the docs php strings should work.

The event exists with
```
  "initialPropertyValues": {
    "datePublished": {
      "value": "today",
      "type": "DateTime"
    },
```

To me that seems at least interesting. Will the actual date now be relative the the event time or always "today"?

Also we don't seem to normalise the `type` name correctly. The event should contain `DateTimeImmutable` as per `PropertyType::getSerializationType` and not `DateTime` or `DateTimeInterface`
That the aliases work is only thanks to symphony's support for them to handle also 
```
Neos\ContentRepository\Core\Feature\NodeModification\Dto\SerializedPropertyValue object
 value => string "now" (3)
 type => string "DateTime" (17)
```
That leads to the property now being accidentally mutable (with no effect but still.)

Also i noticed that the `commandPayload` doesnt contain the default nodetype values - probably also a bug as they have to be deterministic for rebase? !!!!!!!!!!!

**Comment by mhsdesign** [comment]
The cause of this is trusting user input to hard :D We effectively do ` SerializedPropertyValues::defaultFromNodeType($nodeType)` which we merge onto the `initialPropertyValues`.
That explains why the `initialPropertyValues` in the `commandPayload` dont have them, as this modification is not kept for rebases.

We should probably read the properties and let them first be deserialised to ensure all constraints are met. For example an image object should never be written `"foo"` into.


EDIT 3

we seem to check the default properties here https://github.com/neos/neos-development-collection/blob/9c8f3077b337ae38556d43cbd75142ee1484944a/Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php#L72-L75 but discard the results 🤔 probably that a rebase is not fully deterministic but takes the current default values in consideration?


EDIT 4

so in the end it seems everything does kinda work and there are tests for it :D
https://github.com/neos/neos-development-collection/blob/5917d8b357b1c867c66ac949f72a34266df692d6/Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/05-CreateNodeAggregateWithNode_ComplexDefaultAndInitialProperties.feature#L20

but  as far as i can tell is `now` always the current time as its deserialised from symphony not taken the event timestamp into account. Is that correct behaviour?

The serialised properties come back from the projection like this:

```
 string "now" (3) => Neos\ContentRepository\Core\Feature\NodeModification\Dto\SerializedPropertyValue object
   value => string "now" (3)
   type => string "DateTimeImmutable" (17)
```

and will be unserialized on the fly in `PropertyConverter::deserializePropertyValue` without further context.

**Comment by mhsdesign** [comment]
Edit 4

i think im now pretty sure that we should use the timestamp of the date when the node was first created.

For example its otherwise not possible to pass relative dates into a node property:

> PropertyValuesToWrite::fromArray(['myDate' => 'now'])

results in

> Property "myDate" cannot be set to a value of type "string", must be of type "DateTimeImmutable"

**Comment by mhsdesign** [comment]
Edit 5

well i think this was an accidental regression from https://github.com/neos/neos-development-collection/pull/4251
previously `NodeType::getDefaultValuesForProperties` also returned actual date time instances but now it returns only raw properties.

That would also explain all the now obsolete `instanceof DateTime` checks when `getDefaultValuesForProperties` is used, that i could not explain til now.

**Comment by mhsdesign** [comment]
We _could_ even provide a migration, but as far as i can see was no one hopefully foolish enough to use this feature. So i would propose to only write a migration if deemed necessary. You can check if your project might be affected by just checking all `DateTime` properties and see if they have a relative property value.

At least i dindt saw the feature being used in any of the starships i came across. Maybe @ahaeslich can confirm this as well?

**Comment by ahaeslich** [comment]
> At least i dindt saw the feature being used in any of the starships i came across. Maybe @ahaeslich can confirm this as well?

Uh couldn't find it in our Neos 9 project if that is what you are asking. Not sure if anyone tryed it and didn't raise that it doesn't work. In Neos 8 projects I could find the usage of `defaultValue: now`.

**Comment by mhsdesign** [comment]
Thanks for your insight. That confirms what we thought in our weekly. No migration for this.
