### ISSUE TITLE
BUG: Fusion translations not working in Neos 9

### ISSUE THREAD

**Issue by ClaraRuna** [neos/neos-development-collection#4930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using translations in Neos Fusion via xliff files the Strings are not translated. Instead the fallback language is used.

`Neos\Neos\Tests\Unit\View::setUpMockView` is currently skipped ( `$this->markTestSkipped` )

### Expected Behavior

The Strings are translated to the expected language, as it happens in Neos 8.3 and described [in the Docs](https://docs.neos.io/guide/manual/rendering/translating-text-in-fusion).

### Steps To Reproduce

Install Neos 9 and add the following translation file to Neos.Demo/Resources/Private/Translations/de/Presentation/Cards.xlf

```<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file original="" product-name="Neos.Demo" source-language="en" datatype="plaintext" target-language="de">
        <body>
            <trans-unit id="cards.moreButton" xml:space="preserve">
                <source>More</source>
                <target xml:lang="de" state="translated">Mehr</target>
            </trans-unit>
        </body>
    </file>
</xliff>
```

In the Neos user backend, copy the blog-node and at least one blogpost to the German dimension and add a Neos.­Demo:­Content.­BlogPostingList. Set the blog-node as "Blog" property/reference. The blogpost will be shown, but the "More"-button will not be translated. 

### Environment

```markdown
- Flow: neos/flow-development-collection 9.0.x-dev 5b8bcba 
- Neos: neos/neos-development-collection   9.0.x-dev bc39546
- PHP: 8.2.16
```

### Anything else?

The reason appears to be that the **I18n\Service.php always returns default dimension**

 `Neos\Flow\I18n\Translator.php::translateById` always has $locale=en after 
``` 
$locale = $this->localizationService->getConfiguration()->getCurrentLocale();
```

**Comment by kitsunet** [comment]
This _could_ be something to compare 8.3 and 9.0 with each other. We do some ugly magic to set the current locale to whatever the (document) node has you are looking at. 
`\Neos\Neos\View\FusionViewI18nTrait::setFallbackRuleFromDimension`

Seems this code still exists and is adapted to Neos 9.0 but is only called for exception handling, when before in 8.3 it was used in `\Neos\Neos\View\FusionView::render`

**Comment by ClaraRuna** [comment]
Nice, simply adding `$this->setFallbackRuleFromDimension($currentNode->subgraphIdentity->dimensionSpacePoint);` to `Neos\Neos\View::render` fixed it.

**Comment by mhsdesign** [comment]
Probably a duplicate? https://github.com/neos/neos-development-collection/issues/4766

**Comment by ClaraRuna** [comment]
True. I originally thought the bug was in neos/flow
