### ISSUE TITLE
BUG:  autocomplete in Neos password update

### ISSUE THREAD

**Issue by 73nici** [neos/neos-development-collection#4944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a password for another user has been updated via the Neos backend UI and a password manager (BitWarden) is used, pre-filled passwords may occur. (The prefilled passwords are not suggestions)

![image](https://github.com/neos/neos-development-collection/assets/30949443/a4f7d5ca-a8ae-40af-895e-5522bc791783)

### Expected Behavior

Autocomplete and autofill should not be available for setting a new password.

### Steps To Reproduce

1.  Open Neos Backend UI
2. Edit an existing user
3. Open the account edit page
4. Password and password confirmation are filled if BitWarden with autofill on page load is used

### Environment

```markdown
- Neos: 8.3.9
- PHP: 8.1.27
```

### Anything else?

This should be fixable by setting `additionalAttributes="{autocomplete: 'new-password'}"` for `<f:form.password` in
`Packages/Neos/Neos.Neos/Resources/Private/Partials/Module/Shared/EditAccount.html`

**Comment by mhsdesign** [comment]
ja
