### ISSUE TITLE
Assets in node properties are serialised in backend communication leading to slow requests and timeouts

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#5006]
The `Neos.Neos.userInterface.inspector.dataTypes` settings in https://github.com/neos/neos-development-collection/blob/6841c6878c241e9affb6ae2b86e5e19b1e237a09/Neos.Neos/Configuration/Settings.yaml#L197 are missing configurations for other asset types than image. The Asset default configuration is not inherited by the subclasses.

**Current behaviour:**

1. Have a nodetype with a non image asset property like a video
2. Upload video with 100MB
3. The preview html now contains 100MB of serialised video in the node script tag

Same for xhr request from the Neos UI that retrieve node properties

**Expected behaviour:**

Only the asset identity and type should be generated for the UI to consume.

**Comment by kdambekalns** [comment]
But should a video not be an `Asset`? Or does this happen with entirely custom types? I quickly tried this on a Neos 7.3 site that has a lot of videos, and the data loaded was reasonably small in all cases. 🤔

**Comment by kdambekalns** [comment]
Ah, no inheritance at that point! 🙈

**Comment by Sebobo** [comment]
> But should a video not be an `Asset`? Or does this happen with entirely custom types? I quickly tried this on a Neos 7.3 site that has a lot of videos, and the data loaded was reasonably small in all cases. 🤔

Do you have a different configuration than the example in my PR?
Would be interesting if this either was no problem in 7.3 or depends on some other configuration.

I already wondered why nobody noticed this yet.

**Comment by Sebobo** [comment]
Just tested in 7.3 and it behaves the same. The size of the asset is added to the preview document.
