### ISSUE TITLE
`flow cr:setup --reset-projections` might fail if tables to be truncated dont exist

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#5008]
We possibly have to try catch this:

```
private function truncateDatabaseTables(): void
{
    $connection = $this->dbalClient->getConnection();
    try {
        $connection->executeQuery('TRUNCATE table ' . $this->tableNamePrefix . '_node');
    } catch (\Doctrine\DBAL\Exception\TableNotFoundException) {
    }
```

otherwise - in our dev phase at least - when we add tables to projections, the command doesnt work as expected as it will fail to truncate new tables.
I think its fair that reset would be forgiving.

**Comment by bwaidelich** [comment]
@mhsdesign #5089 should do the trick, no?
