### ISSUE TITLE
Fully migrate `ContentCacheFlusherTest` to behat

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#5037]
There is this functional test leftover https://github.com/neos/neos-development-collection/blob/ee36cc29460aa2005a22b577080a85ba505a6d1f/Neos.Neos/Tests/Functional/Fusion/Cache/ContentCacheFlusherTest.php#L25

which has been migrated partially with https://github.com/neos/neos-development-collection/pull/4788 but as @dlubitz pointed out

> I'd say I didn't test the workspace chains.

so that should ideally be added to the new behat tests

**Comment by dlubitz** [comment]
I think we can safely close this, as we improved the testing of the content cache flusher at all. And this specific case was just testing some implementation detail.

**Comment by mhsdesign** [comment]
Thank uuuuu ❤️
