### ISSUE TITLE
Define ContentGraph memory cache flushing

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#5039]
good point, this _is_ a dealbreaker IMO – probably it makes sense to call this something else (e.g. `resetRuntimeCaches`) and then reset the inMemoryCache (we should not _disable_ it).

The main goal of this change was not to expose all those nasty internals such that we can refactor more easily.
In fact `inMemoryCache` is now only public because it is still used by the nasty code of the [frontend controller](https://github.com/neos/neos-development-collection/blob/9.0/Neos.Neos/Classes/Controller/Frontend/NodeController.php#L314-L333) (which I plan to clean up)

But we should make sure that:
```php
$subGraph->find*(...);
$contentRepository->handle(...);
$subGraph->find*(...);
```
behaves as expected, i.e. the second subgraph interaction contains the changes.

Lets see if the tests fail – and if they don't we should add scenarios that reflect the above!

_Originally posted by @bwaidelich in https://github.com/neos/neos-development-collection/pull/5028#discussion_r1593535508_

**Comment by mhsdesign** [comment]
points from todays meeting

            * long running process where other process changes content repository? How to flush
                * manually call markstale??
            * flush in same process when mark stale
            * disable vs flush confusion?

**Comment by bwaidelich** [comment]
I think this issue is obsolete with #5243 and can be closed

**Comment by mhsdesign** [comment]
Yes was about to look this up when i read your issue but you found this already ^^

I believe the only thing that this covers also is the runtimeCache handling in the workspaceFinder which is not incorporated in your issue?

**Comment by bwaidelich** [comment]
> I believe the only thing that this covers also is the runtimeCache handling in the workspaceFinder which is not incorporated in your issue?

That's right, but the workspace projection will be incorporated into the content graph projection anyways

**Comment by mhsdesign** [comment]
ahhh yes i forgot about that todo ;) so +1
