### ISSUE TITLE
AssetUsage needs to switch from contentStreamId to WorkspaceName

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#5060]
The AssetUsage needs to switch from contentStreamId to WorkspaceName from Projection until all depending DTOs.

* AssetUsageProjection
* AssetUsage
* AssetUsageFilter
* AssetUsageReference

This is depending on https://github.com/neos/neos-development-collection/pull/5002

**Comment by mhsdesign** [comment]
was not aware of this now we have 2: https://github.com/neos/neos-development-collection/issues/5084
