### ISSUE TITLE
BUG: media usage missing information about workspaces

### ISSUE THREAD

**Issue by habuchholz** [neos/neos-development-collection#5181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the media usage tab of an image you can see which workspaces are using that picture, but you can't see the name of the person owning that workspace. This prevents the possibility to delete a picture, if a user uses that image in his personal workspace and you can't find out who that person is.

This can potentialy cause data compliant issues, if the image has to be taken down because of copyright problems but one user is still using it in his personal workspace. 

### Expected Behavior

Possibility to enable showing all workspace titles/owners to user with certain roles in the media usage tab.

### Steps To Reproduce

Check image usage of an image that is used in another personal workspace in the media usage tab.

### Environment

```markdown
- Flow: 8.3.8
- Neos: 8.3.12
- PHP: 8.1.27
```

**Comment by skurfuerst** [comment]
Related: https://github.com/neos/neos-development-collection/pull/5291
