### ISSUE TITLE
BUG: Node-Migrations leave a published workspace behind that can't be changed out of

### ISSUE THREAD

**Issue by c4ll-m3-j4ck** [neos/neos-development-collection#5191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When executing a node-migration to change the nodeType of a NodeAggregate, a workspace with a uuid-like name is left behind. After switching the current workspace to this workspace, it is not possible to switch the base workspace back to "live".

The request to `https://neos.ddev.site/neos/ui-services/change-base-workspace` simply times out and nothing happens.

There are no exceptions thrown and no log-entries appear.

### Expected Behavior

After running a node-migration, the changes should be published to the live workspace and the temporary import-workspace should be discarded.

Changing into a workspace should not cause a user to be stuck on this workspace.

### Environment

```markdown
- Flow: 9.0.0-beta10
- Neos: 9.0.0-beta10
- PHP: 8.3
```

**Comment by c4ll-m3-j4ck** [comment]
I've looked into this a little further:

It seems as if there is a while condition in `WorkspaceCommandHandler::requireNonCircularRelationBetweenWorkspaces` that doesn't seem to terminate when I try to change back to the live workspace. 

I additionally tried testing this by creating another internal workspace and switching to this workspace but this fails in the same manner. I don't know however if this happens because the "import" workspace that I initially changed to is broken in some way.

**Comment by c4ll-m3-j4ck** [comment]
Furthermore, apparently this leaves a user in a broken state, I can't change back to the live workspace, I can't change into any other workspace and also I can't delete my user workspace and recreate it, essentially breaking my user permanently.

**Comment by dlubitz** [comment]
@c4ll-m3-j4ck could you already check, if this issue is gone, with Neos 9.0beta11 or higher?

**Comment by c4ll-m3-j4ck** [comment]
I've checked and the issue seems to be resolved!
Thank you very much!
