### ISSUE TITLE
BUG: Changing nodetype in BE to one that has a contentCollection childNode leaves changes that can't be published

### ISSUE THREAD

**Issue by c4ll-m3-j4ck** [neos/neos-development-collection#5192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I change the nodetype in the backend via the _nodeType selector, the nodetype of the selected node is changed correctly. However, if this new nodetype has a child-contentcollection which wasn't present in the previous nodetype, the change which adds this collection can not be published. There is no error thrown but after reloading, the change is still visible in the backend. There is a `WorkspaceWasPartiallyPublished` entry in the events.

Publishing via the cli `workspace:publish` command publishes correctly.

### Expected Behavior

Publishing the changes works as expected.

### Environment

```markdown
- Flow:
- Neos: 9.0
- PHP:
```

**Comment by dlubitz** [comment]
I've tested this and it seems to be fixed with #5320
