### ISSUE TITLE
BUG: Target workspaceName may exceed allowed workspaceName lenght on NodeMigration

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#5199]
As we build the target workspaceName from the source workspaceName and add some additional information, this will lead to an to long target workspace name. 

We need to find a new way of building the target workspaceName or shorten it somehow.

`this-is-my-long-workspace-name` => valid, but becomes:
`migration-this-is-my-long-workspace-name-20240101000000` => invalid

[https://github.com/neos/neos-development-collection/blob/b2d5f289347b42c23fabc57fe[…]toryRegistry/Classes/Command/NodeMigrationCommandController.php](https://github.com/neos/neos-development-collection/blob/b2d5f289347b42c23fabc57fe1bc840aed8ecd31/Neos.ContentRepositoryRegistry/Classes/Command/NodeMigrationCommandController.php#L62-L62)

**Comment by bwaidelich** [comment]
FYI: A migration could look something like

```MySQL
UPDATE
  cr_default_events
SET
  payload = JSON_SET(payload, '$.workspaceName', CONCAT('w', MD5(JSON_UNQUOTE(JSON_EXTRACT(payload, '$.workspaceName')))))
FROM
  cr_default_events
WHERE
  JSON_EXTRACT(payload, '$.workspaceName') IS NOT NULL
  AND JSON_UNQUOTE(JSON_EXTRACT(payload, '$.workspaceName')) NOT REGEXP '^[a-z][a-z0-9\-]{0,30}$'
```
