### ISSUE TITLE
BUG: cr:prune does not remove all events in eventstore

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#5220]
If you try to prune the contentrepository with the command `./flow cr:prune` all contentstream ids get fetched and all events with the given contentstreamids get deleted.

BUT not all contentstream ids are listed in the projection anymore, so we are not able to remove all events with this approach.

We need to find another way to remove the events in the eventstore. But the eventstore (interface) doesn't provide any useful yet.

**Comment by mhsdesign** [comment]
jup this is a know bug (dub of #4913) and i found a good way to do this see:

```php
        $events = $this->eventStore->load(
             VirtualStreamName::forCategory(ContentStreamEventStreamName::EVENT_STREAM_NAME_PREFIX),
             EventStreamFilter::create(
                 EventTypes::create(
                     EventType::fromString('ContentStreamWasCreated'),
                     EventType::fromString('ContentStreamWasForked')
                 )
             )
         );
         $allContentStreamEventStreamNames = [];
         foreach ($events as $eventEnvelope) {
             $allContentStreamEventStreamNames[] = $eventEnvelope->streamName;
         }
```

by filtering via the `EventTypes` this shouldnt be too expensive :)

... will be fixed via https://github.com/neos/neos-development-collection/pull/5297
