### ISSUE TITLE
BUG: Backend Login screen no longer shows site-name

### ISSUE THREAD

**Issue by c4ll-m3-j4ck** [neos/neos-development-collection#5234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are two places in Neos.Neos:View.Login that reference `props.site.name.value`. Site::getName() returns a string however so there is no value-object to unwrap.

The login screen `/neos` no longer shows the name of the site but simply "Login to"

### Expected Behavior

The login screen should show the correct text "Login to {sitename}"

### Environment

```markdown
- Flow: 9.0.0-beta13
- Neos: 9.0.0-beta13
- PHP: 8.3
```

**Comment by crydotsnake** [comment]
Hello @c4ll-m3-j4ck !

Thanks for reporting.

I created a PR.
