### ISSUE TITLE
Serializable i.e. low level commands

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#5353]
Commands are meant to capture the _intent_ of a user to change the state of the system.
But due to the fact that we _re-apply_ commands during a rebase (in order to avoid inconsistencies in the content graph) some commands have a "serialized counter-part" that is (more) idempotent than the original command (e.g. when creating a node, the default values of the schema _at the time of the command_ should be taken into account and not change between rebases).

Those lower-level commands are already marked `@internal` but they can still be send to `ContentRepository::handle()` – We should change that by making a clear distinction between actual commands and those internal (aka serialized) commands.

The affected commands are:
- `CreateNodeAggregateWithNode` => `CreateNodeAggregateWithNodeAndSerializedProperties`
- `SetNodeProperties` => `SetSerializedNodeProperties`
- `SetNodeReferences` => `SetSerializedNodeReferences`

and potentially some more to come. e.g. today we discussed that `CopyNodesRecursively` should have a serialized counter-part too in order to better capture the intent (and to avoid that this command can be used to circumvent constraint checks)

Related: #5054

**Comment by bwaidelich** [comment]
*Note:* Those internal commands could be used to for faster processing, e.g. within importers / migrators. But IMO we should go for the separation (and with it for consistent behavior and extension points). If performance is the bottleneck, low-level services could always directly persist events

**Comment by bwaidelich** [comment]
Note: This can be closed once `CopyNodesRecursively` is removed from the core

**Comment by mhsdesign** [comment]
Copy Nodes is now only a low level command anymore, not public api: https://github.com/neos/neos-development-collection/pull/5371 and will be removed
