### ISSUE TITLE
Change `CopyNodesRecursively` command to capture intent

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#5359]
Currently the [CopyNodesRecursively](https://github.com/neos/neos-development-collection/blob/85b6a4dfe30306775ad142da355d5af9158d5edf/Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Command/CopyNodesRecursively.php) command has two properties that reflect the _inner working_ more than the original intention to copy existing nodes.
This is a problem because it allows to circumvent constraint checks.

Namely:
- `$nodeTreeToInsert` that basically contains a serialized snapshot of all the affected nodes
- `$nodeAggregateIdMapping` that creates new, random, node aggregate ids

Both should not happen at command creation time but in the command _handler_, i.e. we should introduce some `CopyNodesRecursivelySerialized` variants.

Related: #5353

**Comment by mhsdesign** [comment]
More importantly this will allow us to do proper constraint checks (see https://github.com/neos/neos-development-collection/blob/ed9efe32bb17df081029923c8379af90f0e8ae92/Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Dto/NodeSubtreeSnapshot.php#L63-L64 for example)

And further this is required for copying with dimensions: https://github.com/neos/neos-development-collection/issues/5054

**Comment by bwaidelich** [comment]
> More importantly this will allow us to do proper constraint checks

Right, that's why they are mentioned in the 2nd phrase :)
