### ISSUE TITLE
Login CSS does not use cache buster

### ISSUE THREAD

**Issue by hlubek** [neos/neos-development-collection#696]
When updating from Neos 2.2 to 2.3 the login page was broken before I cleared the cache. I suspect this is caused by the configurable CSS file for the login:

```
"stylesheets":{"TYPO3.Neos:DefaultStyles":"resource:\/\/TYPO3.Neos\/Public\/Styles\/Login.css"}
```

A cache buster should be added to this file as well.

**Comment by jonnitto** [comment]
This issue is quite old. Can we close this one?

**Comment by Sebobo** [comment]
@jonnitto this can already be solved by using the flowpack/cachebuster package.

I think this could therefore be closed. Or did you already work on this?

**Comment by jonnitto** [comment]
Nope, I didn't work on this.
