### ISSUE TITLE
Missing properties in new implementation of Dimension*s*Menu

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#724]
Breaking Change in implementation of Dimension_s_Menu. The properties 'presetName' and 'preset' are missing in the new implementation.

https://github.com/neos/neos-development-collection/blob/2.3.3/TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/DimensionsMenuImplementation.php#L124

https://github.com/neos/neos-development-collection/blob/2.2.5/TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/DimensionMenuImplementation.php#L74

**Comment by dlubitz** [comment]
@kdambekalns Can't assign you. But so you are informed.

**Comment by kdambekalns** [comment]
I need to write it down in some clever way, but IIRC the preset name and preset don't make sense anymore, if you consider that this is now covering *multiple dimensions*, each having a preset and preset name.

**Comment by dlubitz** [comment]
Maybe it wasn't the "best" way, but the easiest to get the abbreviation of the language. I've already changed it on my sites, so no problem for me anymore. But as breaking changes are not welcome, I thought I should report this. Already had a look into the new implementation and also had the feeling, that it's not so easy possible to return the `presetName`. But `preset` should work.

**Comment by dlubitz** [comment]
@kdambekalns: Also the Neos.Demo Package uses the preset:
https://github.com/neos/Neos.Demo/blob/master/Resources/Private/Templates/TypoScriptObjects/LanguageMenu.html

**Comment by robertlemke** [comment]
On the master () the demo site currently shows the following error on every page:

> Notice: Undefined index: language in /Users/robert/Sites/neos-master/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/TYPO3_Neos_TypoScript_DimensionsMenuImplementation.php line 121
> 
> landingPage<TYPO3.Neos:Page>/ body<TYPO3.TypoScript:Template>/ parts/ languageMenu<TYPO3.Neos:DimensionMenu>/ items<>/
> 

Related to this issue?

**Comment by kitsunet** [comment]
From all I see the demo site still uses preset and it works, so it seems solved.

**Comment by dlubitz** [comment]
@kitsunet Wasn't an issue with the demo site. Was a breaking change between Neos 2.2 and 2.3. within Dimension_s_Menu. But I guess everybody effected will have found a workaround.
