### ISSUE TITLE
Mulitselect Checkboxes

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#769]
Jira issue originally created by user simonschaufi:

In the backend list view you can easily select multiple lines with this nice usability feature:

http://tympanus.net/Development/MultiElementSelection/index.html

How about adding this? PhpMyAdmin/Gmail/... has a similar feature except that they use the shift key to make from-to selections.
Example: http://rmariuzzo.github.io/checkboxes.js/#range-selection-of-checkboxes
Code from example: https://github.com/rmariuzzo/checkboxes.js/blob/master/src/jquery.checkboxes.js#L75-L98
Other code for shift key: https://gist.github.com/DelvarWorld/3784055
I would be very happy if one of them could be included.

 Jira-URL: https://jira.neos.io/browse/NEOS-1005

**Comment by kitsunet** [comment]
Closing for now, might happen in new UI.
