### ISSUE TITLE
Make inspector tabs better understandable

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#770]
Jira issue originally created by user @aertmann:

Currently the tabs in the inspector are easily overlooked and don't really give the impression that they are actual tabs, the  visual presentation should be changed to improve that.

![neos-inspector-suggestions](https://cloud.githubusercontent.com/assets/903567/23174065/32c0b0b6-f829-11e6-8013-c935aafe925e.png)

 Jira-URL: https://jira.neos.io/browse/NEOS-1118

**Comment by knusperpixel** [comment]
Could this be closed?

**Comment by aertmann** [comment]
Not really, it's still very relevant. However it would make sense to do in the new neos-ui package instead.

**Comment by kitsunet** [comment]
Suggested for new UI, closing this for now,
