### ISSUE TITLE
Document inspector views

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#772]
Jira issue originally created by user @aertmann:

The inspector views introduced with NEOS-760 didn't include documentation.

Like the documentation for properties, views documentation should be added to http://docs.typo3.org/neos/TYPO3NeosDocumentation/IntegratorGuide/ContentStructure.html#node-type-definition

 Jira-URL: https://jira.neos.io/browse/NEOS-1032

**Comment by jonnitto** [comment]
@aertmann As there is Jira not available anymore I don't know which views were introduced. Can we close this issue?

**Comment by rolandschuetz** [comment]
Definitely not up to date anymore, will close this issue.
