### ISSUE TITLE
"Tab Function" for table doesn't work on Safari and Chrome

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#773]
Jira issue originally created by user sokly:

I added content type "Text" and I selected table. Then I typed the text, when I use function tab to move to next columns or row, it jump me out of the content. It works fine on Firefox and IE, but on Safari and Chrome.

Could anyone help me to fix this?

 Jira-URL: https://jira.neos.io/browse/NEOS-1037

**Comment by kitsunet** [comment]
I doubt this will be fixed in the current UI. Closing for now. Ideally CKEditor in the rewritten UI does it better :)
