### ISSUE TITLE
Drag & drop moving of content elements

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#776]
Jira issue originally created by user @aertmann:

It should be possible to drag content elements around instead of having to clip them into the clipboard and move

 Jira-URL: https://jira.neos.io/browse/NEOS-1047

**Comment by jonnitto** [comment]
@dimaip Could something like that possible in the new UI? If yes; I would close this one and create a new Issue in the UI Repo

**Comment by jonnitto** [comment]
In the new UI repository is new an issue: https://github.com/neos/neos-ui/issues/1147
