### ISSUE TITLE
Add Cache-Breaking to static resources

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#777]
Jira issue originally created by user mrimann:

It was lately discussed multiple times on Slack, how to make sure that static asset files like CSS or JS files are prevented to reside in the Browser-Cache upon having a new version of the file on the server.

Several possibilities have been collected:
- Adding a timestamp directly within the Fluid-Template, Example https://github.com/sfi-ru/SfiDistr/commit/2378f79f5bb3a8295c25a003f03daba1ff0e51ba
  -- works well if the whole page can be and is cached
- Adding such a timestamp via an Aspect that wraps around the URI-Resource-Viewhelper (Examples: https://gist.github.com/nlx-sascha/e782fb944e42b3e3c22d and https://gist.github.com/jrenggli/d52582ed90eb5c10c83a)
  -- better as it adds the timestamp of the file's last change
  -- not so cool as it has to be added to each new project

It seems that the variant with the Resource-Viewhelper was preferred by some of the developers - now **the proposal is to directly add that to the Viewhelper itself as an optional feature**, see https://typo3.slack.com/archives/typo3-neos/p1425583562000729

 Jira-URL: https://jira.neos.io/browse/NEOS-1063

**Comment by dimaip** [comment]
I propose to add `addCachebreaker` (name to be discussed) parameter to ResourceUri Fusion object and Fluid VH. The best way to generate that cache breaker is via md5_file I believe, as modification time can't always be trusted, since it may change on deployment.

**Comment by kitsunet** [comment]
I don't understand what speaks against the external solution (could even be a separate VH to calculate the md5_file)

**Comment by kitsunet** [comment]
I am not too resistant to add it though...

**Comment by dimaip** [comment]
@kitsunet I think it's a common enough requirement. Maintaining a pair of VH helper/Fusion object is a bit annoying, I'd rather use a native API.

**Comment by kdambekalns** [comment]
IMHO this should be taken care of by the server setup. E-Tag & friends… Appending some "garbage" to the URL is not the best way to solve this, IMHO.

**Comment by bwaidelich** [comment]
I second @kdambekalns' opinion (even though I supported the idea back then apparently ;)

**Comment by dimaip** [comment]
Thanks for your thoughts. Since E-tag is a preferred solution, let's leave it up to a 3rd-party package if one really needs it.

**Comment by mrimann** [comment]
Thanks to @dimaip there is now a 3rd-party package if someone is interested: https://packagist.org/packages/opsdev/cache-breaker

**Comment by aertmann** [comment]
It's still a useful feature for those who don't know how to or are restricted in adding proper E-Tags, but keeping it as an external package makes sense.

We have actually needed it in Neos because we can't rely on users using proper E-Tags, but I guess we can create our own helper for it too.

**Comment by dimaip** [comment]
I read up on the subject and spoke with a few of the clients who are deep into this stuff, and they all reject using E-Tags as being slow and requiring extra request. Besides, E-Tags never worked reliably for me, where some resources would get stalled (I do have them set up correctly).
I would propose to eventually include this cache breaker thing in the core.

**Comment by daniellienert** [comment]
Have the same problem right now. Thanks @mrimann for the package.
👍  to @dimaip to make that a core functionality.

**Comment by rolandschuetz** [comment]
FlowPack also provides a package for this no:
https://github.com/Flowpack/Flowpack.CacheBuster

**Comment by jonnitto** [comment]
So, what will we do? Will we add this to the core or give the advice to use the [Flowpack.CacheBuster](https://github.com/Flowpack/Flowpack.CacheBuster)?

**Comment by dimaip** [comment]
I still hold up to what I said in the comment above, but would not object to any alternative solution.

**Comment by Sebobo** [comment]
I'll close this for now as the flowpack cache buster package takes care of it and people can customize it to their needs.
