### ISSUE TITLE
assigning same format twice in a row does not work in Aloha

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#778]
Jira issue originally created by user wasiko:
1. mark some text in Aloha editor and select some formating from dropdown - e.g. "Heading2"
2. now mark another text an try to assign same format as in step 1
3. that won't work 
   you have to  select a different format in Aloha's dropdown and afterwards you can assign "Heading2"

Tried this with latest FF and Chrome on http://neos-master.demo.typo3.org/

 Jira-URL: https://jira.neos.io/browse/NEOS-1076

**Comment by ComiR** [comment]
Duplicate of #950 and fixed with #699 👍
