### ISSUE TITLE
Add possibility for relative resource URIs to viewhelper

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#779]
Jira issue originally created by user sschlapkohl:

The new resource-uri-viewhelper returns explicitly absolute URIs for public resources. However, in cases where CSS get included like this, which loads font-faces relatively from /foo/bar e.g. (which you'll want to do) you'll run into cross-domain-security problems if your page is also delivered from a CNAMEd domain, because the font name is resolved relative to the css-location which is set absolutely by the viewhelper to the non-CNAMEd-domain.

Besides: a little more flexibility (relative vs. absolute, // as a protocol prefix) in choosing the kind of URLs in my markup would generally be nice. There is not much reason to use absolute URIs for public resources at all.

 Jira-URL: https://jira.neos.io/browse/NEOS-1080

**Comment by kitsunet** [comment]
Moved to Flow.
