### ISSUE TITLE
Find better solution for "updateSiteAction"

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#781]
Jira issue originally created by user @kitsunet:

The method 
\TYPO3\Neos\Controller\Module\Administration\SitesController::updateSiteAction()

allows changing the site node name. To actually do that it uses internal Node methods anyway but the way it is implemented is rather ineffective.
We should replace this with a DQL query to rename all paths,
BUT this is not trivial, we need to change path, parentpath, pathhash and parentpathhash at the same time and DQL by default offers no MD5 function. So we need to add that as custom function in order to do this.

 Jira-URL: https://jira.neos.io/browse/NEOS-1088

**Comment by jonnitto** [comment]
@kitsunet Can we close this issue?
