### ISSUE TITLE
Check Error if Fluid Namespace Import is forgotten

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#783]
Jira issue originally created by user @skurfuerst:

I know bastian worked on that, but do not know if the error message helps the user yet :)

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12108/screenshot-1.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1105

**Comment by kitsunet** [comment]
Closing due to a) wrong collection, b) this would have to be part of standalone fluid now.
