### ISSUE TITLE
Add label to menu button

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#785]
Jira issue originally created by user @aertmann:

The menu button in the top left corner is overlooked by users not noticing it's a menu due to it's "burger" icon and being next to other buttons with text.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11803/unnamed.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1119

**Comment by kitsunet** [comment]
Moved to UI rewrite...
