### ISSUE TITLE
Improve the Edit / Preview tab UI

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#786]
Jira issue originally created by user rasmusskjoldan:

If a user has a Preview mode selected, collapses the Edit / Preview panel, tries to edit content but is not aware of the Preview mode being selected, there is insufficient UI feedback.

It might be needed that we need to do more tasks to solve this but to start with we need to introduce the following changes:

• Use 2 different colors for both Edit / Preview labels and the mode buttons
• All Edit mode buttons keep the same primary color 
• All Preview mode buttons should be green (#ff8700)
• Mark the active Edit / Preview category corresponding to the selected mode: If a Preview mode is selected and the Edit / Preview panel is collapsed, then the label "Preview" in the tab is both bold and #ff8700. If an Edit mode is selected the "Edit" label is both bold and blue

See attached designs.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/10203/Screen+Shot+2014-04-23+at+15.56.18.png) 
![Jira Image](https://jira.neos.io/secure/attachment/10202/Screen+Shot+2014-04-23+at+15.56.36.png) 
![Jira Image](https://jira.neos.io/secure/attachment/10201/Screen+Shot+2014-04-23+at+15.57.20.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-112

**Comment by kitsunet** [comment]
Moved to new UI suggestions, will probably not happen in current UI anymore.
