### ISSUE TITLE
Prevent tree focus after tree triggered page reload

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#787]
Jira issue originally created by user @aertmann:

When modifying the nodes in the structure tree, the page is reloaded and that leads to the root node of the structure tree being focussed. However this is not desired since that is only necessary when it's a normal page reload being triggered and not one being triggered by the structure tree itself.

 Jira-URL: https://jira.neos.io/browse/NEOS-1126

**Comment by Sebobo** [comment]
This doesn't seem to happen anymore in the new UI, therefore I'll close the issue.
