### ISSUE TITLE
Backend themes (dark, light, high contrast)

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#788]
Jira issue originally created by user @aertmann:

The dark color of the backend user interface is sometimes a problem for screens with poor quality that don't display the subtle color differences correctly. This especially happens for projectors, where dark colors blend together.

The idea behind the dark theme is to bring focus to the website it's surrounding, however if the website is dark a light theme can sometimes make more sense.

So create a dark theme by altering the SCSS constants and compile a different css file from that. Keep in mind that those colors might have to have different constrast ratios than the dark ones to work. It's important to use base colors that works together with the existing color scheme.

The user should be able to select the "User interface theme" in the user settings next to the "Interface language".

In addition to a light theme a high constrast (accessibility) theme makes sense. Coincidentally Chromes print version of the backend actually does quite a nice job at that we could use as inspiration. So the idea is to make everything black and white, except for the colors instead of different variations of the gray. Button most the distinguishable in some way still though.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11820/BhlqZX6CMAAA9zM.png) 
![Jira Image](https://jira.neos.io/secure/attachment/11805/high+constrast.jpg) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1132

**Comment by kitsunet** [comment]
I assume if this is going to happen it will be the rewritten UI, so closing and referencing this in my UI collection for the rewrite.
