### ISSUE TITLE
Turn "Edit / Preview" into a dropdown

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#802]
Jira issue originally created by user gbks:

This turns the "Edit / Preview" button into a dropdown, making the functionality more obvious and removing the need for the slide-in panel. See attached PDF for more explanation, and the png for the visual styling.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11809/Neos+edit+preview+update.pdf) 
![Jira Image](https://jira.neos.io/secure/attachment/11810/Neos-edit-preview-update.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1175

**Comment by kitsunet** [comment]
Transferred to UI rewrite project.
