### ISSUE TITLE
Translate datepicker in DateTimeEditor.js

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#803]
Jira issue originally created by user @radmiraal:

/****
- TODO: Add translations
  *
- $.fn.datetimepicker.dates = {
-      en: {
-          days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
-          daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
-          daysMin: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
-          months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
-          monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
-          meridiem: ["am", "pm"],
-          suffix: ["st", "nd", "rd", "th"],
-          today: "Today"
-      }
-  };
  */
  
  Jira-URL: https://jira.neos.io/browse/NEOS-1177

**Comment by kitsunet** [comment]
I think momentum in the React UI does this just fine.
