### ISSUE TITLE
neos-contentelement-hidden added to a neos:contentElement.wrap when inline editing properties of a hidden document

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#808]
Jira issue originally created by user @dimaip:

Regression introduced with https://review.typo3.org/#/c/36773/

 Jira-URL: https://jira.neos.io/browse/NEOS-1198

**Comment by kitsunet** [comment]
Closing as the original change is no longer accessible and I believe we fixed this issue by now.
