### ISSUE TITLE
Wrong HTML in HEAD section can break the whole backend

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#809]
Jira issue originally created by user mrimann:

We stumbled over an issue that the whole Neos User Interface breaks down as described below, if there's "stupid" as in "wrong" HTML-Code in the HEAD section of the page to be rendered:

```
<a href="https://plus.google.com/xyz" rel="publisher"></a>
```

After changing this to

```
<link href="https://plus.google.com/xyz" rel="publisher" />
```

Within the `<head>...</head>` part of the template, I couldn't reproduce the issue anymore.

We were able to reproduce the issue by adding the "wrong" block of code to the HEAD section, then loading the backend and clicking any (page) node in the node-tree.

See detailed information in NEOS-1114 where we elaborated and tried many other things - but finally managed to limit the issue to the above mentioned cause.

After discussion with [~kitsunet] we decided to bring this up as a separate issue, as Neos should be more robust in such a case.

 Jira-URL: https://jira.neos.io/browse/NEOS-1210

**Comment by jonnitto** [comment]
@mrimann What do you think? Can we close this one? This shouldn't be an issue in the new UI…

**Comment by mrimann** [comment]
To be honest, I have no clue whether this issue is still around and if/how the new UI changed whether it has an unwanted effect or not. But I'm fine with closing this one - looks like it was a very rare edge-case over which no one else stubled since then :-)

**Comment by jonnitto** [comment]
Thanks for your answer. So I'll close this one. If you stumble again, fell free to reopen it…
