### ISSUE TITLE
Inconsistent and disturbing "outline" of neos-top-bar buttons

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#814]
Jira issue originally created by user mostwanted:

Clicking on one of the #neos-top-bar buttons lead to a dotted outline of that button. The outline is not consistent when you compare the 3 buttons with each other. Please have a look at the attached screenshots.

This outline also occures on other buttons like "raw content" and "in-place". As clicking on those buttons does lead to a page reload it is not that obvious compared to the situation mentioned above.

I would suggest to remove the outline of those buttons completely.

Tested at http://neos-master.demo.typo3.org/ with Chrome 42 on OS X Yosemite.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12124/Screenshot+at+Mai+14+11-13-07.png) 
![Jira Image](https://jira.neos.io/secure/attachment/12125/Screenshot+at+Mai+14+11-18-42.png) 
![Jira Image](https://jira.neos.io/secure/attachment/12126/Screenshot+at+Mai+14+11-18-55.png) 
![Jira Image](https://jira.neos.io/secure/attachment/12127/Screenshot+at+Mai+14+11-19-09.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1283

**Comment by kitsunet** [comment]
Moved to UI rewrite project.
