### ISSUE TITLE
Implement a .remove() operation in FlowQuery

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#816]
Jira issue originally created by user @radmiraal:

Currently we have .add() to add elements to a collection, but we do not have an easy way to remove a single element from a collection. The only current way is using a filter, which might then end up something like:

```
${q(node.properties.referencesProperty).filter('[*name != "' <ins> q(node.properties.referenceProperty).property('*name') </ins> '"]')}
```

It would be more readable / usable to have:

```
${q(node.properties.referencesProperty).remove(node.properties.referenceProperty)}
```

 Jira-URL: https://jira.neos.io/browse/NEOS-1298

**Comment by jonnitto** [comment]
Solved with https://github.com/neos/flow-development-collection/pull/1219
