### ISSUE TITLE
As a content editor I want to identify duplicate assets and remove them

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#819]
Jira issue originally created by user @robertlemke:
- some way to show duplicate assets in the media browser
- a button for removing duplicates
- when duplicates are removed, nodes which were using one of these assets must contain the correct references to their assets afterwards (no broken links to assets)
  
  Jira-URL: https://jira.neos.io/browse/NEOS-45

**Comment by Benjamin-K** [comment]
Isn't this fixed in the current version of Neos?

**Comment by Sebobo** [comment]
I don't think this issue still exists.
