### ISSUE TITLE
Dialog for translating documents provides misleading text for site node

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#823]
Jira issue originally created by user @hlubek:

`code`
Start with an empty or pre-filled document?
This Hauptseite does not exist yet in Language Englisch.
You can create it now, either starting with an empty Hauptseite or copying all content from the currently visible Hauptseite in Language Deutsch.
Additionally, there are -1 ancestor documents which do not exist in the chosen variant either, and which will be created as well.
`code`

 Jira-URL: https://jira.neos.io/browse/NEOS-1331

**Comment by kitsunet** [comment]
That seems corrected by now. Therefore closing.
