### ISSUE TITLE
Warn user if baseUri is configured and multiple domains are active

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#830]
Jira issue originally created by user @hlubek:

Having a `baseUri` configured through Settings.yaml is not compatible with a multi site installation or when just having multiple domains for the same site (rare use case because of duplicate content).

We could display a warning at some relevant point (e.g. in the configuration backend module).

 Jira-URL: https://jira.neos.io/browse/NEOS-977

**Comment by bwaidelich** [comment]
This will be obsolete with #2157
