### ISSUE TITLE
TYPO3.Neos:AssetUri is missing

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#831]
Jira issue originally created by user kapale:

Right now there seems to be no way to get the URL of an asset within typoscript.
This function should basically work like TYPO3.Neos:ImageUri and deliver the correct uri to the asset as a string instead of the asset object itself

 Jira-URL: https://jira.neos.io/browse/NEOS-1364

**Comment by kitsunet** [comment]
This is possible with the `TYPO3.TypoScript:ResourceUri` or (from Neos 3.0) `Neos.Fusion:ResourceUri` object as any asset has a resource that can be retrieved via `${myAsset.resource}`. Therefore closing.
