### ISSUE TITLE
TYPO3.Neos.userInterface exported to editing frontend

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#832]
Jira issue originally created by user @kitsunet:

The whole setting key TYPO3.Neos.userInterface is exported to the JavaScript editing interface, currently there are some options in there that probably make not much sense to have exported. This is a performance issue and may be low level information disclosure. We should take care to comment this section in Neos Settings.yaml and maybe move configuration options out of there or export only specific ones.

 Jira-URL: https://jira.neos.io/browse/NEOS-1365

**Comment by kitsunet** [comment]
Won't fix here anymore -> UI rewrite.
