### ISSUE TITLE
Neos UI must support NodeType with a default property other than "title"

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#833]
Jira issue originally created by user @dfeyer:

As an editor, I want to create new document with a default property other than "title" from the navigate component. This can be a requirement (semantic, ex: a person title is not the perfect default property, the default should be name in this case).

Currently the property "title" is hardcoded in AbstractNodeTree.js (and maybe at some other place, please comment this issue if you know other place where the title property is used.

 Jira-URL: https://jira.neos.io/browse/NEOS-1377

**Comment by jonnitto** [comment]
Is solved. You can add customs label with the key `label`.  
Example: https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Configuration/NodeTypes.yaml#L3

**Comment by dimaip** [comment]
Well, kind of, but you would also need to adjust the creation dialog for that nodetype and a creation handler, so not really straightforward.
