### ISSUE TITLE
Google Page Speed API

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#834]
Jira issue originally created by user @kitsunet:

We could include 
https://developers.google.com/speed/docs/insights/v2/getting-started
for pages in inspector, similar to analytics.

 Jira-URL: https://jira.neos.io/browse/NEOS-985

**Comment by Sebobo** [comment]
I like the idea, but this should be done in a separate (Flowpack?) package. Therefore I'll close this for this repo.
