### ISSUE TITLE
Basic Site Tutorial with common components

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#835]
Jira issue originally created by user kapale:

The tutorial in "create a site" should show the basic workflow how to build a webpage with Neos. It should covers the most basic components like a menu, content elements, search, contact form, SEO, Google Analytics and so on.

 Jira-URL: https://jira.neos.io/browse/NEOS-1380

**Comment by mhsdesign** [comment]
https://docs.neos.io/cms/building-your-first-website
