### ISSUE TITLE
Mediabrowser opened from inspector missing back button

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#836]
Jira issue originally created by user @hhoechtl:

If you have e.g. an Image element and you want to select a resource by clicking "Media" the ImageBrowser slides in.
But if you don't select an image, but either click on the filename of the image and the detail view for that image opens, you can't get back to the ImageBrowser.
You need to click "Save" in order to get back, but I think this is not very intuitive because you don't want to save changes, but just get back.
It's even worse, if you click the close button the view just slides in and if you click "Media" again, the same detail view opens up. 
The UX must definitely be enhanced here.

 Jira-URL: https://jira.neos.io/browse/NEOS-1381

**Comment by kdambekalns** [comment]
This is fixed, there is a cancel button now and the media browser resets to the thumbnail/list view when being closed and opened.
