### ISSUE TITLE
Switching dimension via language menu doesn't refresh backend

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#838]
Jira issue originally created by user @hhoechtl:

You are logged in the neos backend and are currently viewing a page in the dimension "en_US".
If you don't use the the dimension switcher from the neos backend, but the dimension menu and switch e.g. to "de_DE" then the ajax page reload opens the page with the correct dimension, but the neos inspector, dimension-switch, pagetree, structure tree, etc. still shows the dimension "en_US".
You then must force the browser to reload in order to view the correct dimension.

There should be a detection for the ajax page reload if the dimension is changed and refresh the neos backend.

 Jira-URL: https://jira.neos.io/browse/NEOS-1388

**Comment by kitsunet** [comment]
Closing as duplicate of https://github.com/neos/neos-development-collection/issues/1218
