### ISSUE TITLE
Backend styling for longer translation labels

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#839]
Jira issue originally created by user @hhoechtl:

The neos backend styling needs to be checked for elements that depend on the length of the text, because if the translation is longer the styling might break.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12206/Bildschirmfoto+2015-07-16+um+10.28.10.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1400

**Comment by kitsunet** [comment]
I guess closing this as it will probably need to happen in new UI...
