### ISSUE TITLE
Aloha: Make list styles configurable through property configuration

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#840]
Jira issue originally created by user sorenmalling:

At this moment, it's possible to configuration parts of the Aloha tools like so

``` java
    links:
      type: string
      ui:
        inlineEditable: TRUE
        aloha:
          placeholder: '<ul><li><a href="/">Link</a></li></ul>'
          autoparagraph: FALSE
          format:
            format: FALSE
          table:
            table: FALSE
          alignment:
            alignment: FALSE
          list:
            ol: FALSE
            ul:
              ul: TRUE
          formatlesspaste:
            button: FALSE
          link:
            a: TRUE

```

but you can't modify the number of ex. "ul" and "ol" styles available. This is due, to the created schema json, doesn't support a array-like configuration that Aloha supports/requires [1], but instead flattens it.

This task will require the configuration to accept handling of more "advanced" configurations, than just simple flattened data.

[1] http://www.alohaeditor.org/guides/plugin_list.html

 Jira-URL: https://jira.neos.io/browse/NEOS-1403

**Comment by DrillSergeant** [comment]
+1 for this feature

**Comment by kitsunet** [comment]
Should go to neos/neos-ui if still needed.
