### ISSUE TITLE
Links to page after moving page are not updated.

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#845]
Jira issue originally created by user lsascha:

One user moved a target page to another directory. After that the links on the start page where not updated and neos also didn't show that this page should be published or anything.
After changing a single image somehow the other images also updated the link.

(the images where all in a single column element linking to the same page)

So this is probably some sort of caching issue

 Jira-URL: https://jira.neos.io/browse/NEOS-1447

**Comment by kitsunet** [comment]
ConvertUrisImplementation adds the necessary cache tags.
