### ISSUE TITLE
./flow site:prune consumes too much memory 

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#847]
Jira issue originally created by user @daniellienert:

After I imported about 30.000 nodes, **site:prune** is failing even wit 512 Mb of ram. I think this should be improved.

```
./flow site:prune
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 2048 bytes) in /Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Types/JsonArrayType.php on line 63
```

 Jira-URL: https://jira.neos.io/browse/NEOS-1459

**Comment by kitsunet** [comment]
Closing as this seems no longer an issue, just made a test with a 150.000 nodes site and php barely scratched 80MB...

**Comment by daniellienert** [comment]
Ouh already 2 years ago 😉
Thanks for taking care!
