### ISSUE TITLE
Backend loadPage shouldn't try to load "javascript:" links

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#850]
Jira issue originally created by user yaramayer:

Since the `*linkInterceptionHandler` is attached to pretty much all links on the page (`this.*linkInterceptionHandler($('a:not(' <ins> this.rootElement </ins> ' a)'));`), any link-based JS functionality is no longer usable.

Preferably, it would be also possible to mark non-"javascript:" links as being "no-follow" as well.

 Jira-URL: https://jira.neos.io/browse/NEOS-1468

**Comment by Sebobo** [comment]
This should be solved with the new UI. Therefore I'll close this.
