### ISSUE TITLE
Optimize lastVisited node for pagespeed

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#852]
Jira issue originally created by user @hhoechtl:

Google pagespeed complains about the short lastvisitednode script that is being inserted into the footer. Is there a reason, why this is in a file. 
If I inline it, Google doesn't complain and we don't loose functionality

```
prototype(TYPO3.Neos:Page) {
    lastVisitedNodeScript.attributes.src >
    lastVisitedNodeScript.content = 'try {sessionStorage.setItem(\'TYPO3.Neos.lastVisitedNode\', document.querySelector(\'script[data-neos-node]\').getAttribute(\'data-neos-node\'));} catch(e) {}'
}
```

 Jira-URL: https://jira.neos.io/browse/NEOS-1475

**Comment by rolandschuetz** [comment]
I believe this is already fixed, cause the script now is async.

**Comment by hhoechtl** [comment]
Yes it is
