### ISSUE TITLE
Make the ConvertUrisImplementation more extensible

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#854]
Jira issue originally created by user michael.gerdemann:

Convert the anonymous function to a normal method, so that the ConvertUrisImplementation is expandable via an aspect.

 Jira-URL: https://jira.neos.io/browse/NEOS-1477

**Comment by mhsdesign** [comment]
@gerdemann was it about this line? https://github.com/neos/neos-development-collection/blob/d73870685dd94ff2b82b57484c3fa516b02583c9/Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php#L96

its been a long time ^^ do you think it would still be helpful?

**Comment by kitsunet** [comment]
Generally ConvertUrisImplementation could be better expandable

**Comment by mhsdesign** [comment]
see also https://github.com/neos/neos-development-collection/pull/3486

**Comment by mhsdesign** [comment]
closing if favor of https://github.com/neos/neos-development-collection/issues/3155
