### ISSUE TITLE
Setup fails to create symlinks on windows

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#855]
Jira issue originally created by user buhit:

The creation of symlinks in installdir\Web_Resources fail in neos 2.0.*. on windows machine.

In verison 1.2.9 it was working...

 Jira-URL: https://jira.neos.io/browse/NEOS-1479

**Comment by kitsunet** [comment]
I don't think there is a difference in how we create the symlinks, closing as nothing happening here.
