### ISSUE TITLE
Make the Backend distinguishable in the browser title

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#859]
Jira issue originally created by user kabarakh:

The user should be able to see which browser tab/window is the frontend and which is the backend. In the screenshot, the right tab is actually the backend. 

An idea would be to add something to the title (the workspace?) or to use a dedicated favicon.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12322/Bildschirmfoto+2015-08-19+um+11.59.24.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1518

**Comment by kitsunet** [comment]
This will be much easier with the rewritten UI, pointing it there.
