### ISSUE TITLE
ui-button-text clickable in Chrome

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#861]
Jira issue originally created by user patrickreck:

The ui-button-text element when formatting Paragraphs is clickable in Chrome (below the intended button). Works ok in Firefox/Safari.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12323/Screen+Shot+2015-08-21+at+12.12.03.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1520

**Comment by kitsunet** [comment]
Closing as the image is no longer available and either this is fixed or will be completely different in the rewritten UI.
