### ISSUE TITLE
Search boxes wont loose focus with Select2 in IE11

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#868]
Jira issue originally created by user @aertmann:

Edit page properties in IE11 where you have to select a reference (searchbox) will keep focus so you cant edit another property of the current page. It seems to be a bug of select2. If you take a look on https://select2.github.io/examples.html with IE 11 and try to open a selectbox with placeholders, you cant loose the focus too. This issue is relatively new: https://github.com/select2/select2/issues/3300 
1. Neos Demo Package installed 
2. Go to the backend 
3. Select a page where the search box is part if the properties editor (e.g. shortcut) 
4. Click in the search box 
5. Try to loose focus on the search box 

Tested with: Firefox 40, Chrome 45, IE 11 (Win 8 + 10), IE 10, IE 9 

 Jira-URL: https://jira.neos.io/browse/NEOS-1547

**Comment by jacquibo** [comment]
Still getting this issue in 4.0.3 :(

**Comment by kitsunet** [comment]
Closing this as we don't use select2 anymore in the React UI.
