### ISSUE TITLE
Neos cannot handle Unicode codepoints > 0xFFFF (outside the BMP)

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#869]
Jira issue originally created by user luchr:
# Cause of the problem

For text fields in the MySQL database the type utf8_unicode_ci is used. Hence in such a textfield you can only save Unicode codepoints in the BMP (code points between 0x0 and 0xffff).
# Impact

Trying to save somewhere in Neos text with unicode code points outside the BMP, one gets an "Internal Server Error".
# Solutions
# Why not using utf8mb4 (that's MySQL's name for real utf8)?
# Update the documentation: "We proudly support 5.88% of the Unicode code points."

Even in this bug report I cannot type characters outside the BMP. 
For the record, we have  f0 9d 9f 9a f0 9d 9f 98 f0 9d 9f 99 f0 9d 9f 9d.

 Jira-URL: https://jira.neos.io/browse/NEOS-1548

**Comment by kitsunet** [comment]
This was released in Neos 4.0, closing.
