### ISSUE TITLE
Deactivating modules in backend does not work

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#872]
Jira issue originally created by user thomas:

As of now it is not possible to deactivate entire modules in the Neos backend via Settings.

For example if you want to deactivate the History module, one would think that

```
TYPO3
  Neos:
    modules:
      management:
        submodules:
          history: ~
```

should do the trick. But this only removes the label for some reason:

!Test_Images_-_Testbereich_-_DRJA.png|thumbnail!

The link is also still there, but when you click on it, you will see an error that no controller was defined.

You can deny access to the module via Policies. But that the Settings approach should work as well.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12402/Test_Images_-_Testbereich_-_DRJA.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1555

**Comment by bwaidelich** [comment]
Backend modules can be disabled by setting their `enabled` flag to `FALSE` (see http://neos.readthedocs.io/en/stable/CreatingASite/Security.html#disable-modules)
