### ISSUE TITLE
Only publish used resources

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#874]
Jira issue originally created by user @hhoechtl:

If you do `resource:publish` Flow publishes all resources of a collection. Even the resources that are not in use.
It could be that you publish resources that should not be available to public (if your publishing target supports directory listing, that's even worse).
Maybe this should be changed to a different collection and the used assets should be moved or there should be a check that only used assets are published.

 Jira-URL: https://jira.neos.io/browse/NEOS-1603

**Comment by kitsunet** [comment]
We cannot know if resources are in use, I think you would want to use a separate collection for these cases but this must be hashed out in more detail. Should probably be also moved to Flow collection.

**Comment by kitsunet** [comment]
Moved to flow.
