### ISSUE TITLE
Adding roles and privileges via API

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#877]
Jira issue originally created by user andi:
- decide on how and where information like roles, permissions, etc. is stored
- implement commands to add roles/permissions
  
  Jira-URL: https://jira.neos.io/browse/NEOS-161

**Comment by kitsunet** [comment]
@foerthner not andi...

**Comment by Sebobo** [comment]
I'll close this as it didn't seem important for 10 years.
