### ISSUE TITLE
Catch configuration errors in `setRoles` of `LDAPProvider

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#878]
Jira issue originally created by user @sebobo:

Currently the authentication will fail without error if the roles configuration is not correct.
Additional help should be provided so it's easier to spot mistakes.

 Jira-URL: https://jira.neos.io/browse/NEOS-1610

**Comment by kitsunet** [comment]
That hsould go to the ldap package maybe? @Sebobo

**Comment by Sebobo** [comment]
Don't remember what that was about. But I think it was solved.
