### ISSUE TITLE
Permission Management UI

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#879]
Jira issue originally created by user andi:
- Add meta information like icon, description, etc. to roles and privilege targets
  ***\* roles can be abstract, and are then not directly asignable/exposed to the UI
- Make it possible to assign parameters to a role and assign that to an account in the user interface
  ***\* Depending on the parameter type, a specialized interface (selector of modules, node tree, etc.) is provided to configure the parameter in the UI
  
  Jira-URL: https://jira.neos.io/browse/NEOS-162

**Comment by Sebobo** [comment]
The description is available since a while. I'm not sure what the parameters should be for and the old link is of course not available anymore.

So I'll close this and a new ticket can be created with more information if any of the requirements are still important.
