### ISSUE TITLE
Remember last selected type in "Create new" dialogs

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#959]
Jira issue originally created by user just2b:

if switching to a different "create new" type, e.g. "new into" and doing a reload, the change is lost again. this should be persisted for the user

 Jira-URL: https://jira.neos.io/browse/NEOS-216

**Comment by kitsunet** [comment]
This will probably only happen in the rewritten UI. There it's at least persistent during the current editing "session". Referencing in the UI rewrite issue collection...
