### ISSUE TITLE
Content-Cache flushes entries for all workspaces when editing nodes

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#960]
Jira issue originally created by user @hlubek:

Creating / updating / deleting a node in the user workspace will flush all cache entries for the node and associated tags. The cache entries are tagged with the node identifier or as a descendant of a node (e.g. for ContentCollection) not taking the workspace name into account. This way a change will always flush all cache entries regardless of the workspace.

In the worst case one or more editors working on the page can cause a live site to perform bad because of missing cache entries while accessing the site.

An idea would be to add the workspace name to the tags that are flushed (for the workspace hierarchy), so the default cache configuration would need to be changed to take the workspace of the node context into account.

 Jira-URL: https://jira.neos.io/browse/NEOS-241

**Comment by kitsunet** [comment]
Is this going any further @hlubek ?

**Comment by hlubek** [comment]
@aertmann Same here (late to the party ;), I did it with an aspect and added new workspace-prefixed tags to the ContentCacheFlusher. This should be BC because we would still flush the non-prefixed tags and use the prefixed tags in our default cache config and cache tag helpers.

I'll create a PR for that.

**Comment by daniellienert** [comment]
@johannessteu: This one should be fixed with your improvements in 4.1?

**Comment by johannessteu** [comment]
jep @daniellienert
