### ISSUE TITLE
Clearly document how to handle site specific node types

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#961]
Jira issue originally created by user @radmiraal:

We started creating a specific HomePage nodetype for every site package. This allows for having a completely separated nodetype structure if you apply the constraints to that.

We need to have an integrator guide for handling the nodetype structure for multiple sites in the same installation.

 Jira-URL: https://jira.neos.io/browse/NEOS-247

**Comment by kitsunet** [comment]
Closing in favor of https://github.com/neos/neos-development-collection/issues/807
