### ISSUE TITLE
Control access to Neos modules via Policy

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#964]
**UPDATE (5th May 2017):**
I just renamed this ticket from "As a Neos Administrator I want to control access to modules" (https://jira.neos.io/browse/NEOS-27).

Background:
Currently access to Neos modules is controlled via a `privilegeTarget` (used to be `resource`) option in the module configuration.
As preparation to make this more flexible (and possibly configurable via Backend) those module privileges should be configured in the `Policy.yaml` solely.

In order to be able to configure ACL via the Neos Backend (that is: during "runtime") we'll need neos/flow-development-collection#593

**Comment by kitsunet** [comment]
@bwaidelich Is this something still on the radar?

**Comment by bwaidelich** [comment]
@kitsunet No, it wasn't really. Thanks for bringing it back up ;) I'll look into this
