### ISSUE TITLE
Provide a reference of available validators for node types

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#967]
Jira issue originally created by user @hlubek:

There is a list of available validators on the page http://docs.typo3.org/neos/TYPO3NeosDocumentation/IntegratorGuide/CustomContentElements.html but it's not an obvious place for the information.

There should be more examples on how to write the actual YAML configuration for each of the available validators.

 Jira-URL: https://jira.neos.io/browse/NEOS-303

**Comment by kdambekalns** [comment]
This issue is very old by now and has not been updated for a while.

Chances are, it is solved or otherwise no longer relevant, so I close it.

Feel free to reopen, if this is still an issue and you can provide new information.
