### ISSUE TITLE
lastVisitedUri mechanism does not consider content dimensions

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#969]
Jira issue originally created by user @robertlemke:

The lastVisitedUri cookie currently only stores the node identifier and not the content dimension values.

Steps to reproduce:
- go to content module
- switch website language to some other than the default language
- to to workspaces module
- got co content module via the module selector or go to http://yoursite/neos

-> currently selected language is the default one

 Jira-URL: https://jira.neos.io/browse/NEOS-312

**Comment by mhsdesign** [comment]
The renamed
`Neos.Neos.lastVisitedNode` cookie

stores now since some time all the information.
