### ISSUE TITLE
Typoscript ExceptionHandler should bubble up Security Exceptions

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#970]
Jira issue originally created by user pumatertion:

In case you need to throw an AuthenticationRequiredException from a PluginController its currently catched and printed out. But it should bubble up to get a redirect to the loginbox.

 Jira-URL: https://jira.neos.io/browse/NEOS-314

**Comment by kitsunet** [comment]
From all I have seen this has been fixed quite some time ago. Closing.
