### ISSUE TITLE
TypoScript not available in internal arguments present in PluginView

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#971]
Jira issue originally created by user pumatertion:

prototype(Foo) < prototype(TYPO3.Neos:Plugin) {
    package = 'Foo.Bar:Baz'
    controller = 'Foo'
    action = 'index'
    shouldBePresentAsInternalArgument = "But it isnt :("
}

Without PluginView it is available.

 Jira-URL: https://jira.neos.io/browse/NEOS-323

**Comment by kitsunet** [comment]
This has been fixed since some time now.
