### ISSUE TITLE
Improve warning notifications when the backend breaks

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#976]
Jira issue originally created by user @aertmann:

When the backend breaks, either due to a broken AJAX request, a broken JavaScript parsing or a session timeout. It should be clear to the editor that there changes are no longer saved, to avoid editor keeping on writing and ending up losing their content.

 Jira-URL: https://jira.neos.io/browse/NEOS-346

**Comment by mhsdesign** [comment]
This seems to be no longer a concern of the React UI
