### ISSUE TITLE
Images with links causes problems when clicking the image

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#979]
Jira issue originally created by user @aertmann:

When a image has a link on it, clicking the image will result in going directly to the image which will lead to an error being shown. The problem is that it's not possible to add the overlay over the image to prevent clicking the link, because there could be other properties (caption, text) that needs to be clickable. We need to come up with a concept for how to handle links in the backend and how to make it possible to click them in some scenarios and not in others.

Concept: Seeing as this only happens for external links since the `_linkInterceptionHandler` in `Application.js` behaves differently for local links, we could handle external links differently. By registering a click interceptor on double click instead of click, opening external links then require double click. This interceptor should although be bound only to content elements / document elements since that is needed for anything to be editable anyway.

 Jira-URL: https://jira.neos.io/browse/NEOS-358

**Comment by jonnitto** [comment]
@aertmann It is ok if I close this issue?
