### ISSUE TITLE
Unpublished node count includes auto created nodes

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#980]
Jira issue originally created by user @radmiraal:

When an editor adds a new node it will trigger a list of new nodes if the nodetype has configured childNodes. This will lead to confusion because all those nodes are counted in the publish menu.

The auto created childnodes should be ignored while counting the unpublished actions, although they should be included in the count as 1 with the document. So if only one thing a auto created child node is modified on the page, it should count as one. If the parent and a auto created child node is modified it should also count as one.

 Jira-URL: https://jira.neos.io/browse/NEOS-360

**Comment by daniellienert** [comment]
Closed as duplicate
