### ISSUE TITLE
Special node types should have the possibility of automatic sorting

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#983]
Jira issue originally created by user @hlubek:

For many node types like news, events and others, the natural sorting order is by date. It is error prone to have the editor sort the node in the tree into the correct position. There should be a mechanism to configure a sort function for a node type that should be used to position the node.

This will not work reliably if different node types exist on the same level because no order is defined for these nodes. This needs an additional thought.

 Jira-URL: https://jira.neos.io/browse/NEOS-383

**Comment by mhsdesign** [comment]
duplicate of https://github.com/neos/neos-development-collection/issues/1099
