### ISSUE TITLE
As a content editor I want to relate a varying number of images / assets to a content node

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#985]
Jira issue originally created by user @robertlemke:
- new node type Text with Images (or extend Text with Image)
- instead of selecting one image, I can click a "+" button to add another image
- images are displayed as a list in the inspector panel, with tiny square thumbnail and title (?)
- an image can be selected from the list by clicking on it and then shows up with the big thumbnail and image editor functionality
- the image list provides a button for removing the relation to that image
  
  Jira-URL: https://jira.neos.io/browse/NEOS-40

**Comment by kitsunet** [comment]
probably something for new UI. Linking there...
