### ISSUE TITLE
Invalid properties state in the inspector is not cleared when loading another page

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#987]
Jira issue originally created by user @hlubek:

How to reproduce:
- Edit a node with properties that has validators configured and fill in an invalid property
- Load another document through the tree
- Try to edit properties of another node
- The inspector is still in a state of unapplied changes
  
  Jira-URL: https://jira.neos.io/browse/NEOS-426

**Comment by mhsdesign** [comment]
Not an issue with the React UI - a prompt makes sure, that you cannot go to another document.
