### ISSUE TITLE
Inline Editable

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#991]
Jira issue originally created by user pumatertion:

What exactly happens with all the meta data added to a wrapping element like <div> f.e.? Why is this needed?

How to use the inline editable viewHelper?

How to use processing in ts to make something inline editable?

 Jira-URL: https://jira.neos.io/browse/NEOS-464

**Comment by kitsunet** [comment]
This has been addressed in documentation by now and metadata is changing in the rewritten UI anyway, so closing.
