### ISSUE TITLE
Warn user when memory is about to exceed

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#994]
Jira issue originally created by user phanebrink:

Some of the hard-to-debug installation issues originate in a low memory_limit (see #54347 for example).

We should detect low memory_limit setting (or even better: detect limit dynamically using memory_get_usage()) during the Neos setup

 Jira-URL: https://jira.neos.io/browse/NEOS-506

**Comment by kitsunet** [comment]
This is pretty much impossible as most memory is actually used during image processing or loading large amounts of data and it's hard to predict how much that will be. Closing.
