### ISSUE TITLE
Support for adding classes to images

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#998]
Jira issue originally created by user @sebobo:

**Original reporter: Markus Karsten**

It is not possible to add a class directly to the img-Tag of an image node, which is for example needed for the bootstrap img-responsive class.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11123/imagenode.patch) 

 Jira-URL: https://jira.neos.io/browse/NEOS-525

**Comment by kitsunet** [comment]
This can easily be done by adapting the template(s), closing.
