### ISSUE TITLE
Inline Editable Implementation without surrounding <div>

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#999]
Jira issue originally created by user @liwo:

I am trying to get a clean output in the frontend for a header:
<header>

<h1>Foo</h1>

</header>

Anything insite header should be inline editable.
If i want to do this, i always have to wrap the resulting <header> tag of editableViewhelper with an additional div wich represents the content type:

{namespace neos=TYPO3\Neos\ViewHelpers}
<div{attributes -> f:format.raw()}> {neos:contentElement.editable(property: 'title', tag:'header')}
</div>

This wrapping div destroys my frontend html structure.

what i tried is: {neos:contentElement.editable(property: 'title', tag:'header', node:node)}
without the wrapping div wich results in a <header> containing several neos attributes. but still not inline editable.

Imho inline editing should be possible without this wrapping div. F.e.: {neos:contentElement.editable(property: 'title', tag:'header')} {neos:contentElement.editable(property: 'title', tag:'div')} {neos:contentElement.editable(property: 'title', tag:'td')}

 Jira-URL: https://jira.neos.io/browse/NEOS-528

**Comment by kitsunet** [comment]
IMHO won't fix, maybe the rewritten UI allows other variants. Using other tags is already possible, closing for now.
